### ISSUE TITLE
DESIGN- No data found section doesn't look like the rest

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1000]
cc @gmwasi 
UPDATE: This issue is still there.
I was able to replicate it. 
Here are the steps:
FI-select one of the plans eg: A1 เขาช่องลม (2107020802) 2020-08-06
then go back the breadcrumbs and select a previous jurisdiction. See image below:
![image](https://user-images.githubusercontent.com/61143692/89665126-d8cfea80-d8e0-11ea-976b-f290f7852b29.png)

 https://web.reveal-stage.smartregister.org/focus-investigation/view/99c85336-f06d-44d3-8845-49b02e1b5688
https://web.reveal-stage.smartregister.org/focus-investigation/view/99c85336-f06d-44d3-8845-49b02e1b5688
Observe the no data found sections. They are grey. It should be a white background.

![image](https://user-images.githubusercontent.com/61143692/89664819-6101c000-d8e0-11ea-9670-4c8f7efdf29e.png)

![image](https://user-images.githubusercontent.com/61143692/86906453-3d4e2d00-c11c-11ea-9e0e-4155111398bf.png)
![image](https://user-images.githubusercontent.com/61143692/86910551-8903d500-c122-11ea-8671-f32cdf12c9cb.png)

**Comment by moshthepitt** [comment]
Please discuss with @p-netm before starting

**Comment by Naima-Bashir** [comment]
Extra point to note: 
Observe how some show No investigations others say no data found.
![image](https://user-images.githubusercontent.com/61143692/89665008-a9b97900-d8e0-11ea-944f-421fd0879a1e.png)
