### ISSUE TITLE
CSV Upload on Windows Chrome, Microsoft Edge and Firefox does not work as expected -RVL-989/1018

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1008]
1- Downloaded the Template CSV ; it downloaded successfully. However, I tried to find the downloaded file and I couldn't find it(it's there but when i try to upload it, it's not showing). See image of previous templates I had downloaded.
2- I tried to upload a csv file and I got this error below. Either because I cant find the recently downloaded file or that I am using a old csv.
3- I have tried to upload again, logged out and logged in again, still the same.
on Windows Chrome the upload functionality does not work but on Ubuntu chrome it does.
![image](https://user-images.githubusercontent.com/61143692/87128929-2aad3280-c299-11ea-84ff-fcdaf97e5e53.png)
https://github.com/onaio/reveal-frontend/pull/970
Same with Edge and Firefox
![image](https://user-images.githubusercontent.com/61143692/87132879-2d128b00-c29f-11ea-9397-5d18a01dd7d8.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/87296543-9698d080-c50f-11ea-99df-4186215acf91.png)
@gmwasi i still cannot be able to upload the csv file that i just downloaded. Let me try to replicate it in another computer and see.

**Comment by gmwasi** [comment]
@Naima-Bashir @moshthepitt I'm unable to replicate this. I've tested on 2 different windows machines and The error is no showing. I have attached a screenshot of one of the instances
![capture](https://user-images.githubusercontent.com/9564887/88377512-0462b900-cda8-11ea-887b-0d9cebdc6e69.PNG)

**Comment by Naima-Bashir** [comment]
@gmwasi and I just had a call where I walked him through the bug. One needs a Windows machine in order to see that there is no CSV extension
