### ISSUE TITLE
RVL-1019 - Set friendly message when trying to access the Monitor page on WebUI without Superset Permissions

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1013]
- [ ] Presently when a user tries to access the Monitor Page on the WebUI without the superset permissions, the page goes into an endless spinner and does not load. There is need to give a friendly message such as "This user does not have permissions to access this page" instead of the spinner.

**Comment by moshthepitt** [comment]
Additionally, ensure that when this page is loaded, the loading indicator is only shown when the async fetch is happening - after which we should render the data or show an error.

**Comment by kelvin-muchiri** [comment]
@moshthepitt @p-netm Is there a user who does not have superset permissions I can use to test, or how can I simulate lack of permissions

**Comment by kelvin-muchiri** [comment]
> Additionally, ensure that when this page is loaded, the loading indicator is only shown when the async fetch is happening - after which we should render the data or show an error.

@moshthepitt I can see appears to have been [handled](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/FocusInvestigation/active/index.tsx#L145)

**Comment by moshthepitt** [comment]
```ts
    supersetService(SUPERSET_PLANS_SLICE, supersetParams)
      .then((result: Plan[]) => {
        fetchPlansActionCreator(result);
        this.setState({
          loading: false,
        });
      })
      .catch(err => {
        displayError(err);
        this.setState({
          loading: false,
        });
      });
```

@kelvin-muchiri 

- I would move setting loading to false in a finally block
- I would explicitly check that `result` is non-falsey before using it
