### ISSUE TITLE
Add more tests for node selection and auto-selection in plan jurisdiction assignment

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1022]
We need to test node selection and auto selection exhaustively.  During development we noticed that various things could affect and introduce bugs here.  Without tests it becomes very brittle where in the future one may not know if merely touching this code introduces bugs or not.

**Comment by moshthepitt** [comment]
Things to test:

- New plans that need auto-selection
- New plans with existing auto-selections
- (Not sure how to test) view a plan and then move away, and then view it again

**Comment by p-netm** [comment]
> Things to test:
> 
>     * New plans that need auto-selection
            - this will be quite an involved integration test. component is `AutoSelectionView`. mount the actual children components and not mocks. start with the slider:
              - simulate onChangeComplete "event" ->  check the slider page updates with correct structures count
              - simulate click on `Continue to Next` button -> should now show structure summary view -> able to drill down; structures count are correct.
              - simualte click on `Continue to Next` button -> should now show JurisdictionTable view
              - each of this components has been tested indipendently in #1077 
> 
>     * New plans with existing auto-selections
        - @moshthepitt I gather for a plan with existing selections, the goal is to see if the rendered view reflects this.
              - mount ManualJurisdiction view contianer; load a plan with jurisdictions; load the tree, drilldown the JurisdictionTable to check if the jurisdictions are indeed targeted.
> 
>     * (Not sure how to test) view a plan and then move away, and then view it again
               - @moshthepitt What should be the assertion here?

**Comment by moshthepitt** [comment]
> @moshthepitt What should be the assertion here?

@KipSigei and I noticed a bug that happened as such (sometimes): load a plan for jurisdiction selection.  Then navigate back to the list of plans and load the same plan again.  We found that the plan's autoselection did not work consistently both times.  I think that this is fixed but it would be nice to have a test to guard against regression
