### ISSUE TITLE
MDA Community Reporting / Monitoring Views 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1026]
Users will need to see reporting on key MDA program indicators on the Reveal Platform.

We will need to create a new option in the "Monitor" dropdown called "MDA Community Reporting."

The reporting views will follow the existing IRS, and now MDA Point, workflows, where the user can click down through jurisdictions and see a consistent set of statistics. For this project in Zambia, the pilot is expected to be implemented at the district level: Gwembe District.

**Note:** _there are two statistics at the district level that need to have hardcoded denominators. This is allow them to see numbers of children treated against the greater population._

**Indicators:**

- **Ratio of children treated against Total Population** --> Total number of children who were registered and received drugs in the community as compared to the total number individuals (including adults) - we will need to hardcode this denominator: estimated total population of Gwembe District is 83,661
- **Ratio of children treated** (Actual vs Expected) --> Total number of children who were registered and received drugs in the community as compared to the total number of children who were expected to receive drugs - we will need to hardcode this denominator: # of children anticipated between ages of 5-14 and 11 months is 25,771
- **# children treated / # children registered+eligible** --> Total number of children who were registered and received drugs in the community as compared to the total number of children the head of household says live in the house (this is a question asked in the registration process
- **# of HH visited / Anticipated # of households** (structures on ground) --> Total number of households visited as compared to the total number of anticipated households visited
- **% structures found and visited** (# of structures found/total number of structures) --> Number of structure found and either marked as not the main structure (grey) treated (green), partially treated (orange) or refused (red) over the current number of structures in the community (all of the above plus unfound structures (yellows)). This excludes structures marked as ineligible (black).
- **# PZQ distributed** --> # of tablets distributed at that jurisdiction

See the indicators sheet in the [Data Dictionary](https://docs.google.com/spreadsheets/d/1irNlenvTf3TzcdSOdKAp2kdYjwO0O1Hl4vvNsJ9saDU/edit?ts=5e7d962c#gid=744478914) for original requirements.

**Comment by moshthepitt** [comment]
@isabelcshaw 

- Please grant access to the data dictionary to me and other engineers who may work on this
- Could you explain clearly on how the drilling down happens? i.e. are we going Country > District (only Gwembe) > others lower level jurisdictions?  If so, what should be shown at the different levels for the indicators that are "hard coded" above?

**Comment by moshthepitt** [comment]
### Implementation note

Instead of hard coding as described in the issue above we should try and use the jurisdiction metadata functionality to upload the total population, total children etc.

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/1142
