### ISSUE TITLE
Team assignment page not showing assignable locations for some plans RVL-1026

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1030]
Version Web. 0.6.0 rc3
Login to Reveal Web
Navigate to the assign page, click on some of the plans listed below. to open the assignment page.

IRS 2020-07-13 Random test plan * newly created.
IRS 2020-07-13July
IRS 2020-07-13July13
IRS 2020-07-13 Random test plan
IRS 2020-07-09 Testing 08
IRS 2020-07-09Catch11
MDA-Point 2020-07-07 Planning tool test
School Test

Current behavior:

The assignment page opens, but the location for assigning teams to does are not listed.
![image](https://user-images.githubusercontent.com/61143692/87430196-8ce59a80-c5ed-11ea-883a-f031abfe14ac.png)
Expected behavior:

Location for assigning teams should be listed.
![image](https://user-images.githubusercontent.com/61143692/87430243-9b33b680-c5ed-11ea-8585-af40edf515a1.png)

**Comment by kelvin-muchiri** [comment]
@moshthepitt @p-netm Since we cannot currently login as user **superset-user**, do we know exactly why locations are not showing for these plans?

**Comment by p-netm** [comment]
> @moshthepitt @p-netm Since we cannot currently login as user **superset-user**, do we know exactly why locations are not showing for these plans?

@kelvin-muchiri tracking

**Comment by moshthepitt** [comment]
@Naima-Bashir I believe that this was happening because these jurisdictions had been deleted from the OpenSRP server.  I am thus closing this but please reopen if still a problem.
