### ISSUE TITLE
The selected jurisdiction on the Planning tool page should be initially 0

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1036]
At the moment it's blank
Selected Jurisdictions
https://web.reveal-stage.smartregister.org/assignJurisdictions/6cc5fa1c-2d32-585e-8063-bb7f0637f982/0ddd9ad1-452b-4825-a92a-49cb9fc82d18/0ddd9ad1-452b-4825-a92a-49cb9fc82d18

**Comment by moshthepitt** [comment]
Fixed
