### ISSUE TITLE
Hide Retired Plans from the OpenSRP Web UI Manage Plans and Reporting page

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1037]
We have three plan status "Draft", "Active", "Complete" and "Retired" We need currently display "Active", "Complete", and "Retired" plans on the web API. Akros has requested that we remove "Retired" plans from the Manage plans page and the reporting pages. 

The target is to have this deployed to Reveal Zambia production by Wednesday 22nd July 2020

**Comment by moshthepitt** [comment]
### Implementation note

- Probably should be an env var of plan statuses to be hidden

**Comment by samkanga** [comment]
@moshthepitt and @ciremusyoka checking on the status of this ticket and if we shall hack the target of getting this deployed to Zambia production today.

**Comment by moshthepitt** [comment]
@samkanga we might not get to deploy this today because we have had delays caused by the change to keycloak.  Friday is probably a safer bet - is that right @ciremusyoka?

**Comment by ciremusyoka** [comment]
@samkanga @moshthepitt friday is ok.

**Comment by samkanga** [comment]
@moshthepitt could we have it out tomorrow. The client needed to test it before a demo slotted for Monday next week on Zambia production.
