### ISSUE TITLE
The columns on the Planning tool page are too wide on the name and too narrow in others

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1040]
![image](https://user-images.githubusercontent.com/61143692/87644287-9ccbbe80-c754-11ea-8e59-654b9dbd0ac0.png)
https://web.reveal-stage.smartregister.org/assignJurisdictions/15cdcd21-92c3-5e9a-acd7-103dd6177a5e

**Comment by p-netm** [comment]
closed by #1065
