### ISSUE TITLE
FI: One cant select the checkboxes

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1041]
![image](https://user-images.githubusercontent.com/61143692/87644457-d56b9800-c754-11ea-97a9-712cae67b4a6.png)

**Comment by gmwasi** [comment]
@Naima-Bashir For FI and Dynamic FI the requirement is to be able to only select one Jurisdiction at a time...once you select, the other checkboxes are disabled.

**Comment by moshthepitt** [comment]
@Naima-Bashir going to close this.  Please reopen if still an issue
