### ISSUE TITLE
Some jurisdictions dont have data on the MDA Point reporting while others have

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1044]
Login to the app:
https://web.reveal-stage.smartregister.org/intervention/mda-point/report/9f9bf764-b6a1-55a9-89e2-99151433e985/f0de23e0-1e42-49e1-a60f-58d920401718
Observe how Lomahasha-Emafusini has data, even if it's 0 and how Nazarene has blank columns
cc @isabelcshaw 
![image](https://user-images.githubusercontent.com/61143692/87660314-87ac5b00-c767-11ea-8c76-2c8d3a8421de.png)

**Comment by moshthepitt** [comment]
Seems like a data bug as opposed to a web app bug
