### ISSUE TITLE
An error appears for a second when one selects the newly created plans

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1045]
Create a new plan
Click on assign and observe the error that is shown
https://web.reveal-stage.smartregister.org/assignJurisdictions/c8b01e0c-187b-512a-b4a1-5dd4f5c1015d
RESULTS: This error(image) is shown for a split second before it loads the page.
![image](https://user-images.githubusercontent.com/61143692/87661988-394c8b80-c76a-11ea-9725-b660d9fa00e7.png)

**Comment by p-netm** [comment]
@Naima-Bashir this is no longer happening from my end. could you please retest this.

**Comment by Naima-Bashir** [comment]
@p-netm I've clicked on:https://web.reveal-stage.smartregister.org/assignJurisdictions/c8b01e0c-187b-512a-b4a1-5dd4f5c1015d and gotten this error- which is a good indicator. This has passed QA, I will however keep an eye out for it.
![image](https://user-images.githubusercontent.com/61143692/91826497-57048000-ec46-11ea-9afb-5dd8e45dda5e.png)

**Comment by moshthepitt** [comment]
Closing coz it seems to not be a problem any more.
