### ISSUE TITLE
Disable Sentry & || Error Boundary during development

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#1049]

**Comment by moshthepitt** [comment]
@p-netm if you leave out the sentry DSN env var then this is disabled, no?

**Comment by p-netm** [comment]
> @p-netm if you leave out the sentry DSN env var then this is disabled, no?

oouh! ok. did not think of doing that. Anyway I just think its a good idea if errors are as loud as they can be during development.
