### ISSUE TITLE
Refactors Oauth flow to account for opensrp server migration to keycloack .

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#1052]
We need to support the new flow for oath login due to opensrp migrating to use keycloack for its user management.
- I believe the changes will mostly be in the onaio/gatekeeper package.
- from preliminary talks it seems that we should expect the response for `user-details` to change
- Also we will know be getting the redirect_uris, and authorization_uris, from an endpoint on the server `/opensrp/rest/config/keycloak`

**Comment by p-netm** [comment]
Just want to leave this here, seems like its the best place for this. as part of the opensrp deployment that effects the above changes:
getHierarchy  will change to hierarchy  for location/getHierarchy/{locationid}  and location/getHierarchy/plan/{planidentifier}

**Comment by moshthepitt** [comment]
@p-netm should we close this?

**Comment by p-netm** [comment]
yeah
