### ISSUE TITLE
Change Keycloak Logout URL on Reveal Stage

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1058]
The current logout URL points to the OpenSRP server in Reveal stage and that doesn't cause a proper logout by the user. We need to change it to: https://keycloak-stage.smartregister.org/auth/realms/reveal-stage/protocol/openid-connect/logout?redirect_uri=

Make sure to enter an appropriate redirect_uri.

Enhancement: We currently open a new browser window to logout the user. we don't need to do this anymore if we have the redirect URI correct for Reveal Stage and could just redirect to the Reveal Stage homescreen.

**Comment by ciremusyoka** [comment]
From this conversation ([slack thread](https://onaio.slack.com/archives/CBSU8L2SC/p1595865145391800)) we had, logging out of keycloak will not be done from the web app.
