### ISSUE TITLE
The checkbox functionality works after one goes back to it

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1060]
login to the webapp
create a new IRS plan for example: https://web.reveal-stage.smartregister.org/intervention/irs/draft/07d57162-cff3-5a26-aa84-212b4dc83c46
After you create it, click on the plan and scroll to the checkbox jurisdictions below the map.
Click on the checkbox and observe if it can be selected. 
After that drill down to lower jurisdictions and try to click on the check boxes as well.
Note that they are not selected.
After that go back the breadcrumb to higher levels like Lusaka 
Observe how the check boxes are now showed as marked. 

![image](https://user-images.githubusercontent.com/61143692/88134217-b6558600-cbec-11ea-8a6b-0f2e21763cc1.png)

**Comment by KipSigei** [comment]
@Naima-Bashir i'm unable to replicate this bug, could you please check again on stage to see if this is still an issue?

**Comment by Naima-Bashir** [comment]
I've retested this. It works as expected. The checkboxes are  marked.
cc  @p-netm @KipSigei
