### ISSUE TITLE
Reveal stage Create Practitioner needs to transition from OpenMRS to Keycloak

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1061]
We transitioned Reveal stage to Keycloak, but the Create Practitioner view still queries the list of users from OpenMRS. We need to get this list from Keycloak, which requires a special permission for that user. We want to retain the same functionality which only displays the list of users who are not already assigned as practitioners.

Screen:
![image](https://user-images.githubusercontent.com/6067053/88135789-baf24e00-cb9c-11ea-8af9-2ee25c6956c0.png)

**Comment by moshthepitt** [comment]
@githengi @Rkareko what endpoint should we use for this?

**Comment by githengi** [comment]
@moshthepitt let me create an Endpoint for listing users from keycloak

**Comment by moshthepitt** [comment]
Blocked by https://github.com/OpenSRP/opensrp-server-web/issues/458

**Comment by craigappl** [comment]
This list of filters should also be updated to search keycloak
![image](https://user-images.githubusercontent.com/6067053/88288479-af8c4900-cca8-11ea-8480-1443f6254c13.png)

**Comment by moshthepitt** [comment]
Unblocked since https://github.com/OpenSRP/opensrp-server-web/issues/458 was fixed and merged.
