### ISSUE TITLE
RVL-1000 - IRS Reporting Updates

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1066]
**Coverage Update**

1. Go to the Zambia Reveal WebUI > Select Monitor > select IRS Reporting > Select a completed IRS Plan. On the dashboard table that comes up, drill down to District level and make the following changes:

- Remove the column named 'room coverage of structures sprayed' 
- Add a column named spray areas visited to follow the column named Spray areas tergeted
- Add three columns at the end of the table Structures Found , Found Coverage(Total structures found within visited spray areas/total structures on the ground within visited spray areas), and Successs Rate(structures sprayed/structures found as a percentage).

2. Go to the Zambia Reveal WebUI > Select Monitor > select IRS Reporting > Select a completed IRS Plan. On the dashboard table that comes up, drill down to Catchment Area level and make the following changes:

- Remove the column named 'room coverage of structures sprayed' 
- Add a column named spray areas visited to follow the column named Spray areas targeted
- Add three columns at the end of the table Structures Found , Found Coverage(Total structures found within visited spray areas/total structures on the ground within visited spray areas), and Success Rate(structures sprayed/structures found as a percentage)

3. Go to the Zambia Reveal WebUI > Select Monitor > select IRS Reporting > Select a completed IRS Plan. On the dashboard table that comes up, drill down to Spray Area level and make the following changes:

- Remove the column named Room coverage of structures sprayed
- Add two new columns Structures remaining to spray to reach 90% SE ((total structures x 90%)-sprayed)) and Reviewed with decision (Default equals n/a if not visited yet, '0' if 90% coverage achieved, 'Not done' if no decision form has been filled out. Changes to date when web ui decision form form filled out for. Form opened from selecting cell 'not done'. Total is count of expected forms not yet filled out)

4. Go to the Zambia Reveal WebUI > Select Monitor > select IRS Reporting > Select a completed IRS Plan. On the dashboard table that comes up, drill down to the zone level (a level below District level):

- Add a zone column filter 
- Remove the column named 'room coverage of structures sprayed' 
- Add a column named spray areas visited to follow the column named Spray areas targeted
- Add three columns at the end of the table Structures Found , Found Coverage (Total structures found within visited spray areas/total structures on the ground within visited spray areas), and Success Rate(structures sprayed/structures found as a percentage). 

Indicator definitions can be found on the jira ticket  [here](https://smartregister.atlassian.net/browse/RVL-1000).

**Comment by moshthepitt** [comment]
### Implementation plan

1. Update the Canopy [database views](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/tree/master/3-reveal/migrations/5-IRS/2-Zambia-2019) for IRS reporting
2. Ensure the new views are exposed as Superset slices
3. Update the web UI to use the new views

**Comment by moshthepitt** [comment]
@craigappl @samkanga 

1. What is a "zone column filter"
2. How do we identify the "decision form" mentioned in the issue?

**Comment by samkanga** [comment]
@moshthepitt see my responses below:

1. The zone is a new location between a health facility catchment area and an operational area. This refers to the ability to filter by this colum.
2. The decision form is found under the "other forms" on the humburger menu on the android client. Its data dictionary can be found [here](https://docs.google.com/spreadsheets/d/1UK83MInKzGplrhC_QWHd0kEFaZVrZBV9heuHdqvjMJc/edit#gid=886242395).

**Comment by moshthepitt** [comment]
> The zone is a new location between a health facility catchment area and an operational area. This refers to the ability to filter by this colum.

These pages do not support any filtering so I do not understand what this means.

**Comment by samkanga** [comment]
@moshthepitt I believe the right term should be sort.

**Comment by moshthepitt** [comment]
@samkanga 

Regarding:

> Reviewed with decision (Default equals n/a if not visited yet, '0' if 90% coverage achieved, 'Not done' if no decision form has been filled out. Changes to date when web ui decision form form filled out for. Form opened from selecting cell 'not done'. Total is count of expected forms not yet filled out)

There are a number of problems:

1. Looking at the [decision form](https://github.com/OpenSRP/opensrp-client-reveal/blob/e8b72a63c04b08fd6a84dd98f6f13da428924528/opensrp-reveal/src/main/assets/json.form/zambia_irs_sa_decision.json), it is not clear to me what the event type of evens arising from this form might be.  As such, I am unsure how to query them from the OpenSRP server API.  For this reason, this new metric may not be fully completed by Monday.
