### ISSUE TITLE
RVL-1024 - IRS Mop-Up Reporting

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1067]
1. Go to the Zambia Reveal WebUI > Select Monitor > Add a New menu named IRS Mop-up Reporting. Add a dashboard table with a drill down on the location column with the following  columns for each of the IRS plans; 
- Name (Location)
- No. of Health Centers to Mop-Up
- No. of Spray Areas to Mop-up
- Structures to spray or areas to reach 90%
- TLA days needed for areas needed to reach 90%

Here is a sample table:
- ![image](https://user-images.githubusercontent.com/5908630/88247487-89fe4000-cca6-11ea-871c-346ad9d17877.png)

2. Go to the Zambia Reveal WebUI > Select Monitor > select IRS Mop-up Reporting. On the dashboard table that comes up, drill down to District level, then drill down to catchment areas. Create the following table

-  ![image](https://user-images.githubusercontent.com/5908630/88247515-abf7c280-cca6-11ea-9426-c38566dd45af.png)
- Each column should be sortable, and multiple sorts should be allowed at once, for example you could sort by health facility and then sort by structures remaining and it should respect the initial sort.

Indicator definitions can be found on the jira ticket [here](https://smartregister.atlassian.net/browse/RVL-1024).

**Comment by moshthepitt** [comment]
@samkanga could we identify the OpenSRP event type that represents the Decision Form mentioned in this issue?

**Comment by samkanga** [comment]
@Rkareko please help with this. The data dictionary is accessible on [this](https://docs.google.com/spreadsheets/d/1UK83MInKzGplrhC_QWHd0kEFaZVrZBV9heuHdqvjMJc/edit#gid=886242395) link:

**Comment by Rkareko** [comment]
@moshthepitt @samkanga @ciremusyoka the event type for the daily summary form is `irs_sa_decision` as seen [here](https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/zambia_irs_sa_decision.json#L3)

**Comment by moshthepitt** [comment]
@samkanga 

how do you determine these for a district:

- No. of Health Centers to Mop-Up
- No. of Spray Areas to Mop-up
- TLA days needed for areas needed to reach 90%

how do you get this for a spray area

- TLA days needed for areas needed to reach 90%

**Comment by samkanga** [comment]
@moshthepitt see the information below:

**Comment by moshthepitt** [comment]
> No. of Health Centers to Mop-up = number that have active Spray Areas (SAs) needing mop-up

@samkanga How do you define a "Health Center"?

**Comment by samkanga** [comment]
On it @moshthepitt

**Comment by gstuder-ona** [comment]
Also @samkanga in the district view here there are spray areas listed directly - is this intentional?  For most IRS reporting you'd do aggregate metrics on the district health facilities and then drill into all the health facility spray areas

**Comment by samkanga** [comment]
@moshthepitt Health centre = health centre catchment area

**Comment by moshthepitt** [comment]
@samkanga that's not enough.  We need a deterministic way for the query to determine what that is.  What field on jurisdictions will tell us which jurisdictions are "health centre catchment area"?   I would have thought this would be a hierarchy level.  Lets get confirmation from the client.  

Maybe point to the current IRS reports and show us the hierarchy level that represents "health centre catchment area"?

**Comment by gstuder-ona** [comment]
@samkanga in the https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/zambia_irs_sa_decision.json#L3 irs_sa_decision form, is that something a person fills out per-spray-area (jurisdiction)?  Or is it per-district?  at some other level?

**Comment by moshthepitt** [comment]
```
reveal1=> select * from events where event_type = 'irs_sa_decision' limit 1;
-[ RECORD 1 ]--+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id             | 39ab1c09-a678-4f4c-9df8-c67f3d1b94fa
base_entity_id |
location_id    | a003039c-509b-4d7c-b2bc-bc2b102af92d
event_type     | irs_sa_decision
provider_id    | chtlatrain7
date_created   | 2020-09-21 15:14:26.982
event_date     | 2020-09-21 00:00:00
entity_type    | Structure
form_data      | {"end": "2020-09-21 15:07:33", "start": "2020-09-21 15:04:31", "return": "yes", "village": "kapachi", "deviceid": "356136100446220", "supervisor": "1705:ZM-SUP-2020-01705", "reasonnotsprayed": "locked", "structures_ground": "123", "structures_sprayed": "90", "structures_tospray": "21", "reason_noteffective": "lowCoverage", "spray_effectiveness": "73", "structures_remaining": "33.0", "structures_toreach90": "111", "number_returning_tlas": "2"}
task_id        |
team_id        | 2763ee17-68f1-5fe4-92ea-56df9aeada4a
server_version | 1600357499882
created_at     | 2020-09-22 05:32:50.12705
structure_id   |
plan_id        |
details        | {}
```

@samkanga the decision form includes some of the information like `structures_sprayed`, `spray_effectiveness`, etc.  Which are  different from the same computed metrics from the other IRS reports (the ones we already have).  What do we do here?  Do we use these values as they are in the decision form?

**Comment by samkanga** [comment]
@moshthepitt the health center catchment area is level 3 on the hierarchy. i.e. One level below the district. See screenshots below:

**Comment by gstuder-ona** [comment]
@moshthepitt @samkanga just fyi, we currently aren't ingesting the "locationTags" information for jurisdictions via NiFi, so we'll need to use position in the hierarchy to indicate a rural health center :-/

**Comment by samkanga** [comment]
@gstuder-ona the irs_sa_decision form is completed at the spray area level which is equivalent to operational area.

**Comment by gstuder-ona** [comment]
@samkanga date-of-last-visit - I still don't have access to the indicators spreadsheet, but can you tell me how this is computed or point me to where I've missed it?  Is this the last spray event timestamp in the area/zone/etc.

**Comment by gstuder-ona** [comment]
@samkanga there were a bunch of questions, just making sure this didn't get missed - in the District level view "Katete" there's a number of different spray areas listed.  Generally, there will be *hundreds* of spray areas for a district - is the intention to list all of them on the same form?

**Comment by gstuder-ona** [comment]
@samkanga ^^ ping on the above

**Comment by gstuder-ona** [comment]
@samkanga at this point we are relying on health centers being at geographic_level = 3 - we have no other way to distinguish them.  Just confirming as:
```
reveal1=> select jurisdictions.id, jurisdictions.name, parent_jurisdictions.name as parent_name, jurisdictions.geographic_level from jurisdictions LEFT JOIN jurisdictions AS parent_jurisdictions ON parent_jurisdictions.id = jurisdictions.parent_id where jurisdictions.parent_id = 'dd5ba964-d76f-4f82-a4e3-c3f822d2ae2a' OR jurisdictions.parent_id = '33b21665-8280-4de1-99e5-5954aaefa1a0' ORDER BY jurisdictions.parent_id;
                  id                  |        name         |   parent_name    | geographic_level 
--------------------------------------+---------------------+------------------+------------------
 c931d92f-68cb-44c1-b0a9-a5cec21523f2 | Yobe NHC            | Chadiza(2020)    |                4
 cdd473db-d3c3-4954-bc0a-b4ca840afb59 | Kapachi NHC         | Chadiza(2020)    |                4
 826a951f-f709-4f09-8f8a-6b31edb8b2a9 | Changaya NHC        | Chadiza(2020)    |                4
 74fcc052-c5d1-4686-b915-e2edc2028ec0 | Kamwala             | Chadiza(2020)    |                4
 94ff1372-a69d-4397-b3fb-45ab6525f89a | Chadiza Central NHC | Chadiza(2020)    |                4
 d67dfa09-1977-4e60-b428-4f5438748cbf | Mlolo NHC           | Chadiza(2020)    |                4
 fc9c128d-8630-418c-a902-7e5d019af80e | Tigwilizane NHC     | Chadiza(2020)    |                4
 9bad6f59-37b7-45e7-b203-dfa9ccb8cb70 | Mbingwa NHC         | Chadiza(2020)    |                4
 4ace14cd-effe-497f-9eac-20bd622503af | Mpundu Zone         | Kashikishi(2020) |                4
 58fdeb77-cae5-407d-8245-e87a1bdac7f3 | Kalila Nshindo Zone | Kashikishi(2020) |                4
 00800e86-80bf-4c84-b6a7-1d1289b3ac90 | Chandiwe Zone       | Kashikishi(2020) |                4
 f47ec07c-825d-4e19-9444-bf71f48d9c95 | Kabuku Zone         | Kashikishi(2020) |                4
 4ed8f536-5c08-4203-8a90-a7e13becb01d | Nkomba Kapepa Zone  | Kashikishi(2020) |                4
 4219cca4-9916-4da9-9cbc-505ab6b5b375 | Yenga Zone          | Kashikishi(2020) |                4
 d595ea79-5cda-4210-8774-98a8a6a41ca5 | Daison Zone         | Kashikishi(2020) |                4
 c20849ec-8537-49cf-b0d2-f1530c99a98b | Mutono Zone         | Kashikishi(2020) |                4
 61839c62-f517-4375-8a11-518bdca4764a | Kasensele Zone      | Kashikishi(2020) |                4
 372d52e9-9409-4f34-8099-a515362db3f5 | Sonka Zone          | Kashikishi(2020) |                4
(18 rows)
```

Note that the Kashikishi(2020) and Chadiza(2020) jurisdictions are both tagged in OpenSRP as "Rural Health Centers" *but* the names of the child zones (Yobe NHC, for example) makes me suspicious that these could actually be health centers at level 4. 
 Could be wrong, just trying to get ahead of any requirements shifting in the future (Yobe NHC is tagged in opensrp as a Zone right now, but maybe later it will need to change).

**Comment by gstuder-ona** [comment]
This work is being tested with the webui right now, when that completes we should be able to deploy : https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/39/files/b60045cf503dbc665f5ead5d050726e06ee2a0d5..b42d44a9fdac38bc987de7e64212ee06a7c365a7
