### ISSUE TITLE
RVL-1023 - IRS Performance Reporting

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1068]
1. Go to the Zambia Reveal WebUI > Select Monitor > Add a menu named IRS Performance Reporting. Add a dashboard table with columns as per the table below for each of the IRS plans. The first column (Name) should have a drill down on the locations. Include filters on the column headers.
-  ![image](https://user-images.githubusercontent.com/5908630/88248329-802a0c00-cca9-11ea-820a-602a8ba02df8.png)
- The insecticide usage rate is as follows: The number of structures sprayed divided by the number of sachets/bottles used by spray operators the data collector was managing

2. Go to the Zambia Reveal WebUI > Select Monit fror > select Performance Reporting > Drill down on District > View Data Collectors level. 
- Create a table with the following columns
-  ![image](https://user-images.githubusercontent.com/5908630/88248428-dac36800-cca9-11ea-9f40-c25846943891.png)

3. Go to the Zambia Reveal WebUI > Select Monitor > select Performance Reporting > Drill down on District > Drill down on specific Data Collector > view Spray operator level
- Create a table with the following columns
- ![image](https://user-images.githubusercontent.com/5908630/88248492-08a8ac80-ccaa-11ea-80c9-e77f1f885150.png)

4. Go to the Zambia Reveal WebUI > Select Monitor > select Performance Reporting > Drill down on District > Drill down on specific Data Collector > Drill down on Spray operator level to access the daily records.
- Create a table with the following columns:
-  ![image](https://user-images.githubusercontent.com/5908630/88248536-2f66e300-ccaa-11ea-9483-618b276cffad.png)

The indicator definitions have been included in the comments section of [this](https://smartregister.atlassian.net/browse/RVL-1023) ticket.

**Comment by moshthepitt** [comment]
Should look like https://macepa.mspray.onalabs.org/performance/

**Comment by moshthepitt** [comment]
### Implementation plan

1. Do the Canopy-side work https://github.com/onaio/canopy/issues/555
2. Make the database views available as Superset slices
3. Implement in web app

**Comment by ciremusyoka** [comment]
@samkanga were can we get data for `bottle/sachets used` and  `Data quality check`. Also how will the calculations for found and sprayed difference be done.

**Comment by samkanga** [comment]
@ciremusyoka making follow-up on this.

**Comment by samkanga** [comment]
@ciremusyoka see my responses below: The data dictionary is accessible [here](https://docs.google.com/spreadsheets/d/1UK83MInKzGplrhC_QWHd0kEFaZVrZBV9heuHdqvjMJc/edit#gid=737768298):

1. bottle/sachets used = bottles_empty on the Daily_Summary_Form [cell A35]; 
2. Data quality checkis(see below) equals a check mark when found difference & sprayed difference both equal 0 for that day; it equals an x when at least one of found difference and/or sprayed difference do not equal 0.
3. Found difference = SOP sum(found structures) - found on Daily Summary form
4. Sprayed difference = SOP sum(sprayed structures) - sprayed on Daily Summary form

**Comment by moshthepitt** [comment]
@samkanga what is the OpenSRP event type for that Daily_Summary_Form

**Comment by moshthepitt** [comment]
@samkanga @ciremusyoka looks like there is a daily summary form here https://github.com/OpenSRP/opensrp-client-reveal/tree/master/opensrp-reveal/src/main/assets/json.form.  Next we need to get help from @githengi or @Rkareko to identify the event type and then from there it should be straight-forward to get the data

**Comment by Rkareko** [comment]
@moshthepitt @samkanga @ciremusyoka the event type for the daily summary form is `daily_summary` as seen [here](https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/assets/json.form/zambia_daily_summary.json#L3)

**Comment by moshthepitt** [comment]
```
reveal1=> select * from events where id = 'abf23bd3-5f68-404b-b217-7a46558bc7c6';
-[ RECORD 1 ]--+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id             | abf23bd3-5f68-404b-b217-7a46558bc7c6
base_entity_id | 24c66924-2582-45a8-ba37-5e9c9b50fc7d
location_id    | f7c54263-7c16-4ee1-b6ee-f8865cf9bd6f
event_type     | Spray
provider_id    | chtlatrain7
date_created   | 2020-09-20 15:47:37.164
event_date     | 2020-09-20 00:00:00
entity_type    | Structure
form_data      | {"end": "2020-09-20 15:36:30", "mopup": "yes", "start": "2020-09-20 15:35:10", "nameHoH": "Getrude Manda", "deviceid": "356136100599655", "genderHoH": "female", "new_sachet": "yes", "eligibility": "eligible", "districtName": "Chadiza District (2020)", "provinceName": "Eastern Prov (2020)", "sprayop_code": "01020:ZM-SOP-2020-01020", "rooms_sprayed": "1", "sprayed_males": "1", "structure_num": "14243546", "rooms_eligible": "2", "structure_type": "residential", "business_status": "Complete", "sprayed_females": "1", "sprayed_u5_uNet": "1", "sprayed_nets_use": "1", "sprayed_totalpop": "2", "sprayed_pregwomen": "1", "sprayed_totalmale": "0", "structure_sprayed": "yes", "sprayed_childrenU5": "1", "notsprayed_totalpop": "0", "sprayed_totalfemale": "1", "sprayed_pregwomen_uNet": "1", "sprayed_totalpop_approve": "I Accept"}
task_id        | 99642821-1eea-440d-b9fe-48d905fe63ca
team_id        | 2763ee17-68f1-5fe4-92ea-56df9aeada4a
server_version | 1600357497782
created_at     | 2020-09-20 20:07:52.918227
structure_id   |
plan_id        | 7e4aba56-d5cc-5b3c-9e01-966e757c389e
details        | {"taskStatus": "COMPLETED", "location_id": "24c66924-2582-45a8-ba37-5e9c9b50fc7d", "form_version": "0.0.1", "locationUUID": "f87d9e13-1161-46a7-877b-401286774777", "appVersionName": "5.2.11", "planIdentifier": "7e4aba56-d5cc-5b3c-9e01-966e757c389e", "taskIdentifier": "99642821-1eea-440d-b9fe-48d905fe63ca", "locationVersion": "0", "taskBusinessStatus": "Not Sprayed"}

Time: 19.586 ms
```

@samkanga @richard we are noticing that spray events do not have the data collector field.  This is a problem with coming up with the data collector part of the report.

What gives?  How can we fix it?

**Comment by moshthepitt** [comment]
This was closed by https://github.com/onaio/reveal-frontend/pull/1241

Pending items are tracked in #1317
