### ISSUE TITLE
 the Jurisdiction Metadata page doesn't create CSVs with the proper extension when you click the download button

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1072]
1. Login to the webapp
2. Click on Admin- Jurisdiction metadata and download the CVS templates. 
3. Click on the downloaded csv templates and observe if they have the proper extensions

![image](https://user-images.githubusercontent.com/61143692/88289929-a8902580-ccfe-11ea-8475-806d77097e15.png)
![image](https://user-images.githubusercontent.com/61143692/88380952-26f7d080-cdae-11ea-8a79-54ade1fc53ba.png)

I think we need to add the .csv to the filename.

**Comment by moshthepitt** [comment]
Closed by https://github.com/onaio/reveal-frontend/pull/1087
