### ISSUE TITLE
Clicking on an IRS plan shows an error for a few seconds then loads the map

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1080]
Login to the webapp
Click on an IRS plan eg: 
Observe the error that is shown for afew minutes before the map loads. 
https://web.reveal-stage.smartregister.org/assignJurisdictions/42aefc2c-cae4-54dd-946e-dee053e4dd49
![image](https://user-images.githubusercontent.com/61143692/88523125-19d22000-d000-11ea-9693-1ebee9e16687.png)
After afew minutes, this is error I am getting
![image](https://user-images.githubusercontent.com/61143692/88535304-5a3a9980-d012-11ea-9c24-65f3bc1fba64.png)

@p-netm says: the hierarchy of RAZambia was removed in staging so all plans other that Eswatini and Nigeria will not load.

**Comment by moshthepitt** [comment]
Duplicate of #1085
