### ISSUE TITLE
One cannot save a new Dynamic IRS plan

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1082]
I tried with Dynamic IRS plan, I will also try with others and observe if the error is the same
 I created a new plan (Dynamic IRS, filled the details and clicked save. The save button shows Saving for quite sometime )
![image](https://user-images.githubusercontent.com/61143692/88540706-1d73a000-d01c-11ea-83a7-6f58490427a9.png)

**Comment by ciremusyoka** [comment]
@Naima-Bashir please confirm if this is still happening. From my end i can create plans without any problem (just created `Dynamic-IRS 2020-07-28 new by EM`).
cc @moshthepitt 

![Screenshot from 2020-07-28 13-33-10](https://user-images.githubusercontent.com/26719807/88655539-92f07680-d0d7-11ea-84a4-dd3847ba083d.png)
