### ISSUE TITLE
Implement Focus Investigation Web UI Reporting For Historical Data (Map)

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#11]
- [ ] Historical Investigation Map for focus area

**Comment by cKellyDesign** [comment]
Seems like this needs more clarification.

@mberg @craigappl are there client requirements for [this page](https://web.reveal-stage.smartregister.org/focus-investigation/historical) for any of the upcoming milestones/deadlines?

**Comment by moshthepitt** [comment]
Closing this as we have no information on what we need to do.
