### ISSUE TITLE
400 Error freezes map view when no structures are returned on Thailand Production

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1100]
The Thailand production server fails to load the map to view if no structures are returned from the data warehouse. This 400 error is marked as a bad request, but it's just the lack of results from Superset. The cited jurisdiction does not have any structures in the Reveal transactional database. jurisdiction_id = 398f1463-0be3-4e6b-9c9e-31ee755e1546

Symptoms:
Spinning map in the web UI:
![image](https://user-images.githubusercontent.com/6067053/89193968-95c9ec00-d55b-11ea-9cc9-5a5afa913fe5.png)

When I dig into the network, I see a 400 error on slice 226: https://superset.reveal-th.smartregister.org/superset/slice_json/226?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22398f1463-0be3-4e6b-9c9e-31ee755e1546%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22}],%22row_limit%22:15000}

Rowcount returned = 0, so it's not a bad request, it's just that no results were returned
![image](https://user-images.githubusercontent.com/6067053/89194060-b72ad800-d55b-11ea-923f-6e7573980e34.png)

I copied the query into Superset SQL builder and there are no results returned:
![image](https://user-images.githubusercontent.com/6067053/89194121-c90c7b00-d55b-11ea-816c-d7a6f406d769.png)
```
SELECT id,
jurisdiction_id
FROM structures
WHERE jurisdiction_id = '398f1463-0be3-4e6b-9c9e-31ee755e1546'
LIMIT 15000;
```
No structures are returned from the Reveal database:
https://reveal-th.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=false&return_geometry=false&properties_filter=parentId:398f1463-0be3-4e6b-9c9e-31ee755e1546

Expected Behavior:
1. the map view renders regardless of the 400 error, it just doesn't show any structures
2. It would be valuable if our handling of the Superset 0 results didn't return a 400 error, just 0 results.

**Comment by armageddon** [comment]
There may be metadata/header information that the javascript needs to be returned from superset

**Comment by craigappl** [comment]
We found out this wasn't the core issue. It had to do with an error in the ETL strategy due to URL encoded greater than values.

**Comment by craigappl** [comment]
I have to reopen. This is still an issue based on the ongoing emergency.

**Comment by kelvin-muchiri** [comment]
@moshthepitt @p-netm I have found the culprit

```
if (
      (!some(pointFeatures) &&
        !some(polygonFeatures) &&
        this.state.locations &&
        !this.state
          .initMapWithStructures) &&
        this.props.structures !== nextProps.structures &&
        nextProps.structures &&
        nextProps.structures.features.length||
      (this.props.currentGoal !== nextProps.currentGoal &&
        !some(pointFeatures) &&
        !some(polygonFeatures))
    ) {
      this.setState(
        { doInitMap: true, initMapWithoutFC: true, initMapWithStructures: true },
        () => {
          // Dirty work around! Arbitrary delay to allow style load before adding layers
          setTimeout(() => {
            this.initMap(null, null);
          }, GISIDA_TIMEOUT);
        }
      );
    }
```

Changing to the code below removes the loader, will the refactor be enough?

```
if (
      (!some(pointFeatures) &&
        !some(polygonFeatures) &&
        this.state.locations &&
        !this.state
          .initMapWithStructures) ||
      (this.props.currentGoal !== nextProps.currentGoal &&
        !some(pointFeatures) &&
        !some(polygonFeatures))
    ) {
      this.setState(
        { doInitMap: true, initMapWithoutFC: true, initMapWithStructures: true },
        () => {
          // Dirty work around! Arbitrary delay to allow style load before adding layers
          setTimeout(() => {
            this.initMap(null, null);
          }, GISIDA_TIMEOUT);
        }
      );
    }
```

**Comment by kelvin-muchiri** [comment]
When no structures are received `this.props.structures !== nextProps.structures && nextProps.structures && nextProps.structures.features.length` is false and `doInitMap` is not set to true. Removing that will have the map display, what I am not sure is why that logic was put there? Should we proceed with that refactor?

**Comment by moshthepitt** [comment]
@kelvin-muchiri good work!  But this means that they are using really old code (i.e. not GisidaLite).  In that case lets us notify @samkanga and @craigappl to work on getting the Thailand web app deployed to use a newer version of Reveal web.

What I would like you to work on is  a test to ensure that this same data will not result in a forever-loading page when using GisidaLite

**Comment by kelvin-muchiri** [comment]
Ok....let me look into it
