### ISSUE TITLE
There should be an error if one tries to save a new plan without a jurisdiction 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1101]
Create a new plan without any jurisdictions on the planning tool.
Observe the results.
https://web.reveal-stage.smartregister.org/plans/planning/new

 The fix: check if there is at least one valid selected jurisdiction id

**Comment by moshthepitt** [comment]
Fixed via https://github.com/onaio/reveal-frontend/pull/1130

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/89995430-1db5a180-dc92-11ea-9492-da3536100466.png)
@ciremusyoka  If you look at the plan title, it shows it's required, the jurisdiction should also have that error  if one tries to save it.

**Comment by ciremusyoka** [comment]
@Naima-Bashir the reason you are seeing required is because you have deleted the plan title. Is that the case?

If you try selecting a location and and cancel an error message will be displayed
