### ISSUE TITLE
Deal with errant virtual jurisdictions

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1108]
![IRS-Reporting-Nchelenge-Live-Fire-Test-August-2020-Nchelenge-District-2020-Reveal-Stage](https://user-images.githubusercontent.com/372073/89336598-51953380-d6a2-11ea-9caf-e6dd9b76fd91.png)

It seems that virtual jurisdictions are repeated weirdly.

**Comment by samkanga** [comment]
@moshthepitt this issue is still being experienced on Zambia Production. [Here](https://web.reveal-zm.smartregister.org/intervention/irs/report/4cbe10b9-231e-5084-9646-0a923dcfa0da/761a068b-7286-43dc-8bf2-51cb50647762) is a quick link to one of the locations with the issue.

**Comment by moshthepitt** [comment]
@samkanga that is not the issue being fixed in this ticket.  This ticket is about virtual jurisdictions i.e. the ones that say "other".  We have this issue that tracks [ongoing work](https://github.com/onaio/reveal-frontend/issues/1437) on this front.

The issue that you are describing is fortunately also already addressed, pending a deployment.  [See this](https://github.com/onaio/reveal-frontend/issues/1430#issuecomment-737827982).
