### ISSUE TITLE
None of the plans marked as Dynamic IRS show on the Monitor > IRS Reporting page. RVL-1050

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1114]
https://web.reveal-stage.smartregister.org/intervention/irs/report
![image](https://user-images.githubusercontent.com/61143692/89378756-30adfc00-d6fd-11ea-907d-421ee4aef859.png)

**Comment by moshthepitt** [comment]
Fixed in https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/17
