### ISSUE TITLE
Upload jurisdiction metadata functionality does not work RVL-1073

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1120]
https://web.reveal-stage.smartregister.org/jurisdiction-metadata
Download the risk and coverage csvs. 
Download the template as well.
Try to upload and observe.
RESULTS: When I try to upload the jursidiction metadata risk csv- I get an error 500
                When I try to upload the csv template, I get an Invalid CSV error
![image](https://user-images.githubusercontent.com/61143692/89545761-70173e00-d80c-11ea-80af-cedf9ffac4cc.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir I think such bugs need to be reported to the [OpenSRP server](https://github.com/opensrp/opensrp-server-web/) repo and brought to the attention of @samkanga and @githengi.  As far as I'm concerned the web app is behaving well i.e. we got an error, and we reported the error &  Fixing the error is out of our control.

**Comment by moshthepitt** [comment]
@ciremusyoka please investigate to determine if there are any fixes that can be done on the frontend codebase.

**Comment by githengi** [comment]
@moshthepitt @ciremusyoka  could you create an issue on OpenSRP repo with the error returned, API invoked and payload

**Comment by moshthepitt** [comment]
@ciremusyoka related and probably should be done at the same time https://github.com/onaio/reveal-frontend/issues/1129

**Comment by ciremusyoka** [comment]
@Naima-Bashir Have tested this with different sets of data and it works correctly. Please try testing again and confirm if it works as expected.

**Comment by Naima-Bashir** [comment]
Just tested this on 14/08/2020
I was able to download the csv templates and upload them successfully. See image below.
![image](https://user-images.githubusercontent.com/61143692/90228842-9c8c1500-de1f-11ea-9322-36bfaa8d56c1.png)

**Comment by Naima-Bashir** [comment]
However, after I upload the csv, I am redirected to the homepage. Is this the expected outcome? cc @moshthepitt @ciremusyoka

**Comment by moshthepitt** [comment]
@Naima-Bashir  I think that it is still failing for large payloads. Like [this one](https://github.com/OpenSRP/opensrp-server-web/files/5055769/settings.json.zip).

**Comment by moshthepitt** [comment]
In addition to the PRs lined above, this was fixed by https://github.com/onaio/reveal-frontend/pull/1271
