### ISSUE TITLE
Clicking on monitor- focus investigations gives a 404 error

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1121]
Click on monitor- FI- then one of the plans
https://web.reveal-stage.smartregister.org/focus-investigation/map/1b48ff6b-990b-5161-8301-e0a99c412546
Observe the 404 error that is shown.

![image](https://user-images.githubusercontent.com/61143692/89546479-54f8fe00-d80d-11ea-9d31-2db4c5571588.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir closing this because those are mapbox errors outside our control.  Please re-open if I am mistaken
