### ISSUE TITLE
The conditional formatting rules shows NaN instead of numbers

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1122]
Click on Monitor- IRS reporting then a specific one like: 
https://web.reveal-stage.smartregister.org/intervention/irs/report/5640fcc2-772a-5e06-9e00-491e3aa544f5/ecfbf048-fb7a-47d8-a12b-61bf5d2a6e7b

Observe the Zambia(vl 2020) (other)
RESULTS: It is showing NaN instead of numbers that represent the formatting colours.
![image](https://user-images.githubusercontent.com/61143692/89546962-d8b2ea80-d80d-11ea-9e25-32705cf074d2.png)

**Comment by moshthepitt** [comment]
This is a duplicate for https://github.com/onaio/reveal-frontend/issues/1108
