### ISSUE TITLE
Dynamic MDA plan cannot be assigned locations or teams 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1124]
For NTD Zambia, we are using the Dynamic MDA plan type. When I log on to stage (user: onatest) and create a new plan type using the Zambia(vl 2020) hierarchy, I am able to create a draft plan. 

When I click back into that plan to assign locations, I cannot click on any of the check boxes to select districts, or operational areas, or even the entire country. 

Earlier, when try to assign users to a plan I was able to set to active, I get a "OpenSRPService read on location/hierarchy/plan failed, HTTP status 400" error. This plan was "Zambia IS MDA 8.20." (video linked from Slack below) 

I tried to troubleshoot this with @samkanga and he was able to create a plan and assign locations. But he could not assign locations to the plan I created. We tested with plan: "IS MDA Zambia Aug 2020." I logged in and out more than once and also opened it in an incognito browser. 

Because of this, one guess I have is that maybe it is not a problem with the hierarchy and maybe it is because I disabled the "MDA Adherence" task on plan creation - is it possible this is creating errors? @craigappl 

I am marking this as high priority because Zambia needs to be ready to go live on Friday. 

Video of the second error from Slack here: https://onaio.slack.com/archives/CBSU8L2SC/p1596819112463100?thread_ts=1596802330.446200&cid=CBSU8L2SC

**Comment by moshthepitt** [comment]
@ciremusyoka please investigate what may be causing the problems described here, and then report back to this issue as a comment.

**Comment by ciremusyoka** [comment]
> For NTD Zambia, we are using the Dynamic MDA plan type. When I log on to stage (user: onatest) and create a new plan type using the Zambia(vl 2020) hierarchy, I am able to create a draft plan.
>
> When I click back into that plan to assign locations, I cannot click on any of the check boxes to select districts, or operational areas, or even the entire country.

@moshthepitt on testing this have realised the [plan](https://reveal-stage.smartregister.org/opensrp/rest/plans/c593f15a-2592-5ff4-9a7b-f53d5b39f5e0) was saved without a `jurisdiction` being assigned which am not sure how it happened. The endless loading on the `Location` field is happening because the [request to get the jurisdiction associated to the plan](https://reveal-stage.smartregister.org/opensrp/rest/plans/findLocationNames/c593f15a-2592-5ff4-9a7b-f53d5b39f5e0) doesn't return any name.

We can add a check to give a user ability to select new jurisdiction if a plan is saved without a jurisdiction

**Comment by moshthepitt** [comment]
> We can add a check to give a user ability to select new jurisdiction if a plan is saved without a jurisdiction

@ciremusyoka please add a validation to the PlanForm that ensures that a plan cannot be saved without a jurisdiction.  This should work for plans created in both "Manage Plans" and "Planning Tool".

Related: https://github.com/onaio/reveal-frontend/issues/1101

**Comment by moshthepitt** [comment]
@ciremusyoka please also make that plan "retired"

**Comment by ciremusyoka** [comment]
> Earlier, when try to assign users to a plan I was able to set to active, I get a "OpenSRPService read on location/hierarchy/plan failed, HTTP status 400" error. This plan was "Zambia IS MDA 8.20." (video linked from Slack below)

This error too is as a result of the plan not having a jurisdiction
![Screenshot from 2020-08-10 12-06-49](https://user-images.githubusercontent.com/26719807/89767801-4f4c3280-db03-11ea-87af-dbc94e229d2c.png)

**Comment by craigappl** [comment]
@ciremusyoka , Can we also check to see if a user is able to set a plan to active at a high jurisdiction such as the country level?

Steps:
- Click Planning Tool>Create New Plan
- choose a country
- See that the status can be captured and the plan can be set to active in this view.

Should we only be able to add "draft" plans at this phase?

**Comment by ciremusyoka** [comment]
@craigappl It is possible to create active plans but they will not appear on the `Planning Tool` page (on clicking Plan > Planning Tool) thus one will not be able to refine the jurisdictions.

**Comment by moshthepitt** [comment]
Closed via #1126 and #1130
