### ISSUE TITLE
Creating a new FI plan and clicking on the map gives an error 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1132]
Login to the web
Then Plan- new plan- FI- drill down to a jurisdiction till the map shows.
Click on the map and observe the error 
https://web.reveal-stage.smartregister.org/focus-investigation/view/da5cf948-15d8-4dda-a8a4-40a444875151
![image](https://user-images.githubusercontent.com/61143692/89899848-8a299580-dbeb-11ea-8612-b52aee88d66f.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir looks like it works as expected.  If it can't load the jurisdiction then it shows a nice error
