### ISSUE TITLE
Allow configuration of intervention types to be displayed on Planning tool

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1137]
Use existing env variable `REACT_APP_ENABLED_PLAN_TYPES` to control plan intervention types displayed on planning tool page (Plan > Planning Tool)

**Comment by moshthepitt** [comment]
I think it may not be necessary, or at least not urgent because if we limit the type of plans that can be created then what shows up on the planning tool may not be a problem.

**Comment by ciremusyoka** [comment]
@moshthepitt  Realised the plans are already being filtered on the selector https://github.com/onaio/reveal-frontend/blob/2116367704c30cd0c577e39c7602c657e6b71f7a/src/store/ducks/plans.ts#L608-L609
