### ISSUE TITLE
Make Jurisdictions Report Plans Reducers DRY

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1143]
The reducers used for plans for IRS, MDA-Point and Dynamic-MDA plans are [very](https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/generic/MDAPointPlans.ts) [very](https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/generic/plans.ts) similar.

Let us find a way to make this code more DRY.

Ideas:

- Use one reducer module and filter by plan intervention type
- Implement a reducer factory

**Comment by ciremusyoka** [comment]
@moshthepitt  Can start by refactoring the reducers to use [@opensrp/reducer-factory](https://www.npmjs.com/package/@opensrp/reducer-factory)
