### ISSUE TITLE
Update the Web UI and ETL process in Namibia production to read the uploaded targets

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1155]
- [ ] We need to update the Web UI and ETL process in Namibia production to read the uploaded targets per jurisdiction instead of structure counts. The uploaded target structures should show under the "Structured Targets" on the IRS dashboard.

**Comment by moshthepitt** [comment]
Fixed by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/9 https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/10 and https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/11
