### ISSUE TITLE
Jurisdiction metadata fails when response from API is empty

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1157]
`Cannot read property 'settingIdentifier' of undefined`  happens when you attempt to download metadata that has not been set:

![image](https://user-images.githubusercontent.com/372073/90378575-36eb9300-e082-11ea-9f71-7aaeb3201dc7.png)

**Comment by kelvin-muchiri** [comment]
@moshthepitt What should be the desired behaviour?
