### ISSUE TITLE
RVL-1067 - Change ‘Zone’ in WebUI to read ‘Location’ for VL (2020) hierarchy level 4

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1170]
- [ ] The naming of the hierarchy level 4 should change from Zone to Location.

For example, Chisenga zone on the image below should read Chisenga Location.
![image](https://user-images.githubusercontent.com/5908630/90630495-cb442a00-e229-11ea-8c61-72ce24bbdd22.png)

**Comment by moshthepitt** [comment]
@samkanga this can only be fixed by changing the jurisdiction name sin OpenSRP.

**Comment by samkanga** [comment]
This is noted @moshthepitt
