### ISSUE TITLE
RVL-1016 - User filter to have by default the username of the user logged in

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1172]
When logging in to the Web, in the manage plan screens and monitoring, the filter by "username" should be set to default to the user who is logged in.

In the below picture, would be set to "SuperSetTester"
![image](https://user-images.githubusercontent.com/5908630/90950028-91a43680-e456-11ea-8659-837f53224c87.png)

**Comment by moshthepitt** [comment]
Let's discuss before you start working on this
