### ISSUE TITLE
RVL-1031 - Add pop up messages based on certain conditions before a plan is closed or retired

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1173]
While doing data analysis and pilot feedback, the client found it difficult to consistently understand user behavior when completing and retiring plans. Hence, there are several user errors. In order to avoid them, we would like to propose the following:

**(1) User tries to complete a plan:**
1.a. If Plan has data show message: You are about to complete a plan, please ensure all data has been 
collected
1.b. If Plan has no data: You are about to complete a plan that has no data, if the intervention has not been 
done you should Retire the plan instead of complete it.

**(2) User tries to retire a plan:**
2.a. If plan has data: You are about to retire a plan that has data linked to it, please ensure this is not an error, if intervention has been completed, please complete plan instead of retire.
2.b. If plan has no data: You are about to retire a plan, are you sure you want to retire the plan? You will not be able to collect data for this intervention.

**Comment by moshthepitt** [comment]
Let's discuss before you start working on this

**Comment by craigappl** [comment]
@moshthepitt , this is an enhancement that I think we should schedule for the next sprint or shortly after.

**Comment by p-netm** [comment]
>  If Plan has no data

@samkanga @moshthepitt what would be the technical definition of a `plan having data`?

**Comment by moshthepitt** [comment]
@p-netm the only way of knowing that is to check the Canopy DB.  For now let's not do that - because I don't think that we should have a Canopy dependency here.  Let's just ask the user to confirm if they want to retire or complete a plan.

**Comment by p-netm** [comment]
places this would affect: 
- monitor page Mark plan as complete
- planform(when updating a plan):
  - planning tool, from plan status field
  - manage plans page, from plan status field


*need to create a unified interface for:*
  - detecting if the status has changed to any of the status of interest i.e complete or retired. (need access to the plan before modification)
  - asking for confirmation if above is found (will probably have to use an alert, *or redirect to confirmation page*.)
  - posting the payload if confirmation is granted.

**Comment by mberg** [comment]
Let's do this after 1023 and 1024
