### ISSUE TITLE
Add better tests for Gisida maps

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#118]
So far in our tests, we completely mock the map component because it has proven to be difficult to test.

We need to find a way to write better tests for the Gisida powered-maps.

This looks promising: https://github.com/mapbox/mapbox-gl-js-mock

**Comment by allthesignals** [comment]
How did this turn out for you? Curious because we struggle with mapbox-gl testing approaches too!

**Comment by moshthepitt** [comment]
@allthesignals we haven't really gotten to it, so far we have just tested "around it", like here:

- https://github.com/onaio/reveal-frontend/blob/fd1c112ce4ad2b469cd94261603b01c1e6f536b3/src/components/GisidaWrapper/tests/index.test.tsx
- https://github.com/onaio/reveal-frontend/blob/bf456afbc901e0e6881f0fbe9110995acff1361e/src/helpers/handlers/tests/handlers.test.tsx
