### ISSUE TITLE
Structures Target not Displaying on Namibia Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1186]
- [ ] The structures target under the IRS reporting tab is presently not showing. I uploaded the value (777) for the Test OA operational area but this figure does not show. However, target coverage appears and it uses the structures target as the denominator. This means the structure target value is getting to the dashboard and its just not displayed. See the screenshot below:
![image](https://user-images.githubusercontent.com/5908630/90972351-fb891280-e520-11ea-9432-854722a22334.png)

**Comment by moshthepitt** [comment]
@samkanga please share the csv that you uploaded

**Comment by samkanga** [comment]
@moshthepitt let me share that.

**Comment by samkanga** [comment]
@moshthepitt I converted the file to txt as I github rejected .csv file.
[JurisdictionHierachyTemplate (2).txt](https://github.com/onaio/reveal-frontend/files/5116416/JurisdictionHierachyTemplate.2.txt)
