### ISSUE TITLE
Mysterious Loss of Team Assignment to Plans on Namibia Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1196]
- [ ] Team assignment made for plans on Namibia production are being removed mysteriously. However, logging into the APK still allows access to the plans. An example is as shown on the screenshot below: 
![image](https://user-images.githubusercontent.com/5908630/91195464-b112bc00-e701-11ea-9765-2b4d07c1cbc7.png)
This is happening for both normal IRS plans and Dynamic Plans

**Comment by ciremusyoka** [comment]
@moshthepitt @githengi the value of `jurisdictionId`  returned by `.../opensrp/rest/organization/assignedLocationsAndPlans` endpoint should not be null ([sample namibia data](https://reveal-na.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans?plan=5bfa9430-b4b8-53e1-9301-73d989f52873) vs [sample stage data](https://reveal-stage.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans?plan=57be179d-5046-5d7b-a89e-4fa79296dd00)) as we are relying on that value to display the assigned teams.

**Comment by moshthepitt** [comment]
@githengi here is the sample Namibia payload

```json
[
    {
        "organizationId": "bc0b81c0-cc83-535a-9414-fb8563ecc762",
        "jurisdictionId": null,
        "planId": "5bfa9430-b4b8-53e1-9301-73d989f52873",
        "fromDate": 1598288400000,
        "toDate": 1599670800000
    },
    {
        "organizationId": "47ce799b-1e5f-4476-8c86-9da23f6bc727",
        "jurisdictionId": null,
        "planId": "5bfa9430-b4b8-53e1-9301-73d989f52873",
        "fromDate": 1598374800000,
        "toDate": 1599670800000
    }
]
```
What can we do to fix this?  Could it be affecting other country deployments?

**Comment by githengi** [comment]
There was a vision of allowing global plan assignments. We can remove this so that assignments must have jurisdictions

**Comment by moshthepitt** [comment]
@githengi I think we should loop in @samkanga and @craigappl to scope how global assignments would look like for the web app.

For this issue, I think that the mysterious thing being reported is that when an explicit assignment was made at jurisdiction level, it was found to be later removed.  Can you confirm if this is happening when a global assignment exists?

**Comment by githengi** [comment]
The main issue would be trying to assign an invalid jurisdiction, when that happens then null is used. I suspect the main issue is assigning to inactive locations, @moshthepitt  are you able to freely reproduce

**Comment by moshthepitt** [comment]
@samkanga are you able to reliably reproduce this?

One thing to note is what @githengi mentioned: `I suspect the main issue is assigning to inactive locations,`

As well as that if the plan end date is in the past, you will not be able to view any assignments.

**Comment by ciremusyoka** [comment]
@samkanga currently i can see teams assigned to different locations. Please confirm if [this pr](https://github.com/OpenSRP/opensrp-server-core/issues/307) fixed the bug.

**Comment by samkanga** [comment]
@ciremusyoka Yes. We are looking good on this one.
