### ISSUE TITLE
Dynamic Plans on Namibia Production not showing synced data

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1197]
- [ ] We submitted data against the dynamic plan **Dynamic-IRS 2020-08-25_IV** but the data did not show on the dashboard. The data remained at zero as shown on the screenshot below:
![image](https://user-images.githubusercontent.com/5908630/91197554-1f587e00-e704-11ea-97ff-f35d1d21619b.png)

**Comment by moshthepitt** [comment]
Was fixed via https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/13
