### ISSUE TITLE
There should be an error when one doesn't select a country while creating plans

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1199]
https://web.reveal-stage.smartregister.org/plans/planning/new
Create a new plan
Dont select the country
Observe how the save button is unresponsive.
There should be an error notification that explains to the user that the country selection is mandatory.
![image](https://user-images.githubusercontent.com/61143692/91287886-fdf5a180-e798-11ea-800e-4148c8df90e2.png)

**Comment by moshthepitt** [comment]
If you scroll up to the country field there is an error show.
