### ISSUE TITLE
Import installed mapbox-gl instead of global window function 

### ISSUE THREAD

**Issue by kahama94** [onaio/reveal-frontend#120]
Currently we are using the global window function to import mapbox-gl on SingleActiveFIMap which is not the cleanest way to handle the import. The reason this approach is used is  due to jest test failure. Link that sheds more light to this issue [here](https://github.com/mapbox/mapbox-gl-js/issues/5026)

**Comment by moshthepitt** [comment]
@kahama94 was this solved though?

**Comment by kahama94** [comment]
@moshthepitt Not yet haven't found a better solution than the one we have
