### ISSUE TITLE
The Structures not Visited not showing up in the IRS Reporting Map for Namibia

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1202]
- [ ] When I log into the Namibia android app and access the plan named Dynamic-IRS 2020-08-25_IV associated with the test OA there are numerous structures that have not been visited (screenshot 1 below). However, these do not show up on the IRS reporting maps on the WebUI. See the screenshot 2 below.

Screenshot 1:
![image](https://user-images.githubusercontent.com/5908630/91300215-97c64a00-e7ab-11ea-8ba3-0ebe9f6ac277.png)

Screenshot 2: Map shows only completed and partially sprayed structures
![image](https://user-images.githubusercontent.com/5908630/91300270-aad91a00-e7ab-11ea-9c95-78a7ded5334e.png)

**Comment by moshthepitt** [comment]
@samkanga please check now.  One thing to note is that on the web we are only showing structures that belong to the selected plan.

e.g.

![IRS-2020-08-21_Nam1-Test-OA-Reveal](https://user-images.githubusercontent.com/372073/91418060-517bf400-e85a-11ea-87fc-7ef21903f70d.png)

**Comment by samkanga** [comment]
@moshthepitt I get you. I will restest this and get more information based on the findings.

**Comment by moshthepitt** [comment]
Closed by #1206
