### ISSUE TITLE
Error in GisidaLite

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#1205]
Testing using this plan:
https://web.reveal-stage.smartregister.org/assignJurisdictions/4fb345b1-3319-5479-b069-e05ca53a33e6

steps to reproduce:
- open the above draft plan from the planning tool.
- drilldown 2 steps down  on the drill down table.
  ราชอาณาจักรไทย > ตาก (63) > 

Expected:
- the page should continue working normally, any errors you might get will be known issues, and should not break the app

Actual:
- the page breaks with a `GisidaLite issues`, see screenshot below:
![Screenshot from 2020-08-26 15-31-22](https://user-images.githubusercontent.com/28119869/91303854-46b95480-e7b1-11ea-9f14-9a0e228a6671.png)

The error suggests we may be breaking this one rule of hooks:
`you ensure that Hooks are called in the same order each time a component render`

**Comment by moshthepitt** [comment]
We usually send a number of things to the map component:

- a layer containing one or more jurisdictions (admin boundaries)
- one or more layers containing structures (points and polygons)

What I am saying is that as long as there is a valid layer, we should make the map load.  Does that make sense?

I think we can get the map bounds and center from any feature collection(s).
