### ISSUE TITLE
Namibia: Download Jurisdiction Metadata Pulling Duplicates and Adds the Term Metadata to the OA

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1207]
- [ ] On the jurisdiction metadata download page, when I use the lower option to download the metadata, the csv comes with duplicate records. In addition, the jurisdiction names on the csv have an added tag metadata. See the screenshot below.
![image](https://user-images.githubusercontent.com/5908630/91428265-12a06b00-e867-11ea-9057-8e4639c12a0d.png)

**Comment by moshthepitt** [comment]
Duplicate of #1239
