### ISSUE TITLE
Show map error messages

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1210]
When an error occurs that causes the map on the planning tool or team assignment page to not load, we currently show an error on the page in a div.

In addition to the above, we should [display a growl message](https://github.com/onaio/reveal-frontend/blob/f952af04dea65437efb5962e078cd5b67f1f8562/src/helpers/errors.ts#L18) with the specific problem that caused the map to not load.

**Comment by ciremusyoka** [comment]
@moshthepitt is the intention here to display non API related errors such as structures not being available or map zoom being invalid eg. https://github.com/onaio/reveal-frontend/blob/1966dc746bf4cdae0651d243e1e90a0d6f4db2c3/src/containers/pages/AssigmentMapWrapper/index.tsx#L188-L190

**Comment by moshthepitt** [comment]
@ciremusyoka yes that's it
