### ISSUE TITLE
Audit loading of jurisdictions in planning tool

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1216]
We need to audit the API calls made by the planning tool e.g. https://web.reveal-stage.smartregister.org/assignJurisdictions/3ea2c755-e2b4-5bdd-88aa-c118e5ef44bc.  Looks like it is loading some jurisdictions more than once.

**Comment by p-netm** [comment]
looks like `ManualSelect` is the one with the problem: its making 2 calls to get the hierarchy..
Reason being that the hook that makes the request has 2 dependencies a `rootId` and a `plan`.
I will remove the `plan` from the dependency array.
