### ISSUE TITLE
Data Completed and Synced on Android App Not Showing on the WebUI Dashboards on Stage

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1218]
- [ ] Data has been submitted against the plan named IRS **VL Lusaka Test Aug 2020_I** on Reveal stage. However, the dashboards remain at zero despite data having synced from the devices. Below is a sample screenshot from one of the devices.
![image](https://user-images.githubusercontent.com/5908630/91659618-8b0e6280-ead9-11ea-856b-ca8f76477992.png)

The screenshot below shows the dashboard that is not populating values.
![image](https://user-images.githubusercontent.com/5908630/91660962-ab421f80-eae1-11ea-8be5-20bddca9930d.png)

**Comment by moshthepitt** [comment]
@samkanga this should be fixed now, yeah?

**Comment by moshthepitt** [comment]
Closing.  Please reopen if still an issue.
