### ISSUE TITLE
Thailand Preview Environment Flagging Errors when Selecting the WebUI Menus

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1220]
- [ ] The Thailand Preview WebUI, is flagging errors when one tries to select any of the menus, that read **We are having trouble retrieving requested resource**. See sample screenshots beow.
![image](https://user-images.githubusercontent.com/5908630/91689231-54355c80-eb6c-11ea-8969-5d41bd8585d0.png)

**Comment by p-netm** [comment]
@samkanga I believe this was resolved, closing this.
