### ISSUE TITLE
Namibia Coverage Targets Not Updating on the WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1223]
- [ ] The structure targets on Namibia Production are not updating following the upload of new values.

**Comment by moshthepitt** [comment]
@samkanga could you give an example?

**Comment by samkanga** [comment]
@moshthepitt let me upload a new value and share feedback on this.

**Comment by samkanga** [comment]
@moshthepitt what is the estimated time within which an uploaded target value should reflect on the dashboard?

**Comment by moshthepitt** [comment]
it pulls new targets every hour @samkanga

**Comment by samkanga** [comment]
Cool. I am just past the 1 hour mark but I will a little more time and recheck this.

**Comment by samkanga** [comment]
@moshthepitt I am at the 2 hours mark and the new target value of 555 is not showing. I however see a value that was uploaded yesterday 200 (see screenshot below). So its more of an issue of how soon it takes to see the updated values. 
![image](https://user-images.githubusercontent.com/5908630/91830303-486c9780-ec4b-11ea-899b-234be6054920.png)

**Comment by moshthepitt** [comment]
Will look into this

**Comment by moshthepitt** [comment]
```sh
           jurisdiction_id            | val  | serverversion | target
--------------------------------------+------+---------------+--------
 40aee4db-1c05-4fdf-a984-612829d6900b | 200  | 1598881019465 |    200
 40aee4db-1c05-4fdf-a984-612829d6900b | 666  | 1598551533633 |    666
 40aee4db-1c05-4fdf-a984-612829d6900b | 1000 | 1598551337034 |   1000
 40aee4db-1c05-4fdf-a984-612829d6900b | 1000 | 1598551260928 |   1000
 40aee4db-1c05-4fdf-a984-612829d6900b | 789  | 1598551154119 |    789
 40aee4db-1c05-4fdf-a984-612829d6900b | 900  | 1598549810589 |    900
 40aee4db-1c05-4fdf-a984-612829d6900b | 555  | 1598437431779 |    555
 40aee4db-1c05-4fdf-a984-612829d6900b | 777  | 1598436217645 |    777
 40aee4db-1c05-4fdf-a984-612829d6900b | 876  | 1598351014887 |    876
 40aee4db-1c05-4fdf-a984-612829d6900b | 819  | 1598349250450 |    819
 40aee4db-1c05-4fdf-a984-612829d6900b | 777  | 1598349250450 |    777
 40aee4db-1c05-4fdf-a984-612829d6900b | 900  | 1598349250450 |    900
 40aee4db-1c05-4fdf-a984-612829d6900b | 111  | 1598349250450 |    111
 40aee4db-1c05-4fdf-a984-612829d6900b | 900  | 1598349250450 |    900
 40aee4db-1c05-4fdf-a984-612829d6900b | 111  | 1598349250450 |    111
 40aee4db-1c05-4fdf-a984-612829d6900b | 555  | 1598332159787 |    555
 40aee4db-1c05-4fdf-a984-612829d6900b | 111  | 1598324747731 |    111
 40aee4db-1c05-4fdf-a984-612829d6900b | 111  | 1598277187123 |    111
 40aee4db-1c05-4fdf-a984-612829d6900b | 819  | 1598167189807 |    819
 40aee4db-1c05-4fdf-a984-612829d6900b | 900  | 1598167189807 |    900
 40aee4db-1c05-4fdf-a984-612829d6900b | 777  | 1598159542960 |    777
 40aee4db-1c05-4fdf-a984-612829d6900b | 900  | 1597657275755 |    900
```

@samkanga ^^ is what has been uploaded to this jurisdiction so far.  The value that is used in the reports of 200 is the very latest thing uploaded.

You can verify this for yourself by running [this query in SQL lab](https://superset.reveal-na.smartregister.org/superset/sqllab?id=10).

**Comment by samkanga** [comment]
@moshthepitt not sure where the missing link is on this one. I have uploaded a new value to test this. Let's see how this goes and we can plan a way forward. In the meantime I will provide a screenshot of the present value uploaded of 566 as seen from the apk.

![image](https://user-images.githubusercontent.com/5908630/91845244-7957c700-ec61-11ea-9a24-37fa81ab7e26.png)

**Comment by moshthepitt** [comment]
@samkanga we need to verify what the mobile app is using.  There does not seem to be a value of 566 in the database.

**Comment by samkanga** [comment]
@githengi share some insight on the setup of the android client. Trying to determine the missing link to the uplaoded csv.

**Comment by githengi** [comment]
@samkanga @moshthepitt  the settings used as the jurisdictions upload for targets. This is the values used on stage https://reveal-stage.smartregister.org/opensrp/rest/v2/settings/?identifier=jurisdiction_metadata-target&serverVersion=0

**Comment by moshthepitt** [comment]
@Wambere could you please look into this?  It seems that the Canopy DB has items that don't match the API e.g. https://reveal-na.smartregister.org/opensrp/rest/v2/settings/?identifier=jurisdiction_metadata-target&serverVersion=0 currently returns only 1 item.

**Comment by moshthepitt** [comment]
@Wambere so the TODO is:

- ensure we get rid of deleted items
- change so that we fetch every 10 min

**Comment by Wambere** [comment]
@moshthepitt this is updated

**Comment by samkanga** [comment]
Thanks @Wambere. I will do another test and share some feedback on my findings.

**Comment by moshthepitt** [comment]
@Wambere is it also updated for stage, and zambia prod?

**Comment by Wambere** [comment]
@moshthepitt I'm getting an error updating stage. Some records have keys with 37 characters instead of 36. Is this intentional? should I update the table to allow this?

**Comment by moshthepitt** [comment]
Please do not update the table.  Share this so that the OpenSRP engineers can fix.

**Comment by samkanga** [comment]
@moshthepitt , @Wambere I can confirm that I uploaded a new value against Namibia production and it has reflected on the dashboard. Thank you for the fix.

**Comment by Wambere** [comment]
@samkanga just for clarity, this fix is not working on stage because of the issue I have raised above. Please follow up with the openSRP team to ensure that this is fixed

**Comment by moshthepitt** [comment]
Closed because this was fixed.
