### ISSUE TITLE
Pressing log out does not completely log out completely even when the user did not select key me logged in

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1224]
- [ ] The logout option for the Reveal WebUI on Namibia prodution seems not to be completely logging out a user. When a user clicks on the OpenSRP button, he gets logged in with the last user account that was logged in. The logout needs to be enforced so that a user who logs out need to provide credentials the next time they login.

**Comment by moshthepitt** [comment]
@p-netm please follow up with the OpenSRP team to ensure that this works as expected

**Comment by githengi** [comment]
@p-netm add token when invoking logout URL. Currently it being invoked and logout is failing since authentication or session is missing.

**Comment by p-netm** [comment]
closed By #1235
