### ISSUE TITLE
The header menu items on Thailand have mixed small letters and capital

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1225]
This is a translated page so I may not be certain:
But if you look at the rest of the titles, the first letter is a capital while "assign" is in small letters

![image](https://user-images.githubusercontent.com/61143692/91842351-8d4cfa00-ec5c-11ea-9790-300745d05280.png)

**Comment by moshthepitt** [comment]
This is happening because of the translation.  We can't really fix it (not possible)
