### ISSUE TITLE
How to handle goal_value = 0?

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#123]
1. What is an example of a goal whose goal value is `0`?
2. How do you calculate progress towards its achievement?

**Comment by craigappl** [comment]
We do not have a clear use case for this. See #122

**Comment by moshthepitt** [comment]
@craigappl @cKellyDesign right now the `goalPercentAchieved` function will always return a 0 for this.  Going to close this issue.  If it becomes a problem in the future we shall create new issues.
