### ISSUE TITLE
IRS reports map not showing all structures

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1232]
Consider this report https://web.reveal-stage.smartregister.org/intervention/irs/report/5640fcc2-772a-5e06-9e00-491e3aa544f5/6be2f032-ab8e-4f0d-999c-d951f7040418/map which should be displaying 9 structures on the map, but only shows 1.

![Oo](https://user-images.githubusercontent.com/372073/91873593-e0857380-ec81-11ea-963c-b6e5f29509e4.png)

The data is [there](https://superset.reveal-stage.smartregister.org/superset/slice_json/592?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%226be2f032-ab8e-4f0d-999c-d951f7040418%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22},{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%225640fcc2-772a-5e06-9e00-491e3aa544f5%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000}).

**Comment by p-netm** [comment]
![Screenshot from 2020-09-09 16-20-55](https://user-images.githubusercontent.com/28119869/92603865-7a6ba280-f2b8-11ea-909d-569c11e6b165.png)

**Comment by moshthepitt** [comment]
Nice work
