### ISSUE TITLE
RVL-1126 - Jurisdiction names in jurisdiction metadata has metadata appended to it

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1239]
- [ ] On the Namibia Production, when a user download the csv file from the "Download Jurisdiction Metadata" section, the jurisdiction names come with ad appended "metadata" addition See screenshot below.
![image](https://user-images.githubusercontent.com/5908630/92074295-68709800-edbe-11ea-9618-ab8cefdba082.png)

**Comment by p-netm** [comment]
This looks like a problem with the upload, the metadata is added automatically in the upload.
@moshthepitt Was this intentional?
