### ISSUE TITLE
Error when trying to get user count endpoint while creating a practitioner, likely due to keycloak permissions

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1249]
We're getting an error when trying to create a practitioner in the OpenSRP server:
![image](https://user-images.githubusercontent.com/6067053/92248814-1a22ce00-ee7e-11ea-9cf7-e7a1192e5b07.png)

The superset-user doesn't have the VIEW KEYCLOAK USERS role that's on other systems:
Nigeria superset-user permissions
![image](https://user-images.githubusercontent.com/6067053/92248681-e3e54e80-ee7d-11ea-81cc-e0b1eae71ae9.png)
Namibia superset-user permissions
![image](https://user-images.githubusercontent.com/6067053/92249172-8271af80-ee7e-11ea-86d3-848fdb8bd21a.png)

**Comment by craigappl** [comment]
it looks like I have access to the roles and I will see if I can adjust it.

**Comment by p-netm** [comment]
@craigappl @moshthepitt @ciremusyoka closing this, since this looks like it was resolved
