### ISSUE TITLE
RVL-1002 - Active FI Map tooltip

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1250]
Render a tool tip upon click of the index case point, include: Case number, Case Classification, and Date of Diagnosis

**Comment by moshthepitt** [comment]
Related https://github.com/onaio/reveal-frontend/issues/930

**Comment by p-netm** [comment]
Elsewhere where we have similar functionality: `PlanForm > CaseDetails`.
we get extract the eventId from the plan by looking for the `opensrpEventId` `useContext` object, we then make a get request to opensrp `event/findBy` endpoint.

for this useCase however; we are getting the plans from superset, and they do not have the eventIds

**Comment by moshthepitt** [comment]
The best solution would be to refactor the Canopy views used for Thailand to include the missing information.

**Comment by mberg** [comment]
After 1023 and 1024

**Comment by lincmba** [comment]
@moshthepitt 
Only events of `'eventType': 'Case Details'` have the fields `case_classification`, `case_number` and `investigtion_date` in the `raw_events` table. However, these events, unlike other events don't have a `task_id` or any other foreign key that would link to a `plan`, `goal` or `goal_target`. 

It's therefore a challenge to have the these fields in the `task_structures_materialized_view` . 
Could the events `full_json` be updated with task_id? Or would it be okay to have an independent query for this.

Sample event full_json of eventType `Case Details`:
```
json
{'id': '7c4ec36f-391a-46c8-ac3f-4fc6288aeee7',
 'obs': [],
 'type': 'Event',
 'teamId': 'bd2efe2b-7dcf-4d48-b2ac-27fced048713',
 'details': {'age': '27',
  'species': 'M',
  'surname': 'Doe',
  'focus_id': '3951',
  'first_name': 'Holly',
  'focus_name': 'Akros_1',
  'case_number': '151311000001089190221104722501',
  'family_name': 'Holly',
  'focus_reason': 'Investigation',
  'focus_status': 'B1',
  'house_number': '',
  'ep1_create_date': '2019-09-06T08:41:49.237+0000',
  'ep3_create_date': '2019-09-06T08:41:49.237+0000',
  'investigtion_date': '2019-09-06T00:00:00.000+0000',
  'case_classification': 'A'},
 'version': 1557860282617,
 'duration': 0,
 'revision': 'v3',
 'eventDate': '2019-09-06T02:00:00.000+02:00',
 'eventType': 'Case Details',
 'dateEdited': '2019-11-28T15:13:37.922+02:00',
 'entityType': 'Case Details',
 'locationId': '3951',
 'providerId': 'nifi-user',
 'dateCreated': '2019-09-09T16:10:17.736+02:00',
 'identifiers': {},
 'baseEntityId': '3951',
 'serverVersion': 1574946962899,
 'formSubmissionId': '887ed95d-a6b3-4503-82f1-56311053cbc7'}
```

**Comment by moshthepitt** [comment]
@lincmba there is a OpenSRPEventId field in the plan object that you can use to relate these to a plan.

cc @Wambere

**Comment by lincmba** [comment]
Found a way to link `Case Details` events to a plan. 
Done this using the raw_plans and raw_events tables in the public schema. This work should be moved to `reveal_stage` schema once the `plans` table has the field `fi_opensrpeventid ` that @Wambere is working on.

**Comment by lincmba** [comment]
@moshthepitt @Wambere 
There are no events of event_type `Case Details` in any schema in reveal Thailand preview.
This is also the case in reveal stage except in raw_events table in public schema.

I created `plans_case_details` table on the  `reveal_stage` schema and populated it with plans from raw_plans table that had opensrpEventId with fi_opensrpeventid as a column, these were 262 records.
Also created `events_case_details` table on the  `reveal_stage` schema and populated it with events of event_type `Case Details` from raw_events table, these were 147 records.

However, when joining these two tables in [this](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/4-FI/1-Thailand-2019/deploy/task_structures_materialized_view.psql) materialized view, none of the records are picked from either table, since, no `tasks.plan_identifier` record matches any `plans_case_details.identifier`. 
Created `task_structures_materialized_view_case_details` in `reveal_stage` schema with the above details.

**Comment by moshthepitt** [comment]
@lincmba please reach out to @Wambere on slack to work out how to get those events synced.

**Comment by lincmba** [comment]
@moshthepitt reached out. Syncing is underway.

Given the challenges outlined, will we still proceed with the original implementation to have these fields in `task_structures_materialized_view` or will we need to change the approach to may be to have a different materialized view for this?

**Comment by moshthepitt** [comment]
> Given the challenges outlined, will we still proceed with the original implementation to have these fields in task_structures_materialized_view or will we need to change the approach to may be to have a different materialized view for this?

Sorry I missed this.  What are the challenges that may result in us using different materialized views?

**Comment by lincmba** [comment]
There are no challenges in using different materialized views, there are challenges in using the existing materialized views.

**Comment by moshthepitt** [comment]
> There are no challenges in using different materialized views, there are challenges in using the existing materialized views.

Sorry, I am asking what are those challenges?

**Comment by lincmba** [comment]
The [task_structures_materialized_view](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/4-FI/1-Thailand-2019/deploy/task_structures_materialized_view.psql) primarily references the tasks table. Then from the tasks table, is joined to other tables (actions, jurisdictions ...) using the `tasks.plan_identifier` field.

Plans with opensrpEventId are not among these plans referenced by tasks. i.e no task references plans with opensrpEventId. 

Therefore joining these plans to the task_structures_materialized_view will have these columns with no data. opensrpEventId is the link we have between the events and the plans.

**Comment by moshthepitt** [comment]
I don't mind you using a new view for this.  Just make it clear how to filter that new view by plan and jurisdiction and task code (or goal id)

**Comment by moshthepitt** [comment]
Unblocked by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/40

**Comment by samkanga** [comment]
@moshthepitt what is the block on this ticket?

**Comment by moshthepitt** [comment]
> @moshthepitt what is the block on this ticket?

Resourcing constraints

**Comment by ciremusyoka** [comment]
@lincmba the quotes on jurisdiction ids should be removed. See jurisdiction_id column on [this slice](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22queryFields%22%3A%7B%22groupby%22%3A%22groupby%22%2C%22metrics%22%3A%22metrics%22%7D%2C%22datasource%22%3A%22169__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A611%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22Last+week%22%2C%22groupby%22%3A%5B%22event_id%22%2C%22case_classification%22%2C%22case_number%22%2C%22date_of_diagnosis%22%2C%22plan_id%22%2C%22goal_id%22%2C%22jurisdiction_id%22%2C%22action_code%22%2C%22task_id%22%2C%22id%22%5D%2C%22metrics%22%3Anull%2C%22all_columns%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22row_limit%22%3A10000%2C%22order_desc%22%3Atrue%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22smart_date%22%2C%22color_pn%22%3Atrue%2C%22show_cell_bars%22%3Atrue%7D).

**Comment by ciremusyoka** [comment]
> @lincmba the quotes on jurisdiction ids should be removed. See jurisdiction_id column on [this slice](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22queryFields%22%3A%7B%22groupby%22%3A%22groupby%22%2C%22metrics%22%3A%22metrics%22%7D%2C%22datasource%22%3A%22169__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A611%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22Last+week%22%2C%22groupby%22%3A%5B%22event_id%22%2C%22case_classification%22%2C%22case_number%22%2C%22date_of_diagnosis%22%2C%22plan_id%22%2C%22goal_id%22%2C%22jurisdiction_id%22%2C%22action_code%22%2C%22task_id%22%2C%22id%22%5D%2C%22metrics%22%3Anull%2C%22all_columns%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22row_limit%22%3A10000%2C%22order_desc%22%3Atrue%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22smart_date%22%2C%22color_pn%22%3Atrue%2C%22show_cell_bars%22%3Atrue%7D).

This was fixed.
