### ISSUE TITLE
RVL-1133 - Monitoring Tab not loading plans

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1251]
- [ ] The monitoring tab on the Thailand WebUI Preview environment, is not loading plans. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/92377696-35573d00-f10d-11ea-9e50-01ac415a3e63.png)

**Comment by moshthepitt** [comment]
![Screenshot from 2020-09-07 15-25-01](https://user-images.githubusercontent.com/372073/92387507-570cf000-f11e-11ea-90d0-4d4cfa54d375.png)

Maybe this is the root cause ^^
