### ISSUE TITLE
Dynamic FI Plans Missing Details in the FI Plans for Thailand

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1261]
- [x] The Dynamic FI plans on the Thailand preview does not show details that were there on the initial FI plans This include:
- Action plan type - Routine 
- Source of infection

Screenshot 1 below shows sample from Thailand Preview
![image](https://user-images.githubusercontent.com/5908630/92490408-ac69ff80-f1f9-11ea-9814-18dce1ba4982.png)

Screenshot 2 below shows sample from Thailand Production
![image](https://user-images.githubusercontent.com/5908630/92490511-cb689180-f1f9-11ea-8c7b-9d52235b6659.png)

**Comment by moshthepitt** [comment]
Let's ensure the FI Status and FI Reason fields are present for Dynamic-FI plans.

**Comment by armageddon** [comment]
There is also logic in the Nifi flows to determine which activities should be included in the plan (for these routine plans created in the WebUI, and case-triggered plans )

**Comment by armageddon** [comment]
https://smartregister.atlassian.net/wiki/spaces/REV/pages/1150910530/Auto+Plan+Task+Gen+multiple+cases+1+active+focus+plan
