### ISSUE TITLE
Dont send empty metadata

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1269]
It seems that when you try to upload metadata which contains blank lines e.g. [smaller.csv.zip](https://github.com/onaio/reveal-frontend/files/5199830/smaller.csv.zip) you send a payload to the server which is like this:

```json
{
    "settingConfigurations": [
        {
            "identifier": "jurisdiction_metadata-population",
            "settings": [
                {
                    "description": "Jurisdiction Metadata for Zambia NTD 2020 id ce7e08b3-896b-4e74-9ef3-45d71143c70z",
                    "key": "ce7e08b3-896b-4e74-9ef3-45d71143c70z",
                    "label": "Zambia NTD 2020 metadata",
                    "value": ""
                },
                {
                    "description": "Jurisdiction Metadata for Southern id 1291e101-5835-41a2-984a-33ee8418bdbz",
                    "key": "1291e101-5835-41a2-984a-33ee8418bdbz",
                    "label": "Southern metadata",
                    "value": ""
                },
                {
                    "description": "Jurisdiction Metadata for Gwembe id 0291e101-5835-41a2-984a-33ee8418bdbz",
                    "key": "0291e101-5835-41a2-984a-33ee8418bdbz",
                    "label": "Gwembe metadata",
                    "value": "25771"
                }
            ],
            "type": "SettingConfiguration"
        }
    ]
}
```

This will result in a 500 from the API server because of the items whose value field is `""`.

We need to modify our code such that we do not send these empty values to the API server.

**Comment by ciremusyoka** [comment]
@moshthepitt is `value` the only property that should not be blank? 
Should we also ensure `label` and `key` are not blank?

**Comment by moshthepitt** [comment]
@ciremusyoka yes.  Although the key is the jurisdiction id and the label is the jurisdiction name so those are harder to be blank.

**Comment by moshthepitt** [comment]
But lets drop anything that has a blank key or label or value

**Comment by ciremusyoka** [comment]
Should we drop the rows with blanks or throw an error (e.g inavlid csv)?

**Comment by moshthepitt** [comment]
Let us do it this way:

- If only some values are missing, we should drop those rows silently (we assume that the user downloaded the template and then filled in just the ones she wanted)
- if all values are missing then raise an error
- if any key or label is missing then raise an error

**Comment by moshthepitt** [comment]
@ciremusyoka lets also document the above rules in the code in a comment or docstring
