### ISSUE TITLE
See historical index cases on the WebUI- the pop up should have information on them when clicked

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1275]
https://web.reveal-th-preview.smartregister.org/focus-investigation/map/9cf6f809-8729-54d3-a526-d000c2985416
When one clicks on the pop up, it's blank
There should be information on it when clicked.
![image](https://user-images.githubusercontent.com/61143692/93101025-783b8680-f6b2-11ea-93a3-3ead526430bd.png)

**Comment by p-netm** [comment]
duplicate of #1250
