### ISSUE TITLE
RVL-1165 Dynamic Plan triggers and FHIRPath should be hidden in create/update plan page - Thailand

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1279]
- [ ] The client has asked that we hide the triggers and the FHIRpath details on the Thailand dynamic plans.

**Comment by moshthepitt** [comment]
@samkanga I don't think that this is something that we should do.

Do we have more information on why the client wants this hidden?

**Comment by samkanga** [comment]
@moshthepitt they say the details are confusing to the users. Tagging @craigappl  for additional thoughts on this.

**Comment by moshthepitt** [comment]
Yeah, I am not sure about this.  The web app already has like 60 config variables to hide or show various things.  I don't want to continue going down that path.

**Comment by moshthepitt** [comment]
@samkanga @craigappl @p-netm

**Comment by p-netm** [comment]
hmm,.. yeap the envs are getting a little crazy and overwhelming.

**Comment by craigappl** [comment]
@moshthepitt , Thailand has stated that it's too confusing for the users and adds too much information when they won't actually change it from the template. In the long run,  we would want to remove this logic so that it's abstracted from users. Right now, we make it available because users may need to tweak the logic until we get it right.

**Comment by moshthepitt** [comment]
@craigappl @samkanga Thanks,  some questions:

1. It seems okay to mark this issue as not "high priority" - do you agree?
2. Long term we need to be cognizant of the fact that adding too many of these configurations where things are hidden or work slightly differently makes our code increasingly complex and harder to maintain (every new piece of code is future technical debt and developer mental load).  So we should push back whenever possible

**Comment by craigappl** [comment]
@moshthepitt how about a compromise. Can we add all of these items in a collapsible menu with the default to be collapsed? The collapsed label could be "Triggers and Conditions"

**Comment by moshthepitt** [comment]
@craigappl that sounds good to me, thank you.
