### ISSUE TITLE
Plan not showing data for MDA reporting - Zambia production 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1291]
There are two plans that should have data coming through from testing and training yesterday: 

**[NTD GW Training Plan 17.09.20](https://web.reveal-zm.smartregister.org/intervention/mda/report/224a2c06-02d5-5d86-8be9-1673f274665a)**
According to Akros, they trained against this plan all day yesterday and today. There is no data showing up in the reporting view, nor is it even loading the hierarchy. 

**[NTD Kashikishi Test 17.09.20](https://web.reveal-zm.smartregister.org/intervention/mda/report/bdf5775b-59fa-5f27-bb5f-3d6b73540061)**
Data is no showing, but it wasn't for many hours yesterday - possibly close to 12. Similarly to above, the hierarchy wasn't showing, it just said "No Data Found" when you clicked on it. It is now showing data, but it does not match what is in the in-app indicators. This may be caused by the previously recorded issue. 

Current in-app indicators / (web indicators) 
Registered child treated: 75% (28.85%)
PZQ dispensed: 44.5 (32.5)
Structures visited: 4% (3.15%)

**Comment by moshthepitt** [comment]
Closed by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/35
