### ISSUE TITLE
RVL-1181 - Plan Monitor Page Indicators are not displaying

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1292]
- [ ] The indicators on the monitor page are not showing for some plans. See the screenshot below:
![image](https://user-images.githubusercontent.com/5908630/93589030-ec2ca600-f9b4-11ea-81d8-bc0a57bf4350.png)

**Comment by moshthepitt** [comment]
Looks okay please see https://web.reveal-th-preview.smartregister.org/focus-investigation/map/50a5e387-722c-5ade-a2cd-9bae070911a5

**Comment by samkanga** [comment]
@moshthepitt check this out: https://web.reveal-th-preview.smartregister.org/focus-investigation/map/50a5e387-722c-5ade-a2cd-9bae070911a5

**Comment by samkanga** [comment]
@moshthepitt I erroneously deleted a comment you made regarding plan https://web.reveal-th-preview.smartregister.org/focus-investigation/map/50a5e387-722c-5ade-a2cd-9bae070911a5 Not sure if there is a way to restore.
