### ISSUE TITLE
For Plans that Task generation is done by OpenSRP server add useContext task generation status

### ISSUE THREAD

**Issue by githengi** [onaio/reveal-frontend#1295]
For Plans that Task generation is done by OpenSRP server add  task generation status with value internal

```
        "useContext": [
            .......................
            {
                "code": "taskGenerationStatus",
                "valueCodableConcept": "internal"
            }
        ]
```

Currently task generation is only being done on OpenSRP server if the concept is provided

**Comment by p-netm** [comment]
- [ ] for non-Th deployments.

**Comment by p-netm** [comment]
@moshthepitt @ciremusyoka 
seems like I'll have to introduce a new env for this:
`REACT_APP_TASK_GENERATION_STATUS`, any contraindication?

**Comment by moshthepitt** [comment]
sadly no we need this
