### ISSUE TITLE
Dashboard Values not showing for Lower Levels on Zambia Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1297]
- [ ] When one is drilling down on the Zambia production dashboard, the figures do not show from the Zone level going downwards.

**Comment by moshthepitt** [comment]
The problem is that the number of levels in the jurisdiction tree/hierarchy has changed.  The existing reports need to be updated to cater to this.

**Comment by moshthepitt** [comment]
Was fixed
