### ISSUE TITLE
Plans created in "Thailand test site BVBD 3" area do not load in Monitor Tab

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1299]
- [x] The Thai team have created a new operational area named **Thailand test site BVBD 3**. An attempt to select a plans assigned into this area under the monitoring tab, is going into an endless spinner.

**Comment by craigappl** [comment]
This was an issue because the underlying datasource table was limiting the query results to 1k results which meant that the plan wasn't returned to the slice. I increased this limit to 5k and it started showing up again.
