### ISSUE TITLE
RVL-1200 -  Foci boundary update not displaying in Web UI monitoring tab (even though successfully synced from device to server)

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1308]
**Web: 0.7.6
Android: 5.2.10**
**Plan:** **Dynamic-FI 2020-09-21- VR Test II**

1. Refer to screenshots below for the foci boundary in the Android App vs Monitoring tab
2. The structure with the red roof at the bottom right of the operational area was included in the foci boundary in the mobile app (orange circle) but is not reflecting in the Web UI.
3. The foci boundary update has synced with the server as I have tried re-installing the app and the change is persisting in Android.

Boundary on Android:
![image](https://user-images.githubusercontent.com/5908630/93880241-d507f400-fce5-11ea-81ed-b1aaf7354bfc.png)

Boundary on Web:
![image](https://user-images.githubusercontent.com/5908630/93880309-ef41d200-fce5-11ea-9780-2ba33c6d941d.png)

**Comment by p-netm** [comment]
the structure is there on the webui, its just that the jurisdiction layer seems to be shifted to the left.
looking at the coordinates
superset response: 
```
    "geometry": {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              100.5244829,
              13.8576014
            ],
            [
              100.5255805,
              13.8428809
            ],
            [
              100.5191809,
              13.8435201
            ],
            [
              100.5112049,
              13.8444406
            ],
            [
              100.5123746,
              13.8519458
            ],
            [
              100.5121894,
              13.8570175
            ],
            [
              100.5183504,
              13.8584364
            ],
            [
              100.5244829,
              13.8576014
            ],
            [
              100.5235115,
              13.8477299
            ]
          ]
        ]
      ]
    },
    "properties": {
      "status": "Active",
      "parentId": "45042d61-2305-4b67-87f4-a451339f79c7",
      "name": "Thailand test site BVBD 2",
      "geographicLevel": 5,
      "version": 9,
      "username": "bvbd_test",
      "OpenMRS_Id": "eed81741-f168-4723-99d8-16a513445a35",
      "externalId": "1201030202",
      "name_en": "Thailand test site BVBD 2"
    },
```
superset response:

```
"{\"id\": \"a7baf57d-ad31-46d2-8d28-0c81dd306b09\", \"type\": \"Feature\", \"geometry\": {\"type\": \"MultiPolygon\", \"coordinates\": [[[[100.5244829, 13.8576014], [100.5247541, 13.8427082], [100.5182666, 13.8392861], [100.5126029, 13.8440269], [100.5123746, 13.8519458], [100.5121894, 13.8570175], [100.5183504, 13.8584364], [100.5244829, 13.8576014]]]]}, \"properties\": {\"jurisdiction_name\": \"Thailand test site BVBD 2\", \"jurisdiction_parent_id\": \"45042d61-2305-4b67-87f4-a451339f79c7\"}}"
```

looking at the co-ordinates: they are not equal.

cc @moshthepitt @githengi

**Comment by moshthepitt** [comment]
@p-netm can you track down where this happens in Canopy?

**Comment by p-netm** [comment]
> @p-netm can you track down where this happens in Canopy?

ok

**Comment by p-netm** [comment]
@samkanga after refreshing the jurisdictions_geojson view;  the superset geometry now matches that which is in opensrp, 
![Screenshot from 2020-09-23 11-41-36](https://user-images.githubusercontent.com/28119869/93988891-ed354d00-fd91-11ea-8009-31fa11a88fac.png)

**Comment by samkanga** [comment]
@Wambere the issue on this ticket is still unresolved. For example, looking at the plan on this [link](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/473054f7-03f0-5b3c-8a44-395d4ad106d1) The boundaries do not match what is on the synced android client. Find below  a screenshot on what is on the android client vs what is on the webUI. cc; @Naima-Bashir 

![image](https://user-images.githubusercontent.com/5908630/95427364-1b995780-0950-11eb-8fe3-12bb8b891c81.png)

**Comment by samkanga** [comment]
I will close this ticket as the issue here has been resolved.
