### ISSUE TITLE
Error When Creating a New Plan on Namibia Production WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1310]
- [ ] When creating a new plan, I get the error on the screenshot below.
![image](https://user-images.githubusercontent.com/5908630/94131678-e4fb1180-fe66-11ea-8f0e-5175d9117781.png)

- A check on the developer tools on the browser shows an error when trying to GET the url: https://reveal-na.smartregister.org/opensrp/rest/user?page_size=1000&source=Keycloak&start_index=0

**Comment by ciremusyoka** [comment]
@samkanga please confirm if you are still getting this error.

**Comment by samkanga** [comment]
@ciremusyoka this was resolved.
