### ISSUE TITLE
Add children treated count to NTD MDA dashboards 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1311]
For the NTD dashboards, we want to add one new indicator / column: # of children treated. 

This should just be a count of all the children with completed MDA dispense forms. I believe we already query this number for the numerator of % of registered children treated. 

From a UI perspective, we'd want this column to be directly to the left of the # of PZQ column.

**Comment by gstuder-ona** [comment]
Fix deployed from here: https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/35/commits/0913299a8088129432296e26ce63d6ccc0720d92

**Comment by moshthepitt** [comment]
More context: https://onaio.slack.com/archives/CBSU8L2SC/p1600925464005500

**Comment by moshthepitt** [comment]
The new column is gotten from `n_events_where_pzqdistributed` and should be title `# of children treated`
