### ISSUE TITLE
Remove partially sprayed from the web ui side menu - Zambia

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1320]
- Remove partially sprayed from the webUI side menu for Zambia. All structures that partially sprayed should be counted as sprayed. i.e appear green on the map.

**Comment by moshthepitt** [comment]
They are already counted as sprayed.

**Comment by moshthepitt** [comment]
Also fixed in https://github.com/onaio/opensrp-inventories/commit/84a06d62ee1c1adc20fdc711e6a020ec2870bd96
