### ISSUE TITLE
All 43 data Collectors not viewable on IRS Performance Reporting

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1323]
- [ ] There are 43 data collectors syncing data against the plan named "VL Zambia 2020 Traning Plan". However, only 36 data collectors can be seen from both Chadiza and Nchelenge Districts.

**Comment by ciremusyoka** [comment]
@moshthepitt if i count the unique data collectors in this districts working under the above plan i get 39. 
Two aren't displayed because they don't have matching location ids on the Spray and daily summary event types, and one doesn't totally exist on the Spray event type.

**Comment by craigappl** [comment]
@ciremusyoka , which field in the event are you using to do those counts?

**Comment by ciremusyoka** [comment]
@craigappl Am using the `provider_id` and  district id(found by joining the `location_id` with jurisdictions).

**Comment by craigappl** [comment]
We did a review today and it appears that only 39 data collectors are returned. The data appears to be accurate.

**Comment by craigappl** [comment]
Here's a sample query for historical reasons:
```
SELECT DISTINCT(provider_id) FROM events
LEFT JOIN jurisdictions_materialized_view AS materialized_jur
    ON location_id = materialized_jur.jurisdiction_id
LEFT JOIN jurisdictions as jurisdiction_querry ON jurisdiction_querry.id = materialized_jur.jurisdiction_path[3]
WHERE event_type = 'daily_summary' 
AND plan_id = '7e4aba56-d5cc-5b3c-9e01-966e757c389e'
AND jurisdiction_querry.id in ('7d1297d2-a7e7-4896-a391-31d14cab9d32', 'a31047b0-0240-4ea5-af8b-d0418a4a099a')
```

**Comment by moshthepitt** [comment]
Closed via https://onaio.slack.com/archives/CBSU8L2SC/p1601638553211800
