### ISSUE TITLE
THAI- Data missed in syncing between Plans and in holding tables  RVL-691

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1333]
TESTING UPDATE 03/02/2020:

user: bvbd_test

area: Thailand test siste BVBD 1

app versions tested on: 2.7.5 and 3.1.2

 

Release 3.1.2:

Created a plan A1 Thailand test site BVBD 1 2020-01-22 RMK release 3.1.2 entered data while offline and synced the data after the plan expired. 

 

Release 2.5.5

Created plan A1 Thailand test site BVBD 1 2020-01-30 RMK 2.7.5 entered data while offline and synced the data after the plan expired. 

 

 Observations:

The submitted data for both plans is visible on the dashboard.
![image](https://user-images.githubusercontent.com/61143692/95066038-89544200-070a-11eb-9edc-223b10279f0c.png)
![image](https://user-images.githubusercontent.com/61143692/95066061-92451380-070a-11eb-86d4-ac49d75b6562.png)
![image](https://user-images.githubusercontent.com/61143692/95066079-9709c780-070a-11eb-86e6-649420e896d6.png)
![image](https://user-images.githubusercontent.com/61143692/95066101-9cffa880-070a-11eb-8481-949c60c0735e.png)
![image](https://user-images.githubusercontent.com/61143692/95066114-a25cf300-070a-11eb-93a7-b67be0630647.png)
![image](https://user-images.githubusercontent.com/61143692/95066127-a7ba3d80-070a-11eb-82ab-049370ac93d3.png)
![image](https://user-images.githubusercontent.com/61143692/95066148-ac7ef180-070a-11eb-8122-cbdc9c78091a.png)

**Comment by moshthepitt** [comment]
Seems this is fixed.  Please re-open if not.
