### ISSUE TITLE
Trying to assign a team to a plan previously assigned fails on Namibia Production 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1335]
- [ ] When a user assigns a team to a plan, then later removes the assignment of the the team to the plan, an attempt to assign the team to the plan  second time fails with an error 400 (see screenshot below) when trying to POST to the url https://reveal-na.smartregister.org/opensrp/rest/organization/assignLocationsAndPlans
![image](https://user-images.githubusercontent.com/5908630/95289268-013d7c00-0873-11eb-91e1-c0b970832e72.png)

**Comment by moshthepitt** [comment]
Blocked by API work

**Comment by githengi** [comment]
@moshthepitt I have tested this now it works.  This issue was created on October 7th 8.34 am GMT. However the version with fix on assignment bugs was deployed later in the same day  at 1.pm.

**Comment by moshthepitt** [comment]
Thanks @githengi - I think @Naima-Bashir and I were also noticing that it works while testing yesterday.  Going to close this issue.
