### ISSUE TITLE
Duplicates when Downloading Jurisdiction Metadata on Namibia Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1337]
- [ ] We previously had an issue where we got duplicates when downloading jurisdiction meta data on targets on Namibia Production. This was resolved and had been working OK. However, the issue appears to have recurred as shown on the screenshot below of a document that I downloaded.

![image](https://user-images.githubusercontent.com/5908630/95343012-b5192880-08c0-11eb-8ae4-b2877c4183ae.png)

**Comment by moshthepitt** [comment]
@samkanga this is an issue with the server API.  Does it have the changes that fixed these issues deployed?

Maybe we need to clear the settings in the server database and then reupload and see if all is ok?

**Comment by moshthepitt** [comment]
Let's modify the jurisdiction metadata payload as follows:

```json
{
  "settingConfigurations": [
    {
      "identifier": "jurisdiction_metadata-target",
      "_id": "THE DOCUMENT ID",
      "settings": [
        {
          "description": "Jurisdiction Metadata for EVULUKULO training id 1066a3b6-0bec-418c-acc3-ecda1632ca4c",
          "key": "1066a3b6-0bec-418c-acc3-ecda1632ca4c",
          "label": "EVULUKULO training",
          "value": "3500",
          "uuid": "THE SPECIFIC SETTINGS ID"
        }
   ]
}
```

#### Where

- THE DOCUMENT ID:  lets generate a UUID deterministically (uuid v5) using the identifier (in this case "jurisdiction_metadata-target")
- THE SPECIFIC SETTINGS ID: lets put the same value as key (the jurisdiction id) (this is for each setting)

**Comment by moshthepitt** [comment]
@ciremusyoka small update:

THE SPECIFIC SETTINGS ID -  lets generate a UUID deterministically (uuid v5) using the identifier and key
