### ISSUE TITLE
THAI- The plans list shows 2 out of "0" instead of the total number of oages

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1338]
Login to thai preview: https://web.reveal-th-preview.smartregister.org/plans/list
Click on plans list. 
Scroll to the bottom and observe the number of pages shown in the total(image below)

![image](https://user-images.githubusercontent.com/61143692/95357486-9589fc00-08d0-11eb-8e25-53e1d7697ae0.png)
![image](https://user-images.githubusercontent.com/61143692/95357531-a20e5480-08d0-11eb-9aa0-ed95d11d78cc.png)

**Comment by moshthepitt** [comment]
Seems this is fixed or only happens when the page is translated using Google translate.  Please re-open if not.
