### ISSUE TITLE
RVL-1248 - Coverage targets not updating in assign jurisdictions - Namibia

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1341]
On Namibia Production:
Once you have input the coverage targets in the jurisdiction metadata section of the Web UI, it does not update the structure counts for that OA in the assign jurisdiction section.

**Steps to reproduce:**
1. In jurisdiction metadata, upload a csv. with targets for Onguta - 600 and Omatunda - 600
2. Download the target data from jurisdiction metadata to check the target was successfully assigned
![image](https://user-images.githubusercontent.com/5908630/95545448-9624ae80-0a06-11eb-8b44-b7ea67ad7542.png)
3. Go to the planning tool and create a new test plan, save this in draft form
4. Click the plan to assign jurisdictions
5. Check the structure counts for Onguta and Omatunda
![image](https://user-images.githubusercontent.com/5908630/95545514-bc4a4e80-0a06-11eb-958a-fe697ece3df1.png)
![image](https://user-images.githubusercontent.com/5908630/95545531-c8cea700-0a06-11eb-9e9e-a2b4ac6e841d.png)
6. The number of structures in the assign jurisdiction section does not match those from the target set in jurisdiction metadata

**Comment by moshthepitt** [comment]
@samkanga this works as expected.  The structure count does not come from "jurisdiction metadata".  It comes from a count of structures associated to the jurisdiction in the OpenSRP Database.

Not sure we are going to change this any time soon so marking this as "wontfix".

**Comment by samkanga** [comment]
@moshthepitt thanks for the information.
