### ISSUE TITLE
THAI LOCAL  There are no other users shown when one clicks on the user filter

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1345]
There are no other users shown when one clicks on the user filter

![image](https://user-images.githubusercontent.com/61143692/95622300-dc682500-0a7b-11eb-8856-af119621dfdb.png)
superset user

**Comment by moshthepitt** [comment]
@Naima-Bashir this is because for some reason this URL https://servermhealth.ddc.moph.go.th/opensrp/rest/user?page_size=1000&source=Keycloak&start_index=0 does not return anything currently

**Comment by moshthepitt** [comment]
@samkanga assigning this to you so that you can follow up with the API team.

**Comment by samkanga** [comment]
@Rkareko please help here.

**Comment by samkanga** [comment]
I will move this issue [here](https://github.com/OpenSRP/web/issues/81) and close this ticket.
