### ISSUE TITLE
THAI LOCAL  Clicking the OAs in the focus investigation 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1346]
I get an internal server error(500) when i still try to access some FI OAs (superset user )
https://mhealth.ddc.moph.go.th/focus-investigation/view/88684506-605d-41db-b904-efbaf9795d2a
![image](https://user-images.githubusercontent.com/61143692/95622720-b5f6b980-0a7c-11eb-84ee-6673715f8133.png)

**Comment by moshthepitt** [comment]
This is happening because reporting on this web app is not yet set up

**Comment by samkanga** [comment]
I will close this ticket as this is now resolved.
