### ISSUE TITLE
THAI LOCAL FI page for Thailand test site BVBD 1 takes forever to load :

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1347]
bvbd_test user 
https://mhealth.ddc.moph.go.th/focus-investigation/view/ab7e1954-0ac8-475e-b70a-e896babdb649
![image](https://user-images.githubusercontent.com/61143692/95623082-5d73ec00-0a7d-11eb-9b8a-ad98f98020f2.png)

**Comment by samkanga** [comment]
@Naima-Bashir I retested this and the access speed appeared OK apart from the permissions errors that are reported on isue #1344.

**Comment by Naima-Bashir** [comment]
An update on my end:
After about 10minutes or so, it gave me this error:
![image](https://user-images.githubusercontent.com/61143692/95782562-bbe8d680-0cd8-11eb-91eb-7cd465151585.png)

cc @moshthepitt @samkanga

**Comment by samkanga** [comment]
@Naima-Bashir I tested this morning and found this to be working. I have added a screenshot below. Please reopen this if the issues re-occurs.
![image](https://user-images.githubusercontent.com/5908630/96081419-e77ae500-0ec1-11eb-8fbb-86ac2bf120e8.png)
