### ISSUE TITLE
THAI LOCAL The user bvbd_test cannot access anything

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1349]
1. When he tries to click on the user filter he gets a 403
![image](https://user-images.githubusercontent.com/61143692/95622859-fbb38200-0a7c-11eb-8ba0-454faaa23578.png)
2. I created a new plan and after I clicked save, I get an error: ACCESS DENIED using bvbd_test user

![image](https://user-images.githubusercontent.com/61143692/95623411-e0954200-0a7d-11eb-9e8e-984abe0e8619.png)
3. Lots of access denied when trying to click on OAs
![image](https://user-images.githubusercontent.com/61143692/95623431-e854e680-0a7d-11eb-99ff-1a687f204aad.png)
4. I am getting a 403 error when I click on the user filter on the plans list
![image](https://user-images.githubusercontent.com/61143692/95623505-10dce080-0a7e-11eb-94bc-9a593b5bca12.png)

**Comment by samkanga** [comment]
This has been resolved.
