### ISSUE TITLE
Focus investigation and general design feedback

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#135]
We need to draw things together a bit to make the web app feel a bit more finalized.  Right now while functional it feels beta as we're missing a few basic linkages.

<img width="1318" alt="Screen Shot 2019-06-25 at 9 11 58 PM" src="https://user-images.githubusercontent.com/42673455/60145331-b1c56080-9793-11e9-96df-e64679e7aaac.png">

First, can look at extending the top header but keeping the side padding where relevant.  Eg. on pages with tables but not the map?

<img width="1141" alt="Screen Shot 2019-06-25 at 9 11 41 PM" src="https://user-images.githubusercontent.com/42673455/60145366-ca357b00-9793-11e9-9b09-56446b66df63.png">

Main thing is I'd like to go full wide screen on map (we need to remember all of our clients are not on high res / retina screens).   It's not a huge priority but it would be nice if we could add opacity to the black and have it overlay the map.  

<img width="1265" alt="Screen Shot 2019-06-25 at 9 12 29 PM" src="https://user-images.githubusercontent.com/42673455/60145441-0a94f900-9794-11e9-8a37-fdd387b2ebcf.png">

Right now I think there is more value in combining the two pages.  If we need more space, we could consider a tab for focus investigation management / settings, etc.  I think combining would make it a lot simpler and let us refine.  We can split out later if needed but right now I think there are too many tradeoffs.  Right now the first page is really of limited value to me.

@rowo @moshthepitt can we prioritize this once we've gotten key functional stuff complete.

**Comment by moshthepitt** [comment]
Going to be fixed via #190, #196, and #198
