### ISSUE TITLE
RVL-1252 Missing TLAs under the IRS Performance Reporting 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1351]
- [ ] There are spray operators whose entries are not showing up under the IRS Performance Reporting. We need to check if there is data from the following SOPs getting to the system: tlanch12, tlanch18, tlanch20, tlanch21 and tlanch25 under Nchelenge District.

This is item 3 on https://smartregister.atlassian.net/browse/RVL-1252

**Comment by ciremusyoka** [comment]
@samkanga tlanch18, tlanch20, tlanch21 and tlanch25 don't have any generated daily summary reports and the reports available for tlanch12 are missing location id.
cc @moshthepitt

**Comment by samkanga** [comment]
@ciremusyoka I  will make follow-up on this.

**Comment by craigappl** [comment]
@moshthepitt and @ciremusyoka , I followed up and am closing this issue. I have requested that Akros ask these users to submit data.
