### ISSUE TITLE
Thai Local - Missing Case Triggered plans on Monitoring Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1352]
- [ ] The case triggered plans are not being displayed on the Thail Local Monitoring page. Sample case triggered plans can be accessed on [this](https://mhealth.ddc.moph.go.th/plans/update/b6d81401-fcd4-457d-8506-b491d081a6a3) link.

**Comment by ciremusyoka** [comment]
@samkanga the [slice](https://superset.reveal-th-preview.smartregister.org/superset/explore/?form_data=%7B%22datasource%22%3A%2235__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A239%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22plan_date%22%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A100%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%22id%22%2C%22plan_id%22%2C%22plan_title%22%2C%22plan_name%22%2C%22plan_status%22%2C%22jurisdiction_id%22%2C%22plan_fi_status%22%2C%22plan_fi_reason%22%2C%22plan_date%22%2C%22plan_effective_period_start%22%2C%22plan_effective_period_end%22%2C%22plan_intervention_type%22%2C%22plan_version%22%2C%22jurisdiction_parent_id%22%2C%22jurisdiction_name%22%2C%22jurisdiction_geometry%22%2C%22jurisdiction_depth%22%2C%22jurisdiction_path%22%2C%22jurisdiction_name_path%22%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%7D) we are using have all jurisdiction ids as null except for only three `Routine` plan. On the UI if we don't display plans without jurisdictions.

**Comment by samkanga** [comment]
I will go ahead and close this tickets as the case triggered plans are now available on the reporting tab.
