### ISSUE TITLE
Thai Local - Missing Indicators Panel on Monitoring Tab

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1353]
- [ ] Open any of the created dynamic plans from the monitoring page on Thailand Local Production WebUI. The page does not show the indicator panel. See a sample screenshot below

![image](https://user-images.githubusercontent.com/5908630/95752339-8a581700-0ca8-11eb-9a59-fc11f33f6fb9.png)

**Comment by ciremusyoka** [comment]
@samkanga we don't have data from the expected [slice](https://supersetmhealth.ddc.moph.go.th/superset/explore/?form_data=%7B%22queryFields%22%3A%7B%22groupby%22%3A%22groupby%22%2C%22metrics%22%3A%22metrics%22%7D%2C%22datasource%22%3A%224__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A3%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22No+filter%22%2C%22query_mode%22%3A%22raw%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%22count%22%5D%2C%22all_columns%22%3A%5B%22id%22%2C%22plan_id%22%2C%22jurisdiction_id%22%2C%22goal_id%22%2C%22measure%22%2C%22goal_value%22%2C%22goal_comparator%22%2C%22goal_unit%22%2C%22action_code%22%2C%22action_description%22%2C%22action_prefix%22%2C%22action_reason%22%2C%22action_title%22%2C%22task_count%22%2C%22completed_task_count%22%2C%22task_business_status_map%22%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22row_limit%22%3A250%2C%22order_desc%22%3Atrue%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22smart_date%22%2C%22color_pn%22%3Atrue%2C%22show_cell_bars%22%3Atrue%7D).

**Comment by samkanga** [comment]
The indicators Panel is now available. I will go ahead and close this ticket.
