### ISSUE TITLE
Namibia - Active plans are not appearing on Monitor view in Web UI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1355]
- [ ] We have a scenario for Namibia production where new active plans are not showing up on the monitoring tab of the WebUI. An example is the plan ed4e7b94-7d44-533a-abae-0f6ee956f3db

**Comment by craigappl** [comment]
Update 8PM EAT: The plan is showing, but no data is populated in it.

**Comment by craigappl** [comment]
It looks like a server version issue with the endpoints. The team needs to review.

**Comment by moshthepitt** [comment]
Closing this as the underlying server version issue seems fixed.
