### ISSUE TITLE
THAI LOCAL- The Submissions on app do not show up on web

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1359]
Login to the android client using bvbd_test
Register structures, create family members, fill in their tasks.
Check on web: https://mhealth.ddc.moph.go.th/focus-investigation
To see if the changes are made on android reflect on web.

RESULTS: The Submissions on app do not show up on web
BOTH Dynamic and Case Triggered Plans

**Comment by moshthepitt** [comment]
@Naima-Bashir @samkanga I think that this should be fixed by https://github.com/onaio/opensrp-inventories/pull/197/commits/c334a41cfc983c3b1c8fb5e803fb572ff5ed27e5.  If you submit data and wait about 20 minutes you should see data. Please test and close this issue if all is ok.

**Comment by samkanga** [comment]
@moshthepitt I confirm this is now working and will go ahead and close it.

**Comment by Naima-Bashir** [comment]
@moshthepitt I will update my testcase to inform the user to wait 20min. This has passed QA
cc @samkanga
