### ISSUE TITLE
Thai Local - Structures Not Showing Tasks on the WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1360]
Structures on the map appear in grey. An example is the plan on the following url: https://mhealth.ddc.moph.go.th/focus-investigation/map/c6c3ffb5-319b-5b6f-a2b1-0aa802e5f1c4

![image](https://user-images.githubusercontent.com/5908630/96003105-8cee7400-0e42-11eb-8f18-09e3b01117d4.png)

**Comment by moshthepitt** [comment]
Fixed this via https://github.com/onaio/opensrp-inventories/pull/197/commits/c334a41cfc983c3b1c8fb5e803fb572ff5ed27e5.  @samkanga please confirm and close this issue if all is ok.

![no grey](https://user-images.githubusercontent.com/372073/96140619-cc7f9380-0f08-11eb-9092-9283ce5fbce6.png)

**Comment by samkanga** [comment]
@moshthepitt this is now resolved. I will go ahead and close the ticket.
