### ISSUE TITLE
Thai Local - Routine Plans Not Showing Tasks on the Map

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1361]
- [ ] I created the plan https://mhealth.ddc.moph.go.th/focus-investigation/map/c43b601b-c95c-5b73-ae5a-a692c8167ef1 and submitted data against it. However, data shows on the indicators to the left of the map but not on the map. See sample screenshot below

![image](https://user-images.githubusercontent.com/5908630/96006013-b65ccf00-0e45-11eb-9641-edce69919eb0.png)

**Comment by moshthepitt** [comment]
This was fixed by https://github.com/onaio/opensrp-inventories/pull/197/commits/c334a41cfc983c3b1c8fb5e803fb572ff5ed27e5. @samkanga please check and close the issue if all is ok.

![things on map](https://user-images.githubusercontent.com/372073/96142080-554aff00-0f0a-11eb-8478-3a5500021c81.png)

**Comment by samkanga** [comment]
@moshthepitt this is now working. I will go ahead and close the ticket.
