### ISSUE TITLE
Thai Local - Edits to Foci Boundaries not Updating on WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1363]
- [ ] I edited the foci boundary to the location **Thailand test site BVBD 2** on the android device as per the screenshot below.

![image](https://user-images.githubusercontent.com/5908630/96086924-b4d5ea00-0ecb-11eb-8aa9-71dd0a53eb21.png)

However, after about 40 minutes the boundaries were not reflecting on the webUI as seen on [this](https://mhealth.ddc.moph.go.th/focus-investigation/map/aee468f5-0a51-5690-afe2-fbf068891308) link and the screenshot below.
![image](https://user-images.githubusercontent.com/5908630/96087043-ea7ad300-0ecb-11eb-9f6f-97c08427f66e.png)

**Comment by moshthepitt** [comment]
@samkanga could you please post a link to a plan on the web UI where this is happening?

**Comment by samkanga** [comment]
@moshthepitt See this: https://mhealth.ddc.moph.go.th/focus-investigation/map/aee468f5-0a51-5690-afe2-fbf068891308

**Comment by moshthepitt** [comment]
@samkanga please confirm that your changes in the app have been synced to the OpenSRP Thailand local server.  I am asking you to do this because I have compared the jurisdiction in OpenSRP and in Canopy and they seem to be exactly the same.

**Comment by samkanga** [comment]
@moshthepitt I did a sync when I did the edit. I will ask @Naima-Bashir to recheck the boundary for Thailand Test Site BVBD 1 just to be sure.

**Comment by samkanga** [comment]
@moshthepitt I confirm I was looking a plan in the wrong location. This is now resolved. I will go ahead and close it.

**Comment by Naima-Bashir** [comment]
This is fixed!! @moshthepitt @samkanga
