### ISSUE TITLE
Thailand Local - Error when Opening Manage Plans Menu

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1366]
- [ ]  When opening the Manage Plans on the Thailand Local WebUI, an error appears that seems related to the users filter menu as shown on the screen below.

![image](https://user-images.githubusercontent.com/5908630/96226021-a73b6580-0f9a-11eb-871c-2718e292913c.png)

**Comment by moshthepitt** [comment]
We need more details please:

- which user is logging in?
- have we confirmed that the user has the right permissions?
- are we taking into account that the error will ALWAYS show if there are no plans for the user -  because there is a user filter applied by default?

**Comment by samkanga** [comment]
@moshthepitt @ciremusyoka this is for the user `vbdu_2.3.6-1` I checked with @Rkareko and confirmed that the user  has plans assigned to them on the OpenSRP Side.

**Comment by moshthepitt** [comment]
@samkanga then the next course  of action is to work with @Rkareko to figure out why the API calls made by the web app return nothing for the user

**Comment by Rkareko** [comment]
@moshthepitt @samkanga the api is truncating anything after the first dot eg vbdu_2.3.6-1 gets shortened to vbdu_2.3 that's why the api call is failling for this particular user.

**Comment by moshthepitt** [comment]
Seems this is fixed.  Please re-open if not.
