### ISSUE TITLE
View List of All Plans

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#137]
When navigating to `/irs` we need to render all existing Plans as rows in a table and a button to create a new Plan.

#### Table Columns
- [x] Name - Unique name of the Plan
- [x] Date created - Date_Time of last modified (depends on onaio/canopy#306)
- [x] Status - Draft | Finalized | In Progress | Complete
- ~~Summary* - `[x] houses, [y] resources` (* this depends on Resource Estimation)~~

#### Interactions
- [x] Clicking Plan name navigates to existing Plan page
- [x] Clicking `Create new plan` button navigates to Create Plan page `/irs/new`
- ~~Table is sortable and filterable via column headers (* nice-to-have)~~

**Comment by moshthepitt** [comment]
@cKellyDesign I think for uniformity we need to change the data source of the plan ([these ones](https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/plans.ts#L138)) from Superset to OpenSRP.  This is informed by [this conversation](https://onaio.slack.com/archives/CBSU8L2SC/p1562932654022100).
