### ISSUE TITLE
Thai Local - Status Code: 500 INTERNAL SERVER ERROR 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1370]
- [ ] When selecting a plan fro the Monitor page, whether routine or case triggered plans the system throws an error Internal Server Error with code 500 when trying to GET from https://supersetmhealth.ddc.moph.go.th/superset/slice_json/0?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22bc581beb-1048-4ed2-a2e9-1d66d03fd293%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22}],%22row_limit%22:15000}

A sample plan with the error can be accessed [here](https://mhealth.ddc.moph.go.th/focus-investigation/map/5e364d55-e9c3-542f-b26d-a930220b0af8).

**Comment by moshthepitt** [comment]
@samkanga this is fixed.

**Comment by moshthepitt** [comment]
Closed, see https://onaio.slack.com/archives/C01ASKAEZKL/p1603119812011300?thread_ts=1603104720.004200&cid=C01ASKAEZKL
