### ISSUE TITLE
RVL-1276 - Namibia - Indicators in the WebUI and in-app are not showing the same values

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1371]
- [ ] The number of structures sprayed on the WebUI (350) are less than those recorded in the android client (371) See below a case for the Operational Area named **OMUKANDU (UUKWIYU)** that can be accessed on the WebUI with the link [here](https://web.reveal-na.smartregister.org/intervention/irs/report/ed4e7b94-7d44-533a-abae-0f6ee956f3db/0edba8cf-437a-4104-a2fe-8143116e2139/map).
Android Client
![image](https://user-images.githubusercontent.com/5908630/96451288-04941880-1220-11eb-9ed1-e4a287a86271.png)

WebUI
![image](https://user-images.githubusercontent.com/5908630/96451225-ec23fe00-121f-11eb-8fc9-428bc6c1e99b.png)

**Comment by moshthepitt** [comment]
@samkanga @hmakandi can we please clarify exactly how the mobile app is calculating this?  Canopy tries to remove duplicates and this is how it calculates: first it does this https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/5-IRS/3-Namibia-2019/deploy/namibia_irs_structures.psql then aggregates by jurisdiction here https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/5-IRS/3-Namibia-2019/deploy/namibia_focus_area_irs.psql

We need to compare how the mobile app does it - I suspect it does it differently.  Then decide which is the correct/preferred way to do it and stick with that.

Let's note that how its done in Canopy was used "as is" last year.

**Comment by moshthepitt** [comment]
Just to be clear.  There are no "bugs" in Canopy or the web app.  So the thing that needs to be done is compare the calculations with the app and go from there.

**Comment by craigappl** [comment]
@moshthepitt , I am picking this up and will do that comparison.

**Comment by Rkareko** [comment]
@craigappl the mobile app processes the spray events and populates the data in the `sprayed_structures` table. Then uses the following query to retrieve the `found structures`, `sprayed structures` and `not sprayed structures` https://github.com/OpenSRP/opensrp-client-reveal/blob/master/opensrp-reveal/src/main/java/org/smartregister/reveal/util/IndicatorUtils.java#L170-L176 . 
The query filters by parent_id (operational area) and plan_id

**Comment by craigappl** [comment]
Notes on mismatch from screenshots:
![image](https://user-images.githubusercontent.com/6067053/96905258-14447480-144d-11eb-90eb-1b7f5256bc17.png)
The colors should match across the two systems.
1. Targeted structures are the same on both, which derives from the imported room count. (370 rooms targeted on both systems) No change required on that field.
2. Web Ui value of Target Coverage Progress and Found Coverage Progress counts (350 in the web Ui screenshot) should match the structures sprayed value in Android (371 in the Android screenshot)
4. 

### Android Investigation

```
select
    sum(ifNull(ss.nSprayableTotal,0)) as foundStruct,
    sum(ifNull(ss.nSprayedTotalFirst,0)+ifNull(ss.nSprayedTotalMop,0)) as sprayedStruct,
    sum(ifNull(nSprayableTotal,0)- ifNull(nSprayedTotalFirst,0) - ifnull(nSprayedTotalMop,0)) as notSprayedStruct
from sprayed_structures ss
join structure s on s._id=ss.id
where parent_id=? and ss.plan_id=?;
```
The structure of the sprayed_structures table has the following columns:
```
base_entity_id
plan_id
spray_status
spray_date
spray_operator
property_type
not_sprayed_reason
not_sprayed_other_reason
family_head_name
householdAccessible
nSprayableTotal
nSprayableZinc
nSprayableTrad
nSprayableMod
nSprayableCanopy
nUnsprayable
popTotal
nameHoH
firstVisitGroupHeading
ableToSprayFirst
nSprayedTotalFirst
nSprayedDDTFirst
nSprayedDeltaFirst
nSprayedActellicFirst
nUnsprayedZincFirst
nUnsprayedTradFirst
nUnsprayedModFirst
nUnsprayedCanopyFirst
unsprayedReasonFirst
refusalReasonFirst
refusalReasonOtherFirst
mopUpVisit
nSprayedTotalMop
nSprayedDDTMop
nSprayedDeltaMop
nSprayedActellicMop
unsprayedReasonMop
refusalReasonMop
refusalReasonOtherMop
nPeopleProtected
unsprayedReasonHH
refusalReasonHH
```

### Android Questions
1. Does the sprayed structures table in the Android client include duplicates if a user edits a form? If so, do we need to account for that in the query?
2. Should we be joining on the sprayed structures.id column instead of the base_entitiy_id columns in `join structure s on s._id=ss.id` I don't know if this matters.
3. The Android client has all of last year's data downloaded to it. I see that we are filtering by ss.plan_id in the where clause. Last year's data did not have the plan_id added to every event. Therefore, I assume there are some events that were downloaded from last year that have a plan id = null Will this have an impact on the Android indicator?
4. Does the parent_id need an s in front of it like s.parent_id in the where clause `where parent_id=? and ss.plan_id=?;`
5. Other than the above, I don't know what data is in the database. I have exported a database and will make that available over slack for the team to review.

### Canopy Investigation
Here are some issues I found:
1. The latest event doesn't seem to be the one that's showing up. It looks like the latest event Date is the one that shows up, but not the latest event based on start and end time. So, if two events are submitted within the same day a few minutes apart, the first one in for that day wins. In this case, the person corrected the data. This results in the total number of sprayed rooms showing up as 350 for this area and it should be 348 based on the data in the data warehouse events table.

Event Id | base_entity_id | formfilledenddatetime | nsprayabletotal | nsprayedtotalfirst |  
-- | -- | -- | -- | -- | --
a9ff360e-be83-46b5-911e-b3aeee5644ad | 06526931-28d5-4605-b103-391c1e540fb1 | 10/12/2020 10:51 | 18 | 13 | <-- This one shows up
309153ed-ed76-4a7e-9e38-43bf49b0c41e | 06526931-28d5-4605-b103-391c1e540fb1 | 10/12/2020 10:55 | 18 | 13 | <-- This one should show up
e8b4d14f-ff74-4eea-8153-1fff9c6ce900 | 256b23b1-9c8f-4161-be14-5bf1ccf31ee5 | 10/12/2020 8:37 | 18 | 11 | <-- This one shows up
380b5898-4e8a-4cb8-be10-8966fd756255 | 256b23b1-9c8f-4161-be14-5bf1ccf31ee5 | 10/12/2020 8:46 | 18 | 12 |  
9a2f3345-8e99-4d9b-aabc-59730f0d8109 | 256b23b1-9c8f-4161-be14-5bf1ccf31ee5 | 10/12/2020 8:57 | 18 | 13 | <-- This one should show up
8a9c8a2e-65d5-4d16-bbd4-ebc9b3e7f079 | 2f0bf24d-99b6-4a79-ab2a-f463d24ff495 | 10/13/2020 11:29 | 7 | 4 |  
fe1fc263-e3a6-4f7e-97bd-2d402897f494 | 2f0bf24d-99b6-4a79-ab2a-f463d24ff495 | 10/15/2020 13:50 | 7 | 4 | <-- This one shows up
351ce192-df95-4d56-8acb-015ed6204b36 | 2f0bf24d-99b6-4a79-ab2a-f463d24ff495 | 10/15/2020 13:50 | 7 | 4 | <-- This one should show up
db8a4be0-8ce4-451f-a019-041c0eab300d | 655f1339-e297-41cc-9a62-f835108b1bb0 | 10/12/2020 10:26 | 22 | 22 | <-- This one shows up
883c0ee8-2076-4816-b1dc-5901b254494d | 655f1339-e297-41cc-9a62-f835108b1bb0 | 10/12/2020 10:28 | 22 | 19 | <-- This one should show up

Here's the query to get that table
```
SELECT id,
       created_at,
       base_entity_id,
       location_id,
       event_type,
       provider_id,
       date_created,
       event_date,
       entity_type,
       COALESCE (form_data->'nSprayableTotal'->>0, '0')::int AS nSprayableTotal,
       COALESCE (form_data->'nSprayedTotalFirst'->>0, '0')::int AS nSprayedTotalFirst,
       COALESCE (form_data->'nSprayedTotalMop'->>0, '0')::int AS nSprayedTotalMop,
       form_data->'end' AS formFilledEndDateTime,
       form_data,
       task_id,
       team_id,
       server_version,
       structure_id,
       plan_id
       
FROM namibia_prod.events
where location_id = '0edba8cf-437a-4104-a2fe-8143116e2139' and plan_id = 'ed4e7b94-7d44-533a-abae-0f6ee956f3db' and event_type = 'Spray'
order by base_entity_id, formfilledenddatetime
```

**Comment by Rkareko** [comment]
@craigappl 
Android Questions
1. The Android client does not have duplicate entries, when data is edited the same record is updated in the `sprayed_strutures` table
2. The `id` and `base_entitiy_id` columns in the `sprayed_strutures` table contain the same values
3. The query only fetches data for this year's plan
4. Only the `structure_table` has a `parent_id` colum

**Comment by moshthepitt** [comment]
@Rkareko I made the change where we select the latest based on form end date, but numbers still are not matching the app.  So I decided to list all the structures and the values we have in this jurisdiction.  Could you do the same so that we can pick out the differences?

```
             structure_id             | nsprayabletotal | nunsprayable | nsprayedtotalfirst | nsprayedtotalmop | nunsprayedtotalfirst | nunsprayedtotalmop 
--------------------------------------+-----------------+--------------+--------------------+------------------+----------------------+--------------------
 df842cb3-21e6-457d-bf4a-71c92541be48 |               2 |            0 |                  2 |                0 |                  0.0 |                0.0
 04f9a006-a39e-4479-9b9a-475f241222bc |               3 |            0 |                  3 |                0 |                  0.0 |                0.0
 7cedb5cc-f82c-4477-b46a-c6e02462f774 |               3 |            0 |                  3 |                0 |                  0.0 |                0.0
 f6d5f1a2-6779-4076-a505-4e9c558982d4 |               4 |            0 |                  4 |                0 |                  0.0 |                0.0
 2fff31ec-281d-42a1-8398-8908116a478e |               4 |            0 |                  1 |                0 |                  3.0 |                3.0
 c383b255-32d5-4b16-a5ba-3a2f6aa4f923 |               4 |            0 |                  4 |                0 |                  0.0 |                0.0
 ef30e9a8-53b4-4b2f-b058-70273a990f46 |               4 |            0 |                  4 |                0 |                  0.0 |                0.0
 449db01e-a69f-44ce-ba3b-43f650ec3805 |               5 |            0 |                  5 |                0 |                  0.0 |                0.0
 44b4ba1e-df8a-4689-be69-cce7cd49085f |               6 |            0 |                  6 |                0 |                  0.0 |                0.0
 371b03d0-101f-41f7-b58d-f54f30cd500e |               6 |            4 |                  4 |                0 |                  2.0 |                2.0
 2f0bf24d-99b6-4a79-ab2a-f463d24ff495 |               7 |            0 |                  4 |                0 |                  3.0 |                3.0
 b04011c0-42b2-4f51-b243-acdd99c433f6 |               7 |            0 |                  7 |                0 |                  0.0 |                0.0
 da15f834-7dc2-4ddc-80ae-7ff5098433cb |               7 |            0 |                  6 |                0 |                  1.0 |                1.0
 ba20e88c-3398-4b6a-b942-e6d4152ec3e8 |               8 |            0 |                  8 |                0 |                  0.0 |                0.0
 22b35d49-4db8-4507-a775-1087feece30a |               8 |            0 |                  8 |                0 |                  0.0 |                0.0
 6927868c-9e68-416a-b9cb-e168aedd4e2f |               9 |            0 |                  7 |                0 |                  2.0 |                2.0
 562b6153-9202-476c-9fb3-20c03e16e0f9 |              10 |            2 |                  8 |                0 |                  2.0 |                2.0
 e171bd50-c442-457a-b852-31d0b56ddd0b |              11 |            0 |                  9 |                0 |                  2.0 |                2.0
 d475caeb-f1f2-460e-b0c5-0d4f738c333e |              13 |            0 |                  8 |                0 |                  5.0 |                5.0
 1ef41bb5-d6fa-4650-a921-fe6c977dd029 |              15 |            3 |                  9 |                0 |                  6.0 |                6.0
 c8eb0b90-ea1d-4dd5-be03-36e61ae67c74 |              17 |            2 |                 14 |                0 |                  3.0 |                3.0
 bc47f68e-b125-43f4-b8a0-041a544a01f8 |              18 |            0 |                  9 |                0 |                  9.0 |                9.0
 06526931-28d5-4605-b103-391c1e540fb1 |              18 |            4 |                 13 |                0 |                  5.0 |                5.0
 256b23b1-9c8f-4161-be14-5bf1ccf31ee5 |              18 |            5 |                 13 |                0 |                  5.0 |                5.0
 bbae8f3f-dc39-45d8-834b-ba78761cd006 |              18 |            4 |                 15 |                0 |                  3.0 |                3.0
 40735aa0-e4bf-4401-8f5b-b4a7f9b8e514 |              20 |            0 |                 16 |                0 |                  4.0 |                4.0
 184fae82-8af2-43aa-9965-957fe7bf9029 |              20 |            0 |                 20 |                0 |                  0.0 |                0.0
 655f1339-e297-41cc-9a62-f835108b1bb0 |              22 |            3 |                 19 |                0 |                  3.0 |                3.0
 80e00708-18df-4026-b3bf-7324975dae45 |              23 |            8 |                 15 |                0 |                  8.0 |                8.0
 2a5c0e2e-aeeb-4235-a425-49bcf43a4cee |              26 |            0 |                  9 |                0 |                 17.0 |               17.0
 330bff99-5252-4dc2-b2eb-4ac486917969 |              26 |           12 |                 14 |                0 |                 12.0 |               12.0
 1d2c44ae-92a6-426d-96bf-6c41e125fffc |              27 |            7 |                 20 |                0 |                  7.0 |                7.0
 1452979a-1439-489c-96d9-a28daf83449b |              28 |            0 |                 16 |                0 |                 12.0 |               12.0
 dc8ae11b-5b30-4200-be81-461356a56c52 |              34 |            0 |                 23 |                0 |                 11.0 |               11.0
 4ce3fc5a-7b6f-4e14-b758-63a48b38328b |              35 |            0 |                 22 |                0 |                 13.0 |               13.0
(35 rows)

```

**Comment by Rkareko** [comment]
@moshthepitt 

structure_id                        |foundStruct|sprayedStruct|notSprayedStruct|
------------------------------------|-----------|-------------|----------------|
04f9a006-a39e-4479-9b9a-475f241222bc|          3|            3|               0|
06526931-28d5-4605-b103-391c1e540fb1|         18|           13|               5|
1452979a-1439-489c-96d9-a28daf83449b|         28|           16|              12|
184fae82-8af2-43aa-9965-957fe7bf9029|         20|           20|               0|
1d2c44ae-92a6-426d-96bf-6c41e125fffc|         27|           20|               7|
1ef41bb5-d6fa-4650-a921-fe6c977dd029|         15|            9|               6|
22b35d49-4db8-4507-a775-1087feece30a|          8|            8|               0|
256b23b1-9c8f-4161-be14-5bf1ccf31ee5|         18|           13|               5|
2a5c0e2e-aeeb-4235-a425-49bcf43a4cee|         26|            9|              17|
2ac7e78f-5140-4d4d-a59a-803d3cd9f16f|          2|            0|               2|
2f0bf24d-99b6-4a79-ab2a-f463d24ff495|          7|            4|               3|
2fff31ec-281d-42a1-8398-8908116a478e|          4|            1|               3|
330bff99-5252-4dc2-b2eb-4ac486917969|         26|           14|              12|
371b03d0-101f-41f7-b58d-f54f30cd500e|          6|            4|               2|
40735aa0-e4bf-4401-8f5b-b4a7f9b8e514|         20|           16|               4|
448fcbff-bb49-45db-b3c0-da9de2acbd51|          0|            0|               0|
449db01e-a69f-44ce-ba3b-43f650ec3805|          5|            5|               0|
44b4ba1e-df8a-4689-be69-cce7cd49085f|          6|            6|               0|
4ce3fc5a-7b6f-4e14-b758-63a48b38328b|         35|           22|              13|
562b6153-9202-476c-9fb3-20c03e16e0f9|         10|            8|               2|
5d5fb71c-7810-4058-8c06-90adb2cd397b|          8|            8|               0|
5f33e3d6-d1f5-4078-9c8d-ff53f0aa2134|          0|            0|               0|
655f1339-e297-41cc-9a62-f835108b1bb0|         22|           19|               3|
6927868c-9e68-416a-b9cb-e168aedd4e2f|          9|            7|               2|
7cedb5cc-f82c-4477-b46a-c6e02462f774|          3|            3|               0|
80e00708-18df-4026-b3bf-7324975dae45|         23|           15|               8|
992b9a0d-7f8e-40c2-9a67-afbafabe8cdd|          0|            0|               0|
b04011c0-42b2-4f51-b243-acdd99c433f6|          7|            7|               0|
b6453430-2036-4954-93d1-37a77fc2bac3|          0|            0|               0|
b7f78e59-49df-4885-b8fe-fcaa3770d4a1|          0|            0|               0|
ba20e88c-3398-4b6a-b942-e6d4152ec3e8|          8|            8|               0|
bbae8f3f-dc39-45d8-834b-ba78761cd006|         18|           15|               3|
bc47f68e-b125-43f4-b8a0-041a544a01f8|         18|           21|              -3|
c383b255-32d5-4b16-a5ba-3a2f6aa4f923|          4|            4|               0|
c8eb0b90-ea1d-4dd5-be03-36e61ae67c74|         17|           14|               3|
d475caeb-f1f2-460e-b0c5-0d4f738c333e|         13|            8|               5|
da15f834-7dc2-4ddc-80ae-7ff5098433cb|          7|            6|               1|
dc8ae11b-5b30-4200-be81-461356a56c52|         34|           23|              11|
df842cb3-21e6-457d-bf4a-71c92541be48|          2|            2|               0|
e171bd50-c442-457a-b852-31d0b56ddd0b|         11|            9|               2|
e84ea4be-aa5c-48c5-9151-962ca835e321|          8|            3|               5|
ef30e9a8-53b4-4b2f-b058-70273a990f46|          4|            4|               0|
f32d80ca-f544-472d-b7fa-de4b9bd24c39|          0|            0|               0|
f6d5f1a2-6779-4076-a505-4e9c558982d4|          4|            4|               0|
ff86bbbb-4410-4b58-b7b3-de0e3112f81b|          0|            0|               0|

**Comment by Rkareko** [comment]
@moshthepitt here is data for one of the structures which has different values 

structure_id                        |nSprayableTotal|nSprayedTotalFirst|nSprayedTotalMop|foundStruct|sprayedStruct|notSprayedStruct|
------------------------------------|---------------|------------------|----------------|-----------|-------------|----------------|
bc47f68e-b125-43f4-b8a0-041a544a01f8|18             |9                 |12              |         18|           21|              -3|

**Comment by moshthepitt** [comment]
@Rkareko for that one we only have one record:

```
event_id             | 01557cad-5d28-4597-b483-5f3a54e353eb
structure_id         | bc47f68e-b125-43f4-b8a0-041a544a01f8
nsprayabletotal      | 18
nunsprayable         | 0
nunsprayedtotalfirst | 9.0
nunsprayedtotalmop   | 9.0
nsprayedtotalfirst   | 9
nsprayedtotalmop     | 0
```

**Comment by moshthepitt** [comment]
@Rkareko is it possible to have negatives in `notSprayedStruct`?  What would a negative logically mean?

**Comment by moshthepitt** [comment]
@Rkareko I also found these three structures:

```
2ac7e78f-5140-4d4d-a59a-803d3cd9f16f
e84ea4be-aa5c-48c5-9151-962ca835e321
5d5fb71c-7810-4058-8c06-90adb2cd397b
```

Where we have no data for in Canopy.  I am investigating.

**Comment by moshthepitt** [comment]
@Rkareko for these three ^^ we don't have any data i.e.

```
-[ RECORD 1 ]---------+-------------------------------------
id                    | 0a0ce6a2-a1eb-455e-ac15-e34e2e2b0e6a
base_entity_id        | 2ac7e78f-5140-4d4d-a59a-803d3cd9f16f
nsprayabletotal       | 0
nsprayedtotalfirst    | 0
nsprayedtotalmop      | 0
formfilledenddatetime | "2020-10-14 08:05:18"
-[ RECORD 2 ]---------+-------------------------------------
id                    | 1c674622-acb7-4c56-85e6-58e7fe7294fc
base_entity_id        | 5d5fb71c-7810-4058-8c06-90adb2cd397b
nsprayabletotal       | 0
nsprayedtotalfirst    | 0
nsprayedtotalmop      | 0
formfilledenddatetime | "2020-10-14 07:09:06"
-[ RECORD 3 ]---------+-------------------------------------
id                    | 33685e09-bdbd-4551-b656-739105a0d980
base_entity_id        | e84ea4be-aa5c-48c5-9151-962ca835e321
nsprayabletotal       | 0
nsprayedtotalfirst    | 0
nsprayedtotalmop      | 0
formfilledenddatetime | "2020-10-12 09:45:14"

```

Could you confirm where the app gets the values?  I can't seem to find any missing events (looks like we have everything) so these are confusing
