### ISSUE TITLE
Reveal Thailand Preview and Local Production - Autocreate new superset users and assign correct role

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1380]
When users are automatically created in Superset, they need to be assigned a role that provides them permission to view the monitor tab in the Reveal web Ui. This has historically been done by assigning them the Gamma and Reveal Data Source roles.

- [x] Users in Thailand Local need to be able to be created in Superset the first time they login to the web Ui if they aren't created in Superset. (This functions correctly in Thailand Preview, but doesn't seem to be the case in Thailand Local.)
- [x] Please create a role and assign it on both Thailand Local and Preview that automatically gets assigned when a user is created.

**Comment by moshthepitt** [comment]
@craigappl @manutarus I have done the following for both Thailand preview and local:

- created a role named `Reveal Web Ui Reporting Access`
- Added the `access all datasources` permissions to this role
- Made it such that this role is added to any user that logs in via OAuth2
- [Modified deployment scripts](https://github.com/onaio/opensrp-inventories/pull/209) to reflect the above

Please test and let me know if this works.  The part that I am unsure about is whether the role has sufficient permissions for what the users need.  But after testing we can change that.
