### ISSUE TITLE
RVL-1305 - Routine plan names are created with the wrong name

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1391]
Routine plan names on Thailand Production are created as "Dynamic + Date" instead of "Area Type + Foci  Name + Date".

Here is a screenshot on how the plans are presently named:
![image](https://user-images.githubusercontent.com/5908630/98001280-85493c00-1dfe-11eb-8e2e-796d4c4b585c.png)

Here is a screenshot on how they should appear.
![image](https://user-images.githubusercontent.com/5908630/98001369-9c882980-1dfe-11eb-966e-94f6470bf2ac.png)

**Comment by Naima-Bashir** [comment]
@samkanga @moshthepitt just tested this: 
This is how the title appears 
![image](https://user-images.githubusercontent.com/61143692/98220912-0b30c880-1f60-11eb-97c4-a50026ff0db3.png)

**Comment by Naima-Bashir** [comment]
this has also passed qa on thai production
cc @samkanga @moshthepitt
