### ISSUE TITLE
Zambia Production IRS Plan Not Showing Data

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1395]
- [ ] [This](https://web.reveal-zm.smartregister.org/intervention/irs/report/a05f0cd3-6f81-565c-a166-c89d1a9cc4df) plan on Zambia production is being used for the Macepa training. The users have submitted data but the dashboard does not display any data. See sample screenshot below.

![image](https://user-images.githubusercontent.com/5908630/98240553-a0d95180-1f7a-11eb-981e-8e74fbf1df57.png)

**Comment by moshthepitt** [comment]
One weird thing I noticed is that all the jurisdictions are "virtual".  See [this](https://superset.reveal-zm-green.smartregister.org/superset/slice_json/5?form_data={%22order_by_cols%22:[%22[\%22jurisdiction_depth\%22,+true]%22,%22[\%22jurisdiction_name\%22,+true]%22],%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22a05f0cd3-6f81-565c-a166-c89d1a9cc4df%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000}) and [this](https://superset.reveal-zm-green.smartregister.org/superset/slice_json/6?form_data={%22order_by_cols%22:[%22[\%22jurisdiction_depth\%22,+true]%22,%22[\%22jurisdiction_name\%22,+true]%22],%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22a05f0cd3-6f81-565c-a166-c89d1a9cc4df%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000})

**Comment by moshthepitt** [comment]
I think I found the problem:

```
reveal1=> select distinct(jurisdiction_depth) from jurisdictions_materialized_view where '7fcd3811-ef21-451e-b407-db635e976246'=ANY(jurisdiction_path);
 jurisdiction_depth
--------------------
                  1
                  3
                  2
                  4
```

The current reports assume that you have 5 levels

**Comment by moshthepitt** [comment]
Created a data warehouse issue to track this [here](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/issues/84)

**Comment by moshthepitt** [comment]
Now that the DB has been upgraded, it seems that we also need an upgrade of the web app
