### ISSUE TITLE
RVL-1315 - Total structures on VL 2020 plan has dropped hence making the coverage values incorrect

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1396]
Zambia Production
Version 1.0.0
User: Superset-user
Login to web ui
Go to monitor
Select plan i.e VL Zambia 2020 IRS Plan

**Issue:**
The total structure values have dropped  down, this is affecting coverage values. There seem to be ~3,000 fewer structures in Chadiza in the denominator and ~12,000 fewer in Nchelenge than expected (i.e. throughout the campaign these were consistently ~29,000 and ~43,000 respectively; and then this morning they were ~26,000 and ~31,000 respectively.

![image](https://user-images.githubusercontent.com/5908630/98329222-c90f9180-2008-11eb-9a60-96df0f8b7c20.png)

**Comment by moshthepitt** [comment]
This is caused [by a bug here](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/5-IRS/2-Zambia-2019/deploy/zambia_irs_structures.psql#L99).  Basically we need to apply a filter for plans to the tasks and events in the query coz right now it can match any plan in the entire world.
