### ISSUE TITLE
Thailand Production Map View Not Showing data on some plans

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1397]
- [x] A number of plans on the Thailand Local instance are not showing data on the map and in the indicators panel. See a sample screenshot below: Affected plans are:
1. https://mhealth.ddc.moph.go.th/focus-investigation/map/093399fc-602a-566a-b300-fce0d96496c1
2. https://mhealth.ddc.moph.go.th/focus-investigation/map/91429684-a83e-537b-b21b-ec0ebd17e126

![image](https://user-images.githubusercontent.com/5908630/98345976-6dec9780-2026-11eb-894e-1c6e31945938.png)

**Comment by Naima-Bashir** [comment]
I cant test this at the moment cc @samkanga @moshthepitt 
![image](https://user-images.githubusercontent.com/61143692/98787183-39a31d80-2410-11eb-84cb-3e4360e3c90a.png)

**Comment by samkanga** [comment]
@moshthepitt the fix for this ticket is not working on Thailand preview. @Naima-Bashir has shared some feedback on the QA channel and I did another test with the plan [here](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/8c251f3b-c607-5d15-a17c-b10506071727) and the data still does not show on the map nor on the indicators panel. The page is throwing a 500 errror when trying to GET [this](https://superset.reveal-th-preview.smartregister.org/superset/slice_json/0?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22333af57d-ad31-46d2-8d28-0c81dd306333%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22}],%22row_limit%22:15000}) url.

**Comment by Naima-Bashir** [comment]
I've tested this https://github.com/onaio/reveal-frontend/pull/1400
I created a plan with only one goal, residential structures and I created new family members on android. I synched it and it's still hasn't shown the families I created
https://web.reveal-th-preview.smartregister.org/focus-investigation/map/b48b0c46-6184-5656-97cb-a345ff57f8eb

**Comment by Naima-Bashir** [comment]
My findings: 
I registered families and completed their tasks on android.
I synched the device and it did not reflect on web 
![image](https://user-images.githubusercontent.com/61143692/99047215-f0d09d80-25a4-11eb-8dc6-ee1ad262ce17.png)
![image](https://user-images.githubusercontent.com/61143692/99047238-f9c16f00-25a4-11eb-890e-2a5b0176bdc8.png)
cc @samkanga @moshthepitt

**Comment by ciremusyoka** [comment]
Have confirmed that:
- The data displayed on the web is exactly as the data obtained from `targets_materialized_view` view on Thailand preview,
- The `targets_materialized_view` view is being refreshed,
- The tasks displayed on web match the tasks on the `tasks` table.

Though we tried syncing the data again on the mobile app successfully, the changes aren't reflected on the `tasks` table.
`e3c6088c-960f-5f3a-9d71-26798c3c91a0` is the plan id we used for testing.

**Comment by moshthepitt** [comment]
@Naima-Bashir could you please post a link to a plan that this is happening for?  I cannot find one.

**Comment by moshthepitt** [comment]
@Naima-Bashir for https://web.reveal-th-preview.smartregister.org/focus-investigation/map/b48b0c46-6184-5656-97cb-a345ff57f8eb/RACD_register_families the web app currently show:

![whatis](https://user-images.githubusercontent.com/372073/99371257-b9792e00-28cf-11eb-952c-46606a932acd.png)

Looks to me like the web app is indeed showing points when you have only one activity (which is the bug reported in this issue).

What should be displayed instead of the above?

**Comment by Naima-Bashir** [comment]
The numerator/denominator count should change for every new family registered, no?

**Comment by moshthepitt** [comment]
Closing this based on discussions [here](https://onaio.slack.com/archives/C01ASKAEZKL/p1605603602004000) and the fact that structures now show up on the map even if there is just one activity:

![กิจกรรมสอบสวน](https://user-images.githubusercontent.com/372073/99390733-33b6ac00-28ea-11eb-930c-a17e5f2498fb.png)
