### ISSUE TITLE
RVL-1330 - Remove Kilwa and Chisenga island structure from the denominator count

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1399]
In Zambia production, Kilwa and Chisenga are islands in Nchelenge district where Reveal is not being used. However these areas have structures on the dashboard which are adding up to the denominator count. The client desires that thestructures in those areas should be removed from the denominator count.  See screeshot below.

![image](https://user-images.githubusercontent.com/5908630/98528552-83afc600-228d-11eb-8d76-c95a740d6a54.png)

**Comment by craigappl** [comment]
I cancelled all tasks, removed the areas from the plan, and ensured no teams were assigned to those areas. The line item is still showing up in the tables, but the counts are gone.
![image](https://user-images.githubusercontent.com/6067053/98609723-cd56db80-22a2-11eb-86c2-aa33b3208b1b.png)
