### ISSUE TITLE
IRS Planning - Select Plan Jurisdictions

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#140]
The Create Plan page needs to be able to determine Jurisdictions (OAs) to be included in the Plan through two components: Map and Table.

#### Dependencies
- [x] Admin Hierarchy / Taxonomy (to know which OAs are actually being de/selected)

#### Requirements
- [x] De/Selecting Jurisdictions can be accomplished via the Map and the Table
- [x] De/Selecting a non-OA Jurisdiction de/selects all child OA Jurisdictions
- [x] Changing selections in either component updates the other
- ~~Capture `Cmd+Z` to undo last interaction (* nice to have)~~

#### Map Interactions
- [s] Selected Jurisdictions are indicated with a ~~blue highlight outline~~ lesser fill-opacity
- [x] Shift-clicking a Jurisdiction de/selects the Jurisdiction (and its children)

#### Table Interactions
- [x] Clicking a checkbox de/selects the Jurisdiction (and its children)

#### Table Columns
- [x] Selected - Contains checkbox indicating selection status of the Jurisdiction
    * @mberg @rowo - Do we need to distinguish completely/partially selected Jurisdictions?
- ~~# - @mberg @rowo - What does this column actually represent?~~
- [x] Name - Name of the Jurisdiction
- ~~Number of Structures - **TBD - how do we get this number?**~~
- ~~Estimated Risk (* If we have Risk data / map-layers)~~
- ~~Resource Estimate (* if we have Resource Estimates)~~

**Comment by moshthepitt** [comment]
@cKellyDesign what kind of data structure do you need for the jurisdictions?
