### ISSUE TITLE
Add Messaging to Thailand Preview Stating its under Maintenance

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1402]
Thailand preview has a database issue which makes it unusable. As this is being worked on the client has requested that we setup a banner stating that the system is under maintenance. The reading in Thai should be `อยู่ระหว่างการปรับปรุงระบบ ขออภัยในความไม่สะดวก`

**Comment by moshthepitt** [comment]
This should would be a component that turns the entire web app into "maintenance mode" where it is the only component rendered.  This would be configurable, and would be made as a package.

**Comment by samkanga** [comment]
This ticket was marked as a won't fix. I will go ahead and close it.
