### ISSUE TITLE
Audit FI map API calls

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1407]
![x](https://user-images.githubusercontent.com/372073/99386100-fdc1f980-28e2-11eb-86b3-cfbe6f35f4b8.png)

1. We are making a call to slice id = 0 --> do we need to do so?
2. We are calling the structures slice --> do we need to do so?
3. We are making more than one call to the same slice.  Is it possible to combine the calls?

**Comment by moshthepitt** [comment]
Closed by https://github.com/onaio/reveal-frontend/issues/1407

**Comment by samkanga** [comment]
@moshthepitt could you confirm that the issue here was as a result of making unnecessary API calls, and that the solution was to remove those (#1 and #2) and making a combination on #3?

**Comment by moshthepitt** [comment]
@samkanga the error 500 was caused by item 1 in the list above.  We were making a call to a slice with id = 0 with does not exist on Superset.

2 and 3 are optimizations.
