### ISSUE TITLE
Keycloak 502 Error when logging into Reveal WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1419]
When logging into the webUI the user is often presented with a 502 error that can only be resolved by clearing cookies or using incognito mode. Below is a screenshot:
![image](https://user-images.githubusercontent.com/5908630/99960709-3e67ba00-2d9e-11eb-96ce-7a177ce8416b.png)

**Comment by craigappl** [comment]
How often does this happen? It seems to happen when a session expires on Thailand local.

**Comment by samkanga** [comment]
I will close this ticket in favor of https://github.com/onaio/reveal-frontend/issues/1302
