### ISSUE TITLE
Re-Order the day numbers to Match the event dates on IRS Performance Reporting

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1421]
The day number and the dates to the events recorded on the IRS performance reporting dashboard are need to be reordered so that for example day one has an older date than day 10. At the moment the higher day numbers have the older dates. See sample screenshot below.

![image](https://user-images.githubusercontent.com/5908630/100062065-0e70f300-2e40-11eb-84c3-5b7dd388b7ff.png)

**Comment by ciremusyoka** [comment]
@samkanga should we re-order the date column (Option A below) or the day column (Option B below)?
Option A:
| Day  | Date |
| -------| --------|
| 1 | 2020-11-09 |
| 2 | 2020-11-10 |
| 3 | 2020-11-11 |

Option B:
| Day  | Date |
| -------| --------|
| 3 | 2020-11-11 |
| 2 | 2020-11-10 |
| 1 | 2020-11-09 |

**Comment by samkanga** [comment]
@ciremusyoka we should go by option 1. Note that for the example you have given the dates are correctly ordered, starting with the oldest to the newest. On the dashboard given, the newest date was being given as day 1. Let me know if this is clear.
