### ISSUE TITLE
IRS Planning - Assigning Teams to Plan Jurisdictions

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#143]
Once a Plan is Finalized, users can start Assigning Teams to Plan Jurisdictions on the Finalized Plan page via the Assignment Table and Popup

#### Dependencies
- [x] OpenSRP or Superset endpoint for Teams
- [x] OpenSRP or Superset endpoint for Plans
- [x] OpenSRP endpoint for assigning Teams to Tasks

#### Requirements
- [x] Map and Table drill down  as described in #125 and #139 respectively
- [x] Non-OA Jurisdiction rows render `<None|Partially|Fully> Assigned` status
- [x] Unassigned OA Jurisdiction rows render `Assign` button 
- [x] Assigned OA Jurisdiction rows render `Assigned to <team name>` status
- [x] Team Selection Popup renders a list of all assignable teams

#### Table Columns
- [x] Jurisdiction Name
- [x] Number of Structures
- ~~Predicted Risk (* If we have Risk data / map-layers)~~
- ~~Resource Estimate (* if we have Resource Estimates)~~
- [x] Teams Assigned - `Assign` button or Assigned status

#### Table Interactions
- [x] Clicking an `Assign` button:
    - ~If no Task is found from Task endpoint(?): Render warning indication~ (not checking tasks)
    - [x] Else: Render Team Selection Popup

#### Team Selection Popup Interactions
- [x] Scrolling shows Teams above and below the current view (basic css `overflow:auto`)
- ~Clicking in Search Input filters the Teams being rendered in the popup as the user types (* nice to have!)~
- [x] Clicking a Team:
    - [x] ~POSTs Jurisdiction Task Assignment to OpenSRP endpoint, then~ Updates local state
    - [x] ~Closes the popup~ Updates the Select component
    - [x] Updates the Jurisdiction Teams Assigned cell

#### Questions
* Q1: Should Tasks be assigned immediately (as soon as a Team is selected) or should there be an Apply Team Assignments (or something) button which triggers the actual Task assignment?
* Q2: Can Tasks be re-assigned?
* Q3: Can multiple Teams be assigned to a single Task?

**Comment by armageddon** [comment]
@cKellyDesign @rowo @mberg Does this issue apply to Focus Investigation assignment as well? The same functionality will be needed for FI as well, and the plans will have the same workflows I think?

**Comment by armageddon** [comment]
Linking back to confluence scoping doc: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1143472206/Reveal+3+-+IRS+Planning

**Comment by cKellyDesign** [comment]
> Does this issue apply to Focus Investigation assignment as well?

☝️ Great question! 

cc - @moshthepitt

**Comment by cKellyDesign** [comment]
@githengi Please follow up here when the `Team Assignment` module is ready, looking for endpoints/params and payload schemas for `POST`/`PUT`ing when assigning Teams to plan-locations.
