### ISSUE TITLE
RVL-1359 - Remove Total Spray Areas, Targeted Spray Areas, Spray areas visited from the IRS reporting dashboard at Operation area level.

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1430]
Zambia prod
Version 1.0.1
User: Superset user.

1. Login to reveal
2. Go to monitoring
3. Select IRS planning
4. Select a Plan. e.g MACEPA: Full Reveal 2020 IRS Plan
5. Drill down the hierarchy to the operation area level.

**Current behavior:**
The table includes Total Spray Areas, Targeted Spray Areas, Spray areas visited. These indicators are not useful at this level. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/100450854-6705f180-30c7-11eb-9adb-444d3ba3b4ab.png)

**Expected behavior:**
Remove Total Spray Areas, Targeted Spray Areas, Spray areas visited from the operation area level table .

**Comment by moshthepitt** [comment]
Seems like a configuration issue.

This [Macepa report](https://web.reveal-zm.smartregister.org/intervention/irs/report/4cbe10b9-231e-5084-9646-0a923dcfa0da/eeec69eb-8f96-4a6e-8946-b9bd2aad1747) should be similar to this [VL report](https://web.reveal-zm.smartregister.org/intervention/irs/report/d40c1227-644b-55d6-b3f3-bed42380322f/ca8d62fd-acec-4498-a041-03414c67efc8).

**Comment by moshthepitt** [comment]
@samkanga this will probably be fixed by deploying [v1.0.3](https://github.com/onaio/reveal-frontend/releases/tag/v1.0.3) or greater.
