### ISSUE TITLE
New Plan on Zambia Production not showing data

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1433]
- [x] The client has created a new plan on the WebUI attached to the Senegal Hierarchy. The plan is available on the monitoring tab but has no data. The Plan is named Senegal Nov Plan and is accessible [here](https://web.reveal-zm.smartregister.org/intervention/irs/report/4ddbd420-a330-5a27-8b58-2a498a80b4ef). The client needs this for a demo later today.

**Comment by moshthepitt** [comment]
@samkanga this looks like its fixed https://web.reveal-zm.smartregister.org/intervention/irs/report/4ddbd420-a330-5a27-8b58-2a498a80b4ef
