### ISSUE TITLE
User Unable to Retire Plan on Thailand Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1434]
The user `vbdc_6.5.1-1` on Thai production is unable to retire the plan named  `A2 เขาช่องลม (2208040405) 2020-11-27`. The client has reported the save button seems to hang on the "Saving plan status" and does not seem to complete the saving process.

**Comment by ciremusyoka** [comment]
@moshthepitt @samkanga the changes we made on dynamic plan template [on this issue](https://github.com/onaio/reveal-frontend/issues/1413#issue-746612410)  are affecting how the plans are being processed before they are saved. The removed condition on bed net distribution is being expected since On the web our code assumes the conditions from the OpenSrp API and the ones on the template are equal in number.
We can fix this making sure we rely on the template when only when creating new plans.

**Comment by moshthepitt** [comment]
> assumes the conditions from the OpenSrp API and the ones on the template are equal in number

@ciremusyoka could give a practical example of this?  What exactly is failing and how?

**Comment by ciremusyoka** [comment]
@moshthepitt The plans failing were created before the templates were updated. And since when editing we are getting some data from the templates we end up trying the get data of non existing condition (in this case the condition we deleted) when processing the data to post to the API.

**Comment by moshthepitt** [comment]
@ciremusyoka  What's the best fix for this?

> We can fix this making sure we rely on the template when only when creating new plans.

Could you point out the relevant code that needs looking at?

**Comment by ciremusyoka** [comment]
> @ciremusyoka What's the best fix for this?
> 
> > We can fix this making sure we rely on the template when only when creating new plans.
> 
> Could you point out the relevant code that needs looking at?

Instead of getting `subjectCodableConcept` [here](https://github.com/onaio/reveal-frontend/blob/81aa49f1972f90c1dabe2cec3f354d5c1c53597d/src/components/forms/PlanForm/helpers.ts#L359-L363) from the template we should push it to the form but as a hidden field.

**Comment by moshthepitt** [comment]
@ciremusyoka ok go ahead with that.

**Comment by moshthepitt** [comment]
@p-netm take note of an example of changes that we'll need to reconcile into what you are working on at some point.  Would be cool to work on one shared codebase.
