### ISSUE TITLE
Data submitted not showing on the dashboard for MACEPA: Full Reveal 2020 IRS Plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1435]
Server: Zambia prod
version 1.0.1
Plan: MACEPA: Full Reveal 2020 IRS Plan
user: superset-user

From the android client, for the location Luna_5 the following screenshot has been captured and shows its fully synced.
![image](https://user-images.githubusercontent.com/5908630/100850831-70130c00-3495-11eb-8f2c-b3ec2e584eb3.png)

However, accessing the same location on the Monitor page (Western - Kaoma - Luena) does not show any data as shown on the screenshots below:
![image](https://user-images.githubusercontent.com/5908630/100851090-c1230000-3495-11eb-90fb-c915d48ef988.png)

The indicators section also does not reflect any data.
![image](https://user-images.githubusercontent.com/5908630/100851126-ced88580-3495-11eb-8967-b7fa518a09a5.png)

**Comment by moshthepitt** [comment]
@samkanga this also looks like it now has data https://web.reveal-zm.smartregister.org/intervention/irs/report/4cbe10b9-231e-5084-9646-0a923dcfa0da/17e209c1-6b78-4c4a-b5f5-eb32b4db8d65
