### ISSUE TITLE
Map view not loading for Plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1436]
- [x] The plan created on the new Senegal Hierarchy does not load the map view on the operational area. It return an error `Map failed to load. Jurisdiction not found`. Is there additional work that is needed to get the map view reflect on the monitor tab? The map view can be accessed on the link [here](https://web.reveal-zm.smartregister.org/intervention/irs/report/4ddbd420-a330-5a27-8b58-2a498a80b4ef/9ccdd2b8-97ba-4ad4-893c-06602c5d6275/map). Below is a sample screenshot of the error:
![image](https://user-images.githubusercontent.com/5908630/100864869-aa85a480-34a7-11eb-9091-402807118c28.png)

**Comment by moshthepitt** [comment]
Looks like it is fixed https://web.reveal-zm.smartregister.org/intervention/irs/report/4ddbd420-a330-5a27-8b58-2a498a80b4ef/9ccdd2b8-97ba-4ad4-893c-06602c5d6275/map
