### ISSUE TITLE
Handle expired sessions

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1439]
Currently, when a user logs in, she receives a token that expires at some point.  When this token expires, the web application does not handle it gracefully at all.  A user often needs to refresh or logout and then log back in, with no warning.  

We need to fix this.

# Proposed solution

- Modify the functionality to get the access token - either modify [getAccessToken](https://github.com/onaio/js-tools/blob/a6433bb02a1f5127a44986a532c8a1435f8a0a91/packages/session-reducer/src/index.ts#L160) or wrap it in another function such that it can either:
    - refresh the token
    - log out the user

## refreshing the token

- The session reducer contains information that can be used to detect when the token expires (expires_in and refresh_expires_in)
- If it is not currently possible to determine when a token expires, then the session reducer should be modified to enable this
- Next, we need a new API endpoint on the [express server](https://github.com/onaio/express-server) that when called, would handle the refreshing of the OAuth2 token with the authentication provider.  The OAuth2 spec provides a standard way of doing this.

With all these in place, then whenever the web app (client side) tries to get the access token for use, it would trigger the refreshing of the token, and then would use that new token.

In case the refreshing of the token is not possible or fails, the user should be logged out and redirected to the login page.

## logging out

Similar to refreshing the token, but instead of trying to refresh the token, we would notify the user that they need to log in again.

**Comment by moshthepitt** [comment]
@ciremusyoka we need to do this in a way that is immediately usable by https://github.com/opensrp/web

**Comment by Naima-Bashir** [comment]
This has passed QA. 
When one logs in, it does not log the user out, it refreshes the token gracefully
