### ISSUE TITLE
User Unable to view Structures on Thailand Production Dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1440]
- [ ] User `vbdu_12.1.1-1` has submitted data against a plan as per the screenshot1 below(taken from the MSSQL based dashboard). However, the data submitted does not show any structures on the monitor view of the WebUI. See the [plan](https://mhealth.ddc.moph.go.th/plans/update/3145b528-9005-5bdf-8445-3e0307d78230) here and the second screenshot below.

![image](https://user-images.githubusercontent.com/5908630/101007098-64494780-3572-11eb-9c77-1fe0fe30ba32.png)

![image](https://user-images.githubusercontent.com/5908630/101007240-6e6b4600-3572-11eb-87f4-aed19c004b76.png)

**Comment by moshthepitt** [comment]
@samkanga this plan has no tasks at all.  The web app report accurately reflects this.  If we believe that the plan does indeed have tasks, we should ask @Rkareko or @Wambere to help investigate that.

**Comment by Wambere** [comment]
@samkanga  the plan `A2 มาลาหน้าโรงเรียน (9502030301) 2020-11-26` with id `3145b528-9005-5bdf-8445-3e0307d78230` is for the jurisdiction `680d2d72-0424-444e-830e-6c58d98c2c31` which has no structures according to `https://servermhealth.ddc.moph.go.th/opensrp/rest/location/sync?parent_id=680d2d72-0424-444e-830e-6c58d98c2c31&serverVersion=0` and therefore no tasks were generated

Could the structures have been deleted somehow?
cc @moshthepitt @Rkareko

**Comment by Rkareko** [comment]
@samkanga  @moshthepitt @Wambere  confirmed that the operational area with id `680d2d72-0424-444e-830e-6c58d98c2c31` does not have any structures in the opensrp db.

**Comment by craigappl** [comment]
Thanks everyone, I notified Pedro.

**Comment by moshthepitt** [comment]
Closing this as we don't need to (and can't) do anything to fix it in this repo.
