### ISSUE TITLE
Uploaded Risk and Structures Data not available When Creating plans through Planning Tool

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1441]
Akros are doing tests on reveal stage on the upload of risk files and structures from a csv. The file is downloading and uploding successfully with the values entered into the risk and target columns of the the csv. However, when they create a plan through the planning tool, the following are the observations:

1. There structures count on the risk slider view remain at zero when the slider is moved from 0 to 100%.
2. On the map view a message appears to the right of the map reading `No descendant jurisdictions are targeted`
3. On the table below the map the risk and structures columns are all empty and do not show any of the uploaded values.

The expectation was that with the slider, one would be able to narrow down to the locations that match the uploaded risk values and be able to select them or deselect them for inclusion in an intervention.

**Comment by moshthepitt** [comment]
@samkanga is it possible to get an example of a plan for which this happens?  That is crucial missing information

**Comment by samkanga** [comment]
@moshthepitt you can use the plan [here](https://web.reveal-stage.smartregister.org/auoSelectJurisdictions/d36e06b3-c556-5f86-801b-d0a686114bcb/ecfbf048-fb7a-47d8-a12b-61bf5d2a6e7b).

**Comment by moshthepitt** [comment]
Blocked by https://github.com/OpenSRP/opensrp-server-web/issues/655

**Comment by ciremusyoka** [comment]
Also depends on https://github.com/OpenSRP/opensrp-server-web/issues/705

**Comment by ciremusyoka** [comment]
The structure counts are changing when the slider is moved. 
> Also depends on OpenSRP/opensrp-server-web#705

Will close this ticket in favour of the above OpenSRP ticket
