### ISSUE TITLE
Case Triggered Plan on Thailand Preview Not Showing data on WebUI Monitor Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1445]
- [ ] The client has reported having dropped structures while working with the plan [here](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/aba909a5-1776-5c20-a071-fb4b6390c28a/RACD_register_families). They went ahead to sync the data but the captured data is yet to reflect on the WebUI monitor page.

**Comment by Wambere** [comment]
@samkanga tasks had not synced. These should be visible now

**Comment by samkanga** [comment]
@Wambere I confirm the data is now visible on the map. Thank you. Did you mean the tasks had not synced from the OpenSRP server to the Canopy DB or is this from the materialised views to the dashboard ? Do we know what caused the tasks not to sync?

**Comment by Wambere** [comment]
@samkanga the data had not synced from OpenSRP into the warehouse. Not sure what caused this, but according to the logs, the first report of this was on Dec 7th at 7.45am

**Comment by moshthepitt** [comment]
Seems this is done.  Closing.
