### ISSUE TITLE
RVL-1358 Senegal Demo Plan displaying NaN on Zambia Prod

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1448]
The Zambia Production system is displaying NaN for the Senegal Demo plan. It looks like it's displaying this because React can't find a value for the calculated columns. **This is only showing a problem at the lowest level before the user clicks to enter the map view.**

Link: https://web.reveal-zm.smartregister.org/intervention/irs/report/73b6805f-c6a9-5194-9af7-f8a2ac9c7d7c/b0d8c52e-1d0b-4107-80f5-593fa55b55ca

Screenshot of headers:
![image](https://user-images.githubusercontent.com/6067053/101692807-969cee00-3a25-11eb-97ea-1276d4625c87.png)

Screenshot of row that has values, but we're still getting NaN for the calculations. Operational area Name 1860
![image](https://user-images.githubusercontent.com/6067053/101692909-ba603400-3a25-11eb-9c2a-4eb4243decca.png)

Below is a list of the indicators that are returned from Superset from the 1860 Row (Direct link: https://superset.reveal-zm-green.smartregister.org/superset/slice_json/6?form_data={%22order_by_cols%22:[%22[\%22jurisdiction_depth\%22,+true]%22,%22[\%22jurisdiction_name\%22,+true]%22],%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%2273b6805f-c6a9-5194-9af7-f8a2ac9c7d7c%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000})
```
{
  "id": "95f1ad66-b388-5c77-a3ba-c44443f7f2d1",
  "plan_id": "73b6805f-c6a9-5194-9af7-f8a2ac9c7d7c",
  "jurisdiction_id": "6fbd2922-c903-463a-8763-a7213d725ccb",
  "jurisdiction_name": "1860",
  "jurisdiction_depth": 4,
  "jurisdiction_path": "[\"173884b5-60c7-4376-ad38-57f21cd90ccg\", \"7cf23db4-de55-4038-8884-1469ceb27173\", \"8da99a60-9c73-4780-8d24-ecc5d67c43b9\", \"b0d8c52e-1d0b-4107-80f5-593fa55b55ca\"]",
  "jurisdiction_name_path": "[\"Senegal\", \"Matam\", \"Ranerou\", \"CS Ranerou\"]",
  "is_virtual_jurisdiction": false,
  "health_center_jurisdiction_id": "b0d8c52e-1d0b-4107-80f5-593fa55b55ca",
  "health_center_jurisdiction_name": "CS Ranerou",
  "totstruct": 19,
  "targstruct": 19,
  "rooms_eligible": 13,
  "rooms_sprayed": 13,
  "sprayed_rooms_eligible": 13,
  "sprayed_rooms_sprayed": 13,
  "foundstruct": 9,
  "notsprayed": 2,
  "noteligible": 3,
  "notasks": 0,
  "jurisdiction_parent_id": "b0d8c52e-1d0b-4107-80f5-593fa55b55ca",
  "sprayedstruct": 7,
  "duplicates": 0,
  "sprayed_duplicates": 0,
  "notsprayed_reasons": "[\"refused\"]",
  "notsprayed_reasons_counts": "{\"refused\": 1}",
  "latest_spray_event_id": "fa29f7a2-63d9-4948-9f7c-c529747639d6",
  "latest_spray_event_date": "2020-12-02T00:00:00",
  "spraycov": 0.3684210526315789,
  "spraytarg": 0.47368421052631576,
  "spraysuccess": 0.7777777777777778,
  "spray_effectiveness": 0.3684210526315789,
  "structures_remaining_to_90_se": 11,
  "tla_days_to_90_se": 0.6733333333333333,
  "roomcov": 1,
  "reviewed_with_decision": "Not done",
  "latest_sa_event_id": null,
  "latest_sa_event_date": "NaT",
  "is_leaf_node": true
}
```

You can see that spraycov, spraytarg, spraysucceess, spray_effectiveness all have numbers.

Expected behaviour:
- The columns calculate properly.

I dug around and found that it looks like this lowest level view has some things named differently.
- foundcoverage https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/IRS/JurisdictionsReport/fixtures/index.ts#L186 isn't in the JSON that's returned from Superset
- spraycovtarget is not in the JSON. Instead we have spraytarg https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/IRS/JurisdictionsReport/fixtures/index.ts#L176
- perctvisareaseffect is not in the json returned https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/IRS/JurisdictionsReport/fixtures/index.ts#L158

**Comment by moshthepitt** [comment]
@craigappl this was fixed by https://github.com/onaio/reveal-frontend/pull/1447
