### ISSUE TITLE
Client upload feature is throwing a 400 error

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1456]
CHAI did a test of the client upload feature on the "Clients" page and reporting that when they used the client template, the sync failed and showed a 400 error. 

This is the client csv template: https://docs.google.com/spreadsheets/d/1uqX6BHxXb5M-3GHVTI2tbCKLMuNbF9hOC5iTHsSd41Y/edit#gid=0

I believe the only constraint is that you need to have the school_id in order for clients to be created. It is possible that it was throwing an error because they were testing without IDs?

When I download the file shown in the uploaded clients list table and then try to upload it again, I do get a successful upload notification, but that csv is blank. Is there a way to confirm this functionality or possibly share a few real school-ids so that I can continue to test this?

**Comment by moshthepitt** [comment]
Seems that we need to do the following:

1. Figure out why the CSV template downloaded is blank
2. Test and ensure that a properly filled in CSV will work

**Comment by moshthepitt** [comment]
> Is there a way to confirm this functionality or possibly share a few real school-ids so that I can continue to test this?

@isabelcshaw I am not sure about this.  We can probably liase with an OpeSRP API engineer to get some school ids so that you can continue to test.

**Comment by githengi** [comment]
@isabelcshaw Missing settings are the cause of the blank CSV.

I have talked with Ronald to upload settings so that this is able to work.

**Comment by moshthepitt** [comment]
Thank you @githengi
