### ISSUE TITLE
RVL-1396 - Structures not appearing in Web UI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1458]
**Thailand Preview Environment**

1. Log-in on Android as bvbd_mhealth/Test123
2. Select operational area BVBD training site 3 
3. Select plan: A1 Thailand test site BVBD 3 2020-12-21 vr2
4. Add a new structure and carry out family registration
5. Save form and sync
6. Check Web UI that structure appears

Screenshots below from mobile app and Web UI monitoring tab
Web UI monitoring tab:
![image](https://user-images.githubusercontent.com/5908630/102863136-3786a280-4443-11eb-85be-f5f2d3a3fe1b.png)

Mobile Device:
![image](https://user-images.githubusercontent.com/5908630/102863179-45d4be80-4443-11eb-8eb3-4798c9765b2b.png)

**Comment by moshthepitt** [comment]
@samkanga I want to discourage issues without sufficient information in the future so permit me to say and ask the following (which should be included in future issues):

1. As one can see, the web app is accurately showing the data that it has. i.e. you can see that the web app claims there are zero structures for it to display.  For this issue, which of the following is correct: 
    - Do we believe that the web app actually received the data, but did not display it?
    - Or do we believe that the web app is probably working okay, but did not receive the correct data?
2. What is this plan's id?
3. What is the URL to the plan on the web app?
4. For this particular issue it seems that there are no tasks for this plan in the Canopy database.  This is an issue that has been reported before.
    - Is it possible to fix it the same way as the other(s) were fixed?
    - When reporting issues that we suspect may have been reported before, could we note that so that the person looking at it has some context?

**Comment by samkanga** [comment]
This is noted. Find the requested information below:
1.  Based on #4 above the web app is working OK, but did not receive the data.
2. [PlanID](2f148705-4f2d-57d7-b487-923f3d69dd4b)
3. [Here](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/50a5d93c-576d-59c4-a695-1cbb7be8ab2b/RACD_register_families ) is the URL of the plan on the Web App: 
4a. Yes. Do we know what causes the tasks not to sync?
4b. This is noted.

**Comment by moshthepitt** [comment]
> Yes. Do we know what causes the tasks not to sync?

@samkanga is this a question for either @Rkareko @githengi ?

**Comment by githengi** [comment]
> > Yes. Do we know what causes the tasks not to sync?
> 
> @samkanga is this a question for either @Rkareko @githengi ?

@samkanga No sure if this is sync between device and OSRP server, or  OSRP server and canopy?

**Comment by moshthepitt** [comment]
@githengi I can't seem to find tasks for the above plan `2f148705-4f2d-57d7-b487-923f3d69dd4b` anywhere - in OpenSRP or Canopy.

**Comment by samkanga** [comment]
@githengi as a temporary fix, could we check if the data is available on the OpenRMS server and attempt to sync it with Canopy?

**Comment by moshthepitt** [comment]
That is what I am currently trying to determine @samkanga

**Comment by githengi** [comment]
@moshthepitt below are the task summary for the plan

    12 | RACD Register Family
     4 | Mosquito Collection
     1 | BCC
    38 | Bednet Distribution
    58 | Blood Screening
     6 | Larval Dipping

**Comment by moshthepitt** [comment]
@samkanga please check it now

**Comment by samkanga** [comment]
@moshthepitt @githengi I confirmed that the data is now showing up on the WebUI. Thanks.

**Comment by moshthepitt** [comment]
For future reference, this was a Canopy connector issue.  It should probably be created on the Canopy repo if it happens again.

**Comment by samkanga** [comment]
@moshthepitt what was the issue with the canopy connector and how was this resolved? Was this the source of the issue in the last occurrences?

**Comment by moshthepitt** [comment]
@samkanga for some reason the Canopy connector had not pulled in all the tasks.  Not sure why,  I fixed it be re-pulling.  @Wambere may know more (when she is back) on why this happen(s/ed)
