### ISSUE TITLE
Existing Team Assignment not Showing on Some Locations on the Zambia Production Instance

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1459]
There are instances where the existing team assignment is not being reflected on the Reveal WebUI for Zambia production. This is leading to an error 400 as shown on the screenshot below. The issue on the screenshot has however been resolved, but the occurence needs additional investigation

![image](https://user-images.githubusercontent.com/5908630/102867942-8be15080-444a-11eb-81ac-1f9c2bfc9509.png)

**Comment by moshthepitt** [comment]
@samkanga @githengi could you give details on the assignment that was being not detected by the web app.  Things like start date, end date, etc

**Comment by githengi** [comment]
The assignment above on `Kakn-15` was not being detected despite it existing.

I had to manually update the fromDate to today for the assignment to reflect on webUI.

The fromDate that was there previously was  `2020-11-30` and toDate `2021-01-15`

**Comment by samkanga** [comment]
@moshthepitt have you had a chance to look at the issue above?

**Comment by moshthepitt** [comment]
@samkanga no I have not

**Comment by ciremusyoka** [comment]
The fix will be to implement pagination for the `/organization/assignedLocationsAndPlans` endpoint to ensure we fetch all assignments.
