### ISSUE TITLE
Render one polygon per Structure on the Map

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#146]
Currently we are adding geometries to the Map for every Task (and a Structure can have multiple Tasks). Ideally we should only be rendering a single geometry per unique Structure, which will use `fill-color` to represent the current Structure status.

- [ ] Include `lastModified` property in Superset [slice](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22slice_id%22%3A%20456%7D)([s](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22slice_id%22%3A%20460%7D))
- [ ] Use `lastModified` property to chose which Task geoms to add to the Map

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/195
