### ISSUE TITLE
Upload json form is throwing a 400 error  RVL-339

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1467]
Login to web stage: https://web.reveal-stage.smartregister.org/manifest/file-upload
Go to admin- releases and click on upload form.
Upload a json form.
I uploaded a blodd screening json form.
Click upload.
Observe the error. 
![image](https://user-images.githubusercontent.com/61143692/104565209-ff970780-565c-11eb-9e9b-dac658a43534.png)

**Comment by samkanga** [comment]
I will transfer this issue to OpenSRP Web [here](https://github.com/OpenSRP/opensrp-server-web/issues/688), and close this ticket.

**Comment by ciremusyoka** [comment]
Instead of throwing 400 we should  show the exact message of the error thrown by opensrp server
