### ISSUE TITLE
Data Synced on Android Device not Showing up on Indicator Count

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1468]
The planID for the affected plan is `d96f5c59-dea2-4612-8da7-2753bbbe8259`

The users went to the field and recorded 42 blood draw data and synced completely. However the web UI shows the blood screening result = 6. Its not clear what the issue is. Below are some screen shots from the synced device and of the dashboard.

Synced Device
![image](https://user-images.githubusercontent.com/5908630/104577722-dd0beb00-566a-11eb-9dfb-7d97f14e1717.png)

Dashboard
![image](https://user-images.githubusercontent.com/5908630/104577767-ebf29d80-566a-11eb-8bc7-30de1eeabd2e.png)

**Comment by ciremusyoka** [comment]
Closed by https://github.com/onaio/canopy/issues/1773
