### ISSUE TITLE
RVL-1421 - BCC activity data not syncing to Web Dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1470]
BCC data was captured on the Thailand production android application and successfully synced. However, the data does not seem to show up on the WebUI page. [Here](https://mhealth.ddc.moph.go.th/focus-investigation/map/6bc867a9-bed1-50bf-9e5c-f263d283b8ba/BCC_Focus) is the link to the WebUI page for the activity.

The user who submitted the data is `vbdu_6.5.3-1`

Below is the android image showing the completed BCC activity with the device synce.
![image](https://user-images.githubusercontent.com/5908630/105174683-fcf05280-5b33-11eb-8fb6-1c90a8fa16ac.png)

**Comment by ciremusyoka** [comment]
@samkanga this was fixed by updating the ware house and the error was attributed to the server version issue on opensrp reported [here](https://github.com/onaio/canopy/issues/1773).
