### ISSUE TITLE
Update Thailand WebUI to Accommodate the Shift of Task Generation to OpenSRP

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1473]
- [x] The Thailand deployment will be shifting the task generation from NiFi to OpenSRP. As part of the process, the flags in the plans that tells NiFi to generate tasks for the respective plans will need to be turned off.

**Comment by Naima-Bashir** [comment]
If this shos internal: 
"code": "taskGenerationStatus",
      "valueCodableConcept": "internal"
      
      it is fine

**Comment by Naima-Bashir** [comment]
@Wambere is nifi task generation shut off?

**Comment by Naima-Bashir** [comment]
Created this plan: https://reveal-th-preview.smartregister.org/opensrp/rest/plans/d53fc448-bae1-56f6-9df7-b923ac79145c

Tested that this is internal: 
{
"code": "taskGenerationStatus",
"valueCodableConcept": "internal"
}
