### ISSUE TITLE
Macepa IRS Lite Southern Live Plan not Showing some Values

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1474]
The Macepa IRS Lite Southern Plan is not displaying data on the` % Total Structures Sprayed` ,  `% Targeted Structures Sprayed` and `Found Coverage` columns as per the plan accessible [here](https://web.reveal-zm.smartregister.org/intervention/irs-lite/report/88d4f46e-5fd0-4a02-967f-57624584ab8b/52a8e221-1f3c-4d45-8130-36b0d1204017). Below is a sample screenshot:

![image](https://user-images.githubusercontent.com/5908630/105977548-8a86f180-60a2-11eb-8953-7e7d30c36209.png)

**Comment by ciremusyoka** [comment]
The targets for the jurisdictions should be uploaded

**Comment by samkanga** [comment]
The targets are now showing. I will go ahead and close this ticket.
