### ISSUE TITLE
Logout user after specified time

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1477]
Add a configurable functionality that will logout user gracefully after a specific amount of time.

**Comment by moshthepitt** [comment]
So right now @Naima-Bashir reported that the token is refreshed continually.

We want to change things such that:

1.  There is a config to turn on/off the auto-refreshing.  If it is off then you will be logged out when token expires
2.  There is a config to control how long a session stays active.  If it is set to 60 * 60 * 3 seconds, for example, then that is the length of time that the token will be auto-refreshed.  After that you are automatically logged out.

**Comment by ciremusyoka** [comment]
> 2. There is a config to control how long a session stays active.  If it is set to 60 * 60 * 3 seconds, for example, then that is the length of time that the token will be auto-refreshed.  After that you are automatically logged out.

My thought is this config will be on express server. Right?

**Comment by moshthepitt** [comment]
Yeah on the express side.  Likely all the configs regarding this will be there.
