### ISSUE TITLE
Implement loading animation Before structures load when toggling between goals

### ISSUE THREAD

**Issue by kahama94** [onaio/reveal-frontend#148]
There is a short lag when we toggle between various goals. Implementing a spinner animation would be ideal to inform a user features are loading

**Comment by kahama94** [comment]
Triggering the spinner is dependent on a boolean showSpinner which is determined by  two boolean flags isLoading and loaded.The two are being added pretty fast causing the spinner not to be seen. To prove this adding a debugger on the Spinner component shows the spinner loading. Looking into the store we have showSpinner set on the following cases TOGGLE_LAYER, TRIGGER_SPINNER, REQUEST_DATA and RECEIVE_DATA. Not certain how to go about this am still researching on how to handle this issue

**Comment by cKellyDesign** [comment]
Closing this as it seems to be a non-issue.
