### ISSUE TITLE
Swap of Wording on Thailand Monitoring page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1480]
Swap the the position of the following two words: ระยะท้องที่ and สถานะ as per the screenshot below on the Thailand Monitoring page:

On the RACD
![image](https://user-images.githubusercontent.com/5908630/106703474-5c059b00-65fb-11eb-825f-40f15c965be1.png)

On the Routine Plans
![image](https://user-images.githubusercontent.com/5908630/106703503-658f0300-65fb-11eb-9a48-b9f0279d78e2.png)

The structure pop-ups on the monitor page are also in English. Do we have the translations for these? See sample screenshot below:
![image](https://user-images.githubusercontent.com/5908630/106887430-2db8b600-66f6-11eb-8782-ac6292e765d5.png)

**Comment by ciremusyoka** [comment]
Additional translations [here](https://docs.google.com/spreadsheets/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit?folder=1MN5J-PK6KUOHC6gw3KKmf12vV-GQFPkr#gid=209283218) under webUI trans NOs 29,30 and 31.
