### ISSUE TITLE
Enforce Automated Selection of Subvillage Classification When Creating Routine Plans

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1482]
**Problem**
Users can sometimes get the subvillage classification (A1, A2, B1, B2)  for routine/reactive plans wrong. 

**Requirements**
- The subvillage classifications is automatically selected from Biophics
- The subvillage classification field in the plan creation page is displayed but not-editable
- Subvillage classification still appears in the name of the plan, in the monitoring page and dashboard

**Considerations:**
- Is there a difference between how to fetch the subvillage classification for routine vs reactive plans. 
- Does automatically fetching the subvillage classification impact the plan name?

![image](https://user-images.githubusercontent.com/5908630/106850850-4c06bd80-66c6-11eb-8fbc-26e8060900c5.png)

**Comment by moshthepitt** [comment]
@samkanga I do not understand what specific changes are being requested for in this issue.

**Comment by samkanga** [comment]
@moshthepitt the request is to have the location classification made automatically based on data contained in biophics and not have this added manually by a user during the creation of a plan.

**Comment by moshthepitt** [comment]
@samkanga that would make this 100% a data engineering (Canopy) project, no?

**Comment by samkanga** [comment]
@moshthepitt I am not sure. Should I post the ticket [here](https://github.com/onaio/canopy/issues).

**Comment by moshthepitt** [comment]
@samkanga this probably needs more details first.  In this issue there are screen grabs of the web app

But this is a request made later:

> the request is to have the location classification made automatically based on data contained in biophics and not have this added manually by a user during the creation of a plan.

So we need a more detailed description of what is required that includes detailed acceptance criteria.

Questions such as these should be answered:

- where is the data in Biophics that is being used for this?
- is it used during plan creation in Biophics (I think Canopy does this)?
- what role does the web app have to play here i.e. do we anticipate needing work done there?

**Comment by githengi** [comment]
@moshthepitt I think the flow here is 

1. Nifi picks classification from Biophics and saved the classification in the location properties e.g a in a property `case_classificaction`
2. Nifi makes sure that updates on case classification table are synced back to OpenSRP locations
3. When one selects the jurisdiction in Web app, the webapp picks the classification from location properties for the selected jurisdiction and populates the component "Local term " in the 1st screen shot above
4. The "Local term " in the 1st screenshot is made readonly

@samkanga the 1st 2 tasks items are canopy related

**Comment by samkanga** [comment]
@githengi @moshthepitt  I have created a separate ticket for tasks 1 and 2 [here](https://github.com/onaio/canopy/issues/1818).

**Comment by Wambere** [comment]
@samkanga the subvillage classification in Biophics are also entered by a user when creating the index case, this is not information in some db anywhere. Which means there is just as much a chance of the user inputting the wrong thing as if done from the web. A better solution would probably be to get this info directly from the source

**Comment by moshthepitt** [comment]
sorry @samkanga @githengi I have questions

> When one selects the jurisdiction in Web app, the webapp picks the classification from location properties for the selected jurisdiction and populates the component "Local term " in the 1st screen shot above

- this means that the location properties will have the classification?  Could we get a sample payload of such a location with this property?
- could you describe the phrase "local term" some more?

**Comment by samkanga** [comment]
@Wambere that makes sense. I was under the impression that the classification information is already available and stored somewhere on the biophics system. I will do additional follow-up on this and revert.
@moshthepitt I can respond on the second bullet. The `Local term` refers to the filed right below the locations when creating a dynamic FI plan. The Local Term is what is returned by the google translator from Thai. See the screenshot shared earlier above.

**Comment by githengi** [comment]
@moshthepitt the location would look like
```
{
    "type": "Feature",
    "id": "{{id}}",
    "geometry": {
        "type": "MultiPolygon",
        "coordinates": [ ]
    },
    "properties": {
        "status": "Active",
        "parentId": "{{parentId}}",
        "name": "{{name}}",
        "geographicLevel": 5,
        "version": 0,
        "externalId": "{{value}}",
        "name_en": "{{value}}",
        "fi_classification": "A1"
    },
    "locationTags": [
        {
            "id": 2,
            "name": "Operational Area"
        }
    ]
}
```

**Comment by samkanga** [comment]
@Wambere CHAI has confirmed the classification information exists on Biophics and will share details on how to access it.

**Comment by samkanga** [comment]
@Wambere here is where to get the classification information on biophics:

**Comment by Wambere** [comment]
Looks like there is a lot of nulls. Is there a plan on how to handle these?
I can just post what is there

**Comment by samkanga** [comment]
@Wambere let me follow-up with CHAI on the issue of the nulls and revert.

**Comment by samkanga** [comment]
@Wambere CHAI has advised we go ahead and fetch the values and replace nulls with N/A. They say the classification list will be updated regularly, so the null values (N/A) should have a classification soon.

**Comment by Wambere** [comment]
@samkanga noted. There was 5726 locations with matches. These have already been updated in openSRP

**Comment by samkanga** [comment]
@moshthepitt tasks 1 & 2 on the list [here](https://github.com/onaio/reveal-frontend/issues/1482#issuecomment-776206206) have been completed.

**Comment by moshthepitt** [comment]
@samkanga feel free to schedule this in the milestone that is most appropriate.

@ciremusyoka could you please provide an ETA?

**Comment by ciremusyoka** [comment]
@moshthepitt @samkanga  one and half days will be enough.

**Comment by ciremusyoka** [comment]
> @Wambere CHAI has advised we go ahead and fetch the values and replace nulls with N/A. They say the classification list will be updated regularly, so the null values (N/A) should have a classification soon.

@samkanga in case we miss the classification when auto assigning on the web what value should we default to.

**Comment by samkanga** [comment]
@ciremusyoka we should default to `N/A`.

**Comment by samkanga** [comment]
@ciremusyoka just a follow-up on the use case of what happens to a plan where the classification was N/A at plan creation but the classification gets updated in OpenSRP. The plans shall maintain the classification adopted at the time if creation.
