### ISSUE TITLE
Updating Layout of Thailand Manage Plans Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1486]
**Problem**
- Users are getting confused between reactive and routine FI plans in the manage plans section

**Requirements**
- Update the manage plans page to look similar to the monitor plans page (i.e. separate tables for Reactive and Routine plans)

Refer to proposed UI below
![image](https://user-images.githubusercontent.com/5908630/106992894-8d60a100-678a-11eb-9fc9-f9a0d5a299cc.png)

**Comment by samkanga** [comment]
@moshthepitt Can we use existing activity type (Dynamic FI/Be) to differentiate between routine and reactive plans. Advice if there are any alternative approaches.

**Comment by moshthepitt** [comment]
@samkanga I'm very unlikely to be convinced that this is a good idea.  Especially when I also take into account all the other requests to change this same page to look or work differently.

- What is the Reveal product vision regarding this?
- From a technical point of view is the additional complexity worth it?
- Do we need input from our design department?

**Comment by samkanga** [comment]
@moshthepitt the request here focused on creating uniformity between the two pages that lists the plans. The client says this is to improve the user experience. I can pass this by @rowo and hear his thoughts on the same.
Separately, if we were to go ahead with this, what would be the associated level of effort in days?

**Comment by moshthepitt** [comment]
> the request here focused on creating uniformity between the two pages that lists the plans. The client says this is to improve the user experience. I can pass this by @rowo and hear his thoughts on the same.

Yeah, I certainly would be hesitant to take this on without Roger's input.

> Separately, if we were to go ahead with this, what would be the associated level of effort in days?

@ciremusyoka could you help come up with the ETA?

**Comment by rowo** [comment]
I think we probably need to revise the entire UI at some point. For example n the OpenSRP Web work, there are more ways to create hierarchy with subnav and subsections. 

For this, our approach should probably be to do the minimal amount of work to fix the problem (if the client is forcing us to fix it). Since there's an existing pattern with separate tables, maybe that's fine. I don't have enough familiarity here on reactive vs routine to really make a good call. @moshthepitt, @samkanga, and @mberg you might need to make this decision.

In general, the thing I don't like about the two stacked tables is table length, discoverability, and general interaction since you lose the headers when scrolling.

**Comment by samkanga** [comment]
@moshthepitt would including a plan type under the filter option work better than having separate tables.

**Comment by moshthepitt** [comment]
> a question from @mberg: would including a plan type under the filter option work better than having separate tables.

Sounds like a better suggestion imho.  But would be cool to get a mockup

**Comment by mberg** [comment]
The mockup is add a filter for plan type as an option where you the have filter for user / teams.

**Comment by moshthepitt** [comment]
@ciremusyoka let's get an LoE for this and pass it on to @samkanga so that we can schedule this

**Comment by samkanga** [comment]
@moshthepitt @mberg I had a chat with CHAI today and they proposed an alternative to the filter for consideration alongside some follow-up questions:

Proposal:
1. Could we instead of the filter next to the user name, include a new plan type column that can be used to sort by either routine or RACD plan? The `activity type` column can be hidden as it is presently not used.

Additional Questions:
1. How was the table separation on routine and RACD tables achieved on the monitoring page different from the organization in instances such as those of IRS and MDA? Is the same approach not possible with the manage plan page?
2. What would be the LOE of making the manage plans configurable so that for countries requiring table separation can have it and where its not required it can be disabled?

**Comment by moshthepitt** [comment]
> Could we instead of the filter next to the user name, include a new plan type column that can be used to sort by either routine or RACD plan? The activity type column can be hidden as it is presently not used.

We could do this.  LoE is 1 -2 days.

---

> 1. How was the table separation on routine and RACD tables achieved on the monitoring page different from the organization in instances such as those of IRS and MDA? Is the same approach not possible with the manage plan page?

The monitor page has FI plans exclusively whereas the "manage plans" page has all plan types.

> 2. What would be the LOE of making the manage plans configurable so that for countries requiring table separation can have it and where its not required it can be disabled?

1 week.  Probably less.

**Comment by samkanga** [comment]
@moshthepitt @ciremusyoka we had additional discussion on this internally and with the client and settled for the option [here](https://github.com/onaio/reveal-frontend/issues/1486#issuecomment-797471463). @ciremusyoka please share an estimate on the LoE to undertake this.
