### ISSUE TITLE
Plans with only blood screening tasks are not appearing in the Web UI monitoring page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1487]
**Description**
**Server**: Thai Preview
**User**: bvbd_mhealth
**Plan**: https://web.reveal-th-preview.smartregister.org/plans/update/03b381af-da01-542b-8ca3-adca7a72b3c0
**Expected behaviour**: Able to view the plan in the monitoring page.

**Operational area**: BVBD training site 3

**Steps to reproduce:**
1. Go to the monitoring tab
2. Filter the normal work table for `blood screening`
3. No results shown
4. Try using the plan ID in the URL: https://web.reveal-th-preview.smartregister.org/focus-investigation/map/03b381af-da01-542b-8ca3-adca7a72b3c0
5. No plan or jurisdiction found

**Comment by ciremusyoka** [comment]
The plan is not syncing in to into `plan_jurisdiction` table of the warehouse.

**Comment by ciremusyoka** [comment]
@samkanga no. 4 can't work because the last part is not supposed to be the plan id.

**Comment by samkanga** [comment]
This issue has been resolved. Additional checks being made on the reason for the behaviour. I will go ahead and close it.
