### ISSUE TITLE
Plans are showing different status on Action plan page and on the Monitor page for Thailand Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1488]
Thailand has reported instances where the same plan shows different status on the action plan page and on the monitoring page. A case in point is the plan with the details below:

- plan : A1 - โป่งลึก (7608060201) - โสน คำสอน - 2021-01-15 - Site
- plan id: b618ca2b-1469-4221-8ff3-a36e08ec8f8c
- status in 'manage plans' (web UI) = complete. [Here](https://mhealth.ddc.moph.go.th/focus-investigation/map/8876ab40-e2cd-5790-950f-ef15e6267bb5
) is a link to the WebUI.
- status in 'monitor' (web UI) = active

See Sample Screenshots below:

**Action Page** - Status reads - Done
![image](https://user-images.githubusercontent.com/5908630/107208157-41c02880-6a12-11eb-8676-4a9a0ab241ae.png)

**Monitor Page** - Status reads - Active
![image](https://user-images.githubusercontent.com/5908630/107207647-9911c900-6a11-11eb-932f-155a744b488c.png)

The expectation is that plans should have the same status irrespective on which page its accessed from.

**Comment by ciremusyoka** [comment]
@samkanga The plans are not syncing into the warehouse.

**Comment by samkanga** [comment]
I will close this issue as the issue has been traced to serverVersion on OpenSRP and a ticket created [here](https://github.com/OpenSRP/opensrp-server-core/pull/408).
