### ISSUE TITLE
Check on the % Total Structures Sprayed Formula on IRS Lite Dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1489]
Akros has asked that we check the calculation on the column titled `% Total Structures Sprayed`. The desired formula is **(Sprayed Structures/Total Structure) * 100**. For some reason the column with the total structures is displaying zeros. See sample screenshot below to the [Macepa IRS Lite Southern Live Plan](https://web.reveal-zm.smartregister.org/intervention/irs-lite/report/88d4f46e-5fd0-4a02-967f-57624584ab8b/52a8e221-1f3c-4d45-8130-36b0d1204017).
![image](https://user-images.githubusercontent.com/5908630/107319143-3a029180-6aaf-11eb-9443-833668115e6d.png)

**Comment by Naima-Bashir** [comment]
This is linked to:  https://smartregister.atlassian.net/browse/RVL-1437

**Comment by ciremusyoka** [comment]
Linked to #1498

**Comment by ciremusyoka** [comment]
Jurisdiction data with `jurisdiction_metadata-structures` identifier was not being loaded to the DWH. 
[Here](https://onaio.slack.com/archives/C01ASKAEZKL/p1614078473013200?thread_ts=1613464821.008600&cid=C01ASKAEZKL) is slack conversation for the fix.

**Comment by Naima-Bashir** [comment]
Frazer from akros has uploaded a new csv for targeted structure and total structures. They want advise on the next step
They want to know when will those updated totals will be reflected?

**Comment by Naima-Bashir** [comment]
this needs to be done “Delete jurisdiction-metadata-structures settings entries where the key field is a higher level jurisdiction” otherwise it will still not be accurate for the higher level jurisdictions.
I have added it to the backlog to be picked up after the milestone is complete

**Comment by Naima-Bashir** [comment]
Linked issue: https://github.com/OpenSRP/opensrp-client-reveal/issues/1263
