### ISSUE TITLE
Ensure MDA Point Reporting is updated 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1490]
We have updated the drug distribution eligibility age range for Eswatini. This that on the app side, drug distribution tasks will now be generated for a wider range of children. We need to make sure that our MDA Point reporting reflects that same rule. I believe that this should just be a change to our queries/filters - no UI changes are being requested on the reporting views. 

Previous eligibility range: >= 5 years to <=15 years 
**Updated eligibility range: **>=6 years and <=18 years****

Here is the MDA Point Reporting view as a reference: 
<img width="1402" alt="Screen Shot 2021-02-09 at 8 25 27 AM" src="https://user-images.githubusercontent.com/12836913/107394147-64a11a00-6ab0-11eb-95d3-834fa292a817.png">

**Comment by ciremusyoka** [comment]
@isabelcshaw Thie reports looks Okay to me. Do we have any reports that are different from what is expected?
If we do please point them out.
cc @moshthepitt
