### ISSUE TITLE
Allow user to export student list at any level of the location hierarchy

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1491]
The "Export Student List" feature is accessed by navigating to "admin" --> "clients." 

Right now, when a user tries to download the student list, they are forced to click all the way through the location hierarchy in the dropdown to choose only the school level. 

<img width="1077" alt="Screen Shot 2021-02-09 at 8 17 58 AM" src="https://user-images.githubusercontent.com/12836913/107393172-556d9c80-6aaf-11eb-9b80-182408f64f6e.png">

The expected behavior is for the user to be able to select any level of the hierarchy in the dropdown, whether it is a region, a district, or a school. If they want to be able to export all of the children in their campaign, we don't want them to have to go school by school in order to do so. 

@rkodev has already completed the backend work on his side for allow for these changes to be made. He'll add some more context in the comments below.

**Comment by moshthepitt** [comment]
@ciremusyoka lets have a quick chat before you start

**Comment by rkodev** [comment]
@moshthepitt @ciremusyoka 
The changes were made to the api **_/rest/upload/template_**  to support the parameter  **_location_id_**  as a comma-separated list if locations or as a higher-level location and it will download all the associated children

**Comment by ciremusyoka** [comment]
@isabelcshaw  can we get @rowo input on the best way to implement the selection of the hierarchy levels and be able to stop at any level and export the students list.
cc @moshthepitt

**Comment by ciremusyoka** [comment]
@moshthepitt Can we have this as a simple drill down table e.g
|#       | Name |      |
|--------|---------|------|
| 1       | Eswatini| Download|
| 2       | Zambia| Download|
| 3     | Namibia| Download|

**Comment by isabelcshaw** [comment]
@ciremusyoka after talking with Roger, we think the best way forward is to use a nested hierarchy with two components: carrots for drill down and selection just by clicking on the label. Here are a few examples of this, but the best (and simplest) model is this first mock: https://marvelapp.com/prototype/f3igd3h/screen/73173137

<img width="463" alt="Screen Shot 2021-02-16 at 2 27 57 PM" src="https://user-images.githubusercontent.com/12836913/108167872-3a042200-70ab-11eb-8b06-77799d2d6a43.png">


<img width="437" alt="Screen Shot 2021-02-16 at 2 27 45 PM" src="https://user-images.githubusercontent.com/12836913/108167886-3f616c80-70ab-11eb-95fa-57a01158fbc0.png">

**Comment by rowo** [comment]
@ciremusyoka so is https://github.com/onaio/reveal-frontend/pull/1502#issuecomment-781987400 what ended up getting built here?

**Comment by ciremusyoka** [comment]
> @ciremusyoka so is [#1502 (comment)](https://github.com/onaio/reveal-frontend/pull/1502#issuecomment-781987400) what ended up getting built here?

@rowo Yes
