### ISSUE TITLE
Plan assignment failing for MDA Point Plans 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1492]
Right now, the assignment feature is broken for MDA Point plans. This was working fine when tested about two or so weeks ago. I am not sure if it is relevant, but a new hierarchy for Eswatini was uploaded by Akros last week. 

Here is the workflow that was tested: 

1. Created a MDA Point plan and assigned it to Eswatini  (MDA-Point IS 2021-02-09) 
2. Activated the plan 
3. Went to the Assign page and selected the plan 
4. The assignment page loads, but you are only able to assign a user to Eswatini - you are not able to click through to lower levels of the hierarchy to assign a plan to any other geography. Also, as the page loads, you see an error that says: "Map failed to load: jurisdiction not found" 

Here is a video of that interaction: 
https://user-images.githubusercontent.com/12836913/107395143-67e8d580-6ab1-11eb-8091-3c041201db68.mov

**Comment by ciremusyoka** [comment]
@isabelcshaw Plans created from planning page should be assigning lower jurisdictions before activating them. The plan you mentioned above is only assigned top jurisdiction only i.e. Eswatini that is why you can't drill down the hierarchy.
