### ISSUE TITLE
Display plan form error of hidden fields

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1496]
In cases were there is an error on a hidden field the plan form submit button remains disabled without any warning.
User should be able to see the error blocking them from submitting a plan.

**Comment by madrinekariuki** [comment]
Tested this by:
-created a plan on review preview.
-note the plan name and search for it and click on it.
-right-clicked on inspect 
-on the network tab, select the auth bearer token,request and endpoint
 -go to postman,  use PUT and configure the endpoint 
-change the "taskGenerationStatus" on the request to unknown value and send the Json request.
-reload the endpoint copied from the network tab to confirm the "taskGenerationStatus" changed
-go to the web preview plan that you created and try to edit the plan e.g change status from "draft" to "in- progress"
-observe how an error pops up showing that theres and error that needs to be corrected.

![image](https://user-images.githubusercontent.com/84722169/127472598-bfefa1f6-527b-45d7-abc9-9c7c4f016ddd.png)
