### ISSUE TITLE
Make it possible to upload and download jurisdiction structure counts

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1498]
- [ ] Upload and download structure count jurisdiction metadata (`jurisdiction_metadata-structures`)

**Comment by Naima-Bashir** [comment]
is this a new feature  https://github.com/onaio/reveal-frontend/issues/1498 ? And what is the LoE so that I can communicate with the client. Their timeline was today  @ciremusyoka

**Comment by ciremusyoka** [comment]
@Naima-Bashir A day will be enough
