### ISSUE TITLE
Plan not appearing in Monitoring Web UI

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1505]
https://smartregister.atlassian.net/browse/RVL-1463

This is currently blocking the sharing of the Android APK with BVBD. If we can determine this is a web issue we can release the APK for testing with BVBD.

Server Thailand Preview
Problem Some plans are not appearing in the Web UI
Plan https://web.reveal-th-preview.smartregister.org/plans/update/f3a8b614-9b79-5269-a45a-8b724a1eaa6e
Plan name: แก้ไขแผนปฏิบัติงาน: A1 Thailand test site BVBD 3 2021-02-04Test

Monitoring tab link: https://web.reveal-th-preview.smartregister.org/focus-investigation/map/f3a8b614-9b79-5269-a45a-8b724a1eaa6e

Map/jurisdiction is not appearing.

**Comment by ciremusyoka** [comment]
There is no record of the plan(f3a8b614-9b79-5269-a45a-8b724a1eaa6e) in the [plan_jurisdiction](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/685be9470015f702d42d31f342e2e0800a836552/3-reveal/migrations/2-transaction_tables/deploy/plan_jurisdiction.psql#L9) table.

**Comment by ciremusyoka** [comment]
@Naima-Bashir this is resolve. Some problem with data syncing into the data warehouse.
Note: this is the correct Monitoring tab link https://web.reveal-th-preview.smartregister.org/focus-investigation/map/e59affdc-1e67-5481-8855-df42e77b98fc
