### ISSUE TITLE
In monitoring tab, case classification column is empty

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1506]
Server: Thai production

User: vbdu_12.4.2-1

Monitoring tab shows case classification column empty

![image](https://user-images.githubusercontent.com/61143692/108679156-2ae30100-74fd-11eb-9ebe-fc5c5ff63b56.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir this by itself is not enough information.  For all we know it could be the legitimate case that all those plans do not have a case classification.  We (you/the client) needs to point out at least one plan that has case classification information and for which the column is blank.

**Comment by ciremusyoka** [comment]
We have this column set to null on the front-end [here](https://github.com/onaio/reveal-frontend/blob/e824bc5876ae6031ed84ca8143e10ec5464684ef/src/helpers/utils.tsx#L294). Am not sure which field on the plan we should be displayed. [Here](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/05ac6be53b1125ce4bc9aede178ae28dfbc0f29c/3-reveal/migrations/2-transaction_tables/deploy/plans.psql#L8) are the available plan fields.
cc @moshthepitt @Naima-Bashir

**Comment by Naima-Bashir** [comment]
@ciremusyoka updates from CHAI

In the index case table, there’s the case classification field (already being used for the monitoring tab) that should be used. There are some instances where case classification field is blank (~12 out of 1,000).

Expected behaviour is where there is a case classification for that plan, show the case classification in the table. If the case classification field is blank then leave it blank in the table.
