### ISSUE TITLE
Enable form configuration for TH-Preview

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1507]
https://smartregister.atlassian.net/browse/RVL-339
Requirement

Enable form configurability for all Thailand Focus forms (in English and in Thai) in TH preview first
Once we’ve test form configuration in Preview we can enable form configurability for Thailand production
Dependency

Relevance files upload bug is fixed - https://github.com/OpenSRP/opensrp-server-web/issues/688

Also depends on this: 

https://github.com/OpenSRP/web/issues/379  

The updates so far are:
When a user creates a plan-changes the definition url for family registration task-saves and activates the plan- assigns his team-logs into android - registers a family- the changes he had made aren't shown.
From @githengi investigation it ​looks like the web Ui did not update the definition uri on the plan. The plan is still pointing to the default family_register.json 

![image](https://user-images.githubusercontent.com/61143692/108679608-d8561480-74fd-11eb-81bb-53e3ec05439f.png)

**Comment by Naima-Bashir** [comment]
a meeting with the team from both Reveal and Opensrp to discuss the way forward on resolving a bug that was caused by some implementation on the OpenSRP side

**Comment by Naima-Bashir** [comment]
Ask client if he published the draft.

**Comment by Naima-Bashir** [comment]
Updates on the JSON uri bug: 

looks like the web Ui did not update the definition uri on the plan. The plan is still pointing to the default family_register.json

**Comment by kelvin-muchiri** [comment]
It was agreed in order to resolve the bug, Reveal would cease to use its redux store and use the opensrp store. Since this is not the ideal solution, we'll research how to make changes on package `@opensrp/form-config` so that it does not require any other project that uses the package to use the opensrp store

**Comment by kelvin-muchiri** [comment]
@Naima-Bashir We encountered another bug on Friday, things did not go as smoothly as planned...We are still trying to find a solution for it with @p-netm

**Comment by kelvin-muchiri** [comment]
@Naima-Bashir The bug was fixed and I have a PR open for review

**Comment by kelvin-muchiri** [comment]
I will be handling the second part which  has to do with translations

**Comment by kelvin-muchiri** [comment]
@Naima-Bashir I have added the strings to be  translated on the doc 41-72

**Comment by samkanga** [comment]
@kelvin-muchiri please share the link with the strings to be translated on this ticket.

**Comment by kelvin-muchiri** [comment]
@samkanga @Naima-Bashir https://docs.google.com/spreadsheets/u/2/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit?folder=1MN5J-PK6KUOHC6gw3KKmf12vV-GQFPkr#gid=209283218

**Comment by kelvin-muchiri** [comment]
@Naima-Bashir Does the 400 error fix wait for the translations in order to be deployed?

**Comment by samkanga** [comment]
@kelvin-muchiri could you share the link of the issue on error 400?

Separately, the Thai team has asked us to add context to the terms shared for translations, similar to what had been done on the strings above the ones you posted. Please assist with that. Let me know once you are done.

**Comment by Naima-Bashir** [comment]
This has passed QA
