### ISSUE TITLE
Dashboards not populating on Zambia production for the VL and Macepa plans.

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1511]
JIRA:  https://smartregister.atlassian.net/browse/RVL-1460
Zambia production
Superset-user

Plans tested:
 login to web ui
go to monitor
MDA reporting
![image](https://user-images.githubusercontent.com/61143692/108823544-a1513300-75d1-11eb-92ba-0bc7b91155c5.png)

Then select the plan below
Gwembe Pilot - Dynamic-MDA 2020-09-18

login to web ui
go to monitor
select IRS reporting
VL Zambia 2020 IRS Plan
![image](https://user-images.githubusercontent.com/61143692/108823589-b0d07c00-75d1-11eb-89d3-7c6af95e1049.png)

login to web ui
go to monitor
select IRS reporting
MACEPA: Full Reveal 2020 IRS Plan
![image](https://user-images.githubusercontent.com/61143692/108823617-bb8b1100-75d1-11eb-8fdd-1cc5aac2f59c.png)

Current behavior:
Data not populating on dashboards

Expected behavior:
Data must populate on dashboards.

**Comment by ciremusyoka** [comment]
@Naima-Bashir The last 2 items looks resolved. Am not sure what the exact problem was but my guess is there were some syncing issues.

**Comment by ciremusyoka** [comment]
The first issue, Gwembe Pilot - Dynamic-MDA 2020-09-18 MDA plan (plan id `c6c4f7d2-9cc8-5b63-883f-ca1c436da0b8`), the jurisdictions assigned on the plan doesn't exist on OpenSrp server.

**Comment by moshthepitt** [comment]
@Naima-Bashir can we close this?
