### ISSUE TITLE
Provide a way to delete jurisdiction metadata

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1514]
We can upload jurisdiction metadata.  But what if I want to delete a metadata entry for a particular jurisdiction?  Currently the web app does not support this, which represents a problem as [seen here](https://github.com/onaio/canopy/issues/1841#issuecomment-785073718).

We need to make it possible to delete jurisdiction metadata for individual jurisdictions.

**Comment by ciremusyoka** [comment]
@Rkareko can we have a use case were to delete jurisdiction metadata entry we upload a CSV with the value of that jurisdiction as blank?
cc @samkanga

**Comment by Rkareko** [comment]
@ciremusyoka cc @samkanga  We can only add a new API endpoint for deleting the corresponding setting metadata record.

**Comment by moshthepitt** [comment]
@Rkareko what we are wondering is whether we can modify this existing CSV endpoint at all?  What happens right now for entries whose value is blank, and can we modify it for blank entries to mean "delete the settings for this key where identifier = whatever was uploaded"?

**Comment by Rkareko** [comment]
@moshthepitt @ciremusyoka after further consultation, yes we can support updating the current endpoint to delete entries whose value is blank

**Comment by moshthepitt** [comment]
Fantastic, thank you @Rkareko

**Comment by Rkareko** [comment]
@moshthepitt is this only limited to settings where the identifier is of type `jurisdiction_metadata-structures`

**Comment by moshthepitt** [comment]
@Rkareko it should also apply to the other jurisdiction metadata settings i.e. where the identifier starts with `jurisdiction_metadata`

**Comment by ciremusyoka** [comment]
Closed by https://github.com/OpenSRP/opensrp-server-web/issues/772

**Comment by moshthepitt** [comment]
@ciremusyoka @samkanga can we test this and write up a documentation that we share with the client/others on how to add and remove jurisdiction metadata?
