### ISSUE TITLE
Too many popups

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#152]
When you click on a structure, the number of popups that appear are more than expected.

![too many popups](https://user-images.githubusercontent.com/372073/60361099-03652980-99e6-11e9-8feb-0f300e2a487e.png)

**Comment by cKellyDesign** [comment]
@mberg are you able to find a structure with multiple tasks to confirm this is no longer an issue?

**Comment by cKellyDesign** [comment]
Confirmed this is still occurring in instances where FI task layers have multiple gisida layers.

<img width="905" alt="Screen Shot 2019-08-14 at 10 12 07 AM" src="https://user-images.githubusercontent.com/4141527/63041327-72a2ba00-be7c-11e9-9ef8-0db6fd9bef8f.png">

**Comment by cKellyDesign** [comment]
Unable to reproduce, closing.
