### ISSUE TITLE
last modified date is incorrect

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1523]
I created this plan here today(3rd March) 
https://web.reveal-th-preview.smartregister.org/plans/update/d53fc448-bae1-56f6-9df7-b923ac79145c
However on the manage plans page here https://web.reveal-th-preview.smartregister.org/plans/list,
 it shows that it was created on the 2020-01-27

![image](https://user-images.githubusercontent.com/61143692/109787098-ebb06080-7c1e-11eb-86b8-aeef70a447f0.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir I think that you are comparing a different plan.  Please confirm the id of the plan in the screenshot matches `d53fc448-bae1-56f6-9df7-b923ac79145c` exactly (This is from [https://web.reveal-th-preview.smartregister.org/plans/update/d53fc448-bae1-56f6-9df7-b923ac79145c](https://web.reveal-th-preview.smartregister.org/plans/update/d53fc448-bae1-56f6-9df7-b923ac79145c))

![Oo](https://user-images.githubusercontent.com/372073/109788367-4dbd9580-7c20-11eb-9507-e5f30c2942ff.png)

Please close this when you confirm the above.
