### ISSUE TITLE
Missing Translations on WebUI Mapview

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1524]
There are some missing translations on the WebUI Map View, for the historical index case issue. See the screenshot below:

![image](https://user-images.githubusercontent.com/5908630/110280361-bb384000-7feb-11eb-8219-6cf5715f2257.png)

**Comment by haseemVD** [comment]
@samkanga Added point 73 in [file](https://docs.google.com/spreadsheets/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit?folder=1MN5J-PK6KUOHC6gw3KKmf12vV-GQFPkr#gid=209283218), 
Need translation to close this issue.

**Comment by moshthepitt** [comment]
fixed by #1553

**Comment by Naima-Bashir** [comment]
Hi @ciremusyoka cc @samkanga 
i've tested this and it has passed QA. 
![image](https://user-images.githubusercontent.com/61143692/116988885-b20cdc00-acd9-11eb-8991-e4a768311228.png)

Quick question, the word RACD is still in english, should it be translated or?
