### ISSUE TITLE
End- Fund - Add Column for Uploading Unofficial Population Data 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1527]
The `Unofficial Population` Data is needed for the End Fund project dashboards. It should be added through the jurisdiction Metadata csv file upload. Please add functionality that will pick data from one of the column in the uploaded csv.

**Comment by ciremusyoka** [comment]
@lincmba can you please provide or point me to the jurisdiction metadata identifiers you added.
