### ISSUE TITLE
Error 500 When Trying to Create an MDA Plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1528]
**Steps to Reproduce:**
1. Go to the Mange plans page
2. Select the create plan option and complete the plan details
3. Hit the save plan button

**Results:**
1. he WebUI returns an error 500 when trying to POST to `https://reveal-ng.smartregister.org/opensrp/rest/plans`. Hence new plans cannot be created.

**Comment by moshthepitt** [comment]
@samkanga Nigeria plans were not initially supported, right?  So this is technically a piece of new work to start supporting Nigeria plans, right?

**Comment by moshthepitt** [comment]
Therefore, what we need to proceed:

- Sample plan JSON for Nigeria-type plans that includes all plan activities
- An understanding that this is a new feature request and therefore may take longer than a bugfix would have taken
