### ISSUE TITLE
Error 500 when trying to activate a draft plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1530]
**Steps to reproduce:**
1. Go to the Manage plan page
2. Select a draft plan for activation
3. Update the status report from draft to active
4. Attempt to save the plan.l

**Results:**
1. The plan is not saves but instead an error 500 is returned when trying to PUT `https://reveal-ng.smartregister.org/opensrp/rest/plans`

**Comment by moshthepitt** [comment]
@samkanga Nigeria plans were not initially supported, right? So this is technically a piece of new work to start supporting Nigeria plans, right?

**Comment by samkanga** [comment]
@moshthepitt confirming that we retested the 3 Nigeria issues with @ciremusyoka , that covered error 500 on saving a plan, activating a plan and team assignment and they are all now working OK. It is not clear what changed but the issue seemed to be an unsuccessful API call hence the error 500.

**Comment by samkanga** [comment]
Closing these tickets as they are now working.
