### ISSUE TITLE
Missing Plan on the Monitoring Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1531]
CHAI created a plan on the Thailand Preview instance. This is accessible on the link [here](https://web.reveal-th-preview.smartregister.org/plans/update/067808c6-f18f-57ad-9cb9-84e3972513aa). However the plan is not showing on the Monitoring page. This is an issue that has been frequent in the past months. Any assistance to sort this out and probably share insights into the cause will be appreciated.

**Comment by ciremusyoka** [comment]
This plan started showing after a while. My guess is there was some syncing issues.
