### ISSUE TITLE
One cannot be able to upload add_structure form (error 500)

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1532]
https://smartregister.atlassian.net/browse/RVL-1495
Login to stage
Click on manifest release and upload a new add structure form
Observe the error 500. {{"message":"The server encountered an error processing the request.","status":"500 INTERNAL_SERVER_ERROR","data":null,"success":false}}

Note: When one makes the form add_structure.json(1) the upload is successful.

**Comment by ciremusyoka** [comment]
The form config now works as expected. Open if this persists.
