### ISSUE TITLE
Unable to Save edits made on draft Case triggered Plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1533]
The plan on [this](https://web.reveal-th-preview.smartregister.org/plans/update/b4dcf39d-cfc4-43d9-9ae5-2386097140af) link is case triggered and viewable on the Thailand Preview WebUI manage plans page. It is presently in draft form which mean. However, despite making changes on the plan, the save button remains inactive and cannot be clicked. Please check what may be the issue is.

**Comment by moshthepitt** [comment]
Closing this via https://github.com/onaio/canopy/issues/1906
