### ISSUE TITLE
BCC Data not Showing on Thailand Production Monitor Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1534]
The plan `A1 เขาแก้ว (2207010601) 2021-02-25` ID: `7dbf2406-1191-5c5b-80d5-da2328fe3f33` has data submitted on the android device and marked as synced to the server. Checks on the OpenSRP server confirms that that data has synced. However, the plan does not show the BCC data on the WebUI under the Monitor page [here](https://mhealth.ddc.moph.go.th/focus-investigation/map/301d72b4-0946-50ea-8897-3cf4ff0acea6).

The same issue applied to the plan `A1 ผักกาด (2204100301) 2021-02-27` ID: `5ba50d6b-4687-5a5a-84a8-3cd846340eed` accessible [here](https://mhealth.ddc.moph.go.th/focus-investigation/map/1a9ccc6b-38e3-5b03-82ec-2172fc1e3ced).

**Comment by ciremusyoka** [comment]
@samkanga Plan `7dbf2406-1191-5c5b-80d5-da2328fe3f33` looks good to me. BCC data is displayed on the web as expected. please cross check.

For plan `5ba50d6b-4687-5a5a-84a8-3cd846340eed` BCC Data is missing on the `actions` table.

**Comment by ciremusyoka** [comment]
@samkanga after further investigation i found this:
1. For Plan `7dbf2406-1191-5c5b-80d5-da2328fe3f33` the `business_status` of the task (task id 9391e5dd-ee3f-4a94-9ba0-2102c7beddf2) on `tasks` table has not update to `Completed` it is still showing `Not Visited`.
2. For Plan `5ba50d6b-4687-5a5a-84a8-3cd846340eed` there is no record of BCC action on `actions` table. Fixing this will solve both the missing data and title on the dashboard.

**Comment by samkanga** [comment]
This issue has been transferred to the Canopy report [here](https://github.com/onaio/canopy/issues/1898).
