### ISSUE TITLE
Fetch structures from Superset

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#154]
After https://github.com/onaio/reveal-frontend/issues/153 and https://github.com/onaio/js-tools/issues/71 are implemented, we should be able to fetch structures for a particular jurisdiction directly from the structures slice in Superset instead of kind of getting structures through tasks.

- [x] Add structures reducer module
- [x] Get structures from the structures reducer module for use in the focus investigation map component

**Comment by moshthepitt** [comment]
We need to fetch structures from this slice: https://superset.reveal-stage.smartregister.org/superset/slice_json/468

We also need to ensure that every query to that slice is filtered to prevent getting tens of thousands of results

**Comment by moshthepitt** [comment]
Sample structure object from superset:

```
{
    "id": "163650",
    "jurisdiction_id": "3390",
    "geojson": "{"id": "163650", "type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[32.5395938, -14.1692235], [32.5396213, -14.169247], [32.5395837, -14.1692883], [32.5395563, -14.1692649], [32.5395938, -14.1692235]]]}, "properties": {"uid": "163650", "code": "163650", "name": "163650", "type": "163650", "status": "Active", "version": 0, "server_version": 1545225058891, "jurisdiction_id": "3390", "geographic_level": 4, "effective_end_date": null, "effective_start_date": null}}"
}
```

**Comment by cKellyDesign** [comment]
**Structure.geojson.properties**
```
{
    "uid": "163650", 
    "code": "163650", 
    "name": "163650", 
    "type": "163650", 
    "status": "Active", 
    "version": 0, 
    "server_version": 1545225058891, 
    "jurisdiction_id": "3390", 
    "geographic_level": 4, 
    "effective_end_date": null, 
    "effective_start_date": null
}
````

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/195
