### ISSUE TITLE
Issues on MDA Point Location Report

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1542]
Some issue son this page: https://web.reveal-stage.smartregister.org/intervention/mda-point/location-report/54fef4ed-a046-54e3-a104-047512133087/58287a8d-280f-413a-b120-919072bf3286

- The superset request sent is not filtered i.e. it should only be requesting relevant data
- For the link above, there appears to be data in Superset that is not shown on the page

**Comment by ciremusyoka** [comment]
@moshthepitt @samkanga This is the materialized view `mda_client_dispense_task_school_report_for_webui`  the data is comming from.  There are only three records for plan `54fef4ed-a046-54e3-a104-047512133087` available and none  with jurisdiction id  of `58287a8d-280f-413a-b120-919072bf3286`.

**Comment by ciremusyoka** [comment]
@moshthepitt working on adding filters on the superset request

**Comment by moshthepitt** [comment]
Closed by #1546
