### ISSUE TITLE
Confirm that MDA Point Plans task generation status is False on creation

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1543]
We need to confirm (and write tests) to ascertain and assure ourselves that all MDA Point plans are created with the task generation status set as "False" on Reveal Stage.

I think that this may be inconsistently creating plans with "True" and sometimes "False" as the value.  For example, this plan https://web.reveal-stage.smartregister.org/plans/update/4794bf7a-1d57-5b72-bddb-3979a2652fae had its value set as "True" incorrectly.

**Comment by ciremusyoka** [comment]
@moshthepitt have tested and confirmed that the the web submits a task generation status of `False` for MDA-Point plans. [Here](https://github.com/onaio/reveal-frontend/pull/1544) is also a test to assert so.
