### ISSUE TITLE
The MDA Lite Reporting page shows no data

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1554]
JIRA: https://smartregister.atlassian.net/browse/RVL-1560
Create a plan to test the dashboards eg:
The plan that was created: MDA-Lite QA Test 2021-04-16" planID:16472edb-96fb-54ae-8714-754cf1f6392e.
Submit some data to it by assigning a team and user and submitting data on android. 
Observe if the plan is showing on the MDA Lite Reporting page
It is not showing on the MDA lite reporting page. 
The other plans on that page show no data at all. See image below
![image](https://user-images.githubusercontent.com/61143692/115194294-f010da00-a0f5-11eb-8e4d-52a5cd5c6627.png)
![image](https://user-images.githubusercontent.com/61143692/115194313-f8691500-a0f5-11eb-972a-5b5d03d1259c.png)

**Comment by ciremusyoka** [comment]
Addressed by [this commit](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/102/commits/9e19a44e3efc8c3b84bb3fc89c7cdabc49501b6d)

**Comment by ciremusyoka** [comment]
@Naima-Bashir closing this since the data is now available
