### ISSUE TITLE
End Fund: Filter the countries to only Have Kenya on Monitoring Tab

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1557]
Presently selecting a plan under the monitoring tab returns all countries loaded on reveal-stage. We should filter this out so we only have Kenya listed. See the sample screenshot below accessible on the link [here](https://web.reveal-stage.smartregister.org/intervention/mda-lite/report/16472edb-96fb-54ae-8714-754cf1f6392e).

![image](https://user-images.githubusercontent.com/5908630/115517637-03f04380-a290-11eb-8d52-85f11017de63.png)

**Comment by samkanga** [comment]
This has been resolved and I go ahead and close the ticket.

**Comment by ciremusyoka** [comment]
fixed by [this commit](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/102/commits/501dd33d262327a7f46e20216a8b884e0b91ab96)
