### ISSUE TITLE
End Fund: Review the Percentage Calculation

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1558]
When a user drills down to the sub-county level, the percentage data on the `Treatment Coverage` and `Other Pop Coverage` appears off. There seems to be an issue with the formula used. See the sample screenshot below accessible on [this](https://web.reveal-stage.smartregister.org/intervention/mda-lite/ward/report/16472edb-96fb-54ae-8714-754cf1f6392e/17de7da3-217f-4e5d-b016-4be97dd49e77) link.

![image](https://user-images.githubusercontent.com/5908630/115517355-bb388a80-a28f-11eb-9800-c2d081b2dcf0.png)

**Comment by samkanga** [comment]
This has been resolved and I will go ahead and close the ticket.

**Comment by ciremusyoka** [comment]
Fixed by [this commit](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/102/commits/64fbd59b5dfbd6d53954f1fff441a91e945f5554)
