### ISSUE TITLE
Write a spec for more secure token store mechanism

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#156]
Following the discussion in https://github.com/onaio/reveal-frontend/issues/39, we now need to write a specification document that covers:

- The intermediary service that will handle oAuth2 access tokens aka "front end proxy" 
- The reveal backend, if any

**Comment by moshthepitt** [comment]
ORY Hydra looks really interesting: https://github.com/ory/hydra

Oathkeeper as well: https://github.com/ory/oathkeeper

**Comment by moshthepitt** [comment]
Setting up Express with Typescript: https://developer.okta.com/blog/2018/11/15/node-express-typescript

**Comment by moshthepitt** [comment]
Probably related in that we may use that structure: https://github.com/OpenSRP/opensrp-web/issues/7

**Comment by moshthepitt** [comment]
#### Steps to implement a minimal backend server to handle authentication/authorization

- Set up a tiny express.js backend server
- Switch to doing the OAuth 2 authentication/authorization on the server side using the [authorization code OAth2 flow](https://oauth.net/2/grant-types/authorization-code/)
- Store the OAth2 credentials on the server side
- Implement server side Redux store - https://redux.js.org/recipes/server-rendering
- Initialize the Redux store from the server side and set the initial state to contain the OAth2 credentials stored in the backend (if any)
- In theory it should now just work, and one should be logged in for however long the OAuth credentials stored in the backend are valid

**Comment by cKellyDesign** [comment]
@moshthepitt Looks solid!

**Comment by cKellyDesign** [comment]
> Switch to doing the OAuth 2 authentication/authorization on the server side using the authorization code OAth2 flow

@moshthepitt how are we doing AuthZ for non-OpenSRP resources? Webapp views? (Auth'ing more than OpenSRP resources may be outside the scope of this ticket)

**Comment by moshthepitt** [comment]
> how are we doing AuthZ for non-OpenSRP resources? Webapp views? (Auth'ing more than OpenSRP resources may be outside the scope of this ticket)

@cKellyDesign the plan is for nothing else to change for now: just how we get the OAuth credentials.  Everything else will come in a future PR.
