### ISSUE TITLE
End Fund - Overlapping Column Details in Dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1560]
The data on the first column at the ward level drill down dashboards, overlaps with the data on the second column. Below is a screenshot of the same which can be accessed on the link [here](https://web.reveal-stage.smartregister.org/intervention/mda-lite/cdd/report/16472edb-96fb-54ae-8714-754cf1f6392e/2ac37ac3-3d78-4642-9e8b-49058a8175d0).

![image](https://user-images.githubusercontent.com/5908630/115666916-d8cc2980-a34d-11eb-8352-8ab139ec3b60.png)

**Comment by Naima-Bashir** [comment]
https://web.reveal-stage.smartregister.org/intervention/mda-lite/cdd/report/d8b68ee9-d640-5ca8-bcce-5d859cd748e5/6cb96ec5-a89f-4eb6-bb5e-83692687095e
