### ISSUE TITLE
ENDFUND: The dashboard is not populating figures accurately at different levels

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1562]
For example. values for 1-4, and 5-14 is populating at ward level,
But the upper levels are not populating values. Similarly not populating on the cdd level
![image](https://user-images.githubusercontent.com/61143692/115832460-9b35d200-a41b-11eb-982c-0aab40e4300d.png)
![image](https://user-images.githubusercontent.com/61143692/115832480-9f61ef80-a41b-11eb-9c4b-7f4b467d54bb.png)
![image](https://user-images.githubusercontent.com/61143692/115832498-a2f57680-a41b-11eb-941f-e2a5c9261c64.png)
![image](https://user-images.githubusercontent.com/61143692/115832515-a688fd80-a41b-11eb-9a26-e553f6432359.png)

**Comment by ciremusyoka** [comment]
@Naima-Bashir please share a link

**Comment by ciremusyoka** [comment]
addressed by [this commit](https://github.com/opensrp/opensrp-reveal-datawarehouse/pull/102/commits/626a6477bdb2de333b61277d0cbf0d8414d0420c)

**Comment by samkanga** [comment]
@ciremusyoka I will close this ticket as it has since been resolved.
