### ISSUE TITLE
END FUND: Include  business status of the wards, on the map view and included on the legend

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1567]
On the End Fund Dashboards map view, we need to add a legend to the left and business case. Below is a sample screenshot on the placement of the legend and the business case presentation on map.

![image](https://user-images.githubusercontent.com/5908630/116339743-a6577c00-a7e6-11eb-9de6-3d4082efdd92.png)

1. At the top of the map is the Plan name and name of the lowest location.
2. On the map is the boundary of the wards within the sub-county. These boundaries should be colour coded with the following business statuses. 

- **Yellow** (NOT VISITED): When the area has been visited and no data has been submitted on the `CDD Supervisor Daily Summary Form` against the specific ward.

- **Orange** (IN PROGRESS): When the area has been visited, meaning data has been entered on the `CDD Supervisor Daily Summary Form` against the ward, but none of the forms completed has the the answer “**yes**” to the question “**Has this task been completed?**”.

- **Green** (COMPLETE): When the area has been visited, meaning meaning data has been entered on the `CDD Supervisor Daily Summary Form` against the ward, and any one of the forms completed has the answer “**yes**” to the question “**Has this task been completed?**” 

Below is a sample map showing the ward boundaries which are expected to pick the colour codings.
![image](https://user-images.githubusercontent.com/5908630/116430404-798b7f00-a84f-11eb-87d9-e5be03344d65.png)

3. On the Map to the left of the Map is the legend on the business statuses and some indicators of interest. The following are the indicators of interest at the sub-country level.

- **Indicator 1**: Treatment Coverage (Census) with a bar.  Below are the colours of the bar based on the coverage value:
`RED` when the coverage is < 65%
`Yellow` when the coverage is >65 & <80
`Green` when the coverage is >80
Below is a sample indicator with a bar.
![image](https://user-images.githubusercontent.com/5908630/116342221-eae51680-a7ea-11eb-8cd4-0a9b9c1e58e6.png)

- **Indicator 2**: Other Pop Coverage (Unofficial) with a bar. Below are the colours of the bar based on the coverage value:
`RED` when the coverage is < 65%
`Yellow` when the coverage is >65 & <80
`Green` when the coverage is >80

- **Indicator 3**: Total Treated - Give the value for the total treated.

- **Indicator 4**: Drugs Administered - Give a value for the count of the total drugs administered.

- **Indicator 5**: Drugs Damaged - Give a value for the count of the total drugs administered.

**Comment by haseemVD** [comment]
@samkanga @ciremusyoka 
Can you please confirm few things,
- denominator and numerator for `Other Pop Coverage (Unofficial)` and `Treatment Coverage (Census)` (Need to display these values below progress bar)
- Description for indicators.

**Comment by ciremusyoka** [comment]
> @samkanga @ciremusyoka
> Can you please confirm few things,
> 
> * denominator and numerator for `Other Pop Coverage (Unofficial)` and `Treatment Coverage (Census)` (Need to display these values below progress bar)

The numerator for both of the above is `Total Treated`

**Comment by samkanga** [comment]
@haseemVD 
`Other Pop Coverage (Unofficial)` = (Total Treated / Census Pop Target (Unofficial) ) * 100
`Treatment Coverage (Census)` = (Total Treated / Census Pop Target (Official) ) * 100

**Comment by ciremusyoka** [comment]
Closed by #1569
