### ISSUE TITLE
Enforce Automated Selection of Subvillage Classification When Creating Routine Plans does not work 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1574]
Go to thailand preview 
Create new plan https://web.reveal-th-preview.smartregister.org/plans/new 
Select the OA
Observe the Action plan name
Previously it used to automatically have a name 
Now until one clicks on it, nothing happens 
However, after one starts typing in, it automatically fills in the name 
Connected to https://github.com/onaio/reveal-frontend/issues/1482

![image](https://user-images.githubusercontent.com/61143692/117118440-6e79a700-ad99-11eb-8ab5-1f0212893305.png)

**Comment by ciremusyoka** [comment]
@samkanga @Naima-Bashir The name was auto populating on selecting the `Local Term`. Now that it is being updated automatically i think that is what is causing this issue.

**Comment by samkanga** [comment]
@ciremusyoka can we make it auto populate when the classification is selected?
