### ISSUE TITLE
Uploaded rosters not showing in the web UI 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1579]
CHAI is reporting that they are able to successfully upload csv files via the Clients page - they are getting a success message and the new children appear in the school download list at the bottom. Those csv files, however, are now missing from the CSV files list at the top. 

Steps: 
Go to Clients page 
Upload a csv file 
Get success message 
Scroll down through list of files uploaded 
csv file is not present 
Download csv of all of Eswatini and see the children created via the csv just uploaded

Note: it looks like the last listed csv file is from April 20th. Is it possible we've hit a UI max here? 

It is important to get this fixed quickly because it is also blocking CHAI confirm that the previous csv download issue (for Windows computers) was resolved.

**Comment by Naima-Bashir** [comment]
This is a valid bug, I have retested with @ciremusyoka  and trying to find out why it is not showing on web but showing on the full Eswatini list

**Comment by ciremusyoka** [comment]
@rkodev please confirm if we have limit to number of records returned by `opensrp/rest/upload/history` endpoint. On the web we are only getting 50 records.

**Comment by rkodev** [comment]
@ciremusyoka Yes the api has a default page size and offset that can be used for paging

**Comment by ciremusyoka** [comment]
@rkodev Noted.
Working on increasing the `batch_size`. 
cc @moshthepitt  @isabelcshaw  @samkanga
