### ISSUE TITLE
MDA Point task generation broken 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1580]
After a round of testing on Friday, CHAI is reporting that task generation is broken again. A new plan was created and new children were uploaded. The user was able to log into the app and see all of the new children, but no tasks were created for any children across both of the plan's two OAs.   

Plan: SB Testing Capsule 2 
OAs: Test Lomahasha OA, Our Lady of Sorrows

![image (6)](https://user-images.githubusercontent.com/12836913/117590150-df46f900-b0e2-11eb-9c8d-5d315456c88d.png)

Following up on this, I cannot find the plan CHAI shared in the reporting views either. I am not sure if there was an issue with plan creation, but Sameen was able to successfully log in and see the new children uploaded, so it doesn't seem likely. 

I spoke to @rkodev and he said that no Android said code changed in the last APK shared, so this is likely a nifi issue. Ronald, pls share any other thoughts I missed. 

As a reminder, our previous issues with task generation were: 
1. A backlog of tasks across Reveal stage 
2. We had to push a fix to modify a processor group so that it anticipates the correct task codes for NTD
3. MDA tasks generation was tagging the group_identifier attribute with the structure_identifier instead of the operational_area_identifier, which is preventing proper task generation for the children in question

@Naima-Bashir could you pls try to replicate this issue? It would be helpful to create a plan using the same OAs and one in a different location.

**Comment by Naima-Bashir** [comment]
Tested this on my android phone.The tasks aren't showing for the children. This is a recurring bug cc @rkodev

**Comment by gstuder-ona** [comment]
@isabelcshaw I've created a test MDA Point plan and see tasks being generated - in 15 mins or so when the old tasks have finished generating I think we'll be back online for testing.

Also, as watching the NiFi flows for errors and reconfiguration is currently manual, we need to schedule periodic maintenance check-ins.  It's apparently very unrealistic to expect that nothing will happen on our shared NiFi instance to interrupt these flows and it's much easier to fix things if we catch them within 24hrs, say.

**Comment by ciremusyoka** [comment]
Resolved through clean up of old tasks from the database.
