### ISSUE TITLE
Edit certain fields in draft makes page unresponsive- Thai Preview

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1587]
@Eric Musyoka cc @Kang'a so quick feedback:
TEST: Ability to add/remove activities in C.T.P:
This functionality works where one can add /remove the activities.
However, I noticed that if I wanted to remove all activities and and add just one, the page shows Added these activities(shows all). If I click on one of the activities I want to add and click the X button, the page hangs. See image below. https://web.reveal-th-preview.smartregister.org/plans/update/40223877-5fc9-4978-a782-32c6cf72fefe
Trying to test if this is happening due to the google translate extension
I checked to see if it was the translate, it is not. The page is unresponsive unless I select all activities.
https://github.com/onaio/reveal-frontend/issues/1378
![image](https://user-images.githubusercontent.com/61143692/117984316-680ea080-b340-11eb-8e4a-d1188c88f87f.png)

**Comment by ciremusyoka** [comment]
@Naima-Bashir The cancel button is working as expected on my end please retest this.

**Comment by samkanga** [comment]
@ciremusyoka I was able to edit the activities but the update button got disabled and I couldn't update the new activities selected.

**Comment by ciremusyoka** [comment]
Reopening this issues to remove the extra cancel unresponsive button pointed out [here](https://github.com/onaio/reveal-frontend/pull/1596#issuecomment-848881314).
