### ISSUE TITLE
After creating a plan in draft mode, the manage actions page is throwing a 401 error- Thai Preview

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1589]
Login to Thai Preview using superset-user
Create a plan in draft mode(I removed some activities here)
Click save- it should lead you back to the lists page. 
Usually at this point, it shows the plans assigned to that user. 
One can be able to remove the filter by user. 
However, this error pops up when one tries to do that: 
"Sorry, something went wrong when we tried to fetch users."

![image](https://user-images.githubusercontent.com/61143692/117985781-ab1d4380-b341-11eb-8851-272f1e52017c.png)

**Comment by ciremusyoka** [comment]
@Naima-Bashir please ensure you are logged in.

**Comment by Naima-Bashir** [comment]
@madrinekariuki please retest this and close it if it has bene fixed 
THAI preview

**Comment by ciremusyoka** [comment]
@Naima-Bashir @madrinekariuki This is working correctly. Closing this issue.
