### ISSUE TITLE
Remove the legend from the adverse reaction columns 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1591]
The adverse reaction columns in the MDA Point reporting views should not have the legend applied to them. There are no targets set for these indicators because these are ad hoc events. Ideally no child has an adverse reaction, so showing 100% as a positive thing is incorrect. 

Desired outcome: these % fields should always be grey like the other counts.  

See screenshot of the ADR indicators here: 
![image (8)](https://user-images.githubusercontent.com/12836913/118199176-547a3d00-b407-11eb-8ca2-c51b37cc13b5.png)

**Comment by samkanga** [comment]
@haseemVD are you able to help with this ticket with Eric being out?
