### ISSUE TITLE
MDA Point Reporting: Tasks recorded as refused show up as SAC pregnant #70

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1597]
In drilldown child view (any child that has refused medicine // pregnant/sick/contraindicated) is appearing as if medicine was taken.

Bug: Child that has refused medicine is noted as MMA drug administered - yes, refused medicine - yes, pregnant/sick/contraindicated - yes
Expected behaviour:
EO1: If child has refused medicine - MMA drug administered - no, refused medicine - yes, pregnant/sick/contraindicated - no
EO2: If child is pregnant/sick/contraindicated - MMA drug administered - no, refused medicine - no, pregnant/sick/contraindicated - yes

**Comment by baokiddy** [comment]
@ciremusyoka Please find a csv of the data within the report table. This is a section of the table
[mda_client_dispense_task_report_for_webui_202105251127.xlsx](https://github.com/onaio/reveal-frontend/files/6537720/mda_client_dispense_task_report_for_webui_202105251127.xlsx)

**Comment by baokiddy** [comment]
@ciremusyoka To give a better description of what is happening within the DB versus the web UI

https://web.reveal-stage.smartregister.org/intervention/mda-point/child-report/eb601285-d5c2-55c3-bcd5-c29ae71a6236/99642369-fec4-4cb2-99c6-c901228b3adf
[mda_client_dispense_task_report_for_webui_202105251133.xlsx](https://github.com/onaio/reveal-frontend/files/6537776/mda_client_dispense_task_report_for_webui_202105251133.xlsx)

**Comment by ciremusyoka** [comment]
@baokiddy was this column `mmanodrugadminreason`  supposed to have values of `1` (ones) and `0` (zeros)?
If not please clarify the values we should expect.

**Comment by baokiddy** [comment]
@ciremusyoka the only column with `1`s and `0`s is `mmadrugadmin`. `mmanodrugadminreason` has `refused`, `pregnant`, `sick`, or `contraindicated`. I can confirm that this is also what I am seeing in the reporting view

**Comment by ciremusyoka** [comment]
Is this the expected behaviour
1. when `mmanodrugadminreason` value is `refused`
-  Show `Yes` on `SACs Refused` column.
- Show `No` on `SACs Sick/Pregnant/Contraindicated` column
2. when `mmanodrugadminreason` value is `pregnant`, `sick`, or `contraindicated`
-  Show `No` on `SACs Refused` column.
- Show `Yes` on `SACs Sick/Pregnant/Contraindicated` column
3. when `mmanodrugadminreason` value is `Null`
- Show `blank` on  both `SACs Refused` and  `SACs Sick/Pregnant/Contraindicated` columns

cc @baokiddy @samkanga

**Comment by Naima-Bashir** [comment]
: cc @ciremusyoka @samkanga @Rkareko @baokiddy 
The cause of the issue is: When we extract the data, this happens when there is a combination of all three: for example when there is a NO (drug administered), YES (SAC refused) and a NO(Sick/Pregnant/)   
Basically if the drug wasn't administered because the person refused(not because they were pregnant or anything)- this bug occurs

**Comment by Naima-Bashir** [comment]
Tested this for this child:
AGE 18 
I recorded refused on android. 
It is not shown on web 
![image](https://user-images.githubusercontent.com/61143692/119847636-d1330e00-bf13-11eb-814f-78deda0afb07.png)
![image](https://user-images.githubusercontent.com/61143692/119847667-d728ef00-bf13-11eb-81df-3b84ad5895f2.png)
THIS HAS FAILED QA

**Comment by Naima-Bashir** [comment]
After a second test, the sync happened and it has passed QA
![image](https://user-images.githubusercontent.com/61143692/119848409-777f1380-bf14-11eb-8d7c-ebc82fe762eb.png)
https://web.reveal-stage.smartregister.org/intervention/mda-point/child-report/4f30994f-6c02-50cd-96bc-b3fcdd966cab/f0de23e0-1e42-49e1-a60f-58d92040cccc
