### ISSUE TITLE
Implement Focus Investigation CRUD

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#16]
Make it possible to:

- Create Focus Investigations
- Edit Focus Investigations
- View Focus Investigations
- Delete Focus Investigations

**Comment by moshthepitt** [comment]
When creating plan goals/targets, the goal comparator should be limited to "=", ">=" or ">"

**Comment by moshthepitt** [comment]
Related: #199

**Comment by cKellyDesign** [comment]
@moshthepitt will #199 close this issue?

**Comment by moshthepitt** [comment]
@cKellyDesign #297 will close this

**Comment by cKellyDesign** [comment]
Closed by #346
