### ISSUE TITLE
The SACs Sick/Pregnant/Contraindicated Column Title At Country level Appears Wrapped

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1600]
The column title `SACs Sick/Pregnant/Contraindicated` at the Eswatini country level appears wrapped. Could we make this fit into the column so that its possible to read it all? See sample screenshot below.
![image](https://user-images.githubusercontent.com/5908630/119526420-0c083b00-bd88-11eb-898f-4d91d5bd93a9.png)

**Comment by Naima-Bashir** [comment]
this has passed QA
![image](https://user-images.githubusercontent.com/61143692/119690303-39b9b680-be52-11eb-8ad4-958dfa89ce26.png)
