### ISSUE TITLE
Plan Names Reported to be Changing in Thailand Replica3

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1605]
**Describe the bug or issue**
CHAI have reported a case where plans names in replica3 changed when they got updated from draft to another status e.g. complete or retired. This mostly affects plans from 2019 to 2020. However, there are some plans also affected from 2021. An example on the changed names is on the screenshot below on the plan highlighted in red and green. The correct name for the highlighted plans should be `A1-ห้วยเกษม (7603020201)-สุพรรณ_สุกหอม-2021-05-11-Site`.

The ID for the complete plan is: `0fde2fb5-fbef-4786-ab28-eb9fb29bc9f0` , for the retired plan is: `788717f3-e530-440e-9f4c-ac76995c29f8`. A sample draft plan whose name value is correct is: `6ceb7df1-8b70-4fb5-be0d-b0b78e765d1a`.

It would be good to investigate this and identify if we can get to understand what is causing this.

![image](https://user-images.githubusercontent.com/5908630/119844475-202b7400-bf11-11eb-8e99-4d02b09104b4.png)

**Expected behavior**
The plan names should remain unchanged.

**Additional context**

**Comment by ciremusyoka** [comment]
@samkanga this plans have the expected names on the web.

**Comment by ciremusyoka** [comment]
@samkanga both monitor and reporting pages have the right plan names.
plan id: `0fde2fb5-fbef-4786-ab28-eb9fb29bc9f0`

**Reporting page**
![Screenshot from 2021-05-31 12-52-59](https://user-images.githubusercontent.com/26719807/120175822-44d46400-c20f-11eb-9e39-398eff26ab6f.png)

**Monitor Page**
![Screenshot from 2021-05-31 12-52-45](https://user-images.githubusercontent.com/26719807/120175898-587fca80-c20f-11eb-9263-34b21db90c0c.png)

**Comment by ciremusyoka** [comment]
@samkanga yes the name is being overridden on plan status change.

**Comment by Naima-Bashir** [comment]
@ciremusyoka kindly take a look 
For old plans, it is still there.

**Comment by ciremusyoka** [comment]
@Naima-Bashir we had a bug on the web that was changing the plans when other fields were edited.  That is the bug that was fixed so the old plans will remain as they were.
To change names of the old plans that has to be done from OpenSrp side.
cc @Rkareko
