### ISSUE TITLE
Thailand Production WebUI Monitoring Page not listing any Plans

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1606]
The Thailand Production WebUI monitoring page is not listing any of the RACD or the routine plans. The expectation is that these should be listed when the filter box is cleared. See sample screenshot below.
![image](https://user-images.githubusercontent.com/5908630/120161798-6548f200-c200-11eb-980b-4a0d27a1bb7c.png)

**Comment by moshthepitt** [comment]
This was closed by bringing Superset back up
