### ISSUE TITLE
NTD: The Total SACs Registered count includes adults in the dashboard (22 instead of 19) #76

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1609]
Describe the bug or issue
The total SAC Registered= Total number of school-aged children registered(according to the data dictionary)

To Reproduce

On android the The total SAC Registered= Total number of school-aged children registered(according to the data dictionary)
This is the expected behavior
For example if you log onto eswatinitest2 on android the The total SAC Registered=19
On the web, it shows 22
![image](https://user-images.githubusercontent.com/61143692/120464641-d249bc80-c3a5-11eb-8229-3e642e61b0b7.png)
https://web.reveal-stage.smartregister.org/intervention/mda-point/report/81e2d31b-417a-532b-a6a2-9f252c012fb0

**Comment by ciremusyoka** [comment]
The row for adults was removed
