### ISSUE TITLE
NTD: The children shown on the web dashboard are duplicated 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1621]
Log onto the web and select one plan eg: https://web.reveal-stage.smartregister.org/intervention/mda-point/child-report/51489b0c-1b40-5a23-b947-b6be8ce965f9/f0de23e0-1e42-49e1-a60f-58d92040bbbb 
Notice how all the children are duplicates. EG look at how 

![image](https://user-images.githubusercontent.com/61143692/122566569-5a8bbb00-d050-11eb-8e07-62af85cc8410.png)
![image](https://user-images.githubusercontent.com/61143692/122566652-755e2f80-d050-11eb-9b4c-dac70c8fdceb.png)

**Comment by ciremusyoka** [comment]
@Naima-Bashir on the web we are displaying the data we are getting. This seems to be an issue with the views not the web.

**Comment by baokiddy** [comment]
@Rkareko @LZRS Just checked this specific plan and found that there are different `school_location_id`s which result in the multiple age records. Considering the school location, we now have an issue since it looks like there are many schools within this jurisdiction. What is the best way to resolve this? I'm unsure as this is the data connected to the children. I've included the exact data below:

```plan_id = '51489b0c-1b40-5a23-b947-b6be8ce965f9', jurisdiction_id = 'f0de23e0-1e42-49e1-a60f-58d92040bbbb'```
[Uploading mda_client_dispense_task_school_report_for_webui_202106221308.xlsx…]()

cc @ciremusyoka @Naima-Bashir

**Comment by madrinekariuki** [comment]
issue Still persistent. 
![image](https://user-images.githubusercontent.com/84722169/123438613-8cb19580-d5d9-11eb-9766-dcf02dc081c8.png)
![image](https://user-images.githubusercontent.com/84722169/123438683-a4891980-d5d9-11eb-951a-ab80064019c4.png)

**Comment by Rkareko** [comment]
> @Rkareko @LZRS Just checked this specific plan and found that there are different `school_location_id`s which result in the multiple age records. Considering the school location, we now have an issue since it looks like there are many schools within this jurisdiction. What is the best way to resolve this? I'm unsure as this is the data connected to the children. I've included the exact data below:
> 
> `plan_id = '51489b0c-1b40-5a23-b947-b6be8ce965f9', jurisdiction_id = 'f0de23e0-1e42-49e1-a60f-58d92040bbbb'`
> Uploading mda_client_dispense_task_school_report_for_webui_202106221308.xlsx…
> 
> cc @ciremusyoka @Naima-Bashir

@baokiddy cc @samkanga @ciremusyoka @Naima-Bashir @madrinekariuki  the juridiction with id `f0de23e0-1e42-49e1-a60f-58d92040bbbb` has only one school under it as seen below

```
select * from core.structure_metadata where parent_id = 'f0de23e0-1e42-49e1-a60f-58d92040bbbb';

 id | structure_id |              geojson_id              |   type    |              parent_id               | uuid | status | server_version |              name              |      date_created       |       date_edited       
----+--------------+--------------------------------------+-----------+--------------------------------------+------+--------+----------------+--------------------------------+-------------------------+-------------------------
 17 |           17 | f0de23e0-1e42-49e1-a60f-58d92040aaaa | MDA Point | f0de23e0-1e42-49e1-a60f-58d92040bbbb |      | ACTIVE |  1599045643874 | Lomahasha - Emafusini Nazarene | 2020-10-08 15:38:59.072 | 2021-04-20 09:18:56.224

```

This can also be verified from the API using this call 
`https://reveal-stage.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=false&return_geometry=true&properties_filter=parent_id:f0de23e0-1e42-49e1-a60f-58d92040bbbb`
