### ISSUE TITLE
NTD: The Dashboard data is empty eg SAC refused and such

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1622]
Log on to stage 
https://web.reveal-stage.smartregister.org/intervention/mda-point/child-report/51489b0c-1b40-5a23-b947-b6be8ce965f9/f0de23e0-1e42-49e1-a60f-58d92040bbbb

Observe how the dashboard does not have any data of children who were administered the dose, refused etc
![image](https://user-images.githubusercontent.com/61143692/122567000-db4ab700-d050-11eb-8cca-29d06f18882b.png)

**Comment by ciremusyoka** [comment]
This the data we are getting from that the slice
[link](https://superset.reveal-stage.smartregister.org/superset/slice_json/576?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22f0de23e0-1e42-49e1-a60f-58d92040bbbb%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22},{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%2251489b0c-1b40-5a23-b947-b6be8ce965f9%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000}) to the data.
