### ISSUE TITLE
NTD: "Filter for upload date is not working in the client CSV table.

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1626]
"Filter for upload date is not working in the client CSV table.
1. Upload a new CSV
2. Filter upload date by descending order - the CSV uploaded is not the top result - it appears mid-way through the table."

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/123048720-620fe300-d407-11eb-8400-f638b9b28749.png)
Observe how June is in the middle of March dates even after the filter is applied

**Comment by ciremusyoka** [comment]
@Naima-Bashir should we have this ordered by date  from recent by default?

**Comment by madrinekariuki** [comment]
@ciremusyoka This is now okay i note that the dates are filtering from recent by default.

![image](https://user-images.githubusercontent.com/84722169/123436133-009e6e80-d5d7-11eb-81a1-90c441e36d66.png)
