### ISSUE TITLE
 Sync data completed, but no data show on the report page web UI

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1629]
(1): sync data completed, but no data show on the report page web UI (but has data on the metabase)
plan name: A2 คลองไทร (8504051001) 2021-06-04
plan id: 60791504-3106-580a-9744-ee21221a0c2f
username: vbdu_11.5.3-2
In Ranong Pprovince
(2) Index Case not found on Web UI: 2 index cases were created yesterday (id 2468 and 2469), but can not find their plan on the web UI

**Comment by ciremusyoka** [comment]
Jurisdiction id:  ccfb736e-d090-44ff-ae67-e65933481086

On the web we getting Index cases from `actions` and `tasks` table. Currently we have no any `Case Confirmation` task or action  with that plan_id.
cc @Naima-Bashir @moshthepitt

**Comment by ciremusyoka** [comment]
Running
```SQL
select
    events.id as event_id,
    events.details->>'id' as case_id,
    raw_plans.id as plan_id,
    raw_plans.full_json->>'status' as status
from events
left join raw_plans
    ON raw_plans.full_json->'useContext'->4->>'valueCodableConcept' = events.id
where event_type ='Case_Details' AND details->>'id' IN 
(
    '2468',
    '2469'
)
order by case_id asc;
```

gives
               event_id               | case_id |               plan_id                | status  
--------------------------------------|---------|--------------------------------------|---------
 e23830b2-7932-4e7e-8eb9-3c3fc75982e7 | 2468    |                                      | 
 efb378c5-d844-4058-aeb4-caec963f9429 | 2469    | 3efd4ab6-0a84-4a56-be0d-0cee1db84d4a | retired

**Comment by ciremusyoka** [comment]
> (1): sync data completed, but no data show on the report page web UI (but has data on the metabase)
> plan name: A2 คลองไทร (8504051001) 2021-06-04
> plan id: 60791504-3106-580a-9744-ee21221a0c2f
> username: vbdu_11.5.3-2
> In Ranong Pprovince

@Naima-Bashir @samkanga please provide additional details on what data is missing for this plan.

**Comment by ciremusyoka** [comment]
Closing this in favour of  https://github.com/onaio/canopy/issues/2210 and https://github.com/onaio/reveal-frontend/issues/1624
