### ISSUE TITLE
MMA coverage and MMA Coverage % Not showing for MDA Operational Area Level dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1630]
The MMA coverage and MMA coverage % on the MDA Point Dashboards, we have figures showing at the higher levels but not at the operational area level.  Have a look and see what is missing. [Here](https://web.reveal-stage.smartregister.org/intervention/mda-point/report/20762fee-0238-5481-8e8a-097d28448006) is a sample plan that you can use to check this out.

Below are screenshots from the higher levels of the plan dashboards and at the Operational Area Level.
![image](https://user-images.githubusercontent.com/5908630/124224324-18fa1600-db0e-11eb-9eae-5e5e128c998b.png)
![image](https://user-images.githubusercontent.com/5908630/124224332-1d263380-db0e-11eb-9571-3c2b12a40313.png)

**Comment by ciremusyoka** [comment]
@samkanga The [data](https://superset.reveal-stage.smartregister.org/superset/slice_json/576?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%220315d73f-9825-4b38-b559-25814ff16644%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22},{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%2220762fee-0238-5481-8e8a-097d28448006%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:15000}) were getting from the view `mda_client_dispense_task_school_report_for_webui` slice `576` for the lower level MMA coverage %  is 0.
cc @baokiddy

**Comment by ciremusyoka** [comment]
There is a bug on the one of the fields [mmaDrugAdmin](https://github.com/onaio/data-solutions/blob/cc2646dccca8a8a36df920821a9c051634bd03c3/reveal/reveal-esw/deploy/filter_pzqcount_and_client_join_update.sql#L127) that we are calculating MMA coverage % from. The field expects a value of `Yes` or `No` but it gets `1` or `0`.

This gives 0
``SQL
SELECT count(*) FROM mda_client_dispense_task_report WHERE mmaDrugAdmin = 'Yes';
``
|count|
|-------|
 |    0|

cc @moshthepitt

**Comment by moshthepitt** [comment]
@ciremusyoka could you point to the code where this is used/happens?

**Comment by ciremusyoka** [comment]
> @ciremusyoka could you point to the code where this is used/happens?

@moshthepitt [here](https://github.com/onaio/data-solutions/blob/b57d3102e2f0a3bf4789e1d26b86d443b09c5957/reveal/reveal-esw/deploy/filter_pzqcount_and_client_join_update.sql#L126-L129) are the lines where this is happening.

**Comment by ciremusyoka** [comment]
Closed by https://github.com/onaio/canopy/issues/2227
