### ISSUE TITLE
Update the BCC action in the plan template

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1635]
The BCC tasks are not being generated on the android client for routine plans on Thiland Preview. This has been found to be an issue with the BCC action on the plan template.

Related to https://github.com/opensrp/opensrp-client-reveal/issues/1487

Update the condition for the BCC action to the following

```
      "condition": [
        {
          "kind": "applicability",
          "expression": {
            "description": "Jurisdiction type location",
            "expression": "Location.physicalType.coding.exists(code='jdn')"
          }
        }
      ]
```

The specific change is from `"expression": "Location.physicalType.text = 'jdn'"` to `"expression": "Location.physicalType.coding.exists(code='jdn')"`

**Comment by madrinekariuki** [comment]
this has been tested on
v5.3.26-RC2
user test77
created a new plan and sync it.
the BCC task was showing.
see below details.
for web 
![image](https://user-images.githubusercontent.com/84722169/127518401-96293afd-5632-4b28-935d-57fcb5dd0fdb.png)

for android

![image](https://user-images.githubusercontent.com/84722169/127518480-5f56280d-7eca-4571-8737-31e68c0d7ec8.png)
