### ISSUE TITLE
Blood Screening Events on Thailand Production WebUI Showing Less Count

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1637]
The blood screening events count for the plan named `A2 ห้วยแก้ว (3409070801) 2021-07-13 scd` with ID `ff5a43e5-f910-56d0-9cc5-977aea9cd44a` shows on the WebUI with a count of 49 events (See screenshot below).
![image](https://user-images.githubusercontent.com/5908630/127110619-3732576d-b96b-4f93-b365-4b2b77f34ec7.png)

However, a check on the data coming from the OpenSRP server shows the a total number of events to be 54 events of which 4 events are said to be duplicated. We need to determine how the filter for the events on the WebUI is implemented to determine if there is an issue with the count of 49 as opposed to 50.

cc: @Rkareko

**Comment by Rkareko** [comment]
@ciremusyoka @samkanga Here are my findings on the opensrp db for the plan with id `ff5a43e5-f910-56d0-9cc5-977aea9cd44a` and jurisdiction with id `5570f8e7-e442-4334-8d27-8cdef071415c`

1. There are 50 blood screening tasks 
 ```
select count(*) from core.task_metadata tm
opensrp-> inner join core.task t on t.id = tm.task_id
opensrp-> where tm.plan_identifier = 'ff5a43e5-f910-56d0-9cc5-977aea9cd44a' and tm.group_identifier = '5570f8e7-e442-4334-8d27-8cdef071415c' and tm.code = 'Blood Screening'  and t.json->>'status' = 'Completed' ;
 count 
-------
    50
```
2. There are 54 blood screening events
```
select count(*) from  core.event_metadata where plan_identifier = 'ff5a43e5-f910-56d0-9cc5-977aea9cd44a' and location_id = '5570f8e7-e442-4334-8d27-8cdef071415c' and event_type = 'blood_screening' and date_deleted is null;
 count 
```
3. From the event count in step # 2 there are 50 events with distinct task identifiers. This can be explained by the factor that edits to blood screening info results in generation of new events
```
 select count(distinct e.json->'details'->>'taskIdentifier' ) from  core.event_metadata em
 inner join core.event e on e.id = em.event_id
 where plan_identifier = 'ff5a43e5-f910-56d0-9cc5-977aea9cd44a' and location_id = '5570f8e7-e442-4334-8d27-8cdef071415c' and event_type = 'blood_screening';
50
```

**Comment by ciremusyoka** [comment]
@Rkareko @samkanga 
On the raw_task table there are 50 tasks with status completed but on tasks table there are 49 (the ones showing on the web).
This `dd1f8a15-9887-4779-b54c-4d40cba9eb88` has a ready status on the tasks table and completed status on the raw_tasks table.
Because it has a ready status that is why it is not appearing on the web.

**Comment by Rkareko** [comment]
> @Rkareko @samkanga
> On the raw_task table there are 50 tasks with status completed but on tasks table there are 49 (the ones showing on the web).
> This `dd1f8a15-9887-4779-b54c-4d40cba9eb88` has a ready status on the tasks table and completed status on the raw_tasks table.
> Because it has a ready status that is why it is not appearing on the web.
> 
> cc @moshthepitt

@moshthepitt could you have a look into this

**Comment by samkanga** [comment]
The missing record is now showing on the dashboard. See screenshot below.

**Comment by moshthepitt** [comment]
Was reported as closed here https://onaio.slack.com/archives/C01RH31DLTY/p1627888465005600?thread_ts=1627369748.005700&cid=C01RH31DLTY
