### ISSUE TITLE
Changes to active investigation page

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#164]
<img width="1193" alt="Screen Shot 2019-07-05 at 9 47 12 AM" src="https://user-images.githubusercontent.com/42673455/60726937-bc59c580-9f0a-11e9-9596-2f1f530e1284.png">

- [x] Please fix table so province, district etc  is only showed once.  Right now it's replicated.

- [x] Please add a column for focus investigation.  This should have the FI name and the link to the map page.  Please remove map link from the focus area section.

**Comment by cKellyDesign** [comment]
@mberg @rowo How should we define the Focus Investigation name? Should it be a combination of the FA and a date?

**Comment by moshthepitt** [comment]
@cKellyDesign there is a plan_title field on the Plan object.

**Comment by moshthepitt** [comment]
We agreed that we do not need to do anything regarding `Please fix table so province, district etc  is only showed once.  Right now it's replicated.` as it is a data issue

**Comment by moshthepitt** [comment]
Closed by #167
