### ISSUE TITLE
Add parameter to indicate whether team assignments should be revoked when a plan is marked as complete or retired

### ISSUE THREAD

**Issue by Rkareko** [onaio/reveal-frontend#1645]
Related to https://github.com/opensrp/opensrp-server-web/issues/905

Functionlaity was added on the opensrp server that revokes team assignments when a plan status is update to either complete or retired.

The thailand implementations requires that team assignments have the ability to persist even after a plan is marked as complete or retired. To make this configurable we have added a parameter on the PUT endpoint for updating plans.

we need the web to be updated to send a parameter `revoke_assignments` with a value of false when making requests to the update plans API for Thailand implementation.

**Comment by madrinekariuki** [comment]
This parameter was added find below screenshot.
check on the network tab on the revoke assignment = false

![image](https://user-images.githubusercontent.com/84722169/129322900-c99c32ae-97c9-497a-ae8f-4795c59ef35c.png)
