### ISSUE TITLE
Plans not syncing/Updating on Thai preview

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1647]
Thai preview is not updating plans

steps
logged to Thai webUI Preview
went to create a new plan.
created a new plan.
Changed the plan to "in progress" and moved the expiration date abit far
saved the plan
moved to the "manage plans" tab
searched for that plan
the plan is missing.

on looking at the last updated plan noticed it was july 6th. See [here](https://user-images.githubusercontent.com/84722169/128312810-58a8410f-911c-4c51-bd75-403be2e71258.png)

jira ticket [here](https://smartregister.atlassian.net/browse/RVL-1771).

**Comment by ciremusyoka** [comment]
The server version (1600354181932) of the plan is lower than the latest server version (1607066366089) of the plans raw table and that is why it is being missed while syncing data.

To get latest server versions of the raw plans 
```SQL
SELECT server_version FROM raw_plans ORDER BY server_version DESC LIMIT 1;
```

**Comment by ciremusyoka** [comment]
Solved this by manually updating the server version from which nifi should sync data from.
Procedure:
1. Update `Hit OpenSRP Endpoint`  processor `Remote URL` property state from  `NiFi Flow »  Reveal 3 (Thailand) » Ingestion from OpenSRP (reveal1) » Plans » Get data from openSRP` to a server version just before the missing plan server servsion. This will pull data from OpenSrp to raw table.
2. Stop `QueryDatabaseTable` processor from `NiFi Flow »  Reveal 3 (Thailand) » Process & store data (reveal1) » Pull from raw table`. Clear state and start the processor. Pulls data from raw tables to ware house table.

**Comment by ciremusyoka** [comment]
@Rkareko cc @samkanga i Created a new [plan](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/b541b3d5-9f67-5d08-8670-a00dc1ebd5ac) and the server version is still less than the highest on raw tables.
This is the [plan](https://reveal-th-preview.smartregister.org/opensrp/rest/plans/fbb87a59-d405-431a-8c2b-502f90f8ec3f) with the highest server version.

**Comment by ciremusyoka** [comment]
@madrinekariuki The plans are now syncing into the data warehouse after @LZRS fixed the server versions issue.
Testes with this [plan](https://web.reveal-th-preview.smartregister.org/plans/update/b5962889-f481-58a6-b19c-d1adb08aedc8).

**Comment by madrinekariuki** [comment]
@ciremusyoka 
On retesting I note that from the Activities for investigating patients and sources of infection page plans have not yet updated we still have the last plan for 2021-07-06.
you are only able to search for a plan from the Manage action page
I have used [this](https://web.reveal-th-preview.smartregister.org/plans/update/db533060-30fd-5a70-93ec-fc393d0eb51f) plan to ttest
 I am using superset acc.
 cc @samkanga

**Comment by ciremusyoka** [comment]
@moshthepitt after doing this [fix](https://github.com/onaio/reveal-frontend/issues/1647#issuecomment-894166312), some plans e.g plan id: db533060-30fd-5a70-93ec-fc393d0eb51f are missing on the  [plan_jurisdiction](https://github.com/opensrp/opensrp-reveal-datawarehouse/blob/30d2d14a3e68608ff9d261b014b9e3ddf7729009/3-reveal/migrations/2-transaction_tables/deploy/plan_jurisdiction.psql#L9) table. 
Do we need to do another manual sync for that table too?

**Comment by madrinekariuki** [comment]
New plans are showing on web but the old plans are yet to show.
@ciremusyoka is still looking into this. example of a missing plan.
N/A Thailand test site BVBD 1 2021-08-05 maddy

**Comment by moshthepitt** [comment]
> Do we need to do another manual sync for that table too?

Only plans that have jurisdictions will end up there.  Is it the case for these plans?  If so then we need to reprocess the part of the flow that handles plan-jurisdictions.  That happens here https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=240b9c36-b60c-38b3-3e69-15c3341ef94d&componentIds=

**Comment by samkanga** [comment]
@moshthepitt looks like the link you shared above is for production while the issue is on preview. cc: @ciremusyoka

**Comment by ciremusyoka** [comment]
> @moshthepitt looks like the link you shared above is for production while the issue is on preview. cc: @ciremusyoka

@samkanga I noted this and looked for the similar processor on preview

**Comment by madrinekariuki** [comment]
for thai preview I note that old plans are now showing. I have tested using this [plan](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/7e8fa1cc-1fb7-5e65-a2f2-f3fcef3bca93)
