### ISSUE TITLE
Thai web preview UI on the View part is displaying weird data

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1648]
we have a weird UI on the Thai preview dashboard
this is on the page where we have the map view.i.e go to home -> activities for investigating patients and sources of infection 
-click on a plan
- while on the plan on top click on an OA
- check the UI and observe how some items are misplaced and some missing e.g. the name  group is only one.
 see below screenshot from this [link](https://web.reveal-th-preview.smartregister.org/focus-investigation/view/f782cbb1-cff8-403e-a895-ac60bda3eebc)
![image](https://user-images.githubusercontent.com/84722169/128466565-bc0e44dd-79e5-42af-b992-fc1c2eb4036f.png)

compare that with this normal view of the UI. from this [link](https://web.reveal-th-preview.smartregister.org/focus-investigation/filter/08766e5b-ffeb-4073-ae58-f0a2539c5ef8/22ae16af-154b-52f4-8cc8-4d2af207ad87)
![image](https://user-images.githubusercontent.com/84722169/128466652-8d5e2393-26da-47a2-a871-4e26810cdc71.png)

cc @ciremusyoka @samkanga

**Comment by ciremusyoka** [comment]
@madrinekariuki  This above screenshots show different views:
First [screenshot](https://user-images.githubusercontent.com/84722169/128466565-bc0e44dd-79e5-42af-b992-fc1c2eb4036f.png) view is for operational areas
Second [screenshot](https://user-images.githubusercontent.com/84722169/128466652-8d5e2393-26da-47a2-a871-4e26810cdc71.png) view is for normal jurisdictions

This is how the operational area view has been all through even on production  (see [here](https://mhealth.ddc.moph.go.th/focus-investigation/view/1252735b-9725-4c19-8d9c-70d7ceecf94b)).
cc @samkanga

**Comment by samkanga** [comment]
@ciremusyoka is there a particular reason these are titles are not aligned like the normal jurisdictions. I would say let's correct these. They probably were missed out and just got identified.

**Comment by ciremusyoka** [comment]
There is no reason @samkanga we can correct

**Comment by madrinekariuki** [comment]
The data showing on both pages is now okay.
see screenshot below
![image](https://user-images.githubusercontent.com/84722169/129320400-3cd25b58-ddb3-4783-9498-8ef15ec9fa38.png)
