### ISSUE TITLE
Re-arrange the order of information for patient details in a case triggered plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1650]
In the patient details section, the first name and surname is separated by the plasmodium type (genus species).
![image](https://user-images.githubusercontent.com/5908630/128724183-4af7fdd1-e5de-48e3-99ce-9defe728d6cc.png)

**Requirements**
1. Re-arrange patient details as follows:
2. First name
3. Surname
4. Genus species

**Expected outcome**
The patient's surname is listed below the first name

**Comment by madrinekariuki** [comment]
this is now okay
see below correct arrangement
![image](https://user-images.githubusercontent.com/84722169/129322617-9e308999-a024-4ec5-969b-7c97ad2428f1.png)
