### ISSUE TITLE
Increase the Number of Plans Returned on the Plans EndPoint

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1653]
Presently the limit on the plans endpoint for Thailand Production is at 7000. The DB however has more than 7000 plans. This means some new plans cannot be viewed on the WebUI. Could we increase the limit to 8000. We may also need to monitor if the introduces any performance issues.

**Comment by ciremusyoka** [comment]
Increased `REACT_APP_OPENSRP_MAX_PLANS_PER_REQUEST` env value to 8000 and re-deployed.
