### ISSUE TITLE
Stage Web UI unavailable

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1656]
the stage UI is currently unavailable we are getting this error.
for those currently logged in its slow
when you try to access the UI from a new browser we get below error.
![image](https://user-images.githubusercontent.com/84722169/129196723-146a4c5d-fc8c-4799-8fd6-ef78f7f259b3.png)

**Comment by ciremusyoka** [comment]
Adde `write` scope which was missing on keyCloak.

**Comment by madrinekariuki** [comment]
We are now able to login to the web UI
