### ISSUE TITLE
Location Classification Seems to be failing on the Plan Template for Thailand Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1661]
The location classification details on the WebUI is returning N/A but show a classification of the location on the monitoring page. An example of this is the case triggered plan whose screenshots are shown below:
![image](https://user-images.githubusercontent.com/5908630/132174031-690c4fbe-da84-49ef-ad97-f9da310317a2.png)

![image](https://user-images.githubusercontent.com/5908630/132174041-2b7b2c7d-da91-4c65-a20a-d91e4ef44f97.png)

However, previous plans in the same location have picked the classification correctly. See the plan with ID: `17427738-cd64-405c-9a32-b235f1216166` [here](https://mhealth.ddc.moph.go.th/plans/update/17427738-cd64-405c-9a32-b235f1216166) . See screenshot below:

![image](https://user-images.githubusercontent.com/5908630/132174783-0f2d34c0-c7b7-4ecb-bf58-ce71c01fede9.png)

Please check what may be causing the change in the classification.

**Comment by ciremusyoka** [comment]
@samkanga currently location classification is auto picked from the jurisdiction properties. The selected jurisdiction json for the [plan](https://mhealth.ddc.moph.go.th/plans/update/1042663c-7981-543c-8533-34b722d68133) returning `N/A`, is missing `fiStatus` (property with the location classification value).
```JSON
{
    "type": "Feature",
    "id": "2d9a6e28-ee51-4d3d-8775-ee6bdbcb7612",
    "properties": {
        "status": "Active",
        "parentId": "c7576ab9-8189-468a-8f2e-912549973234",
        "name": "แม่ละโอ๊ด (5806040202)",
        "geographicLevel": 5,
        "version": 1,
        "externalId": "5806040202",
        "name_en": " (5806040202)"
    },
    "serverVersion": 1601625075170,
    "locationTags": [
        {
            "id": 2,
            "name": "Operational Area"
        }
    ]
}
```

The [other plan](https://mhealth.ddc.moph.go.th/plans/update/17427738-cd64-405c-9a32-b235f1216166) with location classification and created out of same location, was created on `2021-08-09`, which was before we deployed the feature for auto picking location classifications.

**Comment by ciremusyoka** [comment]
After running [this PG](https://github.com/onaio/canopy/issues/1818#issuecomment-822195129) the location now has `fi_classification` property.

```JSON
{
    "type": "Feature",
    "id": "2d9a6e28-ee51-4d3d-8775-ee6bdbcb7612",
    "properties": {
        "status": "Active",
        "parentId": "c7576ab9-8189-468a-8f2e-912549973234",
        "name": "แม่ละโอ๊ด (5806040202)",
        "geographicLevel": 5,
        "version": 1,
        "externalId": "5806040202",
        "fi_classification": "B1",
        "name_en": " (5806040202)"
    },
    "serverVersion": 1601625078972,
    "locationTags": [
        {
            "id": 2,
            "name": "Operational Area"
        }
    ]
}
```

**Comment by samkanga** [comment]
Thank you @ciremusyoka I will check and revert.

**Comment by samkanga** [comment]
@ciremusyoka I can confirm this is now resolved. I will go ahead and close the ticket.
