### ISSUE TITLE
Thailand Preview: Error loading map

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1663]
The map looks blur.
[link](https://web.reveal-th-preview.smartregister.org/focus-investigation/map/%22900038b0-c7e1-5109-8a6e-695a044b0860%22)
![Screenshot from 2021-09-10 09-11-01](https://user-images.githubusercontent.com/26719807/132808059-572f10bd-9c4d-4e82-94e4-4084f8c238fb.png)

**Comment by samkanga** [comment]
Thailand Preview Reveal Web Maps are appearing blurred.
