### ISSUE TITLE
PZQ Indicators not showing up on the Dashboard

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1668]
The PZQ indicators on the Eswatini dashboard are not showing up despite the events having been posted from Android. Please check what the issue may be.
PZQ indicators are missing on `Jurisdictions` and `school levels`.

**Comment by ciremusyoka** [comment]
Sample kid:
plan ID: c453c073-dd67-56d1-9435-2c9622dd7a03
Name: Peregrin Took
client id: 961ea019-eb82-482b-9cce-04216f103e75
Jurisdiction id: f0de23e0-1e42-49e1-a60f-58d92040c

**Comment by ciremusyoka** [comment]
The reporting view `mda_client_dispense_task_jurisdiction_report_for_webui` we are getting data from on the web is missing `pzqdist` column which was added when working on [this](https://github.com/onaio/reveal-frontend/pull/1628) issue.
