### ISSUE TITLE
Thai - preview Activation of index case plans

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1672]
Issue Description:

Created index case plans that are in` draft `cannot be changed to `in-progress`  through the Web UI.

steps:
- open a plan that is in `draft` mode e.g a2e060d3-2e3f-448f-95a1-15e2e37f043e
- changed from draft to `in-progress`
- click on save
- observe how the change is not getting saved and on the network table the error is showing as below:

![image](https://user-images.githubusercontent.com/84722169/137704330-c6b77bcc-646c-4b67-99de-fbcadb501c67.png)

**Comment by madrinekariuki** [comment]
@ciremusyoka 
This issue is persitent This has been tested on Thai preview after plan generation was migrated to OpenSRP. 
example  planID :  `4cd19f95-4d02-40a2-bc77-110a5fabaeb6`

![image](https://user-images.githubusercontent.com/84722169/141423715-0177ab9e-5030-4acd-8827-9deb1b60d04c.png)

**Comment by ciremusyoka** [comment]
@Rkareko the `Case Confirmation` action generated by OpenSRP is not correct.

Generated by Nifi
```JSON
{
      "identifier": "b2c467dd-7ce4-46da-acb6-e8d8e6cfa840",
      "prefix": 1,
      "title": "การยืนยันบ้านผู้ป่วย",
      "description": "ยืนยันบ้านผู้ป่วย",
      "code": "Case Confirmation",
      "timingPeriod": {
          "start": "2021-11-11",
          "end": "2021-11-21"
      },
      "reason": "Investigation",
      "goalId": "Case_Confirmation",
      "subjectCodableConcept": {
          "text": "Operational_Area"
      },
      "trigger": [
          {
              "type": "named-event",
              "name": "plan-activation"
          }
      ],
      "condition": [
          {
              "kind": "applicability",
              "expression": {
                  "description": "Event is case details event",
                  "expression": "questionnaire = 'Case_Details'"
              }
          }
      ],
      "definitionUri": "case_confirmation.json",
      "type": "create"
  }
```
Generated by OpenSRP
```JSON
{
          "identifier": "662d4bff-43cc-4f50-af1e-3bc86f8af253",
          "prefix": 1,
          "title": "การยืนยันบ้านผู้ป่วย",
          "description": "ยืนยันบ้านผู้ป่วย",
          "code": "Case Confirmation",
          "timingPeriod": {
              "start": "2021-09-13",
              "end": "2021-09-23"
          },
          "reason": "Investigation",
          "goalId": "Case_Confirmation",
          "subjectCodableConcept": {
              "text": "Jurisdiction"
          },
          "taskTemplate": "Case_Confirmation",
          "type": "create"
      }
````

**Comment by madrinekariuki** [comment]
This issue has been fixed and now we are able to activate plans through the web UI. 
This has been tested using below plans.

planID : `5f69e1a3-70a0-4d40-88c2-27fb40c77da1`
planName:` A1 - เมืองทอง(Site)-2 - QA test3 - 2021-11-15 - Site`
