### ISSUE TITLE
Completed Case Confirmation Task Not Showing on Thailand Production WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1674]
The plan with ID `a8fbf850-0bff-47e7-ad8b-177c33aebc97` had a case confirmation tasks completed under it. However, the completed task does not show up on the WebUI. See the link [here](https://mhealth.ddc.moph.go.th/focus-investigation/map/a9db8499-a018-585f-9241-eac97697872c) and the screenshot below.

![image](https://user-images.githubusercontent.com/5908630/140467027-eb6491f3-f2f0-4120-b7ab-5df99bcda07e.png)

**Comment by ciremusyoka** [comment]
@samkanga the case confirmation task has a business status of not visited

```SQL
SELECT
    identifier as task_id,
    code,
    status,
    business_status,
    plan_identifier
FROM thailand_prod.tasks
WHERE plan_identifier = 'a8fbf850-0bff-47e7-ad8b-177c33aebc97'
AND code = 'Case Confirmation'
AND group_identifier = '4c37f861-f5a6-44f1-8cde-c99c47494a8d';
```
|task_id| code | status | business_status |plan_identifier|
|---|---|---|--|---|
|e8a9352c-978c-4811-9d48-93fb35ec5b89|Case Confirmation|Ready|Not Visited|a8fbf850-0bff-47e7-ad8b-177c33aebc97|

**Comment by samkanga** [comment]
This has since been resolved.
