### ISSUE TITLE
Data Synced from Andorid Device not Showing on WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1675]
The following three plans have data collected and synced from the andorid device. The data has also synced from the canopy DB to the replica 3 DB. However, the plans dont show any data on the WebUI. These are:

1. b6f8392f-1512-5f53-8061-ec4c371d9291
2. d6c95c66-63ec-55b4-919e-2ef8a37e8be0
3. af2760cd-3407-58a5-aff5-c69b8a4c32fd

[Here](https://mhealth.ddc.moph.go.th/focus-investigation/map/4f8afe62-e9f4-5c0b-873d-4c6ac5bcb214) is the webUI link to the plan with ID: `af2760cd-3407-58a5-aff5-c69b8a4c32fd`

![image](https://user-images.githubusercontent.com/5908630/140468076-567b5751-7427-4fca-a9cd-64caa15a0d7f.png)

**Comment by ciremusyoka** [comment]
@samkanga tasks for the flagged plans have successfully synced on the raw tasks table (`raw_tasks`) but not on the tasks table (`tasks`) on the canopy db.

Raw tasks table has tasks for the plans
```SQL
SELECT full_json::jsonb->>'planIdentifier' as plan_id, count(*) as tasks_count from thailand_prod.raw_tasks 
WHERE full_json::jsonb->>'planIdentifier' IN (
'b6f8392f-1512-5f53-8061-ec4c371d9291',
'd6c95c66-63ec-55b4-919e-2ef8a37e8be0',
'af2760cd-3407-58a5-aff5-c69b8a4c32fd'
)
GROUP BY full_json::jsonb->>'planIdentifier';
```
|plan_id|tasks_count|
|-----|----|
|af2760cd-3407-58a5-aff5-c69b8a4c32fd|411|
|b6f8392f-1512-5f53-8061-ec4c371d9291|399|
|d6c95c66-63ec-55b4-919e-2ef8a37e8be0|162|

Tasks table has no tasks for the plans
```SQL
SELECT plan_identifier, count(*) as tasks_count from thailand_prod.tasks
WHERE plan_identifier IN (
'b6f8392f-1512-5f53-8061-ec4c371d9291',
'd6c95c66-63ec-55b4-919e-2ef8a37e8be0',
'af2760cd-3407-58a5-aff5-c69b8a4c32fd'
)
GROUP BY plan_identifier;

row count  0
```

**Comment by ciremusyoka** [comment]
@samkanga synced the missing tasks on Nifi. We have data visible on the web now.

**Comment by samkanga** [comment]
@ciremusyoka we seem to have a recurrence of the issue above. See the details on the plan below:
Plan ID: `a901a917-6633-529b-86e0-de4594b9eb35`
URL: https://mhealth.ddc.moph.go.th/focus-investigation/map/999be290-0d7a-506e-a682-cac2f6968821

**Comment by samkanga** [comment]
@ciremusyoka on the plan added [here](https://github.com/onaio/reveal-frontend/issues/1675#issuecomment-963057461), I realize there is no household registration data but there is data on bednet distribution. Could you check if there is an issue with the HH registration data?

**Comment by ciremusyoka** [comment]
The plan has 122 tasks and all are `Bednet Distribution`

**Comment by samkanga** [comment]
Closing this ticket as this is now resolved.
