### ISSUE TITLE
Thailand: Plan Triggers and Conditions showing

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1679]
On editing activity `Goal target` when creating a plan, Triggers and Conditions are showing.

![Screenshot from 2021-12-08 12-03-50](https://user-images.githubusercontent.com/26719807/145179886-2ea45a41-1f09-4cd1-815e-c11c3ab57b54.png)

**Comment by madrinekariuki** [comment]
The` Target goal` Triggers and conditions are no longer showing. 
![image](https://user-images.githubusercontent.com/84722169/146543674-1e3e5079-ca2c-4711-93bb-94ab9621f1d2.png)

**Comment by madrinekariuki** [comment]
This has also been deployed on the Thai-[local](https://mhealth.ddc.moph.go.th/plans/new) instance and the Plan Triggers and conditions are Not showing. 
screenshot from Thai Local.

![image](https://user-images.githubusercontent.com/84722169/149161319-fffeb48a-e797-48e1-8c95-e9bec5294d81.png)
