### ISSUE TITLE
Link Focus Area cell to FA Map

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#168]
Currently links to both the map view and single FI vew are in the same cell in the Dropdown table. Ideally the cell for the Focus Area will link to the Map view (which will load the FA with active FIs), while the Investigation Name cell will link to the Single FI view.

- [x] Link to Map from Focus Area column
- [x] Remove Map icon/link from Investigation Name column

**Comment by moshthepitt** [comment]
I think this has been overtaken by events i.e. I think this one is now overidden by https://github.com/onaio/reveal-frontend/issues/190
