### ISSUE TITLE
Thailand: Update Team Assignment on Routine Plans to 5 Years

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1681]
Currently `end date` of teams assigned on the web is set to plan`s `end date`.  Team assignments should run for a period of 5 years.

**Comment by ciremusyoka** [comment]
@samkanga should assignments for other instances also last for 5 years?

**Comment by samkanga** [comment]
@ciremusyoka it should be set to 5 years for both Production and preview for both Case triggered plans and routine plans.

**Comment by ciremusyoka** [comment]
Other instances such as Eswatini?

**Comment by samkanga** [comment]
No. That is only specific to Thailand.

**Comment by madrinekariuki** [comment]
This has been tested and has passed QA. 
This has been tested with below 2 plans:
`72dc21e8-4144-499e-a310-828c7116468c`  case triggered plan.
`c8467122-1c03-5140-be81-e7701c135183`  routine plan


steps:

- create a plan
- wait for team assignment to happen
- use [this](https://reveal-th-preview.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans?plan=72dc21e8-4144-499e-a310-828c7116468c) endpoint to check on `toDate` for the plan


observations. 
the toDate should show five years from now.

Nb the date format is in Unix timestamps  change it to human readable using [this](https://www.epochconverter.com/) site.

screenshots
![image](https://user-images.githubusercontent.com/84722169/146555413-4e0d8ac4-b211-4271-8bfe-799f0ec0ece1.png)

![image](https://user-images.githubusercontent.com/84722169/146555565-2e1d107a-004e-4c45-b123-e3b006ef2a78.png)

**Comment by madrinekariuki** [comment]
This has been tested on T[hailand-local](https://mhealth.ddc.moph.go.th/plans/list) instance as well.

plans used:
25413828-b5ac-5281-864c-b7b68537d85c routine plan
bb816a50-44b9-4571-b8a5-c56cce9cbb19 Case triggered plan

steps:
create a plan
wait for team assignment to happen
use [this](https://servermhealth.ddc.moph.go.th/opensrp/rest/organization/assignedLocationsAndPlans?plan=25413828-b5ac-5281-864c-b7b68537d85c) endpoint to check on toDate for the plan.

observations.
the toDate should show five years from now.
