### ISSUE TITLE
Plans not showing on the reporting page on Thailand preview.

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1682]
An issue has been noted on Thailand preview where plans created are not appearing on the action reporting page, despite having been activated, and have team assignments and are in progress. 

sample plans are:
```
A1 - เมืองทอง(Site)-4 - Madrine QA Test 3 - 2021-12-14 - Site
A1 - เมืองทอง(Site)-4 - Madrine QA Test 2 - 2021-12-14 - Site

```

![image](https://user-images.githubusercontent.com/84722169/146015120-344d5828-4682-4128-9c76-7c768379670a.png)

**Comment by ciremusyoka** [comment]
@madrinekariuki @samkanga This is resolved. The view we get this data from was not refreshing.

**Comment by madrinekariuki** [comment]
This has passed QA. the plans are now visible.
![image](https://user-images.githubusercontent.com/84722169/146545387-6861b6b9-267d-47a6-873d-41ea325892b1.png)
