### ISSUE TITLE
Show Team Assignment on Assign Endpoint Where Team Assignment End Date is Indefinite

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1684]
We have run into occasional issues on OpenSRP side where team assignment is set to end on an indefinite date ``. When this happens, one cannot see the team assignments from the `/assign` end point. It has not been possible to tel the cause for this on the OpenSRP side but as a stop gap measure we would like to ensure that the use case is accounted for on the WebUI side.

**Comment by ciremusyoka** [comment]
[Here](https://reveal-th-preview.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans?plan=e49aced6-391d-4c6a-abd9-f7770826ba2a) is a sample of such assignment on Thailand Preview.
Plan id: e49aced6-391d-4c6a-abd9-f7770826ba2a

**Comment by Rkareko** [comment]
@madrinekariuki How to test

1. Create a new plan
2. Activate it
3. Use the API to assign a team to it. The team assignment in this case would not have an end date. Follow the 4. Assign `Organizations to Locations and Plans` section on this [doc](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1628864513/Setting+up+Keycloak). Omit the `toDate` from the payload

**Comment by madrinekariuki** [comment]
@ciremusyoka @Rkareko 
This has been tested. 

steps to test:
Followed the steps [here](https://github.com/onaio/reveal-frontend/issues/1684#issuecomment-1009686868).

Observation:
- the plan's team assignment showed up even with the `toDate` value missing on the plans payload.

**Comment by madrinekariuki** [comment]
This has also been tested on the Thai- local instance and the plan's team assignment showed up even with the toDate value missing on the plans payload.
this was tested using both a routine plan and a case triggered plan

plan IDs used
`200b17ed-6151-4e16-a126-0c68b138ac19` case triggered
`8f82dd78-065f-5dca-bec5-165104bfe59f` routine plan
