### ISSUE TITLE
Logic for Activity Targets

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#169]
Currently the targets for activities are potentially a bit confusing.

We use the following format for all activity targets:

<img width="260" alt="Screen Shot 2019-07-05 at 3 02 01 PM" src="https://user-images.githubusercontent.com/42673455/60741009-e8d70700-9f35-11e9-87d3-9444b94b3104.png">

We have two types of targets we need to support and they should be displayed differently.  We have **count** and **percentage** based targets.  Count based is we just have to reach a specific count.  Percentage means we have to reach a certain percent to achieve the target.  85% home sprayed for IRS is an example.

The [reporting dictionary](https://docs.google.com/spreadsheets/d/1tK1cWvLrgHJ2TKEtlHwCXV6bv2ZH2ONVTgk28uooYpw/edit#gid=1834208304) has the logic.  Here is a short summary 

**Percentage Targets**
- IRS - 90% - number of structures visited and sprayed
- ITN - 90% - number of structures with adequate net coverage (note: we need to discuss how this is calculated)
- MBS (Mass blood screening) - 100% - this is based on the number of family members registered in the family registration 
- Family Registration - 100% - families registered (don't know how the target is generated)

**Count**
- RACD - 50 - number of people that need to have a blood screening
- Larval - 3 - number of dips completed
- Mosquito - 3 - number of traps set and collected

**Formatting**

For count formatting we should change it to the following

**Mosquito**
_Measure: Number of traps set and collected_
1/3 (33% complete). 2 tasks remaining

For percentage:

**Bednet Distribution**
_Measure: Percent of residential structures visited_
Progress towards 90% target: 42% (6 of 16)

**Comment by craigappl** [comment]
The target unit for percent is always "Percent". The unit for others should be "form(s)"

**Comment by rowo** [comment]
This is kind of what the above looks like:

![Progress Drawer - All Campaigns Copy](https://user-images.githubusercontent.com/1584163/60744270-2c843d80-9f43-11e9-8fbb-2df8593abf75.png)

What do you think about updating to this:
- Simplified progress and measure labels
- The "percent target" kind of bothers me. A percent towards the percent target seems a bit awkward. I think it's better just to show total percentage and make the target clear within that line or change the target into a calculated real value (shown below)

![Progress Drawer - All Campaigns Copy 2](https://user-images.githubusercontent.com/1584163/60744517-483c1380-9f44-11e9-8336-7c673dda0a2e.png)

**Comment by rowo** [comment]
I was also just thinking for something like that bednet distribution, why not just show the progress bar and not worry about confusing it with an exact percent. 

Actually, the remaining structures/traps needed is probably more useful for both of those than an exact percent.

**Comment by mlberg** [comment]
Hi @rowo have been thinking about this.  For the percent target we could have a chart but a line where the target is.  Eg the chart can still go to a hundred but we have a line at 90% for the target.

**Comment by mlberg** [comment]
@craigappl I'd like to start introducing the idea of tasks as the nomenclature instead of forms

**Comment by mlberg** [comment]
Ok reviewed with @rowo let's go with his design as it makes a lot of sense

**Comment by rowo** [comment]
Matt is talking about the updated, second one.

**Comment by moshthepitt** [comment]
Update for when we are implement this, based on https://onaio.slack.com/archives/CBSU8L2SC/p1563361427005300:

For `percent` targets, the denominator is calculated off of the goal's target.

For example, if the goal target was 80% and we have a total of 20 tasks, with 10 being complete:

We would calculate the denominator: 0.8 * 20 = **16**
We would calculate the "percentage achieved": (10 / 16) * 100 =  **62.5%**

Then display: 

`Progress: 10 of 16 structures (62.5%) `

**Comment by moshthepitt** [comment]
For `count` type goals i.e. not percent, we simply use the goal target as the denominator.

For example if the goal was 3 traps and we have 4 completed tasks, we would simply display:

`Progress: 4 of 3 traps (133%)`

**Comment by moshthepitt** [comment]
This is the one to be implemented: 

![Progress Drawer - All Campaigns Copy 2](https://user-images.githubusercontent.com/1584163/60744517-483c1380-9f44-11e9-8336-7c673dda0a2e.png)
