### ISSUE TITLE
Create a new focus investigation

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#170]
For the focus investigation, we need the ability to generate a new focus investigation.

This should be initiate from an "Add Focus Investigation" button on the Active Focus page. 
 
<img width="1144" alt="Screen Shot 2019-07-04 at 12 22 55 AM" src="https://user-images.githubusercontent.com/42673455/60639763-fedbaf00-9df1-11e9-8ef1-be4de65cb9d0.png">

The create focus investigation form should contain the following components:

- Name [This will be autogenerated) using the FI status jurisdiction and date.
- interventionType
- Focus Investigation Status
- Focus Investigation Reason
- Intervention Type
- Location (Jurisdiction = focus area) - This should be a drill down to the focus area
- Start Date
- End Date
- Activities

Each of the following activities should be listed.  This should be a multi-select with a checkbox. 

- Mosquito Collection
- Larval Dipping
- Bednet Distribution
- Case Confirmation
- Blood Screening
- RACD Register Family

If the activity is selected then the user should be prompted to add a numeric target.

**Todo**
- Need to confirm if all targets are numeric or if some are percentage based for FI

The form will be submitted to Nifi using some of the predefined templates (see below).

```
name: ${fiStatus}-${jurisdiction.name}-${now()} (today's date?)
title: ${fiStatus} - ${jurisdiction.name} - ${now()} (today's date?)
interventionType: "FI"
fiStatus: "${fiStatus}"
fiReason: "Case-triggered" (Hardcoded)
jurisdiction.code: "${jurisdiction}"
goal:
target.detail.detailQuantity.value: ""
target.detail.detailQuantity.comparator: ""
target.detail.detailQuantity.unit: ""
due: "${}"
action.timingPeriod.start: "${}"
action.timingPeriod.end: "${}" 
```

For reference, please view the [Nifi templates](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1143242833/Automatic+Plan+and+Task+Generation#AutomaticPlanandTaskGeneration-Template1) for creating plans.

Link to data dictionary https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=1195610913

Web UI / Reporting Data dictionary https://docs.google.com/spreadsheets/d/1tK1cWvLrgHJ2TKEtlHwCXV6bv2ZH2ONVTgk28uooYpw/edit#gid=1834208304&range=A4

**Comment by moshthepitt** [comment]
@mberg @craigappl @cKellyDesign  some questions:

1. Concerning the activities, is it possible that a focus investigation might have multiple activities of the same type (e.g. Blood Screening on something else) but with different goals/targets?
2.  Still on the activities, I do not think that it should be a simple select box.  It needs to be a form set that allows you to not only select the activity but also set its goals i.e. it should allow for us to say something like do the `Mosquito Collection` activity at at least `5` sites, or do the `Blood Screening` activity for at least 50 people etc.  Do you agree?
2. In this proposed workflow, where do the cases (e.g. from BIOPHYCS) come in? Or are we limited to only "routine" focus investigations?
3. I suppose the `Intervention Type` will be hard coded to "FI" for this form, right?
4.  Will we be getting a mockup to guide us for this work?

**Comment by cKellyDesign** [comment]
@moshthepitt 

1. From the discussions we had in Capetown, I thought that FIs could have multiple types of intervention activities.
2. This makes sense, I'm trying to remember if these types of settings were to be handled via implementation specific configs. It's unclear to me how much control the user should have here.
5. I think we definitely need mockups (cc @rowo)

**Comment by moshthepitt** [comment]
> From the discussions we had in Capetown, I thought that FIs could have multiple types of intervention activities. @mberg @craigappl - do you recall?

Sorry @cKellyDesign I meant the plan's intervention type field.  Right now I believe it can be `FI` or `IRS` so for this form it should be `FI`

**Comment by mlberg** [comment]
Hi @moshthepitt my understanding is the plan will be FI (@craigappl please confirm) but it will have multiple activities.  Each activity, if active, should be able to able a numeric count target or percent target.  These are listed out in the web ui dictionary.

**Comment by moshthepitt** [comment]
We also need a way to select the focus area for the FI plan.  Not sure what kind of UI will work best here

**Comment by mlberg** [comment]
https://smartregister.atlassian.net/wiki/spaces/REV/pages/1143242833/Automatic+Plan+and+Task+Generation#AutomaticPlanandTaskGeneration-NifiBusinessLogictobeDeveloped

Use Plan template 1 for the plan

**Comment by cKellyDesign** [comment]
- [ ] @mberg to get clarity on number 3 and open a new ticket for that specifically

**Comment by cKellyDesign** [comment]
> We also need a way to select the focus area for the FI plan. Not sure what kind of UI will work best here

@moshthepitt - @mberg suggested this could all be in a form, wherein a user selects the Focus Area from a dropdown / list of FAs, rather than via drilldown table/map.

- [ ] Either way, we'll definitely need some mockups for this user flow. (<~~~ @rowo)

**Comment by rowo** [comment]
@mberg Do we have to differentiate (in the UI) a user-created focus investigation from an auto-generated one? 

@moshthepitt @cKellyDesign I'll take a look at drawing this up. I see creating a new focus investigation being done from anywhere, so maybe in addition to the active investigation page it's in the top nav dropdown and on the focus area page. (I prefer the name "Focus Areas" to "Historical Focus Investigation".) This feels like a wizard, similar to a checkout flow except there is no shopping cart i.e. draft of a focus investigation.

**Comment by moshthepitt** [comment]
The select box design will have to take into account that there are possibly thousands of focus areas.

We'll also probably use this to power it https://react-select.com

**Comment by rowo** [comment]
@mberg Few questions:
1. Can there be multiple investigations in one area at a time?
2. Do any of the create FI fields needs to be filled out in order? For example, would any fields appear different based on answers to other fields?
3. Can you create an FI to start at a future date? If yes, can you create multiple investigations for the future? Would this appear in the active investigation list or not?
4. Are there any constraints on the end date?
5. Do user created investigations have to be differentiated between generated ones (when cases are discovered)?

**Comment by craigappl** [comment]
I'm replying to comments in this thread:
----------
@moshthepitt 
> @mberg @craigappl @cKellyDesign some questions:
> 
> 1. Concerning the activities, is it possible that a focus investigation might have multiple activities of the same type (e.g. Blood Screening or something else) but with different goals/targets?
No, we need to restrict this. The list should remove any activities that have already been added.
> 2. Still on the activities, I do not think that it should be a simple select box.  It needs to be a form set that allows you to not only select the activity but also set its goals i.e. it should allow for us to say something like do the `Mosquito Collection` activity at at least `5` sites, or do the `Blood Screening` activity for at least 50 people etc.  Do you agree?
Yes, that's correct. 
> 3. In this proposed workflow, where do the cases (e.g. from BIOPHICS) come in? Or are we limited to only "routine" focus investigations?
We need the ability to create ad-hoc plans. The cases from BIOPHICS will come in through Nifi and be automatically created through that process. Those will create active plans.
> 4. I suppose the `Intervention Type` will be hard coded to "FI" for this form, right?
Yes
> 5. Will we be getting a mockup to guide us for this work?
Yes, Roger is working on that
----------
@rowo 

> @mberg Do we have to differentiate (in the UI) a user-created focus investigation from an auto-generated one?
No, this would be beyond MVP if we need it.


----------








> @mberg Few questions:
> 
> 1. Can there be multiple investigations in one area at a time?
Yes
> 2. Do any of the create FI fields needs to be filled out in order? For example, would any fields appear different based on answers to other fields?
No, they are all independent
> 3. Can you create an FI to start at a future date? If yes, can you create multiple investigations for the future? Would this appear in the active investigation list or not?
Yes, you should be able to create them, save as draft and then edit them. @mberg will add more detail here.
> 4. Are there any constraints on the end date?
No
> 5. Do user created investigations have to be differentiated between generated ones (when cases are discovered)?
No

**Comment by mlberg** [comment]
Replaced with #188
