### ISSUE TITLE
Completing a Focus Investigation

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#171]
Support the ability to complete or close a focus investigation.

<img width="554" alt="Screen Shot 2019-07-03 at 11 54 13 PM" src="https://user-images.githubusercontent.com/42673455/60638867-13b64380-9dee-11e9-86e5-6e725158205e.png">

The form will provide the ability to suggest a reclassification for the focus and report driver of transmission.

Reclassification options include:
- A1
- A2
- B1
- B2

Report driver of transmission

The plan can be updated by sending a PUT with plan JSON to the [Plan Endpoint in OpenSRP](https://reveal-stage.smartregister.org/opensrp/rest/plans/)

**Comment by moshthepitt** [comment]
@mberg what kind of information goes into `Report driver of transmission`?

**Comment by moshthepitt** [comment]
@githengi what info do we need to POST to OpenSRP to mark a plan as completed?

**Comment by githengi** [comment]
Update status to `retired` as per FHIR plan spec

**Comment by moshthepitt** [comment]
Where would the rest of the things on the proposed form go?

**Comment by githengi** [comment]
classification would go to useContext for the element with the "code": "fiStatus".

The other details should go to an openSRP event.

**Comment by mberg** [comment]
Need to increment the version of the plan.

**Comment by cKellyDesign** [comment]
De-scoping the Note for the upcoming release, will have to do it later because we don't know how the event payload needs to have the note included.

**Comment by cKellyDesign** [comment]
@craigappl @githengi - How do we include the note in the event payload when PUTing to the OpenSRP endpoint?

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/361
