### ISSUE TITLE
View Prior FI Investigations from FI Map View

### ISSUE THREAD

**Issue by mlberg** [onaio/reveal-frontend#173]
Similar to issue #172 have the ability to toggle between prior focus investigations and the current active ones from the FI map view.

<img width="1034" alt="Screen Shot 2019-07-06 at 11 16 53 PM" src="https://user-images.githubusercontent.com/42673455/60763521-3477d680-a044-11e9-9985-4f5dae876019.png">

<img width="324" alt="Screen Shot 2019-07-06 at 11 16 59 PM" src="https://user-images.githubusercontent.com/42673455/60763522-36da3080-a044-11e9-87f5-63f74ad643b2.png">

**Comment by moshthepitt** [comment]
Fixed by #222
