### ISSUE TITLE
Update page titles

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#174]
When you navigate to a new page, the page title should be updated depending on what is on that page.

**Comment by p-netm** [comment]
> We need:
> 
>     1. To ensure all pages have an appropriate page title (i.e. `<title>` title)
> 
>     2. There is a test to specifically check that the title is as expected for each of the above pages.  The hope is that this can set a precedent in which this test is included in future components

Should the test be a standalone test i.e. within its ```it()``` block or can I just bundle it up in the ```it('renders correctly without crashing', ()=>{})``` block

**Comment by moshthepitt** [comment]
It should be one test in the existing test suite for the component i.e. your second option

**Comment by moshthepitt** [comment]
Ideas on how to do this: https://stackoverflow.com/a/52448126

**Comment by moshthepitt** [comment]
We should probably investigate using `react-helmet`
