### ISSUE TITLE
Investigate IRS Reporting Needs

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#179]
We need to do a gap analysis of sorts to figure out what the Reveal web app may be lacking that is required for IRS reporting.

One way of doing this may be setting up a Reveal frontend instance that is set up to use mSpray data from the last IRS season (this data may need to be manipulated a little to fit the current data structures i.e, OpenSRP tasks, structures and jurisdictions).

**Comment by mlberg** [comment]
This is post July 31. We'll do this in August

**Comment by cKellyDesign** [comment]
Given the latest requirements this conversation won't happen until September.

**Comment by moshthepitt** [comment]
@craigappl can we get accurate dates for when IRS reporting needs to be in the web app?  Once we have those dates, we need a few weeks to tackle this issue.
