### ISSUE TITLE
Ensure superset user is logged out after logging out

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#186]
When you click the log out button, we need to ensure that we log out of superset by calling the `deAuthZ` method in SupersetConnector

**Comment by cKellyDesign** [comment]
This can simply be accomplished by `fetch`ing `https://reveal-[X].smartregister.org/opensrp/logout.do` from the browser when clicking log out.

**Comment by moshthepitt** [comment]
@FrankApiyo while this works, I think it is not the right way to do this.

A better or more right way to do it would be to extend the [logout component](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/logout.tsx) that comes with the gatekeeper package.  One way to do this is to make it take an additional prop that represents the logout URL and then call it.  One benefit of doing it this way is that everyone who uses gatekeeper gets free access to this new feature.

I think you should consider:

- creating an issue to do this on the js-tools repo
- creating an issue to remove this "workaround" from Reveal FE and use an updated gatekeeper package, when ready

Let me know if you agree with what I am saying?

cc: @cKellyDesign @p-netm

**Comment by FrankApiyo** [comment]
This makes sense... I think it should be done. The gatekeeper package should be able to handle all oath2 transactions made by any app that uses it and that includes logout.

Also There could be an enhancement that I just learned that we could add to the logout process where a callback URL is passed to the callback endpoint which it should then redirect to after logout(this ideally should  be our login URL). This will help avoid opening another window. This may not be implemented on openSRP though. I'll find out.

**Comment by moshthepitt** [comment]
@FrankApiyo sounds exciting!  Please create the issues :)
