### ISSUE TITLE
Updates to Active Focus Investigations [Discussion]

### ISSUE THREAD

**Issue by rowo** [onaio/reveal-frontend#190]
![Active - Home](https://user-images.githubusercontent.com/1584163/61155759-a70f0900-a4bf-11e9-920a-ac0b3d9c23db.png)

1. Reordered the columns 
2. Added a new "FI Status" column hat shows draft vs. active. Drafts are clickable to go to the draft investigation.
3. Added a "New" label on case-triggered investigations that shows up until a user clicks into the draft
4. Added a "Add Focus Investigation" button
5. Renamed page to "Current Investigations" to reflect that it's not just active.
6. Split up tables to separate routine (user-created) vs. reactive (case-triggered)

**Comment by moshthepitt** [comment]
@rowo regarding splitting the routine and case-triggered:

1. How does the search box work, does it search through both?
2. If we have 100 records on each table, how do we display that?  What is the max. number of rows per table, how should we place the pagination controls?

**Comment by rowo** [comment]
1. Yes sorry I guess it should say "search current investigations" and at its simplest, both tables can just filter down to matching rows. If we want to do something more custom for search results we can try that..
2. I am assuming we don't need pagination since I can't see how there would be like 500+ investigations at once, but I'm okay with a long-list webpage if there's no problem to technically load/show that much information. @mberg do you have an idea of how many active investigations there will be for Thailand at any given time?

**Comment by rowo** [comment]
I chatted with @mberg about this. Updated: 
- Removed links on the cell contents to a right action column (this matches the OpenSRP web approach and is arguable less confusing and more flexible). This means this last column needs to be fixed and appear even on narrow browsers.
- Moved the focus area column to after village to keep the location order. Added an icon link to this element to jump to the area. 

![Current Investigations](https://user-images.githubusercontent.com/1584163/61263599-92e53900-a757-11e9-92cc-159a409895fb.png)

 cc: @moshthepitt

**Comment by moshthepitt** [comment]
@rowo how do you feel about icons on the actions column instead of words?

Also, I am assuming that we are waiting for a sign off from at least @mberg before we work on this in code?

**Comment by rowo** [comment]
@moshthepitt 
- I think words a clearer especially since the action changes in this case depending on investigation status. In OpenSRP Web, there is a word action and then another column of icon pulldown if there are more actions. 
- Yes I think we need sign off from Matt since the requirements weren't super exact, so I think he needs to review it all to know if it matches up everyone's expectations.

**Comment by rowo** [comment]
@moshthepitt After talking to Matt just now, we are reverting back to the name as link (removing the actions column). I will add a comment to the PR.

![Current Investigations](https://user-images.githubusercontent.com/1584163/61749254-4958a780-ad70-11e9-8ff9-bc22c17ee09c.png)
