### ISSUE TITLE
RVL-138 Draw Target around Index Case in Web UI

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#193]
Implement the target around the Index Case in the web UI as it is in the Android client. The specification can be found at https://smartregister.atlassian.net/wiki/spaces/REV/pages/1148289075/Indicate+Index+Case+Household+visually+in+Web+UI

**Comment by moshthepitt** [comment]
Something that could be used for this: https://turfjs.org/docs/#circle

**Comment by moshthepitt** [comment]
https://stackoverflow.com/questions/37599561/drawing-a-circle-with-the-radius-in-miles-meters-with-mapbox-gl-js/39006388#39006388

**Comment by cKellyDesign** [comment]
Gisida as a function to draw a fixed radius circle like this as a layer, will find examples.

**Comment by moshthepitt** [comment]
@cKellyDesign it is set to 1 Kilometre, but this is configurable

**Comment by craigappl** [comment]
@moshthepitt Note that we don't need the 1km circle, we need the target with crosshairs.

**Comment by moshthepitt** [comment]
@craigappl thank you for this clarification!

**Comment by cKellyDesign** [comment]
[icon-index-case.svg.zip](https://github.com/onaio/reveal-frontend/files/3435793/icon-index-case.svg.zip)

This is the icon for the crosshairs, think we can just add this as a new layer would probably be easiest.
