### ISSUE TITLE
Use Symbol Layers

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#194]
To match the mobile client, we need to use symbol layers for:

- Case confirmation
- Mosquito Collection
- Larval Dipping

**Comment by githengi** [comment]
![breeding](https://user-images.githubusercontent.com/25123762/61277437-d624c380-a7ba-11e9-8caf-d3b7204674dd.png)
![mosquito](https://user-images.githubusercontent.com/25123762/61277455-df159500-a7ba-11e9-82be-39a905c0a000.png)
![icon-index-map](https://user-images.githubusercontent.com/25123762/61277469-e6d53980-a7ba-11e9-93d1-a60b03551ecd.png)
