### ISSUE TITLE
Updates to Focus Area "profile" [discussion]

### ISSUE THREAD

**Issue by rowo** [onaio/reveal-frontend#196]
![Focus Area](https://user-images.githubusercontent.com/1584163/61327550-29147000-a7e7-11e9-8bdb-6e47c95a604a.png)

1. Added tables to represent investigations that are: current reactive, current routine, previous reactive, previous routine.
2. Used columns from current investigations (#190), but removed the location, status... (this is the rule for any columns with shared data — if FI status (i.e. A1, B1 etc) is editable, we might want to keep that showing)
3. The Add Focus Investigation button is added to the current routine table.
4. Edit: Added a "delete" and "mark as complete" to the current investigations. This is the only place to delete a draft investigation because the only other independent view of an investigation is an edit state.
5. Edit: Added some columns to the Complete Investigations

**Comment by moshthepitt** [comment]
@rowo for this page:

1. do you think that there is a chance that the completed investigations section might get too large/long given enough time?
2. unfortunately we don't have a way to delete right now (not supported by OpenSRP server at the moment)
3. does the search box on this page search all investigations, active and current?
4. the "new" indicator, how long is something considered new? 1 day? 1 week?

**Comment by rowo** [comment]
@moshthepitt 
> do you think that there is a chance that the completed investigations section might get too large/long given enough time?
Sure, after a long time. But even if you did 6 investigations a year in an area it would take 20 years to be too many for a page. And the answer to that wouldn't be general pagination, but categories/grouping like by year. The table could have a more dense view though (like gmail has a 3 view levels for emails)

> unfortunately we don't have a way to delete right now (not supported by OpenSRP server at the moment)
So what does this mean for draft investigations @mberg ?

> does the search box on this page search all investigations, active and current?
Yes, that'd be cool — to apply to all of the below tables.

> the "new" indicator, how long is something considered new? 1 day? 1 week?
My idea was it would appear until the user clicked into it, which would take the user to the "[Edit investigation](https://github.com/onaio/reveal-frontend/issues/199#issue-468847329)" view. Then it can disappear. Alternatively, a timeframe of 2-3 days or so seems okay to me as well (since I think the timeframe for a FI is that 1-3-7 timeline). @mberg thoughts on this?

**Comment by rowo** [comment]
@moshthepitt @cKellyDesign 

Updates from call with Matt:
- We want to revert back to having the investigation name be the link and not the "View" column for both this and the [current investigations page](https://github.com/onaio/reveal-frontend/issues/190). This will save some space and he is okay with having two distinct approaches for table row actions vs. OpenSRP (name links vs. action column links). 
- The "New" flag logic = show this until whenever in "draft" mode i.e. it disappears when the reactive FI is activated. This should only show for reactive FI's. Matt is wary about adding more logic at this point.
- For delete, he wasn't sure if we add this to the server or not so you might want to follow up with him on it. Regardless, for the UI there is no more delete on this view. That functionality moves to the "Edit FI" page whenever we end up adding delete.

![Focus Area](https://user-images.githubusercontent.com/1584163/61746173-21b21100-ad69-11e9-9e8f-33b76fa462d8.png)
