### ISSUE TITLE
Move layer creation out of GisidaWrapper

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#197]
@cKellyDesign @kahama94 @KipSigei 

I think the GisidaWrapper component is getting very complex and I have been thinking a lot about how to simplify it and make it easier to work with, think about, and test.

The way I see it, it should be a simple wrapper component around the Gisida Map component.  It should not be doing a lot of computation and/or manipulation of data if possible.  Do you agree?

To that end, and to improve its flexibility, I was thinking that we should create some helper function (aka the layer builder) that takes _things_ that we want to display on a map (points, polygons, etc), and then creates Gisida layers.  We could make this function very very flexible such that it is able to create as many layers of different (or the same) types that we want.  Crucially, this function will not at all interact with the Redux state unless we cannot get away with that.

Next, these layers are fed into the GisidaWrapper as props, which in turn ensures they are displayed on the map.

### Pros

- We shall be able to work with as many layers and layer types as we want without introducing complexity in the GisidaWrapper component, and hopefully the layer builder function will be able to handle whatever we throw at it without constant modification/refactoring
- We'll hopefully get rid of the hairy and confusing state management that we currently have in the GisidaWrapper component
- Ultimately, working with Gisida from any component should be more simple to reason about and implement 
- The components that want to render a Gisida map will simply build layers and then call the GisidaWrapper component in a standard way

### Cons

- Probably a lot of work
- Introduction of one more layer of abstraction
- The components that want to render a Gisida map will need to do two things instead of one (build layers via the layer builder function and then call the GisidWrapper)

---

What are your thoughts?

**Comment by cKellyDesign** [comment]
> The components that want to render a Gisida map will simply build layers and then call the GisidaWrapper component in a standard way

@moshthepitt - I agree with this concept, I think it makes a lot of sense to pull the layer creation out of the Gisida wrapper and into the container pages/components so that the wrapper is literally just handling the gisida map. The GisidaWrapper will still need to register / utilize the gisida redux reducers, but agree that the Reveal redux state can be largely left alone from within the gisida wrapper.

**Comment by cKellyDesign** [comment]
- [ ] FI Map Page
- [ ] FI Details Page
- [x] IRS Planning Jurisdiction Selection Page
- [x] IRS Reporting Map View page

**Comment by moshthepitt** [comment]
This is no longer necessary as we'll be [getting rid of GisidaWrapper](https://github.com/onaio/reveal-frontend/issues/1150) instead.
