### ISSUE TITLE
Updates to Focus Investigation "profile" [discussion]

### ISSUE THREAD

**Issue by rowo** [onaio/reveal-frontend#198]
![Focus Investigation](https://user-images.githubusercontent.com/1584163/61327513-113cec00-a7e7-11e9-89d7-aad40f9e3d76.png)

![Focus Investigation Complete](https://user-images.githubusercontent.com/1584163/61327524-15690980-a7e7-11e9-8846-bb44a77dbc53.png)

- Add a "mark as complete" button
- Update the progress to match activity target issue https://github.com/onaio/reveal-frontend/issues/169
- Add a flag for active vs. complete and a "reactive investigation" vs. "routine investigation" title.
- The breadcrumbs should be links. 
- ~~Remove pulldown to other investigations (this is more of a standalone investigation rather than a way to browse investigations (not sure if this is/was implemented yet)~~ Edit: nevermind. There is a pulldown again.

**Comment by moshthepitt** [comment]
@rowo I remember there was an involving discussion on the need to change how the indicators are displayed.  I think this was the chief complaint from the Thailand client.

On the mockups I see we have something like:

> Progress 18 of 20 structures visited (90%) 

In this case, 19 is the number of completed tasks, right?

But what does 20 represent?  it could be one of two things:

- The number of total tasks 
- The value of the goal's target from the Plan definition

These two numbers are usually the same, but we've seen cases where they are different in both directions (i.e. both when the total number of tasks is lower and greater than the goal target value).

Additionally, when the goal target is of unit "percent", the goal target value will be a target percentage so in this case it is clear that the denominator will be the total number of tasks.

Which means the part that is unclear to is what numbers to use for goals whose unit is not "percent".

@mberg @craigappl @cKellyDesign @githengi  have we come to an agreement on this?

**Comment by moshthepitt** [comment]
Related: https://github.com/onaio/reveal-frontend/issues/169

**Comment by moshthepitt** [comment]
@rowo regarding the pull down, and sorry if this has been addressed elsewhere, what is shown there?  Is it other focus areas, or other investigations in the current focus area?

**Comment by rowo** [comment]
It is other investigations in the current focus area that would have an investigation view (the active and completed). The investigations should be listed out in chronological order, most recent first, with the current selected investigation and active investigations labeled. As an upgrade, the list could be divided into the same sections as the focus area page i.e. Current reactive, Current routine, Completed reactive, Completed routine, though I'm not actually sure if that's more useful or jsut by date alone. @mberg ?

**Comment by moshthepitt** [comment]
thanks @rowo
