### ISSUE TITLE
Create/Add and Edit FI page

### ISSUE THREAD

**Issue by rowo** [onaio/reveal-frontend#199]
## Add new FI
![Add Focus Investigation](https://user-images.githubusercontent.com/1584163/61326732-71329300-a7e5-11e9-847c-770349c5eaa2.png)
- For user-created investigations
- Clicking on the checkbox will make visible a target as described in https://github.com/onaio/reveal-frontend/issues/188#issue-467064059 and https://github.com/onaio/reveal-frontend/issues/188#issuecomment-511298511
- The start date is for display and FI naming only, equivalent to the "case notification" date in reactive investigations. 
- Saving the FI as active will mean this view isn't editable anymore (and the FI isn't editable). Therefore, we probably need a confirmation step if an investigation is saved as Active. What do you think @mberg ?
- Save button updates to the selected status i.e. "Save as draft" or "Save and activate"
- @mberg are all fields required?

## Edit FI (either a draft of a user-created, or a new draft of an incoming case-triggered)
![Edit Focus Investigation](https://user-images.githubusercontent.com/1584163/61326755-7c85be80-a7e5-11e9-84e4-b8bbb614c466.png)
- Start date will change to "Case notification date" for case-triggered instances
- Generally the same as above "add FI" form except with a new uneditable name field. I don't know if the name changes if the start date or case notification date changes during edit. @mberg what do you think?

**Comment by moshthepitt** [comment]
@craigappl @mberg @rowo some questions based on the latest mockups:

1. How do we determine the goal priority?
2. How do we determine the action prefix?
3. How do we determine the goal due date?
4. How do we determine if the goal unit is "percent" or "task/each/whatever"?
5. Are we going to hard code the goal comparator value to `>=`, for now?
6. How do we determine the action `subjectCodableConcept` field(s)?
7. How do we determine the action `timingPeriod` fields?
8. Are we going to limit the number of targets per goal to one?

**Comment by moshthepitt** [comment]
It seems that this is the minimum payload that you can send to the OpenSRP server to be able to create a plan object:

```json
{
    "identifier": "0e85c238-39c1-4cea-a926-3d89f0c98428",
    "version": "1",
    "name": "mosh-mosh",
    "title": "Mosh test 2",
    "status": "draft",
    "date": "2019-06-18",
    "effectivePeriod": {
        "start": "2019-06-18",
        "end": "2019-07-30"
    },
    "useContext": [],
    "jurisdiction": [],
    "goal": [],
    "action": []
}
```

Therefore, the following fields are required:

1. **identifier** - needs to be a UUID - should be unique per plan
2. **version**
3. **name** (needs to be computer-friendly)
4. **title** (this is meant to be human readable)
5. **status** (active/draft/retired)
6. **date**
7. **effectivePeriod**
    - start
    - end
8. **useContext** 
9. **jurisdiction** - empty list is fine but should be populated with jurisdiction ids otherwise 
10. **goal** - empty list is fine but should be populated with goal objects otherwise
11. **action** - empty list is fine but should be populated with action objects otherwise

**Comment by moshthepitt** [comment]
### Implementation plan notes

1. Create general purpose plan form (using [Formik](https://github.com/jaredpalmer/formik))
    - Write functionality to translate values in the form to valid Plan goal objects
    - Write functionality to translate values in the form to valid Plan action objects
    - Write functionality to translate values in the form to valid Plan jurisdictions (initially the field should be a simple input that takes one jurisdiction id)
    - Write functionality to translate values in the form to valid Plan useContext objects
    - Write functionality to translate values in the form to valid Plan effectivePeriod objects
    - Write functionality to generate the plan identifier (probably using uuid v5 via [UUID](https://www.npmjs.com/package/uuid)
    - Write functionality to generate the plan name/title (should be easy to override coz I think at some point we may have typed in plan titles at least)
2. Create a general purpose robust plan validation method (using [Yup](https://github.com/jquense/yup))
3. Write tests to ensure you can't get invalid tasks
4. Enhance the jurisdiction field of the form to have a fancier filtered select i.e. first you see Provinces, then drill down the hierarchies (probably only for FI plans) - probably using [react-select](https://react-select.com/)
5. Write more tests
    - That the form results in actual plan objects with all the goals, actions, etc correct
    - That the form can work when you are doing an edit

---

Hopefully the above "framework" can be done in a way that is easily usable for both FI and IRS plan creation

**Comment by cKellyDesign** [comment]
Seems like all the bullets of number 1 are required regardless of implementation, no?

@moshthepitt - how does the LOE of building/validating the form with reactstrap form elements and custom event handlers compare to doing it with Formik and Yup? Can we accomplish this in phases (starting with the former and iterating to the later)?

**Comment by craigappl** [comment]
@moshthepitt

> * How do we determine the goal priority?
The goal priority should be a field that's defined in the web form as part of the goal
> * How do we determine the action prefix?
The action prefix should be the order in which the user enters the actions (1 - N)
> * How do we determine the goal due date?
The goal due date should be defined by the user for the action.timingPeriod.end.
> * How do we determine if the goal unit is "percent" or "task/each/whatever"?
The user should enter this
> * Are we going to hard code the goal comparator value to `>=`, for now?
Yes
> * How do we determine the action `subjectCodableConcept` field(s)?
That's hard coded based on the intervention type. So, if the code is "IRS", we know the subjectCodableConcept should be "Residential_Structure"
> * How do we determine the action `timingPeriod` fields?
These should be entered by the user
> * Are we going to limit the number of targets per goal to one?
Yes. We are only supporting one right now in the MVP.

**Comment by moshthepitt** [comment]
@craigappl thanks!  This is very very helpful.  Just a couple more questions:

> That's hard coded based on the intervention type. So, if the code is "IRS", we know the subjectCodableConcept should be "Residential_Structure"

What about when the intervention type is `FI`?  What are the rules for the various action/goals `subjectCodableConcept` values?  

> The goal priority should be a field that's defined in the web form as part of the goal

The allowed goal priority values are these - yes?

- high-priority
- medium-priority
- low-priority

**Comment by moshthepitt** [comment]
@cKellyDesign 

> Seems like all the bullets of number 1 are required regardless of implementation, no?

Yeah it feels that way

> how does the LOE of building/validating the form with reactstrap form elements and custom event handlers compare to doing it with Formik and Yup? Can we accomplish this in phases (starting with the former and iterating to the later)?

We'll still use reactstrap, Formik and Yup just make it a better/easier less manual experience.  I think for this part the LOE is one day, I'll attempt to do that today.

**Comment by moshthepitt** [comment]
@rowo based on the responses from @craigappl above, I think the mockup should change slightly but due to the fast approaching deadline for this, I'll start work today.  When I have a working version (i.e. it can actually create valid plans) then I'll share with you and we can then hopefully iterate on the design of the form.  Does that sound like a good plan?

**Comment by moshthepitt** [comment]
Plan definition spec: https://www.hl7.org/fhir/plandefinition.html
