### ISSUE TITLE
Updating Page titles for Gatekeeper imported views

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#203]
Views without a custom titile:
- [ ] oath pages login, logout, outh pages
- [ ] Document.title for IRS/plan page is untested.

**Comment by moshthepitt** [comment]
@p-netm could you also create this issue on the `js-tools` repo?

**Comment by cKellyDesign** [comment]
Migrated to https://github.com/onaio/js-tools/issues/94
