### ISSUE TITLE
Fix IRS/plan page test

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#204]
This test ```renders IRS Plan page correctly``` in IRS/plan/tests/ is broken, the component does not actually get past the load component as seen [here](https://github.com/onaio/reveal-frontend/blob/60ca90ce3f61f63d70e2dccac2567f009eb2c187/src/containers/pages/InterventionPlan/IRS/plan/tests/__snapshots__/index.test.tsx.snap#L110)

**Comment by cKellyDesign** [comment]
@p-netm @moshthepitt what PR is linked to this ticket?

**Comment by moshthepitt** [comment]
Seems this is fixed.  Please re-open if not.
