### ISSUE TITLE
Improve tests of components that use SupersetConnector

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#212]
The components that fetch data from Superset need tests that ascertain the Superset service was called with the correct/expected parameters.

- [ ] FI map page component
- [ ] FI single page component
- [ ] FI active list component

**Comment by p-netm** [comment]
A __request for comment__: Is this what is needed ; say for the Active FI
the code : 

```typescript

import superset from '@onaio/superset-connector';

const supersetParams = superset.getFormData(2000, [
      { comparator: FI_PLAN_TYPE, operator: '==', subject: 'plan_intervention_type' },
    ]);
    supersetService(SUPERSET_PLANS_SLICE, supersetParams).then((result: Plan[]) =>
      fetchPlansActionCreator(result)
    );
```

The test:

```typescript
jest.mock('@onaio/superset-connector', () => {
  // tslint:disable-next-line: label-position
  const superset = {
    getFormData: () => ({}),
  };
  return superset;
});

const supersetServiceMock: any = jest.fn();

// the actual test
expect(supersetServiceMock).toHaveBeenCalledWith(0, {});

```

**Comment by moshthepitt** [comment]
@p-netm yes, more examples here https://github.com/onaio/js-tools/blob/master/packages/SupersetConnector/src/tests/supersetConnector.test.ts#L20
