### ISSUE TITLE
Investigate 0/0 (0%) goal metrics

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#213]
What is going on here?

![AwesomeScreenshot-Focus-Investigation-A2-Tha-Luang-Village-1-Focus-02-Reveal-Stage-2019-07-19-21-07-48](https://user-images.githubusercontent.com/372073/61557538-232fc080-aa6d-11e9-9d8f-95320f053e2b.png)

**Comment by p-netm** [comment]
```typescript
{
    completed_task_count: 0,
    goal_comparator: ">=",
    goal_unit: "Percent",
    goal_value: 100,
    task_count: 0,
}
```

So the math behind this will give us: ```0 completed tasks``` of a ```100% of 0 = 0``` as the target task count.

**should i drop goal entries whose target task count is 0?**
say we have a hypothetical goal with the following values :

```typescript
{
    completed_task_count: 0,
    goal_comparator: ">=",
    goal_unit: "Percent",
    goal_value: 40,
    task_count: 1,
}
```
the target count would still be ```0``` here.
What should i do about goals with the above values?

**Comment by moshthepitt** [comment]
In this case let us use the `goal_value` - does that sound ok?

**Comment by p-netm** [comment]
> In this case let us use the `goal_value` - does that sound ok?

not sure i follow: so say for : 
```typescript
{
    completed_task_count: 0,
    goal_comparator: ">=",
    goal_unit: "Percent",
    goal_value: 100,
    task_count: 0,
}
```
what should be the displayed values?

**Comment by moshthepitt** [comment]
`0 of 100 (0%)`

**Comment by p-netm** [comment]
is it possible that we could have the ```goal_unit !== "Percent"``` but with a ```goal_value``` of```` 0```

**Comment by moshthepitt** [comment]
that case would be a bug and would hopefully be exceedingly rare, so we dont need to do anything special to deal with it i.e. it can remain `0 of 0 (0%)`
