### ISSUE TITLE
Get map icons from settings

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#218]
The map icons should not be hard coded, but should be loaded from settings. i.e. https://github.com/onaio/reveal-frontend/blob/master/src/helpers/utils.tsx#L206

**Comment by p-netm** [comment]
__Proposed Approach__:
1. copy over the full `imgArr` to settings
2. create the literal string values in the constants file for keys: `id` and `imageUrl`.
3. replace the literal string values in the object which would now be in settings with the const defined in step 2
