### ISSUE TITLE
Scope Request: How to generate tasks?

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#220]
So once we have created a new plan (either IRS or FI) via the web app, how do we create/generate the tasks for it?

We need to scope how this works from the web app point of view.

**Comment by mberg** [comment]
Agree we need to have this discussion with @craigappl it relates to the work janette is doing i believe

**Comment by craigappl** [comment]
My thinking is that we have Nifi do this on a cron schedule by querying plans by the serverVersion date. We have the case triggered focus investigation plan and task generation process scoped, but not the routine interventions or IRS.

The task scoping is defined in this part of the doc: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1143242833/1.+Automatic+Plan+and+Task+Generation+Original+-+1+case+1+focus+plan+generated#id-1.AutomaticPlanandTaskGeneration:Original-1case:1focusplangenerated-NifiBusinessLogictobeDeveloped

We will need to update it for IRS and FI plans.

**Comment by moshthepitt** [comment]
@craigappl that's a good plan.  But how does NiFi identify plans that have tasks, and plans that don't have tasks?

I guess one way is to check the OpenSRP API to see if tasks exist for the plan.  But I am not sure if this is robust enough - what do you think @githengi ?

**Comment by githengi** [comment]
Currently the only want to know if a plan has tasks is to query for the tasks using the plan identifiers and jurisdiction(s).

We can also add an element on the plan to track if tasks has been generated on not.

**Comment by cKellyDesign** [comment]
Closing: This seems scoped and done, reopen if you disagree :)
