### ISSUE TITLE
Add links to all bread crumbs on map view

### ISSUE THREAD

**Issue by kahama94** [onaio/reveal-frontend#221]
![AwesomeScreenshot-Focus-Investigation-A1-Tha-Sen-8-Focus-01-Reveal-2019-07-23-19-07-53](https://user-images.githubusercontent.com/50580477/61730206-95f8ae80-ad81-11e9-9280-c8dc61a22ace.png)

**Comment by cKellyDesign** [comment]
@mberg @craigappl @moshthepitt - where would these links go?

**Comment by moshthepitt** [comment]
@cKellyDesign they would be new pages that list focus investigations but filtered to the jurisdiction level of the breadcrumb

**Comment by FrankApiyo** [comment]
I'm going write a new method that takes in two arguments: 

1. locationHierarchy; a number indicating the hierarchy of the location like the `level` field here: https://github.com/onaio/reveal-frontend/blob/master/src/configs/settings.ts#L71 

2. location; the name of the location extracted from the bread crumb

This new method called: `filterPlans` will remove, using the Array.prototype.filter method,  any plans that do not have the location specified by the location parameter above in their `jurisdiction_name_path` property  at index `locationHierarchy - 1`; (as in 'plan.jurisdiction_name_path[locationHierarchy - 1]`)
