### ISSUE TITLE
Create OpenSRP events to accompany plan CRUD processes

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#223]
Whenever we create/update a plan we should also create an OpenSRP event to serve as a log of the change.

**Comment by moshthepitt** [comment]
@githengi do you have a rough idea of what the event object(s) in this case might look like?

**Comment by githengi** [comment]
The below can be used when creating a Plan, when editing a plan the eventType can be changed to `Update Plan` 


```
{
  "identifiers": {},
  "baseEntityId": "<<Plan ID>>",
  "eventDate": "2019-05-14T00:00:00.000+02:00",
  "eventType": "Create Plan",
  "formSubmissionId": "b65d3abc-c5eb-454b-b04f-69bcc30f0705",
  "providerId": "<<logged in username>>",
  "duration": 0,
  "entityType": "Plan",
  "details": {
    "key1": "value",
    "key2": "value",
    "keyn": "value"
  },
 "obs" : [
  {
      "fieldType": "concept",
      "fieldDataType": "start",
      "fieldCode": "163137AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "parentCode": "",
      "values": [
        "2019-05-14 16:34:08"
      ],
      "set": [],
      "formSubmissionField": "start",
      "humanReadableValues": []
    },
    {
      "fieldType": "concept",
      "fieldDataType": "end",
      "fieldCode": "163138AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "parentCode": "",
      "values": [
        "2019-05-14 16:34:56"
      ],
      "set": [],
      "formSubmissionField": "end",
      "humanReadableValues": []
    }
]
  "version": 1557860282617,
  "dateCreated": "2019-05-14T21:12:33.095+02:00",
  "type": "Event"
}
```

**Comment by cKellyDesign** [comment]
@githengi - a few questions on the schema:

1. Does `duration` ever change? What should it be if not `0`?
2. What type of things go into `details`?
3. Are the times in the `obs` array the start and end times?

**Comment by githengi** [comment]
@cKellyDesign below are my responses
1. Duration time in minutes that the user took in filling the form
2. Details would be used to save details about the event, This should e.g tag the plan being edited,  and other details 
3. Yes items in the obs is the fields that were changes
4. That is usually would be mapped to a `name`  in a html form element. Its used to uniquely identify a field. It can be code from a Concept Lab e.g OpenMRS or just a text e.g 'citizenship' for a field that captures data about citizenship and that is not mapped to a concept

**Comment by cKellyDesign** [comment]
@moshthepitt @githengi @craigappl - How essential is this for the upcoming release milestones?

**Comment by moshthepitt** [comment]
This is not essential right now.

**Comment by cKellyDesign** [comment]
@moshthepitt @githengi is this still a requirement of the Webapp?

**Comment by githengi** [comment]
This can be dropped for now
