### ISSUE TITLE
Investigate replacing moment.js

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#233]
We should check to see if we can replace moment.js with something that is smaller

**Comment by moshthepitt** [comment]
Look into https://date-fns.org/

**Comment by cKellyDesign** [comment]
What's moment's size? Can we just install what we need? Looks like that's the first point for `date-fns`

**Comment by cKellyDesign** [comment]
Closing this because let's stick with Moment unless/until we decide against this later.
