### ISSUE TITLE
Replace componentWillReceiveProps

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#237]
This is a ticket to track the work around replacing Reacts depricated `componentWillReceiveProps` lifecycle function.

**Comment by cKellyDesign** [comment]
Seems like this would go hand in hand with #286, especially if we are loading Jurisdiction geojson as the user Drills down through the Jurisdiction hierarchy.

**Comment by cKellyDesign** [comment]
@moshthepitt are there any good resources you can share on why and how?

**Comment by moshthepitt** [comment]
### Why

[Update on Async Rendering (explains why this was deprecated)](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

### How

1.[You should move all the code from the componentWillMount to the constructor or componentDidMount](https://stackoverflow.com/a/49213753)
2. [Replacing ‘componentWillReceiveProps’ with ‘getDerivedStateFromProps’](https://hackernoon.com/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607)
3. [Simply use React hooks](https://reactjs.org/docs/hooks-intro.html)

**Comment by cKellyDesign** [comment]
@moshthepitt am going to incorporate this approach in the IRS Report List and IRS Report Map views :)

**Comment by moshthepitt** [comment]
This is no longer necessary as we'll be [getting rid of GisidaWrapper](https://github.com/onaio/reveal-frontend/issues/1150) instead.  `componentWillReceiveProps` was only used here.
