### ISSUE TITLE
Move Gisida Event Handlers into Handlers file

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#243]
We should centralize our Gisida mouse event handlers, just need to make sure the handlers are set up in a way to receive all data, states, and props via params.

**Comment by moshthepitt** [comment]
@cKellyDesign @KipSigei I think that eventually these need to go back into Gisida.  Yes?

**Comment by cKellyDesign** [comment]
@moshthepitt I as actually thinking it would be really cool to have a suite of utility event handlers for certain things. In this case we would have to really separate business logic from the core utility involving the map Even then I think the business piece would be hard to pull of this file and the utility would need to be imported from gisida/-react (if not another gisida-addon type of library!)

**Comment by cKellyDesign** [comment]
Closing this issue because we are currently re-addressing how to structure customizable and configurable helpers and handlers.
