### ISSUE TITLE
Add more IRS Planning pages Tests

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#244]
Currently there is low test coverage in the IRS Planning pages which needs to be added.

**Comment by cKellyDesign** [comment]
relates to #416

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm @kahama94 - I'm realizing now that I'm not really sure on how to mock some of the things necessary to test the actual page, particularly Mocking up the API calls in `ComponentWillMount` to [Superset](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L249) and [OpenSRP](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L301). Do we have a good example of how to do this?

**Comment by moshthepitt** [comment]
@cKellyDesign maybe these help?

- OpenSRP service tests: https://github.com/onaio/reveal-frontend/blob/master/src/services/opensrp/tests/index.test.ts#L78
- Superset service tests: https://github.com/onaio/reveal-frontend/blob/master/src/services/superset/tests/index.test.ts#L35
- PlanForm tests: https://github.com/onaio/reveal-frontend/blob/master/src/containers/forms/PlanForm/tests/index.test.tsx#L748
- Superset connector tests: https://github.com/onaio/js-tools/tree/master/packages/SupersetConnector/src/tests
- The GateKeeper package tests also has some nice mocking: https://github.com/onaio/js-tools/tree/master/packages/gatekeeper

**Comment by cKellyDesign** [comment]
Replaced by #664
