### ISSUE TITLE
Capture all tasks that should render symbol layers

### ISSUE THREAD

**Issue by kahama94** [onaio/reveal-frontend#251]
Current implementation only tests Mosquito collection symbol leaving larval dipping and case confirmation untested. Inclusion of this will ensure tests cover all symbol layer instances

**Comment by FrankApiyo** [comment]
I'll change task6 here: https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/tests/fixtures.ts#L658 to be a larval_dipping task and then task7 here: https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/tests/fixtures.ts#L699 to be a case confirmation task. Both these tasks are at the moment bed net distribution tasks

**Comment by kahama94** [comment]
Fine by me since we have bednet distribution tested in other cases

**Comment by cKellyDesign** [comment]
@kahama94 @FrankApiyo what's the status of this ticket?

**Comment by kahama94** [comment]
I think we can move the the list that holds goals to a settings file.  After that We can test the list by matching snapshots for the map layers
 ``` store.getState()['map-1'].layers ```. This will mean when someone adds or removes a new goal on the list the tests will fail requiring snapshot update

**Comment by moshthepitt** [comment]
This is no longer necessary as we'll be [getting rid of GisidaWrapper](https://github.com/onaio/reveal-frontend/issues/1150) instead.
