### ISSUE TITLE
FI Plan: Add tests

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#260]
- [x] Test PlanForm
- [x] Test PlanForm for new plans
- [x] Test PlanForm for existing plans
- [x] Test PlanForm validations
- [x] Test PlanForm submission
- [x] Test PlanForm helpers
- [x] Test NewPlan
- [x] Test UpdatePlan
- [ ] Test JurisdictionSelect
- [x] Test DatePickerWrapper

**Comment by cKellyDesign** [comment]
Closing this b/c or #292
