### ISSUE TITLE
Redo react select functionality

### ISSUE THREAD

**Issue by kahama94** [onaio/reveal-frontend#262]
When selecting an option on activefi component we are not able to load goals since the plan isn't done pushing to the server so by the time it mounts it isn't getting the data it needs from mounting.

- [ ] Add a pointer instead of cursor when selecting various plans

- [ ] Replace react  select with async select

**Comment by cKellyDesign** [comment]
> we are not able to load goals since the plan isn't done pushing to the server so by the time it mounts

This sounds like there needs to be an asynchronous check confirming the PUSH (by subsequently GETing) the Plan before then re-directing and trying to fetch (similar to #308).

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm @kahama94 should this be considered a part of #300 (aka - displaying error messages if/when API service requests fail?)

**Comment by kahama94** [comment]
@cKellyDesign  I agree The current implementation uses react select component. but we should be using async select. I think issue #300 handles notifications while this one handles  rethinking the select component. I think it is more contextually relevant to the PlanForm Async-Select component?

**Comment by cKellyDesign** [comment]
Closing this as it will be addressed by #300
