### ISSUE TITLE
Refactor link to new plans

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#266]
To make the code more DRY, we should move this component to one place where we can import it from when re-using:

```ts
            <Link
                to={NEW_PLAN_URL}
                className="focus-investigation btn btn-primary float-right mt-5"
              >
                Add Focus Investigation
            </Link>
```

**Comment by FrankApiyo** [comment]
I'll Create a new component call `LinkToNewPlans` that'll render Link and then import it to wherever it's used.
