### ISSUE TITLE
Re-use jurisdiction geometries instead of Re-downloading them

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#277]
This ticket is primarily for IRS planning page but should be also be considered any time a page is pulling geojson from the server it should first check local state to see if they exist. 

...UNLESS the geojson properties are different (like for goals) then we will still need to re-download the jurisdiction. Ideally we should have one set of geometry for each GIS entity which gets contextually specified at attached if/when needed.

**Comment by moshthepitt** [comment]
What are you ideas on how to achieve this?

**Comment by cKellyDesign** [comment]
What I'm thinking is basically:
1. determine what Jurisdictions are involved
2. check the store to see which Jurisdictions have geojson
3. make API requests only for those that don't have them
4. then `fetchJurisdictions(Jurisdiction[])` (dispatch / save to store)
5. the page can then move on with the process of rendering them all from geojson in the store

The main barrier that I've run into so far is dealing with the asynchronous-ity of dispatching to the store when a component needs the results of this process to move onto the next step of things (like building GisidaWrapper props). Was thinking of adding `isLoading` or `isFetching`  boolean to the Jurisdiction store (which could be quickly dispatched to true at the beginning of some of these chained async processes).

**Comment by cKellyDesign** [comment]
Closing this as it is currently happening, we only download geojson of administrative jurisdictions if no tilesets are provided.
