### ISSUE TITLE
Can we load the IRS planning map progressively

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#286]
@cKellyDesign do you think it would be a good idea to load the IRS planning map progressively?

i.e.
- as soon as we have the first geometry, load the map and show something to the use
- continue to load the other geoms aynchronously
- show a less intrusive Loading indication while this happens

**Comment by cKellyDesign** [comment]
@moshthepitt I had thought of this and for simplicity's sake I did all the loading up front, but it would be nice if we could quickly fetch Jurisdictions with geoms only as they are needed. I think the tradeoff here is making the user wait while subsequent geoms load as the user interacts with the page vs if we do it all up front the user can navigate around at will.

**Comment by mberg** [comment]
We should only be showing the map one level at a time and just for the
jurisdictions in the list.  I think right we may be loading a lot more
jurisdications then that.

**Comment by cKellyDesign** [comment]
So I think it depends on the actual use case around planning IRS campaigns:

* If the user never realistically needs to select individual spray areas via the map, then we don't actually have to get the geoms at all
* If the user occasionally selects individual spray areas via the map, then progressively loading on (parent) admin click
* If the user is jumping from district to district and wants to see the individual spray areas on the map then it may make sense to async load in chunks to let the user start diving in while loading geoms are loading

Also, if we are doing this we will probably need to add an `isLoadingGeoms` flag to the store so the system knows there's more coming!

**Comment by cKellyDesign** [comment]
> We should only be showing the map one level at a time

@mberg on staging this is the current functionality for Namibia since it is using tilesets, and I was able to extend this functionality to maps without tilesets as of 5c7e042 (in PR#281) just a few minutes ago.

**Comment by cKellyDesign** [comment]
Latest update on this is that we can accomplish this by using the `findByIdWithChildren` to "find" the level 0 jurisdiction by ID and all of it's children. This endpoint allows us to pull more than 1000 jurisdictions at a time so the requests may get large, but no larger than from Superset.

**Blocker**: Zambia does not have a level 0 jurisdiction in OpenSRP

**Comment by moshthepitt** [comment]
This was done as part of https://github.com/onaio/reveal-frontend/issues/892 in #788
