### ISSUE TITLE
Adjust Look and feel of symbol layers

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#287]
Some of the symbol layers like Larval dipping look at least strange at the default zoom level

i.e.

![default](https://user-images.githubusercontent.com/372073/62385349-7de11600-b55d-11e9-9045-2a7bd0567600.png)

Vs zoomed in

![zoomed in](https://user-images.githubusercontent.com/372073/62385358-86395100-b55d-11e9-8162-db79f48ffcd0.png)

**Comment by cKellyDesign** [comment]
Yeah I can't even see the icon/circle when it's zoomed out. @kahama94 please make the circles a quite a bit bigger compared when zoomed out.

**Comment by cKellyDesign** [comment]
- [ ] Look for good sample layers in the Routine FI Plans
- [ ] Adjust the styling
