### ISSUE TITLE
Show correct FI details on map

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#288]
![correct fi details](https://user-images.githubusercontent.com/372073/62385507-f47e1380-b55d-11e9-91e7-1a48ecebce04.png)

**Comment by cKellyDesign** [comment]
@moshthepitt what is the expected result here?

**Comment by moshthepitt** [comment]
> what is the expected result here?

@cKellyDesign This was not scoped.  @craigappl @mberg can you provide guidance?

**Comment by mberg** [comment]
Sorry I think it’s just to show the right details about the Fi Eg The classification status isn’t right.  I think that’s all it is

**Comment by moshthepitt** [comment]
@mberg but what details do we want to show?  Are we showing only the classification status?

**Comment by cKellyDesign** [comment]
Let's start by just showing the classification status. (Unless there is more required @mberg?)

**Comment by cKellyDesign** [comment]
> Let's start by just showing the classification status.

We're already showing start and end dates, so the task for this ticket should be:
- [ ] Add classification status above start and end dates

**Comment by cKellyDesign** [comment]
closing this issue because non-routine plans are already dynamically displaying the plan's Classification Status from the plan definition.

**Comment by moshthepitt** [comment]
@cKellyDesign but currently saying Case classification === "FI" is not accurate.  We need to at least change that - no?

**Comment by cKellyDesign** [comment]
What are the values to be displayed?

**Comment by moshthepitt** [comment]
@cKellyDesign idk which of the values to display

**Comment by cKellyDesign** [comment]
Closing this as it seems to be a non-issue.
