### ISSUE TITLE
Investigate why Redux store is being reloaded

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#289]
When you first log in to the web app, and you navigate to the active FI page, the web app requests for all those plans from Superset.

When you go to an individual plan and then go back to the list page, you will notice that it re-loads the list from scratch instead of using what it should already have had in the Redux store.

**Comment by p-netm** [comment]
now i could be wrong, but isn't this the currently coded in way of loading the plans. I.e. any time the component mounts make a request to retrieve the plans and then render them.

**Comment by moshthepitt** [comment]
@p-netm that is true.  My concern is with the Redux store.  i.e. once you go to the list page, a number of plans are put into the redux store for plans.  When you then load the single FI page, these plans should still be maintained so that when you come back to that list page, the Redux store is not empty and the page can be rendered right away.  

It should not matter that we are doing fetch requests every single time i.e. we should first render what is in the Redux store as we wait for the async fetch request to finish.

**Comment by moshthepitt** [comment]
While working on another reducer, I noticed that after [adding this kind of test](https://github.com/onaio/reveal-frontend/pull/305/commits/331e81a47d1783bfae194876bfd59619d97b968b), I had to make [this change to the dux module](https://github.com/onaio/reveal-frontend/pull/305/commits/c463757b8ffac0c965514a0d657754bf51de79ba) for things to work.

**Comment by p-netm** [comment]
This makes so much sense now
