### ISSUE TITLE
PlanForm: Dynamic plan activities

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#298]
We need to make it possible to alter the activities in the PlanForm.

This means:

- ability to add new activities
- ability to remove existing activities

### Constraints

- IRS plans can only have the IRS activity
- FI plans cannot have the IRS activity

**Comment by cKellyDesign** [comment]
@mberg @craigappl how soon is this feature required?

**Comment by moshthepitt** [comment]
It's not a lot of work actually!  The biggest issue is the design but I'll implement by Thursday next week and then if we need to redesign we'll do so

**Comment by cKellyDesign** [comment]
@moshthepitt is this adequately scoped?

**Comment by moshthepitt** [comment]
Nope.  But I have enough to work with
