### ISSUE TITLE
IRS Planning Save Draft/Finalized Confirmation UI

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#308]
Currently there is no way to visually confirm when a Plan is saved as a Draft or as a Finalized Plan \. We need to add:

- [ ] Confirmation of success (popup modal? alert banner?)
- [ ] Warning of failure (popup modal? alert banner?)
- [ ] Re-direct on confirmation of successful save from OpenSRP

**Comment by moshthepitt** [comment]
The notifications of success/failure will probably be fixed after https://github.com/onaio/reveal-frontend/issues/300

**Comment by cKellyDesign** [comment]
Closing this as it will be addressed in #300
