### ISSUE TITLE
Mark as complete for FI plan does not work

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#310]
Marking a plan as complete does not work.

This needs to update the plan and change the status to complete.

<img width="1165" alt="Screen Shot 2019-08-07 at 8 37 36 PM" src="https://user-images.githubusercontent.com/57921/62667068-0b54a980-b954-11e9-9b23-dd1090f5729c.png">

**Comment by cKellyDesign** [comment]
Requirements for this interaction:

1. Technically needs to create a plan
2. Technically needs to verify success of `1`
3. Visually needs to indicate status of `1` and `2`
4. Feature: include a note?

@mberg @craigappl @moshthepitt - am I missing anything?

**Comment by moshthepitt** [comment]
@cKellyDesign it does not need to create a plan.  It needs to edit an existing plan and change its status to "complete".  Moreover, it needs to include the note as per #171

**Comment by cKellyDesign** [comment]
> it does not need to create a plan. It needs to edit an existing plan

Doh, of course!

**Comment by p-netm** [comment]
__Proposal__:
- Add a click handler to the Mark as complete button
- write an action Handler that takes the plan prop:
    - Make an Patch/Post call with plan status as complete
    - Dispatch a clone of the plan with only change being plan_status set to complete

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/361
