### ISSUE TITLE
Saving IRS Draft and Save Finalized plan doesn't work

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#312]
Neither of these work

<img width="1170" alt="Screen Shot 2019-08-07 at 9 46 29 PM" src="https://user-images.githubusercontent.com/57921/62669305-1cee7f00-b95d-11e9-965f-b280c9f868d8.png">

**Comment by cKellyDesign** [comment]
@mberg investigating this now, did the test from this image get updated in the backend? When loading the IRS plans list page I'm seeing `Pierre3` as active.

**Comment by cKellyDesign** [comment]
@mberg when testing locally both buttons are working to save the plan as a draft and then as finalized. Will test on staging now.

**Comment by cKellyDesign** [comment]
As per conversation with @mberg updates to the plan are not being saved when clicking the buttons, am investigating this.

**Comment by cKellyDesign** [comment]
As of version `v0.1.3` both buttons are working and correctly POST/PUTing to the OpenSRP server with updated Jurisdictions, version numbers, and status.
