### ISSUE TITLE
IRS Planning - Jurisdiction Selection Map Styling

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#318]
A few more interactions need to be flushed out:

- [x] Loading an existing draft should have selection `fill-color` stops generated on load
- [x] Toggling the `Toggle All` checkbox in the drilldown table should update the selection `fill-color` stops
- [x] When drilled down, `Toggle All` checkbox should only descendant Jurisdiction selections

**Comment by moshthepitt** [comment]
Fixed by #319
