### ISSUE TITLE
Investigate why test slow down on CI

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/reveal-frontend#322]
Investigate why tests slow down drastically from commit: ec55906f, causing build and test jobs in circle-ci to timeout. We resorted to: `jest --runInBand` from here: https://jestjs.io/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server ; that improves speed by running tests sequencially

**Comment by moshthepitt** [comment]
One reason is the existence of giant snapshots

**Comment by cKellyDesign** [comment]
Closing this issue, snapshot reduction can be tracked in individual tickets.
