### ISSUE TITLE
Fix Warning: An update to PlanDefinitionList was not wrapped in act

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/reveal-frontend#336]
```console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: An update to PlanDefinitionList inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in PlanDefinitionList (at tests/index.test.tsx:37)
          in Router (created by WrapperComponent)
          in WrapperComponent
    console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
          in PlanDefinitionList (at tests/index.test.tsx:37)
          in Router (created by WrapperComponent)
          in WrapperComponent
```

**Comment by FrankApiyo** [comment]
I've attempted to wrap the rendering on PlanDefinitionList in this test in act from 'react-dom/test-utils'.  as the warning recommends. That didn't work. The second error says it can be fixed by cancelling all subscriptions and asynchronous tasks. The only asynchronous task I could find in the `PlanDefinitionList` component is this: https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/PlanDefinitionList/index.tsx#L57. which uses fetch. Fetch is mocked in this test: so that should not be the problem too; https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/PlanDefinitionList/tests/index.test.tsx#L10. Finally I also updated react to version 16.9.0 after reading this issue: https://github.com/facebook/react/issues/15379

**Comment by moshthepitt** [comment]
I would wait on this issue.  React 16.9 will be officially released soon and it will probably be easier to fix this there.

**Comment by p-netm** [comment]
> I would wait on this issue. React 16.9 will be officially released soon and it will probably be easier to fix this there.

@moshthepitt 
React-version is now 16.13.1, it includes an async act which is hopefully what we require to address this test errors.

**Comment by moshthepitt** [comment]
Thank you @p-netm.  Could you pick up one of the smaller tests that has this and see if you can resolve the issue in that test?

**Comment by moshthepitt** [comment]
Seems this is fixed.  Please re-open if not.
