### ISSUE TITLE
Number of structures in IRS Jurisdiction Plan Table 

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#339]
The IRS Jurisdiction Selection drill-down-table needs an column for number of structures.

### Requirements
- [ ] 1. Create Superset slice for number of structures per jurisdiction (or add column to existing query, @moshthepitt thoughts on this?)
    - [ ] Administrative non-operational-area jurisidctions should `SUM` the structure counts of their descendant operational-areas
- [ ] 2. Join the Superset slice response data to the tileset in the Gisida layer
- [ ] 3. Show number of structures
- [ ] 4. Add column in drill-down-table with: 
    - [ ] column header: `# of Structrues`
    - [ ] row value: integer for number of structures

### Timelines
@mberg @craigappl - Can we push back on this for now since we are just now scoping this and we don't have actual number-of-structures data?

**Comment by moshthepitt** [comment]
> The IRS Jurisdiction Selection drill-down-table needs an column for number of structures.

Sorry, could we document why this is needed? @mberg @craigappl

**Comment by moshthepitt** [comment]
@cKellyDesign I think this one was taken off the table and can be closed?

**Comment by cKellyDesign** [comment]
> I think this one was taken off the table and can be closed?
