### ISSUE TITLE
Add Number of Structures to Plan Definition

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#340]
According Slack convo in #reveal [starting here](https://onaio.slack.com/archives/CBSU8L2SC/p1565796619058600) the number of structures in Jurisdictions associated with a Plan needs to be saved to the Plan Definition as activity goals.

### Requirements
- [ ] 1. PlanForm should save IRS plan with `0` structures
- [ ] 2. IRS Jurisdiction Selection should save IRS plan with calculated number of structures based on selected jurisdictions (blocked by #339 )
- [ ] 3. Set number of structures for `Plan.goals.target.detail.value`? (schema: https://github.com/onaio/reveal-frontend/issues/188#issuecomment-511298511)

### Scoping Needed
3a. Is `Plan.goals.target.detail.value` the correct place to set this value?
3b. For which types of goals need to be set in this way?

### Timelines
@mberg @craigappl - Can we push back on this for now since we are just now scoping this and we don't have actual number-of-structures data?

**Comment by moshthepitt** [comment]
@cKellyDesign I think this one was taken off the table and can be closed?

**Comment by cKellyDesign** [comment]
> I think this one was taken off the table and can be closed?

Yup!
