### ISSUE TITLE
Reveal frontend styling update goals

### ISSUE THREAD

**Issue by rowo** [onaio/reveal-frontend#343]
@mberg brought up a project to update the design for Reveal. Anyone and everyone, please comment here on anything that's been bothering you in terms of UI/UX.

The goals for the design refresh, in order of priority, are:

1.  Add visual polish
2. Update existing quirky functionality to be more user-friendly based on internal, partner and user feedback
3. Stylistically theme the UI for Reveal brand (it should not match OpenSRP Web branding) — See: [Reveal brochure site](https://revealprecision.com/) for extent of Reveal brand look. Will reach out to Akros if they have anything else (but I think nothing exists for translating branding to UI)

We need further inputs around timeline, scope and resourcing. However for now, @OluwatobiMayowa and I are going to be reviewing where the project is and create a project brief doc with more specifics.

**Comment by moshthepitt** [comment]
Thank you @rowo for setting this up.  These are what bother me the most:

- Could we look at making the site wider
- The plan form is a really long form, how can we make the UI/UX better here
- The FI map view - how can we:
    - make it better looking
    - make it more similar to how the mobile app map works
- The FI profile view
- The FI list views

**Comment by moshthepitt** [comment]
- mSpray reporting

**Comment by OluwatobiMayowa** [comment]
@moshthepitt Please these credentials do not load up the site after several attempts. Can you please help look into this:

https://reveal-stage.smartregister.org/opensrp/login.jsp
superset-user
Va[(sQVU&#RNA376

**Comment by OluwatobiMayowa** [comment]
https://docs.google.com/document/d/1UxzWLJOImxCqHg8gg4bDiTTEFXC9pPb13cakVhNgqgI/edit#

**Comment by cKellyDesign** [comment]
Closing this issue as the initial discussion was had and subsequent work will be tracked in individual tickets.
