### ISSUE TITLE
Debug Focus Area Profile Page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#345]
This page seems to have a number of problems that we need to investigate:

- [x] The map sometimes loads, sometimes does not load and sometimes loads then starts reloading
- [x] The list of focus areas on this page should be filtered by the focus area (jurisdiction) id.  This is not the case
- Some of the queries sent to Superset result in weird 400 errors (see #350)

![focus area](https://user-images.githubusercontent.com/372073/63078040-e3140e80-bf42-11e9-8e55-ded9d29649e3.png)

**Comment by moshthepitt** [comment]
This is an example of a "bad request": `https://superset.reveal-stage.smartregister.org/superset/slice_json/460?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22ce135203-681d-4e9a-92f0-b75919b88e08%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:3000}` - in this case the plan id sent does not seem to exist

**Comment by cKellyDesign** [comment]
@moshthepitt it looks like the [plan exists](https://reveal-stage.smartregister.org/opensrp/rest/plans/ce135203-681d-4e9a-92f0-b75919b88e08), it's the goals/tasks which don't exist for the plan Id. [In this case](https://superset.reveal-stage.smartregister.org/superset/slice_json/460?form_data={"adhoc_filters":[{"clause":"WHERE","expressionType":"SIMPLE","comparator":"ce135203-681d-4e9a-92f0-b75919b88e08","operator":"==","subject":"plan_id"}],"row_limit":3000}) there are no results for tasks with this plan_id. Seems like the issue around `bad request` is that we need error handling for cases of `no-data` being returned from superset.

**Comment by moshthepitt** [comment]
> @moshthepitt it looks like the [plan exists](https://reveal-stage.smartregister.org/opensrp/rest/plans/ce135203-681d-4e9a-92f0-b75919b88e08), it's the goals/tasks which don't exist for the plan Id. [In this case](https://superset.reveal-stage.smartregister.org/superset/slice_json/460?form_data=%7B%22adhoc_filters%22:%5B%7B%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22ce135203-681d-4e9a-92f0-b75919b88e08%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22%7D%5D,%22row_limit%22:3000%7D) there are no results for tasks with this plan_id. Seems like the issue around `bad request` is that we need error handling for cases of `no-data` being returned from superset.

Makes sense!

**Comment by cKellyDesign** [comment]
@moshthepitt @kahama94 - It appears the Focus Area profile view is re-requesting jurisdiction geojson on subsequent renderings of the same foucs area, which finishes after the component mounts, causing new props to be passed to the mounted/rendered GisidaWrapper with `null` for `geoData`, which then **passes** [this conditional](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L218) in `componentWillReceiveProps` but then fails to actually `getLocations` and `initMap`, thus rendering the spinner again.

We can add a condition to check if `nextProps.geoData !== null` for a quick fix, but am still trying to figure out why the parent container is passing `null` to the GisidaWrapper in the first place.

**Comment by moshthepitt** [comment]
@kahama94 any thoughts on this?

**Comment by cKellyDesign** [comment]
@moshthepitt @kahama94 - It appears the Focus Area profile view is re-requesting jurisdiction geojson on subsequent renderings of the same foucs area, which finishes after the component mounts, causing new props to be passed to the mounted/rendered GisidaWrapper with `geoData`, which then **passes** [this conditional](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L218) in `componentWillReceiveProps`, which then tells GisidaWrapper [to reset locations](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L226), which then [updates the state](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L315), but then [this conditional](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L239-L250) in `componentDidUpdate` **doesn't pass**, thus never [calling initMap](https://github.com/onaio/reveal-frontend/blob/master/src/components/GisidaWrapper/index.tsx#L256) again.

Ultimately there are many things we can do to improve / fix this the right way which are largely covered in other tickets, and there's a simple fix we can do here to prevent the bug right now:
- [ ] don't compare complex `objects` with `===`, `stringify` instead

**Comment by cKellyDesign** [comment]
@moshthepitt was there a specific use-case or pattern you saw the Map not rendering at all? For me it is always rendering at least once before "un-rendering" (to show the spinner).

**Comment by cKellyDesign** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/349
