### ISSUE TITLE
Add support for new PlanDefinition useContext object

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#355]
```ts
{
  "code": "taskGenerationStatus",
  "valueCodableConcept": "False"
}
```

This one is used to track whether a plan has had tasks generated or not.

**Comment by moshthepitt** [comment]
@craigappl could we please make this a true boolean type instead of a string?  JSON has support for bool values.

See: https://www.w3schools.com/js/js_json_datatypes.asp

**Comment by cKellyDesign** [comment]
Let's punt this to `w35` since it just came up a few days ago. @craigappl @mberg is this ok?

**Comment by craigappl** [comment]
We can't do this because FHIR doesn't support using boolean types in the useContext field

**Comment by moshthepitt** [comment]
@craigappl thanks
