### ISSUE TITLE
Add updated/created plan to Redux store optimistically

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#357]
Add the plan definition object that was just created/updated to the redux store optimistically so that we dont have to wait for it to be pulled from the OpenSRP server.

**Comment by moshthepitt** [comment]
Implementation plan:

1. Add `addPlanDefinition` action creator as a prop to PlanForm
2. Use it to update store with the plan definition object in the PlanForm payload once plan is created/updated successfully

**Comment by cKellyDesign** [comment]
One thing is that pulling the Plan Definition from OpenSRP is a good way to determine that it, in fact, was successfully added to OpenSRP. Maybe that's less relevant for `PUT`ing (vs `POST`ing). Thoughts?

**Comment by moshthepitt** [comment]
Yeah it is definitely a trade-off where we assume that if we get a 201/200 from OpenSRP then the plan was created/updated and we don't have to wait to pull it, and can show something to the user straight away.

**Comment by cKellyDesign** [comment]
>Implementation plan:
>1. Add addPlanDefinition action creator as a prop to PlanForm
>2. Use it to update store with the plan definition object in the PlanForm payload once plan is created/updated successfully

3. Navigate to FI Map Active view and load newly minted Plan(**!**)

(**!**) Most certainly the tasks for this Plan will not be available yet, so we should probably show a pending status of sorts if no tasks are found for a given Plan/Activity/Goal (needs ticket)

**Comment by cKellyDesign** [comment]
@moshthepitt, how might we extract enough to add a `Plan` to the store?
```
/** Plan - interface for plan[-jurisdiction] objects */
export interface Plan extends PlanRecord {
  jurisdiction_depth: number;
  jurisdiction_id: string;
  jurisdiction_name: string;
  jurisdiction_name_path: string[];
  jurisdiction_parent_id: string;
  jurisdiction_path: string[];
}
```

**Comment by cKellyDesign** [comment]
We have an `extractPlanRecordFromPlanPayload` function, but we either need a `extractPlanFromPlanPayload` or an `extractPlanFromPlanResponseAndPlanPayload`, either way I'm not sure how to define the required props here.

**Comment by cKellyDesign** [comment]
Seems like we would have to fetch the Jurisdiction(s) first, then pass that in along with the Plan Definition (`payload`). Without this I don't think we can load the Map page right away.

**Comment by moshthepitt** [comment]
@cKellyDesign I think the work on your branch https://github.com/onaio/reveal-frontend/compare/357-optomistic-synchronisity seems like it would work, no?

> Seems like we would have to fetch the Jurisdiction(s) first, then pass that in along with the Plan Definition (payload). Without this I don't think we can load the Map page right away.

I think the idea for me is to have the new/updated plan definition in the Redux store so that when you next attempt to view the list of plans on the manage page, this plan is already there, optimistically.  Of course that page will then make a call to OpenSRP to load the "real" plan but this shouldn't affect the user at all - he/she will have seen the plan (and possibly clicked to view it) already.

Were you talking about the IRS page?

**Comment by moshthepitt** [comment]
Superseded by https://github.com/onaio/reveal-frontend/issues/1020
