### ISSUE TITLE
Add tests for GisidaWrapper geoData

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#362]
We need to add better tests for the GisidaWrapper component, including (but not limited to) making sure the GisidaWrapper only updates its state when `nextProps.geoData` is actually different than `this.props.geoData`.

**Comment by moshthepitt** [comment]
This is no longer necessary as we'll be [getting rid of GisidaWrapper](https://github.com/onaio/reveal-frontend/issues/1150) instead.
