### ISSUE TITLE
Show jurisdiction names in FI Edit page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#372]
![show names](https://user-images.githubusercontent.com/372073/63248031-233efe00-c26f-11e9-9c60-ac852d5a957b.png)

Currently we are showing only jurisdiction identifiers when editting existing plans instead of jurisdiction names.

This is because the plan definition objects do not have a reference to the jurisdiction names.  However showing jurisdiction ids does not really convey usable information to the user.  We should fix this.

### Ideas on how to fix

We could have an async process that goes through the jurisdictions and quietly replaces the jurisdiction id with the jurisdiction name.  This process should be non-blocking i.e. it should not block or delay the page from loading and should only start after the `UpdatePlan` component has fully mounted.

**Comment by moshthepitt** [comment]
### Considerations

- We don't want to hit the OpenSRP API too many times all at once
- We definitely do not want to get the geojson of any of these jurisdictions
- It would be nice to be able to get more than one jurisdiction object at a time

**Comment by cKellyDesign** [comment]
@moshthepitt Agreed it, we need to show names instead of IDs and we should fetch the data in a non-blocking way. How do you feel about using the superset Jurisdictions slice with a filter to get the info for all relevant jurisdictions at once?

**Comment by moshthepitt** [comment]
@cKellyDesign I was hoping we could use the OpenSRP API hence why I created this issue https://github.com/OpenSRP/opensrp-server-web/issues/97 - with my thought process being that this should not have a dependency on Superset (thinking that this is an OpenSRP thing that may be part of OpenSRP web some day and may be deployed when Superset is not).  Thoughts?

**Comment by cKellyDesign** [comment]
Oooh sawa, yes with https://github.com/OpenSRP/opensrp-server-web/issues/97 this would work well with only OpenSRP.

**Comment by cKellyDesign** [comment]
Closing this issue, continuing tracking in: https://github.com/onaio/reveal-frontend/issues/417
