### ISSUE TITLE
IRS Indicators Scoping

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#381]
It seems that we need the following IRS indicators:

- structuresTargeted
- structuresFound
- structuresSprayed
- targetCoverage
- foundCoverage
- householdsNotAccessible
- refusalsFirst
- refusalsMopup
- lockedFirst
- lockedMopup

Each of these needs to be scoped i.e. in Reveal, where do you get the numbers for these indicators, and how do you calculate them?

Helpful doc: https://docs.google.com/spreadsheets/d/1-F9exjuVo6qZ6YuQW8NLKLuysjTyIb4IPKEWOQL4RjQ/edit#gid=744478914

**Comment by moshthepitt** [comment]
This is part of #192

**Comment by moshthepitt** [comment]
- **structuresTargeted** ='total structures targeted' as per shapefile or csv
- **structuresFound** =sum(nSprayableTotal)
- **structuresSprayed** =sum(ifnull(nSprayedTotalFirst,0)) + ifnull(nSprayedTotalMop,0))
- **targetCoverage** =structuresSprayed/structuresTargeted
- **foundCoverage** =structuresSprayed/structuresFound
- **householdsNotAccessible** =sum(case when householdAccessible = 'No' then 1 else 0) 
- **refusalsFirst** =sum(case when unsprayedReasonFirst = 'Refused' then 1 else 0) /structuresFound
- **refusalsMopup** =sum(case when unsprayedReasonFirst = 'Locked' then 1 else 0) /structuresFound
- **lockedFirst** =sum(case when unsprayedReasonMop = 'Refused' then 1 else 0) /structuresFound
- **lockedMopup** =sum(case when unsprayedReasonMop = 'Locked' then 1 else 0) /structuresFound

This is from: https://docs.google.com/spreadsheets/d/1-F9exjuVo6qZ6YuQW8NLKLuysjTyIb4IPKEWOQL4RjQ/edit#gid=744478914

**Comment by moshthepitt** [comment]
For comparison, this is how the indicators were calculated in mSpray: https://github.com/onaio/mspray/blob/docs/docs/irs.md

**Comment by moshthepitt** [comment]
### Differences with mSpray

- **New Structures**: this was included in mSpray calculations.  Could we confirm that it is now not required?
- **Sprayed duplicate**: this was included in mSpray calculations.  Could we confirm that it is now not required?
- **structuresFound**: in mSpray this was calculated to include `Sprayed duplicates`.  Can we confirm that this has now changed?
- **structuresSprayed**: in mSpray this was calculated to include `Sprayed duplicates`.  Can we confirm that this has now changed?
- **Spray Effectiveness**: it seems that this indicator is not present in Reveal requirements.  Can we confirm that it is not required?

@mberg @rowo @craigappl can you confirm the above please?

**Comment by craigappl** [comment]
@moshthepitt , These indicators are for the Namibia project as the first customer of IRS. Zambia will likely have a different way of calculating these indicators, so we should be able to define these calculations separately for different countries. Note that Zambia indicators will likely come in Mid September. Also note that each country will have different spray forms.

1) New Structures are not required. The Namibia team only wants to count spray form submissions, not form submissions that add new structures. However, we need to display those locations that do not have a spray form submission in the map view.
2) Sprayed Duplicate: Duplicate spray forms are different in Reveal. Reveal has the capability to submit multiple spray forms and we use this for mop-up in Namibia. In this case we will not calculate duplicates. We will perform all calculations on the last form that was saved in the Android client, regardless of the android client that it was saved on. I think this is the "end" field on the spray form. It's definitely NOT the serverVersion.
3) structuresFound: We will not include sprayed duplicates for Namibia
4) structuresSprayed: We will not include sprayed duplicates for Namibia
5) Spray Effectiveness: We should add this calculation in. It's valuable and not covered. See the row added to the Namibia spreadsheet https://docs.google.com/spreadsheets/d/1-F9exjuVo6qZ6YuQW8NLKLuysjTyIb4IPKEWOQL4RjQ/edit#gid=744478914&range=A12
6) Pierre added another Indicator called householdsNotAccessible. Please view it at https://docs.google.com/spreadsheets/d/1-F9exjuVo6qZ6YuQW8NLKLuysjTyIb4IPKEWOQL4RjQ/edit#gid=744478914&range=A7

**Comment by moshthepitt** [comment]
### Notes to self

- **sprayEffectiveness** =structuresSprayed/(COUNT(locations that were added, but no spray form was submitted)+householdsNotAcessible+structuresFound)

**Comment by moshthepitt** [comment]
@craigappl thanks.  Will ping you should I have further questions.

**Comment by moshthepitt** [comment]
@craigappl how do you determine this "locations that were added, but no spray form was submitted"?

**Comment by craigappl** [comment]
@moshthepitt , Namibia doesn't want those to show up in the drilldown tables. They will display as yellow in the map view.
