### ISSUE TITLE
IRS Reporting pages web UI

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#382]
There are some dashboard mockups here https://smartregister.atlassian.net/wiki/spaces/REV/pages/1152516110/IRS+Forms+and+Web+UI+Dashboards+Namibia

We need to scope how exactly to come up with these dashboards in Reveal.

**Comment by moshthepitt** [comment]
This is part of #192

**Comment by cKellyDesign** [comment]
It is not at all clear to me what we are supposed to build for IRS reporting based on the link in the description.

@mberg @craigappl - What is the timeline on this and please provide mockups before scoping.

cc @rowo @moshthepitt

**Comment by mberg** [comment]
@rowo please see this issue

https://smartregister.atlassian.net/wiki/spaces/REV/pages/1152516110/IRS+Forms+and+Web+UI+Dashboards+Namibia

It has what the table should look like.  this is in reveal powered by superset.  It's supposed to work very similar to how mspray dashboards currently work (minus for now some of the higher level map aggregation views)

**Comment by rowo** [comment]
Navigation is a bit unrefined. Need new IRS reporting item. Maybe just use FI one and see what's different. Need to resolve conflict between old nav organized by FI and IRS vs. planning and reporting.

So new views similar to FI and apply to IRS. We only had planning before and that was pusehd to mSpray. Now it's going to live here in Reveal.

**Comment by cKellyDesign** [comment]
Marking this as in progress b/c Roger is working on Mockups

**Comment by rowo** [comment]
@mberg can you review?

Few questions:
- Are these all housed within a single IRS plan? 
- Is the user supposed to be able to navigate to other IRS plans from previous years or see any of that information?
- Is there an individual village page or is that just the map since we're only looking at the current IRS plan and don't need to see past IRS in that area?

### All Districts i.e. National

![IRS - all districts](https://user-images.githubusercontent.com/1584163/64225563-e9463c80-cea9-11e9-8b33-768b947cb470.png)

### Single District

![IRS - single district](https://user-images.githubusercontent.com/1584163/64225682-6ec9ec80-ceaa-11e9-8fcc-017117f3b088.png)

### Village Map

![IRS - village map](https://user-images.githubusercontent.com/1584163/64225856-2f4fd000-ceab-11e9-8626-2d87e666c398.png)

### District Map

![IRS - district map](https://user-images.githubusercontent.com/1584163/64225861-31b22a00-ceab-11e9-861c-fbcf48cb0a97.png)

**Comment by moshthepitt** [comment]
@rowo I can take this one:

> Are these all housed within a single IRS plan?

Yes they are.

**Comment by moshthepitt** [comment]
@rowo 

Could you please explain what this one is showing?

![IRS - district map](https://user-images.githubusercontent.com/1584163/64225861-31b22a00-ceab-11e9-861c-fbcf48cb0a97.png)

**Comment by mberg** [comment]
> @rowo
> 
> Could you please explain what this one is showing?
> 
> ![IRS - district map](https://user-images.githubusercontent.com/1584163/64225861-31b22a00-ceab-11e9-861c-fbcf48cb0a97.png)

Legend on this doesn't make sense.  The colors relate to spray status not a percentage of target coverage.  What's missing is some of the other spray indicators that are in the dashboard. They need to be listed on this page.

**Comment by rowo** [comment]
@mberg @moshthepitt The district map is what they described in that atlassian issue:

![Untitled-1](https://user-images.githubusercontent.com/1584163/64265540-18d46380-cf01-11e9-9329-76cb1e1867f6.png)

**Comment by moshthepitt** [comment]
> The district map is what they described in that atlassian issue (see below). There are maps for the district (or higher level areas) and for the individual villages. So the one with the big shapes are for showing district shapes with target coverage values.

@rowo so that is kind of like this page, https://macepa.mspray.onalabs.org/456/456 or this one https://macepa.mspray.onalabs.org/456/480 (basically a drill down of the previous link) right?  If so, we'll replace the squares in the mockup with actual shape of the villages/areas, yes?

**Comment by mberg** [comment]
We don't need maps at this point above the spray area.  For the data above summary tables suffice.  We had summary maps in mSpray but we don't need those right now.  We can tackle that in a second phase.

It's basically a two level drill down one of provinces. Then of spray areas or villages.  For each spray area or village, you can drill down to the map view.

So in summary, we have 2 summary levels.  One is districts the other is spray areas for that district.  Clicking on the spray area takes you to the map for that area.

**Comment by mberg** [comment]
To clarify again we don't need aggregate map views for now.  Just the data tables and map view for the final one.

@rowo each drill down will be by plan.  So we might want to be able to eventually allow you to view different plans (past seasons) for a specific location.  We don't need to worry about that for this phase of work though.

**Comment by cKellyDesign** [comment]
> It's basically a two level drill down one of provinces. Then of spray areas or villages. For each spray area or village, you can drill down to the map view.

@mberg - Cool I like this approach, I do think it should be a 3 level drill-down (`Province`, `District`, `Village`/`SprayArea`) because that is how the location tree is structured in OpenSRP.

@moshthepitt @rowo - some navigation implications (correct me if I miss something):
1. We have a page of active IRS Plans as a simple flat table (without indicators?)
2. User clicks a Plan, navigates to a page with a three level drilldown with indicators
3. User drills down to `Village`/`SprayArea` which has a link to a map view (like FI)
4. User navigates to an IRS Monitoring plan map view at the `Village`/`SprayArea` level (like FI)
5. We have a sidebar on the Map showing indicators for that `Village`/`SprayArea` (like FI)
6. User clicks on indicators in the sidebar to show layers on the map (or will layers be static?)
6. We have a button in the sidebar to Mark an IRS Plan as Complete (like FI)

**Comment by moshthepitt** [comment]
> User clicks on indicators in the sidebar to show layers on the map (or will layers be static?)

In the mSpray implementation one was able to filter the structures by clicking on the sidebar e.g. view only sprayed structures etc

**Comment by rowo** [comment]
@mberg Here's an update for you to review. @cKellyDesign I think for v1 based on what Matt wrote, I don't think we have 1 and 3 from your list.

![IRS - all provinces](https://user-images.githubusercontent.com/1584163/64285709-176b6100-cf2a-11e9-820c-0bfe6d880e6a.png)

![IRS - single province](https://user-images.githubusercontent.com/1584163/64285718-19352480-cf2a-11e9-9c48-4c2564330f56.png)

![IRS - single district](https://user-images.githubusercontent.com/1584163/64285725-1c301500-cf2a-11e9-9f6a-57be4a52e2d5.png)

![IRS - village map](https://user-images.githubusercontent.com/1584163/64285729-1e926f00-cf2a-11e9-8198-a3a3b478ed07.png)

**Comment by cKellyDesign** [comment]
@rowo oh ok cool, sounds like the drilldown page will just open when an active plan is opened from the existing IRS Plans List page.

**Comment by mberg** [comment]
> > It's basically a two level drill down one of provinces. Then of spray areas or villages. For each spray area or village, you can drill down to the map view.
> 
> @mberg - Cool I like this approach, I do think it should be a 3 level drill-down (`Province`, `District`, `Village`/`SprayArea`) because that is how the location tree is structured in OpenSRP.
> 
> @moshthepitt @rowo - some navigation implications (correct me if I miss something):
> 
> 1. We have a page of active IRS Plans as a simple flat table (without indicators?)
> 2. User clicks a Plan, navigates to a page with a three level drilldown with indicators
> 3. User drills down to `Village`/`SprayArea` which has a link to a map view (like FI)
> 4. User navigates to an IRS Monitoring plan map view at the `Village`/`SprayArea` level (like FI)
> 5. We have a sidebar on the Map showing indicators for that `Village`/`SprayArea` (like FI)
> 6. User clicks on indicators in the sidebar to show layers on the map (or will layers be static?)
> 7. We have a button in the sidebar to Mark an IRS Plan as Complete (like FI)

@cKellyDesign this makes sense.  We can roll up to provinces too.

**Comment by mberg** [comment]
> @rowo oh ok cool, makes sense for 1, sounds like the drilldown page will just open when an active plan is opened from the existing IRS Plans List page.
> 
> For 3, oh right, without the map, we're just drilling down through that table, then at the District level it's a list of villages/spray areas which the user can click to go to the Map View, yes?

Yes map is the bottom node of the drill downs

**Comment by mberg** [comment]
@rowo overall this looks good.  Few comments.

I @cKellyDesign idea of having the plan list being the starting points for the drill downs.  That would also be somewhat analogous to how the focus investigations currently work.   The plan views needs some work but I like this approach.

On the map view, we need a way to distinguish the primary activity indicators that are defined in the plan.  For IRS it's target coverage.  Found coverage is not defined in the plan but is a related indicator.  I would like it so any activity indicator defined in the plan always shows up on top.  We would then have sub indicators like found coverage that can be below but ideally in a different section.  We want to ensure we keep the indicator part dynamic like it is with focus investigations.

**Comment by mberg** [comment]
@rowo is the location drilldown intended to be a way to jump to a location? If so, I like the idea but we can leave it for v2

**Comment by mberg** [comment]
Filters would also be great but can be v2

**Comment by cKellyDesign** [comment]
> I @cKellyDesign idea of having the plan list being the starting points for the drill downs.

I just realized that this would take the user through `Planning > IRS Plans`
- [ ] `7` we should also route `Reporting > IRS Plans` through the same list view component, and
- [ ] `8` filter both by `draft` and `active` plan statuses (using the same functionality added by @p-netm to do this with FI)

**Comment by cKellyDesign** [comment]
- [ ] `9` add columns to Finalized plan Drilldown Table

**Comment by rowo** [comment]
@cKellyDesign @moshthepitt @mberg Here is another round of updates, including that initial "active plans" page. 

![IRS - active plans](https://user-images.githubusercontent.com/1584163/64307096-05f27b00-cf63-11e9-9afd-e291d9b12a3b.png)
- @mberg I'm assuming there's no actual "training" or "testing" plan setting, so potentially three IRS plans would show up on mobile for something like the first screen below.

![IRS - all provinces](https://user-images.githubusercontent.com/1584163/64307136-2b7f8480-cf63-11e9-92cc-24856c6d32c5.png)

![IRS - single province](https://user-images.githubusercontent.com/1584163/64307206-5f5aaa00-cf63-11e9-9a14-ad7bac5720a3.png)

![IRS - single district](https://user-images.githubusercontent.com/1584163/64307143-31756580-cf63-11e9-9da3-82ac92f7c819.png)

![IRS - village map](https://user-images.githubusercontent.com/1584163/64307252-8022ff80-cf63-11e9-9947-50016ba25164.png)
