### ISSUE TITLE
FI Planning tak1 user needs to have credentials to create plans in tak areas

### ISSUE THREAD

**Issue by anniecmartin** [onaio/reveal-frontend#384]
No users have access to create plans for two focus areas (Ban Khane Chu & Ban Huai Haeng) in Tak. User testing will be taking place in Tak tomorrow and we need to pre-prepare a couple of plans as well as have the ability to demonstrate ad-hoc/routine plan generation through the WebUI and down to the mobile client "on-the-fly"

Ideally only user tak1 needs to be able to do this.

These two areas need to be accessible in the locations selection on the FI Create Plan page:
![image](https://user-images.githubusercontent.com/35212108/63325336-306cf300-c32a-11e9-8082-bb0a1ae73977.png)

**Comment by moshthepitt** [comment]
Fixed this by changing the `geographicLevel` of `Tak` to `0`
