### ISSUE TITLE
Nambia IRS Sprayed Room logic

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#386]
IRS for Namibia is different then the standard IRS to date where tasks are based on known structures per operational area.

With Namibia, IRS is measured in sprayed rooms not structures sprays.  Namibia will provide for each operational a value of estimated rooms (based on estimated number of structures).  The rooms won't be calculated against enumerated structures in the operational area.

So to summarize

**Planning**
They will provide a CSV that will have the operational area name and the number of estimated rooms.

This number will be used to set the activity target for that operational area.  This is different then traditional IRS that uses the number of enumerated structures for that area.

For Namibia, we would like to add a column that shows # Rooms in the planning table.  

**Mobile & Task Creation Logic**
The task logic should work similar to larvicide or mosquito trap where you have a numeric target but don't know the location of where to put the trap.

For IRS, the workflow will be to register a household.  This will create a task to record the number of rooms sprayed.  This will be captured in a spray form that will contain a question of the number of rooms sprayed.  

Note: Please confirm if it makes sense for the task to just be of the registered structure?  That way we can know the number of households registered but no form filled out.  It should probably always be the same.  Just don't know the best way to structure the task for this.  @craigappl @githengi thoughts?

**Analysis**

We will count the room sprayed values from that form to calculate against the activity target for the plan.  So basically the spray coverage indicator = sum of rooms sprayed / estimated rooms.

**For Discussion**

We probably want to define a different type of IRS activity type in Reveal for Namibia.  

Does this work for a proposed name?

IRS Room Sprayed (No Target)

**Comment by cKellyDesign** [comment]
> With Namibia, IRS is measured in sprayed rooms not structures sprays.

This seems like a considerable departure from the current scope, what is our deadline for this?

**Comment by cKellyDesign** [comment]
> Namibia will provide for each operational a value of estimated rooms (based on estimated number of structures).

2. When will we be getting this data?
3. How will this data be structured? (so we can mock it up before they give us the real thing)

**Comment by cKellyDesign** [comment]
> This number will be used to set the activity target for that operational area.

4. By this do you mean use this number as the value for `structuresTargeted`? (see #381)
5. Are we able to use `structuresTargeted`, `structuresFound`, `structuresSprayed ` for Namibia or do we need to define other indicators?

**Comment by cKellyDesign** [comment]
> For Namibia, we would like to add a column that shows # Rooms in the planning table.

5. Since we're already relying on a superset query to get all the hierarchy information, maybe we could add the number of buildings as a column to the existing slice. Then it's baked into the data right from the source and we can just add a simple column via the DrillDown Table Props.

**Comment by cKellyDesign** [comment]
> Discussion: We probably want to define a different type of IRS activity type in Reveal for Namibia.

6. Is it a different type of IRS activity or is it a different configuration of the same type of IRS activity? The difference may seem subtle but it effects how much we hard-code into Reveal and how much we pull into configurations. Also, I don't know which would be more/less work at this point.

**Comment by mberg** [comment]
> > With Namibia, IRS is measured in sprayed rooms not structures sprays.
> 
> 1. This seems like a considerable departure from the current scope, what is our deadline for this?

**Comment by cKellyDesign** [comment]
> The task logic should work similar to larvicide or mosquito trap where you have a numeric target but don't know the location of where to put the trap.

7a. Don't the sprayers need to know where to go spray? Am I reading this correctly?

>For IRS, the workflow will be to register a household. This will create a task to record the number of rooms sprayed. This will be captured in a spray form that will contain a question of the number of rooms sprayed.

7b. When does `register a household` occur? Is it before teams are assigned to then go and spray at the household being registered?

7c. If `register a household` is happening at the same time as spraying, how do the sprayers know which households have not been registered? 

7d. Is it correct here to assume that `houshold`s roughly equate to `structures`?

**Comment by mberg** [comment]
@cKellyDesign 



2 - I've requested it.  We will get in a CSV.  We can mock it up with whatever values we want for now.  It will just be two items jurisdiction name + number.










> > With Namibia, IRS is measured in sprayed rooms not structures sprays.
> 
> 1. This seems like a considerable departure from the current scope, what is our deadline for this?

1 - Deadline - yes I understand and I apologize for that.  It follows a similar pattern to other activities so I hope that helps make it easier to implement.

We need to plan creation and android part to work by Aug 29th when they are going to field test.  Reporting can come a week or two later when IRS reporting is due.  For planning, we can potentially not make visible the number of rooms if that is too difficult. We just have to pass the value to the plan for each jurisdiction and we have to support this new type of activity in the android side.

**Comment by mberg** [comment]
For 4 - yes it's the same instead of structures it will be rooms which are linked to structures.

5 - yes that's excactly my thought. We just upload the CSV data and do a join.

6 - It's IRS but structured in a way that is different then IRS.  So we should give it a different activity name (and logic - similar to mosquito traps)

**Comment by cKellyDesign** [comment]
>  I've requested it. We will get in a CSV. We can mock it up with whatever values we want for now. It will just be two items jurisdiction name + number.

@mberg Not name, it needs to be the jurisdiction ID.

**Comment by mberg** [comment]
I can manually update the file to match when we get it

**Comment by cKellyDesign** [comment]
> I've requested it. We will get in a CSV. We can mock it up with whatever values we want for now. 

Proposed mockup method: 
- [x] Download the CSV for the [Jurisdictions slice](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22slice_id%22%3A%20471%7D)
- [ ] Add a column with arbitrary numbers for structure rooms per jurisdiction
- [ ] Upload the CSV as a static Table in superset, create static table slice
- [ ] Locally point to the new static table slice to mock live jurisdiction data and numbers for structure rooms per jurisdiction

**Comment by cKellyDesign** [comment]
Since the entire Reveal WebApp is agnostic to client country, I don't see a way of automatically choosing the `IRS by Room` activity automatically (vs the existing `IRS by Structure`), the easiest way will be for the user to simply select the correct type of `IRS` activity for their context.

@craigappl @githengi - given the additional IRS activity type `IRS by Room` (or whatever we're calling it), what changes would we need to make the [following Plan Definition](https://reveal-stage.smartregister.org/opensrp/rest/plans/7a505b36-3d34-436f-b30f-07b9ea15dfbf) to work in OpenSRP / task generation?

```
{
  identifier: '7a505b36-3d34-436f-b30f-07b9ea15dfbf',
  version: '1',
  name: 'Berg-Test',
  title: 'Berg Test',
  status: 'draft',
  date: '2019-07-01',
  effectivePeriod: {
    start: '2019-07-31',
    end: '2019-08-21',
  },
  useContext: [
    {
      code: 'taskGenerationStatus',
      valueCodableConcept: 'True',
    },
    {
      code: 'interventionType',
      valueCodableConcept: 'IRS',
    },
  ],
  jurisdiction: [
    {
      code: '674b66eb-b2aa-49b0-8635-2df5b0490aa8',
    },
    {
      code: '0d521fed-0fc0-432d-ac5d-6b6c2f5669d6',
    },
    {
      code: '786564f9-51f1-49b3-8090-a753846d494a',
    },
    {
      code: 'd63c5209-fb63-4ac9-a845-fe0c80c286d4',
    },
    {
      code: '5f47b1b1-9910-4877-a4d4-63d3af864616',
    },
    {
      code: 'fa531b26-3518-46ff-a220-cbafee181d13',
    },
    {
      code: 'd4b0c760-0711-40bc-b417-9c810184131c',
    },
    {
      code: 'd6396aeb-436d-4b78-91bd-7387ec2e8d5c',
    },
    {
      code: '35968df5-f335-44ae-8ae5-25804caa2d86',
    },
  ],
  serverVersion: 1565898994192,
  goal: [
    {
      id: 'IRS',
      description: 'Spray structures in the operational area',
      priority: 'medium-priority',
      target: [
        {
          measure: 'Percent of structures sprayed',
          detail: {
            detailQuantity: {
              value: 90,
              comparator: 'u003eu003d',
              unit: 'Percent',
            },
          },
          due: '2019-08-21',
        },
      ],
    },
  ],
  action: [
    {
      identifier: 'ea503b2d-b170-441b-af14-e2116a9b47f3',
      prefix: 7,
      title: 'Spray Structures',
      description: 'Visit each structure in the operational area and attempt to spray',
      code: 'IRS',
      timingPeriod: {
        start: '2019-07-31',
        end: '2019-08-21',
      },
      reason: 'Routine',
      goalId: 'IRS',
      subjectCodableConcept: {
        text: 'Residential_Structure',
      },
      taskTemplate: 'Spray_Structures',
    },
  ],
}
```

**Comment by cKellyDesign** [comment]
10. What is the prioritization of this ticket compare to other items already scoped for https://github.com/onaio/reveal-frontend/milestone/6 ?

10a. Should this be prioritized over https://github.com/onaio/reveal-frontend/issues/236 ?
10.b Should this be prioritized over Jurisdiction Selection UI fixes ?

**Comment by mberg** [comment]
We also need to figure out a way to view the IRS map ugh

I’ll try and prioritize these tonight

**Comment by cKellyDesign** [comment]
> We also need to figure out a way to view the IRS map 

11. That will need scoping too

**Comment by mberg** [comment]
Yes. Luckily it’s similar to fi view but we need to figure out navigation
to get to it. Probably can be handled in the irs reporting drill down
tables like we currently do with mspray

**Comment by cKellyDesign** [comment]
How does jurisdiction selection change?

**Comment by cKellyDesign** [comment]
> Reporting can come a week or two later when IRS reporting is due. 

13. Didn't see this before, let's track this convo in https://github.com/onaio/reveal-frontend/issues/179

**Comment by mberg** [comment]
Closing this.  Replacing it with #388
