### ISSUE TITLE
Nambia IRS Sprayed Room logic v2

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#388]
IRS for Namibia is different then the standard IRS to date where tasks are based on known structures per operational area.

With Namibia, IRS is measured in sprayed rooms not structures sprays. Namibia will provide for each operational a value of estimated rooms (based on estimated number of structures). The rooms won't be calculated against enumerated structures in the operational area.  Rhis is different then traditional IRS that uses the number of enumerated structures for that area.

Planning

They will provide a CSV that will have the operational area name and the number of estimated rooms.

We will append a target_rooms field to the [jurisdiction table](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22datasource%22%3A%2250__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A471%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3Anull%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22100+years+ago+%3A+%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A10000%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%22id%22%2C%22geographic_level%22%2C%22parent_id%22%2C%22name%22%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%7D).   This needs to be added to both the hierarchy table which the android client downloads and also the superset slice.

To set the target for the plan we will introduce a **dynamic** property to set the target goal.  This will allow us to apply a single activity in a single plan across all jurisdictions.  To do this we will set the target quantity in the plan to equal **jurisdiction.target_rooms*.

_Planning Interface_

Will show in the jurisdiction table the number of rooms.

**Mobile Client**

The IRS app can work as it currently does.  The only difference is there will be no defined tasks linked to structures.  The user will just need to add the structure before spraying it.

When we have offline indicators in the app, we'll refer to the **jurisdiction.target_rooms** to set the target.  The numerator will be the number of sprayed rooms for the sprayed form.

**Reporting**

The target will be set using the **jurisdiction.target_rooms** property.  The numerator will be the number of sprayed rooms from the sprayed form.

**Comment by pld** [comment]
@moshthepitt @githengi what's the level of effort for this issue?

This reads like at least 3 issues combined into a single issue, can you break it down into those 3 issues and then estimate level of effort separately for those issues?

**Comment by moshthepitt** [comment]
@githengi suggested a really nice way to put the jurisdiction id in the goal targets of the plan definition object (I'll let him explain this in a comment here as he is best placed to do so).

If we go this way, the work on the Canopy/web app side will probably be:

1. Modify the flows to account for the possibility of a goal having more than one target (LOE is 1 - 2 days)
2. Modify the PlanForm component and the NewPlan and UpdatePlan components to be able to handle this new IRS activity (LOE is 2 - 3 days)

---

I have purposely not included an LOE for reporting because I think that is a completely different discussion and needs to be scoped with the rest of the IRS reporting requirements (https://github.com/onaio/reveal-frontend/issues/381 and https://github.com/onaio/reveal-frontend/issues/382).

**Comment by mberg** [comment]
Ok please share that.  I like the approach i proposed as it allows some of the properties to be a bit more dynamic.  Note: we'll need to have this in place for the data collection part by Aug 29th when they will start field testing.

**Comment by pld** [comment]
Is that timeline possible? Shouldn’t we wait until we know the size of the issues

**Comment by githengi** [comment]
The suggestion is to track the jurisdiction in the goal targets.
The FHIR plan spec allows a  goal target to have ` detailCodeableConcept` as part of a target.
![image](https://user-images.githubusercontent.com/25123762/63427263-6b9c1e80-c41d-11e9-8e4c-bcc4a6fb122f.png)

My suggestion is to tag the jurisdiction in the `detailCodeableConcept` and thus have a target for each jurisdiction per goal for IRS plans.

**Assumptions**
With this approach if `detailCodeableConcept` is missing for a target we can assume the target is global for the plan. 
This should be validated so that there is no scenario where some targets don't have `detailCodeableConcept`  while others have.

**Comment by githengi** [comment]
The level of effort for making this change is 1 day on the OpenSRP server.

**Comment by pld** [comment]
Are we OK with using that approach for now, and the more scoping and breaking down more the detailed approach so we can work it into the next milestone?

**Comment by mberg** [comment]
I’m not clear how this works.

Right now we need to have a unique value per jurisdiction.

Sam can you share how the json

**Comment by githengi** [comment]
```
{
  "id": "Case_Confirmation",
  "description": "Confirm the index case",
  "priority": "medium-priority",
  "target": [
    {
      "measure": "Number of case confirmation forms complete",
      "detail": {
        "detailQuantity": {
          "value": 1,
          "comparator": ">=",
          "unit": "form(s)"
        }
      },
      "detailCodeableConcept": {
        "text": "jurisdiction_id"
      },
      "due": "2019-05-21"
    }
  ]
}
```

**Comment by githengi** [comment]
@mberg does the above make sense

**Comment by craigappl** [comment]
@githengi , the FHIR spec means that you can do one of those three under the detail, either a quantity, a range or a detailCodableConcept. It wouldn't allow both a quantity and detailCodableConcept in the same target.

**Comment by cKellyDesign** [comment]
> Modify the PlanForm component and the NewPlan and UpdatePlan components to be able to handle this new IRS activity (LOE is 2 - 3 days)

Ticket created at https://github.com/onaio/reveal-frontend/issues/399

**Comment by cKellyDesign** [comment]
> They will provide a CSV that will have the operational area name and the number of estimated rooms. We will append a target_rooms field to the [jurisdiction table](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22datasource%22%3A%2250__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A471%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3Anull%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22100+years+ago+%3A+%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A10000%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%22id%22%2C%22geographic_level%22%2C%22parent_id%22%2C%22name%22%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%7D). This needs to be added to both the hierarchy table which the android client downloads and also the superset slice.

Ticket created at #400
