### ISSUE TITLE
Add loading indicator to IRS planning location selection

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#390]
When you click on a checkbox to select/deselect an area, there is sometimes a lag as the map updates.  We should show some kind of loading indicator.

![IRS  ,Berg IRS 2 Namibia (draft) _ Reveal](https://user-images.githubusercontent.com/372073/63422169-8e750580-c412-11e9-88cd-8b06cdd9e160.png)

**Comment by mberg** [comment]
@cKellyDesign and i discussed a way to avoid this.  We'll start off the map with no areas selected which makes things a lot faster

**Comment by cKellyDesign** [comment]
Yup, got it even faster in #403! Issue was b/c we this is determining jurisdiction descendants over and over again in a not very efficient way. Sorting the array of Jurisdictions returned from the API (by `geographic_level` high to low) helps the existing function by about 2x.

Sorting affords us a new approach of defining jurisdiction descendants (~10-100x faster after some initial perf'ing) and saving `childrenByParentId` to state negates the need to redefine descendants over and over.
