### ISSUE TITLE
Add Namibia Specific IRS Business logic to PlanForm

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#399]
> Modify the PlanForm component and the NewPlan and UpdatePlan components to be able to handle this new IRS activity (LOE is 2 - 3 days)

from https://github.com/onaio/reveal-frontend/issues/388#issuecomment-523389554

- [ ] PlanForm component
- [ ] NewPlan
- [ ] UpdatePlan

**Comment by mberg** [comment]
We don't need to do these anymore as the plan definition will be the same.  We need to figure out a way to reference the structures property in the hierarchy table to calculate the denominator for Namibia.  We might want to see if that is something we define at the plan level.

**Comment by cKellyDesign** [comment]
The plan definition will be the same, this ticket is specifically for the work to `calculate the denominator` in the PlanForm pages.

> We need to figure out a way to reference the structures property in the hierarchy table...

I believe the Webapp is to get this data directly from the OpenSRP endpoint (WIP).

> ...to calculate the denominator for Namibia. We might want to see if that is something we define at the plan level.

@mberg I was under the impression this should be calculated based on the number of structures in all the Jurisdictions selected in the plan, is that correct?

**Comment by mberg** [comment]
Number of structures is not something included in the plan. The only thing in the plan is the percent of spray coverage.  eg. 85%

This is because the amount of structures will vary by jurisdiction.  

As a result, the current thinking is to not define the denominator in the plan but have it reference something external for reporting.  We currently do this for IRS now in that we are getting the number of structures from the shapefile.  The main difference is we are just going to be referring to the properties from the jurisdiction which we got from a shape file.  I created an issue on this earlier to try and summarize.  Let me know if we need to hop on a call to discuss.

**Comment by cKellyDesign** [comment]
> The only thing in the plan is the percent of spray coverage. eg. 85%

That `85%` is saved to the plan definition at `Plan.goal.target.detail.detailQuantity.value` ([example plan definition](https://reveal-stage.smartregister.org/opensrp/rest/plans/0e85c238-39c1-4cea-a926-3d89f0c98427)), which is what we're talking about calculating for each plan `because the amount of structures will vary by jurisdiction`.

So cool, not the number of structures being saved to the plan, just a metric using the number of structures.

> As a result, the current thinking is to not define the denominator in the plan but have it reference something external for reporting.

To my understanding [via this thread](https://github.com/onaio/reveal-frontend/issues/400#issuecomment-523770126), the `external reference` for reporting should also be OpenSRP / the Jurisdictions redux store, I think this is completely condusive (if not the exact same) as what you're saying with: `we are just going to be referring to the properties from the jurisdiction`.

> Let me know if we need to hop on a call to discuss.

I'm open to a call but I think we're actually on the same page!

@moshthepitt - Once we are getting number of structures from OpenSRP, will you review and see if there's anything we need to make this calculation when defining a new IRS plan?

**Comment by moshthepitt** [comment]
> Once we are getting number of structures from OpenSRP, will you review and see if there's anything we need to make this calculation when defining a new IRS plan

@cKellyDesign  will do

**Comment by cKellyDesign** [comment]
@moshthepitt are we getting the number of rooms from the custom Jurisdiction superset slices? if not then seems like we still need to upload a to superset, or just serve it as CSV from a google sheets? (to join with data from custom Jurisdiction superset slices)

**Comment by cKellyDesign** [comment]
Closing this issue because it will be addressed by #464
