### ISSUE TITLE
Add Number of Rooms Column to IRS Jurisdiction Selection

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#400]
> They will provide a CSV that will have the operational area name and the number of estimated rooms. We will append a target_rooms field to the [jurisdiction table](https://superset.reveal-stage.smartregister.org/superset/explore/?form_data=%7B%22datasource%22%3A%2250__table%22%2C%22viz_type%22%3A%22table%22%2C%22slice_id%22%3A471%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3Anull%2C%22time_grain_sqla%22%3A%22P1D%22%2C%22time_range%22%3A%22100+years+ago+%3A+%22%2C%22groupby%22%3A%5B%5D%2C%22metrics%22%3A%5B%5D%2C%22percent_metrics%22%3A%5B%5D%2C%22timeseries_limit_metric%22%3Anull%2C%22row_limit%22%3A10000%2C%22include_time%22%3Afalse%2C%22order_desc%22%3Atrue%2C%22all_columns%22%3A%5B%22id%22%2C%22geographic_level%22%2C%22parent_id%22%2C%22name%22%5D%2C%22order_by_cols%22%3A%5B%5D%2C%22adhoc_filters%22%3A%5B%5D%2C%22table_timestamp_format%22%3A%22%25Y-%25m-%25d+%25H%3A%25M%3A%25S%22%2C%22page_length%22%3A0%2C%22include_search%22%3Afalse%2C%22table_filter%22%3Afalse%2C%22align_pn%22%3Afalse%2C%22color_pn%22%3Atrue%7D). This needs to be added to both the hierarchy table which the android client downloads and also the superset slice.

- [ ] 1. Load provided CSV into OpenSRP new `locations` table column
- [ ] 2. Load Jurisdiction Hierarchy from OpenSRP
- [ ] 3. MOCKUP `2` and `3` via static CSV upload
- [ ] 4. Add optional `target_structures` to Jurisdiction typings
- [ ] 5. Add `Target Structures` column to the Jurisdiction Selection Drilldown Table

**Comment by moshthepitt** [comment]
`Join new Table to Jurisdiction Table
`
Instead do this can we work with @githengi to make this into a property on the jurisdiction object in OpenSRP?

**Comment by cKellyDesign** [comment]
I thought this data was being sourced from a CSV, is the plan to upload this into Superset? Eventually it will need to be added as a column to the Jurisdiction slice so we can get all that data in a single call, right?

**Comment by moshthepitt** [comment]
I think when we get the CSV we should just find a way to add the numbers as a new property in jurisdictions

**Comment by cKellyDesign** [comment]
Was hoping to get this data all at once [from this request](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L239-L250) when loading the Jurisdiction Selection page. Though I wouldn't mind switching from this superset slice call to an opensrp call, it's just that [the OpenSRP locations call](https://reveal-stage.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=true&return_geometry=false) only returns 1000 rows.

**Comment by cKellyDesign** [comment]
Though if we are progressively loading Jurisdictions then this would be less of a problem, we just need the whole location tree (or at least the whole location tree for Namibia) as we load the Jurisdiction Selection page.

**Comment by cKellyDesign** [comment]
@githengi thought on this? ☝️

**Comment by moshthepitt** [comment]
I'm thinking if we can avoid a Superset dependency here it would be very very cool.  But if not then that's fine.

> Though I wouldn't mind switching from this superset slice call to an opensrp call, it's just that the OpenSRP locations call only returns 1000 rows.

@githengi how can we go around this?

**Comment by cKellyDesign** [comment]
We could break it into cascading calls, though I don't know how performant that would be:

1. [Get all level-0 Jurisdictions](https://reveal-stage.smartregister.org/opensrp/rest/location/findByProperties?is_jurisdiction=true&properties_filter=geographicLevel:0&return_geometry=false)
2. Get all children of all level-0 jurisdictions (11 requests)
3. Repeat until we have all Jurisdictions (N requests)

> 3. Repeat until we have all Jurisdictions (N requests)

N would be a lot less if we know from the beginning which level-0 Jurisdiction we need.

**Comment by moshthepitt** [comment]
@cKellyDesign curious why do we need to get absolutely ALL jurisdictions on the server all at once?

**Comment by cKellyDesign** [comment]
To map out the location tree hierarchy to populate the Jurisdiction Drilldown Table. If we could get all the descendant jurisdictions of a particular level-0 Jurisdiction I think that might be ideal.

**Comment by githengi** [comment]
> I'm thinking if we can avoid a Superset dependency here it would be very very cool. But if not then that's fine.
> 
> > Though I wouldn't mind switching from this superset slice call to an opensrp call, it's just that the OpenSRP locations call only returns 1000 rows.
> 
> @githengi how can we go around this?

We add a param to limit the number of locations returned.

Also once this implemented https://github.com/OpenSRP/opensrp-server-web/issues/90 it shall be possible to return all the descendants of a location

**Comment by moshthepitt** [comment]
> We add a param to limit the number of locations returned.

@githengi can we also use that param or do something else to get more than 1000 items returned?

**Comment by cKellyDesign** [comment]
> We add a param to limit the number of locations returned.

@githengi - what's the status of this one? if still pending that's fine, just checking in :)

**Comment by githengi** [comment]
Its still pending, we have scheduled to work on it tomorrow

**Comment by cKellyDesign** [comment]
Mockup step blocked by errors when uploading (scrubbed) client CSV, [as per slack conversation](https://onaio.slack.com/archives/C8ZNYCRFV/p1567534092026600).

**Comment by cKellyDesign** [comment]
@mberg @moshthepitt were we ever able to get the Number of Rooms CSV uploaded into Superset? (wondering if this is still blocked)

**Comment by cKellyDesign** [comment]
Closing this issue because we're getting this data from the Superset Plan-Jurisdiction slices.
