### ISSUE TITLE
IRS Jurisdiction Selection replace superset with opensrp api call

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#404]
Inspired by https://github.com/onaio/reveal-frontend/issues/400#issuecomment-523894960

The initial call to Superset slice 471 to get all Jurisdictions in the location hierarchy with a call to OpenSRP to get all descendant Jurisdictions of a given (country) Jurisdiction.

**Comment by moshthepitt** [comment]
Closed by #1003
