### ISSUE TITLE
Improvements to Focus Area Profile View

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#407]
(I don't know the name of this view)
![image](https://user-images.githubusercontent.com/6067053/63601217-dbbfb700-c579-11e9-9c56-4cf6588bbc86.png)

Issues:
- [x] (Low) The search box doesn't work
~~- [ ] (High) We need to support pagination on all tables on this screen. It's currently limited to six~~
- [ ] (Medium) (Optional) Sort each table in reverse chronological order based on startDate

**Comment by kahummer** [comment]
@moshthepitt @craigappl The current single FI view seems not to have the search box
![Screenshot from 2020-03-16 10-46-13](https://user-images.githubusercontent.com/16018123/76734331-ce675580-6773-11ea-9a88-19ce0eee1e7f.png).

**Comment by moshthepitt** [comment]
@kahama94 I removed it in #728

**Comment by moshthepitt** [comment]
I suggest you leave it removed, we had kind of agreed to remove all the search boxes that do not work for now. @kahummer
