### ISSUE TITLE
Teams Management - list Teams view.

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#408]
__Overview__
 -  Add page to list teams

**Comment by cKellyDesign** [comment]
@p-netm do you have sufficient scoping for this? Are the teams coming from OpenSRP?

**Comment by p-netm** [comment]
> do you have sufficient scoping for this? Are the teams coming from OpenSRP?

Not adequately, so i guess no. yes the teams will be coming from OpenSRP but what am not certain about is if the endpoints to be hit for retrieving the teams are ready.

**Comment by moshthepitt** [comment]
@cKellyDesign This work was just the UI.  When the API is ready, we'll probably have a different issue to connect that to the UI.
