### ISSUE TITLE
IRS Update Plan View

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#417]
<img width="919" alt="Screen Shot 2019-08-26 at 5 58 57 AM" src="https://user-images.githubusercontent.com/4141527/63706515-79b6ba00-c7e4-11e9-911d-eda3d066afaa.png">

Currently when opening an IRS plan in the `UpdatePlan` page all of the selected jurisdiction IDs are being rendered (by the thousands) and needs to be optimized (which needs scoping).

Example `Home => Manage Plans => Testaru NA 1`

### Possible Solutions
1. Move the selected Jurisdiction list/information below the other form fields
2. If only one Jurisdiction is selected, show relevant information for that Jurisdiction
3. If multiple Jurisdictions are selected, show the number of jurisdictions (and relevant aggregations?)
4. Add a button to edit the Jurisdiction Selection, which navigates to `/intervention/irs/draft/<plan_id>
5. If changes are made without saving a draft before navigating away from page, prompt user to save

I don't think we can do all of these before [User Acceptance](https://github.com/onaio/reveal-frontend/milestone/6), but maybe 1, 2, and/or 3.

@moshthepitt @mberg - Thoughts?

**Comment by moshthepitt** [comment]
Yeah this is a real nasty problem.  Maybe we should loop @rowo in to help think through this?

Also, note that it is closely related to https://github.com/onaio/reveal-frontend/issues/372

**Comment by moshthepitt** [comment]
> There can easily be thousands of selected Jurisdictions in an IRS plan, so if we do allow users to edit IRS Jurisdiction selections in this form then we should also add a search field.

> Focus investigations should update their single selected Jurisdiction via dropdown (not done), 

I'd like to note that in the initial spec, we should **not** allow editing of jurisdictions for any plan (FI or otherwise) via the PlanForm.

**Comment by moshthepitt** [comment]
> I don't exactly know what this page is (it's not in the original designed scope, right?).

@rowo This is the page that kind of morphed from your mockups here https://github.com/onaio/reveal-frontend/issues/199

**Comment by cKellyDesign** [comment]
This is no longer blocked, please:
- [ ] add `overflow-y: scroll` and `max-height: 200px` around this list

Once the page pulls data from OpenSRP and has Jurisdiction Names:
- [ ] replace id strings with names

**Comment by moshthepitt** [comment]
Finally closed by #443
