### ISSUE TITLE
IRS Team/User Performance Scoping

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#434]
If we are going to truly replace mSpray with Reveal then we need to also scope and build team/user performance tables that look and work like: https://macepa.mspray.onalabs.org/performance/

**Comment by cKellyDesign** [comment]
@moshthepitt is this topic adequately covered in other tickets / conversations? Is there more to scope that doesn't already have tickets?

**Comment by moshthepitt** [comment]
Superseded by https://github.com/onaio/reveal-frontend/issues/1068
