### ISSUE TITLE
Update and Standardize Table Design

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#442]
Currently, we have two types of tables which look a bit different and should be styled to look the same as in the mocks: https://marvelapp.com/cc83f0e/screen/61278058

### ListView Table
<img width="1047" alt="Screen Shot 2019-09-12 at 11 47 40 AM" src="https://user-images.githubusercontent.com/4141527/64811998-33d35300-d553-11e9-9b22-a3310da67734.png">

### DrillDown Table
<img width="1161" alt="Screen Shot 2019-09-12 at 11 48 41 AM" src="https://user-images.githubusercontent.com/4141527/64812055-54031200-d553-11e9-8025-857c91b7f742.png">

**Comment by cKellyDesign** [comment]
@OluwatobiMayowa the Drilldown tables are looking great across the board:

<img width="1125" alt="Screen Shot 2019-10-29 at 5 03 24 PM" src="https://user-images.githubusercontent.com/4141527/67774607-b9ad4e00-fa6e-11e9-8726-19793c4288d3.png">

If we can update the ListView table styling to match that would be really helpful for the consistency of the UI: 

<img width="1117" alt="Screen Shot 2019-10-29 at 5 03 31 PM" src="https://user-images.githubusercontent.com/4141527/67774682-dfd2ee00-fa6e-11e9-968d-8e7e44918668.png">


then we can see about deploying to staging for sign-off and getting this finally pushed to master and prod!

**Comment by oluwatobim** [comment]
Hi @cKellyDesign Seems like the second screenshot is not using ReactTable, is that right? And if so, would there be any special reason for that?

**Comment by cKellyDesign** [comment]
@oluwatobim I believe it was the developers choice to use [a different share component](https://github.com/onaio/js-tools/tree/master/packages/ElementMap), but I believe we can add more classes to the resulting table / rows to make it easier to style.

**Comment by oluwatobim** [comment]
@cKellyDesign The table design has now been updated to match the React Table.

**Comment by moshthepitt** [comment]
Looks like we are not going to do this one
