### ISSUE TITLE
Team Assignment - Search functionality on the teams listing page

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#446]
- The endpoints for search organizations are not currently ready

The idea is to have be able to search a team by name 
![search team form input](https://user-images.githubusercontent.com/28119869/65026097-88564400-d940-11e9-9373-04985487c69a.png) here

__question__: should the search be fuzzy or exact

**Comment by cKellyDesign** [comment]
@p-netm whichever is easier at this point, probably exact? 

@rowo @OluwatobiMayowa - thoughts?

**Comment by rowo** [comment]
I agree on whichever is easier, especially for team search.

**Comment by OluwatobiMayowa** [comment]
Seconded @rowo @cKellyDesign

**Comment by cKellyDesign** [comment]
@p-netm is there anything else blocking this issue?

**Comment by p-netm** [comment]
@cKellyDesign No, not at the moment, thatnks for clearing that up for me.

**Comment by p-netm** [comment]
closed by #891
