### ISSUE TITLE
Team Assignment - scoping for the  Organization listing page

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#447]
- This is about the area field in the reveal mockups for the teams list page
![area screenshot](https://user-images.githubusercontent.com/28119869/65027870-c43ed880-d943-11e9-9b39-6ad58155ddf4.png)

The concern is that we could have a lot of areas to display, one of the suggested approaches is to display the areas in a format such as `area_1 + 43`; however to ensure integrity of the count value would require extra queries one for each already displayed team

**Comment by p-netm** [comment]
The mockup to use
![organizationslistingscoping](https://user-images.githubusercontent.com/28119869/65236793-fab25a00-dae1-11e9-8821-9147f34ea11f.png)

__have fields__:
- organization name
- organization identifier

__ have not's fields__:
- count of locations
- supervisor
- Team members count

**Comment by p-netm** [comment]
- Current `organization` api endpoints only gives me a list of organizations with team name, identifier, and a few more meta data fields

- Need help with getting the locations count; i.e  the number of locations assigned to this organization, this is not returned in the response of the current `organization` endpoint
- Need help with getting the count of team Members who are part of a certain organization.
- Need help with getting the supervisor of the team, this seems like it could have been part of the organizations' object returned by the `organizations` endpoint but it isn't, unless its possible to have organizations that don't have a supervisor i suppose.
-

**Comment by pld** [comment]
We can keep this simpler for first implementation:
- 2nd bullet doesn't need to get done
- 3rd bullet doesn't need to get done
- 4th bullet doesn't need to get done

In the mock-up you should remove the following columns:
- location (these are not assigned to teams)
- supervisor, we don't need this now
- number of team members, we don't need this now

**Comment by p-netm** [comment]
ok

**Comment by moshthepitt** [comment]
@pld thanks.  I think your comments essentially mean that the organization listing page that we have right now works.  @p-netm  will work to clean up the PR for this work.

**Comment by pld** [comment]
cool, removing the blocked label

**Comment by p-netm** [comment]
closed by #462
