### ISSUE TITLE
Team - Assignment - scoping for the single Organization view

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#448]
since reveal does not have this, ill be following the opensrp-web mockup.
![single organization](https://user-images.githubusercontent.com/28119869/65028379-a3c34e00-d944-11e9-9e18-6ecc645b4176.png)

The blocker here is that we don't have ready endpoints for retrieving Team members.

**Comment by p-netm** [comment]
And Not sure if I am required to work on assigning team Members to an organization. I  haven't thought about this workflow and thus not sure if the endpoints are available, will look into it once the work is confirmed.

**Comment by mberg** [comment]
Yes this is a key aspect.  The API endpoints are there for this.

Once the organization has been created, we need to create providers (users).  These providers can then be assigned to an organization (team) which is what this page is supposed to support.


We don't need location or supervisor.

**Comment by p-netm** [comment]
Creating issues for : creating and Assigning new Team Members

**Comment by moshthepitt** [comment]
@mberg thanks, we have a way forward for this and will update you when we have something to show.
