### ISSUE TITLE
Zambia Tilesets

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#449]
Currently we need to generate tilesets based on the OpenSRP locations for Zambia similar to how we set them up for Namibia.

- [ ] Create geojson file for all OpenSRP locations
- [ ] Generate tilesets with `tippecanoe`
- [ ] Upload new tilesets to mabpbox studio
- [ ] Update Zambia tilesets configurations in `settings.ts`

**Comment by cKellyDesign** [comment]
@mberg @craigappl we still need to generate tilesets (which match the location tree in OpenSRP) for the Zambia IRS Maps. Please provide the shapefiles or geojson for the entire Zambia location tree to unblock this ticket.

**Comment by cKellyDesign** [comment]
at some point in my processing, it looks like the ids got truncated...starting them over again.
<img width="1038" alt="Screen Shot 2019-10-11 at 2 32 17 PM" src="https://user-images.githubusercontent.com/4141527/66686442-5630bd00-ec34-11e9-8ee4-8b221884dfa2.png">

**Comment by moshthepitt** [comment]
@cKellyDesign can we close this?
