### ISSUE TITLE
Correct % refusals and locked logic RVL-523

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#457]
The % refusals and locked for individual villages looks good but its wrongly aggregated for Oshana and Oshakati.

https://smartregister.atlassian.net/browse/RVL-523

I don't have enough visibility of the data to understand what is happening here wrong but if we can please check it.

**Comment by cKellyDesign** [comment]
> [from Jira ticket] From what I understand, the total can’t be more than 100%

![Capture](https://user-images.githubusercontent.com/4141527/65927726-b52e4080-e3af-11e9-847b-b1ed81844cfd.JPG)


@moshthepitt this sounds like a data aggregation issue with the slice query, looks like it's still happening in production and it's hard to say if it's happening on staging (b/c of lack of data)

**Comment by cKellyDesign** [comment]
This is done https://smartregister.atlassian.net/browse/RVL-523
