### ISSUE TITLE
Team-Assignment - Creating a Pracitioner

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#458]
Preliminary work towards assigning practitioners to a team requires a page to actually create the practitioner.

Task:
- Adding a form and a page to create practitioners

Blocker:
- Need an userId from openMRS , so as to link the the practitioner to an openMRS user.
 Will probably need a proxy on the opensrp server that helps get this data from openMRS.

**Comment by cKellyDesign** [comment]
> Need an userId from openMRS

@p-netm what is the status of this blocker?
