### ISSUE TITLE
Move type definitions out of settings.ts

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#469]
We need to move all the type definitions out of settings.ts and into something like types.ts.  This is based on the conversation here https://github.com/onaio/reveal-frontend/pull/459#discussion_r329840979

**Comment by DavisRayM** [comment]
Is this issue unassigned? I’d like to work on it

**Comment by moshthepitt** [comment]
@DavisRayM please go ahead and assign it to yourself
