### ISSUE TITLE
Make IRS reporting configs more configurable

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#471]
We need a way to define the following settings variables in a way that can work for both Namibia and Zambia on the same branch.  Perhaps we can do this the same way we did it for IRS table columns?

- sidebarIndicatorRowsIRS
- sidebarLegendStopsIRS

**Comment by moshthepitt** [comment]
Namibia IRS legend stops: https://github.com/onaio/reveal-frontend/blob/008a4db46a9de15ae172742e2e8a699053dc29d4/src/configs/settings.ts#L966

**Comment by moshthepitt** [comment]
Namibia IRS indicator rows: https://github.com/onaio/reveal-frontend/blob/008a4db46a9de15ae172742e2e8a699053dc29d4/src/configs/settings.ts#L920

**Comment by cKellyDesign** [comment]
Good call, we should set this up the same way as the `IRSTableColumns` coupled with env vars: https://github.com/onaio/reveal-frontend/blob/irs-reporting-table/src/containers/pages/IRS/JurisdictionsReport/helpers.ts#L279
