### ISSUE TITLE
IRS Map sidebar improvements

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#472]
- [x] For Namibia, Spray Coverage should be listed above Found Coverage
- [x] For Zambia, Spray Coverage should be listed above Found Coverage
- [ ] For Zambia, the not sprayed reasons and duplicate reasons should be listed similar to how it was done in mSpray e.g. https://macepa.mspray.onalabs.org/reactive/irs/chw/3106/3122 (click on target area stats top right)

**Comment by cKellyDesign** [comment]
> the not sprayed reasons and duplicate reasons should be listed

Do we have this data already coming in from the Superset slices? Also, this sounds like it will be another type of `IndicatorRow`.

**Comment by moshthepitt** [comment]
> Do we have this data already coming in from the Superset slices? Also, this sounds like it will be another type of IndicatorRow

Not yet, will have it soon

**Comment by cKellyDesign** [comment]
@rowo @OluwatobiMayowa - could we get a simple mockup incorporating a type of metric-list type of row in the sidebar:
![64307252-8022ff80-cf63-11e9-9947-50016ba25164](https://user-images.githubusercontent.com/4141527/65963224-2b15c480-e40f-11e9-98b4-b7da9be9a473.png)


To show the data from the `Not Sprayed Reasons` row:
<img width="344" alt="Screen Shot 2019-10-01 at 5 38 04 AM" src="https://user-images.githubusercontent.com/4141527/65963129-f99cf900-e40e-11e9-94a7-ed605b7b765f.png">

**Comment by rowo** [comment]
@cKellyDesign is this just a two column table (in the second image) replacing the indicator boxes in the Refusals section (in the first image)?

**Comment by cKellyDesign** [comment]
@rowo in addition I think

**Comment by rowo** [comment]
@cKellyDesign Like so?
![Group 3](https://user-images.githubusercontent.com/1584163/66010760-52f83d00-e48e-11e9-8c80-fc46d5274840.png)

**Comment by moshthepitt** [comment]
@cKellyDesign fixed some of the items in the todo list here in #478

**Comment by cKellyDesign** [comment]
@rowo like so, thanks boss

**Comment by moshthepitt** [comment]
@p-netm what is blocking this one?

**Comment by p-netm** [comment]
> @p-netm what is blocking this one?

@moshthepitt just remembered the issue for this one, seems like we don't have data from reveal staging for `zambia_focus_areas` slice. I think the data that would be displayed is got from that slice.

**Comment by moshthepitt** [comment]
@p-netm is it possible to work with fixtures made from data coming from the Zambia server?

**Comment by moshthepitt** [comment]
The remaining part of this has been superseded by https://github.com/onaio/reveal-frontend/issues/1069
