### ISSUE TITLE
Namibia target coverage bug on map

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#482]
![bugz](https://user-images.githubusercontent.com/372073/66056091-41bb3900-e53f-11e9-8432-4f00d72c1a87.png)

**Comment by moshthepitt** [comment]
The progress bar is also not colored like it should be

**Comment by cKellyDesign** [comment]
@moshthepitt in the screenshot it looks like the denominator is zero for the first row so, it's unclear what the value actually should be

**Comment by moshthepitt** [comment]
@cKellyDesign I think the thing is looking for a wrong value hence getting zero

**Comment by cKellyDesign** [comment]
This is the endpoint being called and you're right, `structurestargeted` is not one of the properties: https://superset.reveal-stage.smartregister.org/superset/slice_json/554?form_data={"adhoc_filters":[{"clause":"WHERE","expressionType":"SIMPLE","comparator":"9f9210ef-9ad3-4cb6-953e-2c9466febeac","operator":"==","subject":"jurisdiction_id"},{"clause":"WHERE","expressionType":"SIMPLE","comparator":"6807a4a9-52bf-4d0d-b4d0-50fdd86590f8","operator":"==","subject":"plan_id"}],"row_limit":1}

**Comment by moshthepitt** [comment]
oh goodness, it should be `target_2019`
