### ISSUE TITLE
Can not view Focus Investigation Plans in the web UI

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#485]
We are unable to view focus investigation plans in the web UI due to javascript consul errors that seem to be null pointers:

![image](https://user-images.githubusercontent.com/6067053/66074327-813a5300-e548-11e9-83f6-29ed38ff96aa.png)

**Comment by cKellyDesign** [comment]
@moshthepitt do you think this is similar to #491 where it's getting no-data from Superset slices?

**Comment by moshthepitt** [comment]
@cKellyDesign yes I think this has the same root cause

**Comment by moshthepitt** [comment]
This was fixed in #728
