### ISSUE TITLE
RVL-91 - Change BCC Plan Label in Form and Nifi

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#488]
The BCC Goal and Activity needs to be changed so that it shows differently in the Web UI. We need to make this change in the plan generation web form and possibly in the automatic plan generation in BIOPHICS.

Whatever is displayed in the card view on the right side of the web UI needs to say "BCC Activities Complete" I can't login right now to see what is currently displayed, but I think it is the description of the target which can be found [here](https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=1805975071&range=H154) in the data dictionary

Changes:
- [ ] Update the form in the web UI
- [ ] Update the Nifi flows that create plans from BIOPHICS if a BCC activity is added to those plans.

**Comment by moshthepitt** [comment]
@craigappl could you add details to this please, now that you can log in?

**Comment by pld** [comment]
@Wambere can you please post a link to the relevant process group for these NiFi flows

**Comment by Wambere** [comment]
This is the plan generation flow: https://nifi.reveal-stage.smartregister.org/nifi/?processGroupId=016b1018-4d92-1951-13f0-9e8c775ed64f&componentIds=016b1025-4d92-1951-16a9-ea177aac0486

There is 4 different replaceText processors, all of which have text from https://smartregister.atlassian.net/wiki/spaces/REV/pages/1143242833/Automatic+Plan+and+Task+Generation#AutomaticPlanandTaskGeneration-NifiBusinessLogictobeDeveloped

so all would need to be changed

**Comment by moshthepitt** [comment]
@craigappl @samkanga  does this still need to be done?

**Comment by kahummer** [comment]
@craigappl @moshthepitt are we talking about these views?
![Screenshot from 2020-03-16 11-08-40](https://user-images.githubusercontent.com/16018123/76735739-a0cfdb80-6776-11ea-80e3-f086be3d30a4.png)
![Screenshot from 2020-03-16 11-10-18](https://user-images.githubusercontent.com/16018123/76735820-cfe64d00-6776-11ea-8cae-14b743b4d1ab.png)

**Comment by moshthepitt** [comment]
@craigappl mentioned that we need to wait to get more feedback https://onaio.slack.com/archives/CBSU8L2SC/p1583741756094900

**Comment by craigappl** [comment]
@kahummer and @moshthepitt , the screenshot is what we need to deliver. Please make sure that the underlying plan template is changed, not just the string, so that the Plan which is submitted to the OpenSRP server has the right text.

**Comment by craigappl** [comment]
We do not need to make changes in the Nifi script because all plan strings have been translated to Thai on the production server.

**Comment by moshthepitt** [comment]
@craigappl sorry it is not crystal clear to me.  Do you mean the screenshot that @kahummer shared?  On that screenshot, what needs to be changed?

**Comment by moshthepitt** [comment]
Superseded by https://github.com/onaio/reveal-frontend/issues/775
