### ISSUE TITLE
Where should the IRS card on home page link to?

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#494]
![reveal hom irs link](https://user-images.githubusercontent.com/372073/66150712-69350300-e61e-11e9-9083-b54a06468c2b.png)

**Comment by cKellyDesign** [comment]
@mberg @rowo Can we get circle back to what we show on the landing page of the site? To Kelvin's point above it's not clear from the current design where the IRS link will go, and it seems like different clients will want different things.

cc @moshthepitt @OluwatobiMayowa

**Comment by rowo** [comment]
Originally, when it was organized by intervention (like DiSARM), it would've gone to an important priority view for the respective intervention. With the navigation change (forget what issue that was where I asked about it) and all of the new stuff that's changed, we'll need to talk through nav and workflow again.

**Comment by cKellyDesign** [comment]
If IRS is not enabled then that card shouldn't render.

**Comment by moshthepitt** [comment]
Closing, please reopen if still an issue
