### ISSUE TITLE
Ensure both points and polygons are rendered for IRS reporting maps

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#504]
Will fix https://github.com/onaio/canopy/issues/473

**Comment by moshthepitt** [comment]
Going to try this approach https://stackoverflow.com/questions/36923916/render-a-featurecollection-from-a-geojson-file-with-multiple-types-in-map-gl

**Comment by cKellyDesign** [comment]
Beautiful, if we do that we don't need the if-else blocks, we can just create the layers every time, and FCs with only one type will just not show anything for the other source-type.
