### ISSUE TITLE
Allow active plans to be edited in the UI

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#515]
We should be able to see and click on Active plans in the IRS Planning list view.

**Comment by moshthepitt** [comment]
- Does this need to be for every plan?
- Should we just trust that things can and change in a plan, and it should be okay to edit it whenever?
- Does it apply to all plan fields, or are there some tha should not be editable?

**Comment by cKellyDesign** [comment]
@mberg @craigappl @pld @githengi - please consider Mosh's questions above ☝️

**Comment by cKellyDesign** [comment]
> Does this need to be for every plan?

For now I'm making changes which should only effect IRS plan Jurisdiction selection (and eventually assignment).

**Comment by moshthepitt** [comment]
For context, we intentionally disabled [editing many fields](https://github.com/onaio/reveal-frontend/blob/master/src/containers/forms/PlanForm/index.tsx#L884) on plans.  Looks like we need to review this.

**Comment by moshthepitt** [comment]
> For now I'm making changes which should only effect IRS plan Jurisdiction selection (and eventually assignment).

But is it absolutely agreed upon that we should do this, or is what is happening in Zambia a rare thing?  I guess I am just worried that freely editing plans probably has a lot of consequences - though we are doing it clunkily anyway right now.
