### ISSUE TITLE
Task and structure sync optmization

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#520]
Currently locations like MTD require 70MB of data to downloads the plan and associates structures and tasks.

Task sync in particular seems to take the longest.

We should look to see if we can optimize the bandwidth of these downloads.

**Structures**
For structures - since most structures are poly's they are only 4 points so there isn't too much we need to simplify the geojson.  We could look at simplyfing the spray area boundaries to reduce the geojson size.

**Tasks**

Can we please paste a snippet of the payload we use to sync tasks to the client?  Are we passing the full task json?  Wondering if there is a way to compress what we sending.  If we are doing standard HTTP compression it may be enough but it would be good to discuss.

**Comment by moshthepitt** [comment]
@mberg I think this was meant for the Reveal mobile app.  Will close it.  Please reopen if I am wrong.
