### ISSUE TITLE
Bulk Assign Organizations to parent Jurisdictions

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#529]
Currently the webapp only allows assigning teams to a single operational area Jurisdiction, which needs to be build upon to support batch assignments to plan-jurisdictions.

**Suggested Implementation:**
1. For non-administrative jurisdictions (spray areas), functionality stays the same
2. For administrative jurisdictions, add Assign Button with label: `[N] teams assigned to [X] spray areas`
    a. `X` requires the child components to know all descendant ids of the admin Jurisdiction 
    b. `N` uses `X` to sum the number of organizations assigned
3. For administrative jurisdictions, using the OrganizationSelect component should generate Assignments for the descendant spray area Jurisdictions, not the admin jurisdiction itself
4. When saving the plan as draft or final, double check all organization-plan-jurisdiction Assignments are for spray area Jurisdictions only.

**Comment by Naima-Bashir** [comment]
This is currently invalid since the assignments are sent at once.
