### ISSUE TITLE
Area NYM 91b Zambia IRS reporting is broken

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#532]
Only yellow structures on map:

![638c6070-94cf-4b75-8549-e150b54d48ed](https://user-images.githubusercontent.com/372073/66902193-e68e4980-f008-11e9-91bf-352cf876e6c0.png)

But numbers in table:

![e5ceb570-50dc-47b2-858d-43c45d16f488](https://user-images.githubusercontent.com/372073/66902204-ebeb9400-f008-11e9-9982-b4200dbfc436.png)

**Comment by moshthepitt** [comment]
Atlassian issue: https://smartregister.atlassian.net/browse/RVL-582

**Comment by moshthepitt** [comment]
So the problem here is caused by the fact that the web app does not geo queries when requesting for structures from Superset.  See below:



```sh
reveal1=> select
distinct(jurisdictions.id),
jurisdictions.name,
subq.count
from jurisdictions
left join lateral (
    select count(*) from zambia_irs_structures
    where ST_Contains(jurisdictions.geometry, zambia_irs_structures.structure_geometry)
) as subq on true
where jurisdictions.id = '4bfcde0d-15df-48b4-a675-173f3125c6e6';
                  id                  |  name   | count 
--------------------------------------+---------+-------
 4bfcde0d-15df-48b4-a675-173f3125c6e6 | NYM_91b |   197
(1 row)
```

Vs

```sh
reveal1=> select count(*) from zambia_irs_structures where structure_jurisdiction_id = '4bfcde0d-15df-48b4-a675-173f3125c6e6';
 count 
-------
   125
(1 row)
```

When you do a geo-query this focus area has 72 additional structures.

**Comment by moshthepitt** [comment]
There are various ways to solve this:

1. Change the database somehow such that all structures point to a `jurisdiction id` that is the same as the geographic region in which the structure is located
2. Change the web app to make a geo-query against Superset.  Not sure how performant we can get this to be - and maybe we should be doing it anyway.

**Comment by moshthepitt** [comment]
This is the filter that we would need to do to make the geo query from the web app via Superset

```sql
select * from zambia_irs_structures
where ST_Contains(
    (select jurisdiction_geometry from jurisdictions_materialized_view
    where jurisdiction_id ='4bfcde0d-15df-48b4-a675-173f3125c6e6'),
    structure_geometry
);
```

* there are many ways to do this query, but the above is what works via Superset

Running an explain analyze gives us this:

```sh
Seq Scan on zambia_irs_structures  (cost=8.43..125611.91 rows=131649 width=517) (actual time=721.856..32388.901 rows=197 loops=1)
   Filter: st_contains($0, structure_geometry)
   Rows Removed by Filter: 389958
   InitPlan 1 (returns $0)
     ->  Index Scan using jurisdictions_materialized_view_idx on jurisdictions_materialized_view  (cost=0.41..8.43 rows=1 width=4376) (actual time=0.014..0.015 rows=1 loops=1)
           Index Cond: ((jurisdiction_id)::text = '4bfcde0d-15df-48b4-a675-173f3125c6e6'::text)
 Planning time: 0.158 ms
 Execution time: 32388.953 ms
(8 rows)
```

I think it is too costly a query to make.  Is it possible to optimize it further?

**Comment by pld** [comment]
This makes sense to me, that is a very expensive query.

Do you have a sense of how long the query will take if we chose the 1st option?

Is the LOE for the 1st option low enough that it's not worthwhile to implement the 2nd option now, while working on the 1st option?

**Comment by moshthepitt** [comment]
@pld the query in option 1 would quite fast at ~13ms 

```sh
QUERY PLAN | Bitmap Heap Scan on zambia_irs_structures  (cost=5.24..405.25 rows=105 width=517) (actual time=12.200..12.247 rows=125 loops=1)
-[ RECORD 2 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN |   Recheck Cond: ((structure_jurisdiction_id)::text = '4bfcde0d-15df-48b4-a675-173f3125c6e6'::text)
-[ RECORD 3 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN |   Heap Blocks: exact=25
-[ RECORD 4 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN |   ->  Bitmap Index Scan on zambia_irs_structures_structure_jurisdiction_idx  (cost=0.00..5.21 rows=105 width=0) (actual time=12.190..12.190 rows=125 loops=1)
-[ RECORD 5 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN |         Index Cond: ((structure_jurisdiction_id)::text = '4bfcde0d-15df-48b4-a675-173f3125c6e6'::text)
-[ RECORD 6 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN | Planning time: 0.108 ms
-[ RECORD 7 ]-------------------------------------------------------------------------------------------------------------------------------------------------------------
QUERY PLAN | Execution time: 12.277 ms
```

> Is the LOE for the 1st option low enough that it's not worthwhile to implement the 2nd option now, while working on the 1st option?

I research and implementation may take a few hours - so lets say half a day.

**Comment by moshthepitt** [comment]
Thanks @pld

**Comment by anniecmartin** [comment]
I defer to you all for the technical solution, just want to comment to ensure that "jurisdiction id that is the same as the geographic region in which the structure is located" means that in the database we are running a geoquery based on the structure's location, and using that query to set the jurisdiction and NOT just taking the location id that is associated through user login and selection.

**Comment by moshthepitt** [comment]
Confirmed as closed by the client.

**Comment by moshthepitt** [comment]
Confirmed as closed by the client.
