### ISSUE TITLE
IRS reporting table is broken when there are no jurisdictions

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#533]
When either one of the slices in `REACT_APP_SUPERSET_IRS_REPORTING_JURISDICTIONS_DATA_SLICES` dont return data, the IRS reporting table gets broken.

![broken irs table](https://user-images.githubusercontent.com/372073/66912057-7d173680-f01a-11e9-924e-6ea0b82ea7fc.png)

**Comment by cKellyDesign** [comment]
Closing this for now, re-open if we start seeing this again
