### ISSUE TITLE
IRS Plan-Jurisdiction Assignment Cleanup

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#537]
There are some bugs which need to be addressed with the UI involved with assigning organizations to plan-jurisdictions for IRS plans.

- [ ] **Popover and Dropdown should not go below the page**
![scroll](https://user-images.githubusercontent.com/4141527/66964713-44805880-f02c-11e9-8b87-082cc93e63b9.png)

- [x] **Page title should not have prepending comma**
![Screenshot from 2019-10-16 17-59-15](https://user-images.githubusercontent.com/4141527/66964737-5235de00-f02c-11e9-885c-7f59b7bc47b1.png)

**Comment by Naima-Bashir** [comment]
To be retested
