### ISSUE TITLE
MDA Plan Scoping

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#538]
This ticket tracks the scoping conversation around the webapp's responsibility for MDA plans ([confluence ticket](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1213530119/Mass+Drug+Administration))

### Reporting
- [x] R1. Derek has provided [this sheet of dashboard definitions](https://docs.google.com/spreadsheets/d/17DEdIOMuxI-MO3aGBUJBntBgi1VqHgqRUzvKGZ__PUA/edit?usp=sharing)
- [x] R2. We need to define table columns / indicators to display in the report table
- [x] R3. We need to define map layers and sidebar content for the report map
- [ ] R4. We need a timeline for when this needs to be in which production environment(s) @craigappl 
- [ ] R5. We to implement and it needs to be dynamically configurable 

### Planning
- [ ] P1. We need to define the MDA Plan definition
- [ ] P2. We need to know the Activities spec for MDA Plans @githengi 
- [ ] P2. We need a timeline for when this needs to be in which production environment(s) @craigappl 
- [ ] P3. We need to implement and it needs to be dynamically configurable 

### Assigning
- [ ] A1. We need to know if there are any special requirements for MDA assignments @craigappl 
- [ ] A2. We need a timeline for when this needs to be in which production environment(s) @craigappl 
- [ ] A3. We need to implement

## Questions
- [ ] Q0. In what order should we be prioritizing the above sections?
- [x] Q1. Are multiple jurisdictions allowed in an MDA Plan (similar to IRS?)
- [ ] Q2. Do we need Family Management modules (similar to Organizations/Practitioners)? @mberg 
- [ ] Q3. Are MDA Plans considered Focus Investigation plans? (Do we list them as a new table on the `Reporting > Focus Investigations` or should they be listed on their own page `Reporting > MDA`)? @mberg @rowo 
- [ ] Q4. What does `Add support for kicking off MDA round 2` imply for the webapp? @craigappl 
- [ ] Q5. What is the MDA adherence activity goal? Is it 100% of people in the OA? Or is there some other threshold or calculation we need to make?

(@mberg please assume all the questions have your name next to them!)

**Comment by pld** [comment]
is there a timeline for these pieces and for the whole thing? please tag me when input for specific pieces is need, I'm going to unassign myself

**Comment by cKellyDesign** [comment]
[Referencing confluence](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1213530119/Mass+Drug+Administration#Minimum-Viable-Product):
> The supervisor drills down to the selected operational area

Q1: Seem like the answer is yes

**Comment by cKellyDesign** [comment]
[Referencing the googlesheet](https://docs.google.com/spreadsheets/d/17DEdIOMuxI-MO3aGBUJBntBgi1VqHgqRUzvKGZ__PUA/edit?usp=sharing):

R2:  Reporting Drilldown tables will require both Administrative level columns (Province, District, Catchment) AND Operation Areas.

@moshthepitt does the spreadsheet provide enough clarity to you in terms of how to set up the Superset slices for both Jurisdiction levels?

**Comment by moshthepitt** [comment]
@cKellyDesign yeah it looks like the spreadsheet has all we need

**Comment by cKellyDesign** [comment]
It looks like we already have an MDA plan in the staging environment which loads in the `Manage Plans` list as MDA and loads in the `Update Plan` view as FI. The assign and monitoring pages are both filtering by plan type which is why we don't see them there. I'm going to start by adding `MDA` as an intervention type so we can at least start seeing them in the Assign page.

**Comment by cKellyDesign** [comment]
**On R5 / WebUI Technical Implementation:** 

* Reuse/replicate IRS Reporting tables/maps (M/L)
* Set up Superset slices for the jurisdictions and operational areas (L)
* Define table columns and indicator configs in helpers (S)
* Add `MDA Reporting` nav item (XS)

**Comment by cKellyDesign** [comment]
**On P3 / WebUI Technical Implementation:**

* Add Plan type (`MDA`) to New/Update Plan forms (XS)
* Add MDA activities to Plan Definition and New/Update Plan forms (M)
* Configure MDA specific constraints (S)

**Comment by cKellyDesign** [comment]
On A3 / WebUI Technical Implementation:

* Add MDA plans to the Assign Plans list view (S)

**Comment by cKellyDesign** [comment]
@moshthepitt can this be closed or is this ongoing / in the roadmap?

**Comment by moshthepitt** [comment]
Let's close it.  Not sure that it is actually "ongoing".  We can always reopen later if need be.

cc: @craigappl @mberg
