### ISSUE TITLE
RVL-563 - Structures don't seem to be syncing from tablet to web

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#541]
We have an issue that needs to be investigated in Namibia Production:

Village: Oshipumbu (Reveal Id: a54ac0de-6187-45f3-92df-e98a740cd6eb)
Hierarchy: Namibia>Oshana>Oshakati>Oshipumbu

It looks like there are a number of added locations where updates aren't properly being synced from the OpenSRP server to the data warehouse. The below screenshot shows the view in the android client on the left and the web on the right. These tasks and events are all syncing tablet to tablet, so we expect it has to do with something in the ETL process to the data warehouse.
![image](https://user-images.githubusercontent.com/6067053/67098472-207a5f80-f171-11e9-838f-d887293c33a7.png)

Can we perform the following steps:
1) Compare the task status in this area from what's returning in the opensrp server against what's returning in the data warehouse.

**Comment by moshthepitt** [comment]
Will do.  But its probably things that have not synced from OpenSRP to Canopy.  This will help: https://github.com/OpenSRP/opensrp-server-web/pull/146

**Comment by mberg** [comment]
Seeing same issue in Zambia

**Comment by mberg** [comment]
We have to make this work rock solid

**Comment by cKellyDesign** [comment]
@gstuder-ona @craigappl @mberg - was this issue addressed in the data reset on friday?

**Comment by cKellyDesign** [comment]
nvm - checked the [jira ticket](https://smartregister.atlassian.net/browse/RVL-563) so closing
