### ISSUE TITLE
Add Plans Reducer getter for all Plans

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#547]
Currently all the getter methods in the Plans reducer require a parameter for Intervention Type and default to `FI`, and we simply need a way to return all plans without filtering by type. Reasoning behind this is so we don't need to update pages which show all plans every time we add a new Plan type.

**Comment by tikitakas** [comment]
Can i just refactor the selector to return all plans by default instead of using a specific intervention type as the default value?
