### ISSUE TITLE
Dont render NULL jurisdiction in FI Plan

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#550]
![NULL jurisdictions](https://user-images.githubusercontent.com/372073/67423643-4d010200-f5dd-11e9-90a6-8beab17d5d02.png)

**Comment by cKellyDesign** [comment]
@p-netm @moshthepitt - is this still happening?

**Comment by moshthepitt** [comment]
Closing this - I havent seen this happening recently

**Comment by moshthepitt** [comment]
![Current Focus Investigations   Reveal Stage](https://user-images.githubusercontent.com/372073/74718474-5b85c000-5243-11ea-9ecb-48b4f3bfb010.png)

^^ seems it is still happening.
