### ISSUE TITLE
Render list of practitioners in dropdown, not OpenMRS users

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#566]
Currently when assigning Practitioners to Teams we are rendering a dropdown of Practitioners but showing their OpenMRS usernames. Let's instead render the Practitioner names to make it a more coherent experience from creating Practitioners to assigning them to Teams.

<img width="934" alt="Screen Shot 2019-10-28 at 10 54 51 AM" src="https://user-images.githubusercontent.com/4141527/67661259-c8faa180-f971-11e9-82ba-9a20b8a1a7a6.png">

**Comment by moshthepitt** [comment]
Closed by https://github.com/onaio/reveal-frontend/pull/568
