### ISSUE TITLE
missing openmrs IDs

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#571]
The following have missing OpenMRS's which need to be added

KPB_5 - fcdab5e6-f5ac-4d2c-93ca-79dc9be23008

MWA_44 | 82210b38-c546-482a-bf40-999250f14bbd
MWA_277 | f48c14d4-b776-45d9-9be7-f777cbefd00e
MWA_327 | 122204b1-9705-4159-b600-935915ae2d30
MWA_171 | d03d6fc4-f863-4348-a0a9-063f1c883cca
MWA_1917 | b491363b-2452-44ad-b146-74e6a794992f
MWA_1926 | 7f8bc4a5-710c-4c8a-b293-05c4ff29a9b1
MWA_1925 | 4635a376-6d1f-4d10-be1c-1d4d6e2bd92c
MWA_330 | 2bfc13ee-e808-4217-88b1-9005ec396a97
MWA_1914 | 31eec5b7-21d0-4a0e-9f59-c200a170d022
MWA_1901 | dfa7052f-ac45-47fe-b34a-ae1d2bc9b893
MWA_1903 | e5508bc3-c070-40b4-a8eb-e4a4d902083c
MWA_1922 | b8ee31ef-bebd-4b8e-8fb2-3da897d475e6
MWA_1905 | 3fe3d84b-bef1-4518-bcab-86f4a187d182
MWA_172 | c289293c-b055-4208-81ee-b24243473eb2
MWA_168 | 3a3c0514-4174-4c14-ba5a-4fd7c2a6bb8f
MWA_1923 | 57ef1bff-399b-49af-8a1a-10879357be66
MWA_1927 | 5fae193b-877d-455e-82f9-db14166f2efa
MWA_317 | 29c4f569-81e9-4b7b-82ea-19a26302078c
MWA_1924 | 41cea9c6-248e-4c0f-b22e-8fa36fc44fbb
MWA_322 | 793e572b-af9e-4131-b232-9f49134c3159
MWA_1920 | 2f1199d5-3703-4b67-9065-dd0c294441e5
MWA_165 | b345dbd0-f5b2-467d-90e5-d5dfbe15dbfd
MWA_1912 | 930a29cf-8ba3-424e-852f-f3d3357118ca
MWA_162 | fb860bce-b967-4533-96c2-8b1bbd144612
MWA_1929 | a6af402f-f523-4877-a063-ee80e2496112
MWA_270 | 0d33c1f4-a2e4-4b67-bfc1-a12b13b2d0fa
MWA_163 | 65e97428-2653-4c35-9fab-f7a32fbc0c88
MWA_1919 | 8ef3fffa-5ec2-4522-b73c-f8ab32537ca7
MWA_1902 | de55d732-725b-44b9-8b2a-666d0e8f5940
MWA_1928 | 8af22d1e-3a49-4073-890e-ced28fee85db
MWA_275 | 0b062e36-7c36-43d6-b6ed-ea5f5e4c607d
MWA_1918 | 42832a90-dc6b-4f30-95ee-5b92f112291b
MWA_164 | 30a88305-19b8-483f-91aa-0d4f9894292d
MWA_1921 | 7cb7db85-bca5-48bb-9438-886855ee29f0
MWA_1904 | bc76bc9d-0a18-4791-b151-949e6a330c59
MWA_1930 | df3dafb7-f1f1-4dfc-a0bb-71ed517cf8af
MWA_1906 | bfea7fdd-e2bc-46e3-8730-3ba7f5fb2ffc
MWA_1913 | 479db6bc-69c6-4ca6-97f5-8f1f4b1d3841
MWA_1915 | 42c842c5-b3cb-4fbd-a82b-d9cd3dfba905
MWA_1907 | 4c2399e5-b5b6-42fc-a3d6-cef9ec26c59c
MWA_1916 | e9882bce-5d2c-4757-9d82-d1713e954e15
MWA_1908 | 47dd2412-47e1-412d-b4f8-3b08afade0c7
MWA_1909 | c462e361-4fee-4ae2-a13d-57173b914ed0
MWA_1910 | a8176465-de35-467e-a1de-1124c09b978f
MWA_166 | 0612c6f2-2e2f-40b7-8312-bf1d71effc28
MWA_1911 | e49ad594-ce8a-4066-81cf-f6e11a6c30bc

**Comment by moshthepitt** [comment]
Not a Reveal web issue
