### ISSUE TITLE
Improve clarity on select box in focus investigation single page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#572]
![image](https://user-images.githubusercontent.com/372073/67749625-966aaa80-fa3e-11e9-9fa9-bfded558e2d3.png)

The select box in the focus investigation map page should be more descriptive.  Perhaps say "Other plans in this area"

**Comment by moshthepitt** [comment]
Context: https://dsme.slack.com/archives/CJJ5P39TM/p1572332870079200

**Comment by cKellyDesign** [comment]
@moshthepitt why are we doing this? https://github.com/onaio/reveal-frontend/blob/master/src/components/SelectPlan/index.tsx#L14-L20

**Comment by moshthepitt** [comment]
@cKellyDesign I think when we made that component we couldnt get it to navigate to that URL on just simply clicking so we had to add that hack
