### ISSUE TITLE
Possible FI Focus Area fixes

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#579]
![fi area](https://user-images.githubusercontent.com/372073/67895155-070ee580-fb6b-11e9-85a0-7382aca7c965.png)

**Comment by cKellyDesign** [comment]
@mberg do you know if this page is supposed to show `draft` plans?

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm what does the search field in this screenshot actually do? If it's not actually doing anything then we should just remove it at this point?

**Comment by moshthepitt** [comment]
> @mberg do you know if this page is supposed to show draft plans?

I think it should not, because:

1. there are no meaningful reports for draft plans
2. I think it is something left over from back when we didn't have the manage plans page and needed to show all plans here
3. the other filters e.g. in the select box leave out draft plans

**Comment by cKellyDesign** [comment]
> there are no meaningful reports for draft plans

This is an excellent point, I'm going to remove them.

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/580
