### ISSUE TITLE
Add "Not in spray area" to IRS reports in Zambia

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#585]
In Zambia any points that are not geographically located within a spray area (level 4 jurisdictions) are assigned a jurisdiction_id of the parent i.e. they are assigned to a level 3 jurisdiction.

We therefore need to:

- [ ] write a query that gets the l3 jurisdictions and aggregates all the points assigned directly to them.  This will be very similar to https://github.com/onaio/canopy/pull/411/files?file-filters%5B%5D=.md&file-filters%5B%5D=.sql#diff-2434081f82f5ff4a0748da4212dd1016 but will only include l3 jurisdictions and structures directly linked to them
- [ ] aggregate the above upwards to l2, l1, and l0 jurisdictions.  This will be very similar to https://github.com/onaio/canopy/pull/411/files?file-filters%5B%5D=.md&file-filters%5B%5D=.sql#diff-4c99a1073b8ab31030cff28685e35278 but will only include the records obtained by the above query in aggregating upwards through the jurisdiction hierarchy
- [ ] the above two queries should result in two new slices that can be fed into Zambia IRS jurisdictions table here https://github.com/onaio/reveal-frontend/blob/master/src/configs/env.ts#L70

More Context: https://smartregister.atlassian.net/browse/RVL-600

**Comment by moshthepitt** [comment]
Starting work on this.  Will update progress here.

**Comment by gstuder-ona** [comment]
> In Zambia any points that are not geographically located within a spray area (level 4 jurisdictions) are assigned a jurisdiction_id of the parent i.e. they are assigned to a level 3 jurisdiction.

Started looking from this assumption - there are some structures (22) that are assigned a level-3 jurisdiction in Zambia, but *all* of them are actually inside a level-4 jurisdiction (and so mapped there by our structure_geo_jurisdiction view).  I think this means if we follow the logic above, that there are actually zero structures currently to report as "other".

After doing another pass of the data though, there are structures assigned a level-4 bound but that are outside the level-4 geometry.  It's not totally clear to me what we want overall between these two cases:

1) Structure assigned a L-3 jurisdiction but is geometrically inside another L-4 jurisdiction
2) Structure assigned a L-4 jurisdiction but is geometrically outside it (maybe with a buffer) and inside an L-3,2,1,0 jurisdiction or none at all

@craigappl @mberg do we know which cases we want to report as "other"?  If we're just going by geometry, I'm a bit confused as to why we default to the assigned structure jurisdiction?

**Comment by gstuder-ona** [comment]
re:"this will be very similar to"

Technically, I'd love to avoid duplicating the entire IRS reporting view stack - I think it's possible if instead we wire in "virtual" jurisdictions at all levels to catch all the structures not in a leaf jurisdiction.  Then we just need to map jurisdictions through the views like we do already for geo-assigned jurisdictions.

WIP, but any feedback welcome.

**Comment by moshthepitt** [comment]
The intention is to eventually have an additional row in the IRS reporting tables in the web app similar to the last row here: https://macepa.mspray.onalabs.org/477

Ideally we'd have this row in every hierarchy of jurisdictions if there are spray events not in any of the jurisdictions e.g. if district A has 3 child jurisdictions: X, Y and Z but we have spray data that we believe is in district A but not in any of its known children, then we would list this as "Not in target area"

So it looks like this is what we want:

> Structure assigned a L-4 jurisdiction but is geometrically outside it (maybe with a buffer) and inside an L-3,2,1,0 jurisdiction or none at all

**Comment by moshthepitt** [comment]
> Technically, I'd love to avoid duplicating the entire IRS reporting view stack - I think it's possible if instead we wire in "virtual" jurisdictions at all levels to catch all the structures not in a leaf jurisdiction. Then we just need to map jurisdictions through the views like we do already for geo-assigned jurisdictions.

@gstuder-ona this exactly.  We want this "virtual" jurisdictions that we can just conveniently add as a superset slice or slices here https://github.com/onaio/reveal-frontend/blob/master/src/configs/env.ts#L70 - with the theory that if they have the same structure as "real" jurisdictions then the `JurisdictionReport` component will seamlessly work with them upto and including drilling down and up.

**Comment by gstuder-ona** [comment]
> We want this "virtual" jurisdictions that we can just conveniently add

Not sure we even need to add a new slice for it, honestly - I think we just need to create a zambia_jurisdictions_materialized_view which extends jurisdictions_materialized_view with catch-all jurisdictions for every non-leaf (<4) jurisdiction level (did this as a test).  Then the structure_geo_jurisdictions uses that, and the rest of the IRS reporting basically is unchanged - we'll just get an extra "_other" jurisdiction for every level in the UI (and visualization should work too?).

**Comment by gstuder-ona** [comment]
> @craigappl @mberg do we know which cases we want to report as "other"? If we're just going by geometry, I'm a bit confused as to why we default to the assigned structure jurisdiction?

Just talked with @ukanga - we're going with a full, all-levels geo-query and not trusting OpenSRP at all.  It'll be expensive, but ideally we can push all this up to OpenSRP later.

**Comment by gstuder-ona** [comment]
Fix is in place, under review by Akros

**Comment by cKellyDesign** [comment]
Seems like this is done, closing.
