### ISSUE TITLE
Add Growl Notifications for Team Assignment

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#587]
We need to add a few alerts to the Team Assignment pages:

- [x] Render a Reactstrap `Alert` component below the dropdown in the `Assign Practitioners` view when a user adds and removes Practitioners from a Team, display a simple growl notification indicating: `[Practitioner] was [added/removed] from [Organization]`
- [x] Provide enough space between dropdown and the `Add Practitioners` button so it doesn't bump up and down as the alert toggles
- [x] Render a Reactstrap `Alert` component indicating `[Practitioner] as been saved' below the `Save Practitioner` button in the `new Practitioner` view for 1 second before navigating away from page

**Comment by p-netm** [comment]
@cKellyDesign
1. would it be simpler implementation-wise to have the alerts float above say the top-right corner of the screen 
https://codesandbox.io/s/vibrant-leftpad-bro79

**Comment by cKellyDesign** [comment]
> would it be simpler implementation-wise to have the alerts float above say the top-right corner of the screen

@p-netm make it so!
