### ISSUE TITLE
New Practitioner Form page fixes

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#589]
- [x] Sort the usernames drop-down alphabetically
- [x] Capitalize the `n` in `New Practitioner` breadcrumb and page title

<img width="879" alt="Screen Shot 2019-11-12 at 10 39 52 AM" src="https://user-images.githubusercontent.com/4141527/68699892-cb93f400-0538-11ea-8223-370c1a17c17d.png">

**Comment by cKellyDesign** [comment]
@p-netm one more request from the client on this one:

- [ ] Force Practitioner names to be Unique (so when they are listed the user is able to tell which is which) and show indication that the name is already in use

**Comment by p-netm** [comment]
@cKellyDesign would like to bring a few things to your attention before proceeding with this.
1. the changes to how the users are displayed in the assign page introduced in #568 removes ambiguity as to which practitioner is being picked. There is a case where we have 2 practitioners `Loko Doe` that are mapped to the same openMRS user,.. however this scenario is from a time when there were no constraints that ensure a 1-1 mapping between user and practitioner. 
2. assuming we still want to enforce uniqueness of the practitioner name, i feel like this probably needs to start in the server
    - given 2, user.username and practitioner.name will both be unique, (here comes a naive suggestion) might we consider doing away with one.

**Comment by cKellyDesign** [comment]
@p-netm 
1. Yeah there are duplicates in the server which we've explained to the client is a result of activity from before this fix was put in, and agree that we need to clean the staging server
2. Good point, I'm not sure why we have user.usernames which are different than practitioner.name

@craigappl @mberg any input on number 2?

**Comment by cKellyDesign** [comment]
@p-netm i'm assuming on number 2 it's just a matter of business logic agreed upon with the client and don't think this should be a blocker

**Comment by cKellyDesign** [comment]
_Re-opening this ticket to track the third task._

Current blockers described by @p-netm in #591:
* [No way to ensure we have ALL practitioners in the local store](https://github.com/onaio/reveal-frontend/pull/591#issuecomment-557109798)
* [No way to filter the OpenSRP API request by practitioner name](https://github.com/onaio/reveal-frontend/pull/591#issuecomment-556069901)
