### ISSUE TITLE
Deleted data still shows up on UI

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#595]
_Reproducing_:
- create practitioner on UI,
- delete practitioner using postman or whichever tool
- back on the UI, perform any action that leads to new practitioners being fetched and rendered
- the deleted practitioner is still in store and thus shows up on the ui.

This bug happens due to how fetched response data is fetched from the api, ie. we are currently appending new fetched data to already existing records and thus deleted data in the store is never removed.

**Comment by cKellyDesign** [comment]
@p-netm are we dispatching any action to remove the practitioner from the store? If not then it seems like we should have an action/-creator capable of removing an array of practitioners from the practitioner store when we DELETE (or PUT in the case of making inactive) the practitioner in OpenSRP.

**Comment by p-netm** [comment]
> re we dispatching any action to remove the practitioner from the store?

Nope, we do have a removeAction but its majorly used in testing, currently we add whatever data we get to whatever data that is in the store, a decision that was intentional and implemented in #314 to solve the issue #289 
Maybe we can add a flag to the action creators that tell the reducer if we want an action of type `fetchsomething` should overwrite the current records or append to them.

**Comment by cKellyDesign** [comment]
@p-netm not sure about passing a flag in, unless it would change the action.type so it doesn't fall into [this case condition](https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/opensrp/practitioners/index.ts#L156-L167). As long as it's `PRACTITIONER_ROLES_FETCHED` it seems like it will be difficult to do any removing (unless we refactor and move that logic into the action creator).

Another option could be to dispatch `removePractitionerRolesAction` to wipe out the practitioner store and then repopulate it, but that seems a bit wasteful. Or maybe we modify `removePractitionerRolesAction` to accept an optional list of practitioners to remove?

**Comment by p-netm** [comment]
> not sure about passing a flag in, unless it would change the action.type so it doesn't fall into [this case condition](https://github.com/onaio/reveal-frontend/blob/master/src/store/ducks/opensrp/practitioners/index.ts#L156-L167). As long as it's `PRACTITIONER_ROLES_FETCHED` it seems like it will be difficult to do any removing (unless we refactor and move that logic into the action creator).

i was thinking of sth like
```typescript
// the action creator
const actionCreator = (someArray: Practitioner[], overwrite: boolean) => {
  return {
    overwrite,
    practitionersById: someArray, // by id,
    type: FETCH_PRACTITIONERS,
  };
};

// the reducer
switch (action.type) {
  case FETCH_PRACTITIONERS:
    const practitionersToAdd = action.overwrite
      ? action.practitionersById // this repopulates the store with newly fetched data
      : { ...state.practitionersById, ...action.practitionersById }; // this adds fetched data to existing practitioners data
    return {
      ...state,
      practitionersById: practitioners,
    };
}

```

Or add another action type, so that  we can have one that appends data and another that overwrites data, this would remove the need for a flag, then for the single pages we can fetch data with the action type that adds and for other pages like listing pages we can use the action type that overwrites.

> `` to wipe out the practitioner store and then repopulate it, but that seems a bit wasteful

I agree

> Or maybe we modify `removePractitionerRolesAction` to accept an optional list of practitioners to remove?

I think this a tad harder, since i believe solution would have to look sth like
```typescript
// the action creator
const actionCreator = (someArray: Practitioner[]) => {
  return {
    practitionersById: someArray,
    type: FETCH_PRACTITIONERS,
  };
};

// the reducer
switch (action.type) {
  case REMOVE_PRACTITIONERS:
    const remainingPractitioners: { [id: string]: Practitioner } = {};
    // some loop
    Object.entries(state.practitionersById).forEach(([key, value]) => {
      if (!action.practitionersById.includes(value)) {
        remainingPractitioners[key] = value;
      }
    });
    return {
      ...state,
      practitionersById: remainingPractitioners,
    };
}
```
and here there is the  assumption that we somehow already know the practitioners that were deleted.

**Comment by cKellyDesign** [comment]
@p-netm Cool I like your first implementation, I think the boolean isn't actually business logic and it fits here very elegantly, it lets whatever is dispatching the action be responsible for determining which data was deleted. Let's set the default value of `overwrite` to `false` and spread `action.practitionersById` and let it be so!
