### ISSUE TITLE
RVL-164: mSpray Operational performance/efficiency dashboards

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#603]
[Jira Ticket](https://smartregister.atlassian.net/projects/RVL/issues/RVL-164)
**Client Description**
> I want to see dashboards that track team progress and efficiency similar to the mSpray dashboards
>
> Desired outcome: mSpray dashboards built out in full /
>
> I would like access to mSpray dashboards, which I am familiar with from working with mSpray

**High Level Implementation**
- [ ] 1. Configure the ELTs similarly to the existing reporting dashboards ([indicator scoping](https://docs.google.com/spreadsheets/d/1nE-iqh11U22a8kpMAKXZ_UgdpMYy7jQY1UcHgQ85Tis/edit#gid=737768298))
- [ ] 2. Include indicator drill-down tables similar to the reporting pages with a link to the map at each hierarchical level ([table scoping](https://docs.google.com/spreadsheets/d/1nE-iqh11U22a8kpMAKXZ_UgdpMYy7jQY1UcHgQ85Tis/edit#gid=737768298))
- [ ] 3. Include indicator maps similar to reporting maps, with additional indicator UI in lower left corner (to match mSpray)

**Comment by cKellyDesign** [comment]
@craigappl @ukanga @mberg - Flagging an issue with number 2 above: from the indicator and table spreadsheets the Coverage dashboards seem like they will fit into our current location based drill-down hierarchy, but I'm not sure about the hierarchies described in for the Performance dashboards. Is it supposed to be like this?
```
District
|_ Data Collector
   |_ SOP
```
If so then we will need to add parent IDs to each of the entities (which isn't scoped in the indicators sheet) in order to understand that relation and to render with the Drildown table.

Also - What are Data collectors and SOPs? Are they simply new entities we're getting from OpenSRP? Are these endpoints set up? (cc - @Rkareko)

**Comment by moshthepitt** [comment]
@cKellyDesign I had written a little spec of this from the data point of view: https://github.com/onaio/canopy/issues/555

**Comment by cKellyDesign** [comment]
@moshthepitt seems like this can be closed, ama?
