### ISSUE TITLE
Add ref app Zambia configuration

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#611]
The IRS Jurisdiction Selection and Team Assignment pages both determine their top level location by name, thus changing `Zambia` to `ra Zambia` requires its own configuration.

**Comment by moshthepitt** [comment]
> The IRS Jurisdiction Selection and Team Assignment pages both determine their top level location by name

@cKellyDesign this seems really fragile to me.  Is there something we can do to make it less fragile?  Maybe use geographic level or something else?

**Comment by moshthepitt** [comment]
@cKellyDesign can you help unblock this one if possible, please?

**Comment by cKellyDesign** [comment]
> @cKellyDesign can you help unblock this one if possible, please?

Slack Convo: https://onaio.slack.com/archives/GUSEVD5CZ/p1584622097016900
