### ISSUE TITLE
Add Number validation to Plan Form where there should be numbers

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#622]
This isn't critical, but may impact the internationalization work in the web UI. We should add validation on the fields that expect numbers in the Add/Edit plan form (0123456789) All other values in that field should cause validation errors.

**Comment by kelvin-muchiri** [comment]
@craigappl Are there any specific fields. Also, seems like there is a problem with the validation message for quantity too. Is it a problem?
![Screenshot from 2020-02-06 12-38-12](https://user-images.githubusercontent.com/19818819/73925631-68b7bc00-48df-11ea-9dad-c6e1c1b47198.png)

**Comment by moshthepitt** [comment]
@craigappl I am going to close it as I think we have all the validations in place.
