### ISSUE TITLE
Investigate indicator calculations for FI indicators on map page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#627]
It seems that allthe FI indicators are done as `no. of tasks completed / total no. of tasks` .

For at least some (maybe all) of the indicators, we need to factor in the task business status when calculating the indicator.  See this issue for complaints from the client: [https://smartregister.atlassian.net/browse/RVL-700](https://smartregister.atlassian.net/browse/RVL-700)

The slice data received from Superset looks like this:

```js
{
    id: "8ba69c91-48d4-5d1f-8608-0da010d291c9",
    plan_id: "d79016e7-24cd-5e06-8a76-243e7b0555b5",
    jurisdiction_id: "5ec6a370-d27a-4091-bc2a-441c97d8b142",
    goal_id: "RACD_Blood_Screening",
    measure: "Number of registered people tested",
    goal_value: 50,
    goal_comparator: ">=",
    goal_unit: "Person(s)",
    action_code: "Blood Screening",
    action_description: "Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person",
    action_prefix: "2",
    action_reason: "Routine",
    action_title: "Blood screening",
    task_count: 329,
    completed_task_count: 61,
    task_business_status_map: "{"Complete": 61, "Not Visited": 268}"
}
```

We need to investigate two things:

1. Are we using the `task_business_status_map` field for these calculations?
2. What is missing in the task_business_status_map, if anything?

**Comment by moshthepitt** [comment]
@craigappl @samkanga I am not seeing the "Tested" business status that is being mentioned here: https://smartregister.atlassian.net/browse/RVL-700

Do you have any insight for that?

Also, can we define clearly in this issue how the various FI indicators are supposed to be calculated?  This document is not clear for me: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1150877703/Web+UI+Goals+Progress+Indicator+visualization

**Comment by moshthepitt** [comment]
This is the data dictionary: https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=282831159

**Comment by samkanga** [comment]
Hi @moshthepitt check out this additional dictionary and see if this is helpful: https://docs.google.com/spreadsheets/d/1tK1cWvLrgHJ2TKEtlHwCXV6bv2ZH2ONVTgk28uooYpw/edit#gid=1834208304

**Comment by moshthepitt** [comment]
@samkanga @craigappl thanks, this is much clearer.  What does `location.properties.type` mean in that doc?

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm what are the implementation steps for this? What needs to be done on the front end vs what needs to be done in the ETL?

**Comment by moshthepitt** [comment]
@cKellyDesign @samkanga  I think we need to:

1. Get clarification on how each of the FI indicators is supposed be calculated (there are seven indicators one for each activity)
2. We may need to modify the `targets_materialized_view` to include any missing data from the above step
3. Once we have the materialized view where we want it, we need to change the web app to use it

**Comment by craigappl** [comment]
location.properties.type is defined when a user saves a register location form by dropping a point OR when they save the IRS spray form. The value can be one of the following:

"Residential Structure", "Larval Breeding Site", "Mosquito Collection Point", "Potential Area of Transmission"

https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=0&range=E21

**Comment by cKellyDesign** [comment]
@moshthepitt what's the status of this?

**Comment by moshthepitt** [comment]
@samkanga @craigappl am I right to say that the client is still scoping for this?

**Comment by samkanga** [comment]
@moshthepitt making follow-up with client on the ticket and I will revert here with more information.

**Comment by ciremusyoka** [comment]
@samkanga  any additional information on this?

**Comment by moshthepitt** [comment]
After going live in Thailand, it seems that the client is happy with how things work now.  Will close this.
