### ISSUE TITLE
Jan 7th Thai web UI translation feedback

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#632]
We received this feedback from the Thai team regarding translations on the web UI. Please review this and update as needed.

[https://drive.google.com/open?id=1YoL4eibw5LLTLAwsXDelXPPTOII6b9C_](https://drive.google.com/open?id=1YoL4eibw5LLTLAwsXDelXPPTOII6b9C_)

**Comment by cKellyDesign** [comment]
### Next Steps
- [ ] Triage [attached powerpoint](https://drive.google.com/open?id=1YoL4eibw5LLTLAwsXDelXPPTOII6b9C_)
- [ ] Update [Translations Sheet](https://docs.google.com/spreadsheets/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit?ts=5e0d6060#gid=0)
- [ ] Update [TH i18n File](https://github.com/onaio/reveal-frontend/blob/586-internationalization/src/configs/strings/th.json)

**Comment by moshthepitt** [comment]
@craigappl I think this feedback format is really hard to work with because the person implementing has to do a lot to find the string to change.  I think @cKellyDesign  will do this for now but in the future, if possible, it would be nice to get the feedback in a better format from our partners.

**Comment by cKellyDesign** [comment]
Agreed, luckily the red text in the powerpoint is selectable! 😅 

Ideally, the feedback is provided in the translations sheet, if a user copies the incorrect translation from the browser they should be able to search the sheet and replace it. Double ideally, they will leave a comment denoting the update, but if not we can still peek at the sheet version history to see what was updated.

- Pg 2 - This appears resolved in staging
- Pg 4a - This was already resolved
- [x] Pg 4b - This was not updated but is now (139753b8)
- Pg 5a - Same as 4a
- [x] Pg 5b - Same as 4b
- [ ] Pg 7
- [ ] Pg 8a
- [ ] Pg 8b
- [ ] Pg 9
- [ ] Pg 10
- [ ] Pg 12a
- [ ] Pg 12b
- [ ] Pg 12c
- [ ] Pg 16

**Comment by moshthepitt** [comment]
@cKellyDesign can we now close this?

**Comment by cKellyDesign** [comment]
Yeah closing this b/c this feedback is done, more/newer feedback is/can be tracked in newer tickets.
