### ISSUE TITLE
Generalize and decouple LinkAsButton defaultProps.text

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#634]
Currently the default text for the general `LinkAsButton` component is specific to adding focus investigation plans and should be generalized.

- [x] Change defaultProps.text to `Link` (and update the component's snapshot)
- [x] Specify `text` prop in references using the default props (so their snapshots don't break)
- [x] Add ticket for migrating the LinkAsButton to a `js-tools` package ([ticket](https://github.com/onaio/js-tools/issues/128))

**Comment by moshthepitt** [comment]
@ciremusyoka once we have an issue on js-tools created, we can close this.

cc: @cKellyDesign

**Comment by cKellyDesign** [comment]
Ticket created at https://github.com/onaio/js-tools/issues/128
