### ISSUE TITLE
Stop un-mounting containers when GA Tracking

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#641]
Our current implementation react-ga's page tracking follows suggested practices, but is forcing our container components (and all of their children components) to unmount and remount every time the URL changes.

### Implementation Options
A. Tweak [current implementation](https://github.com/onaio/reveal-frontend/blob/master/src/components/page/WithGATracker/index.tsx#L51-L89) to avoid unmounting containers, or
B. Refactor to use a [different suggested implementation](https://vanja.gavric.org/blog/integrate-google-analytics-with-react-router-v4/#routecomponentimhobestapproach)

Additionally:
C. If a GA code is not provided via env variables then do not initialize GA tracking.

**Comment by moshthepitt** [comment]
This issue's successful resolution must be accompanied by https://github.com/onaio/js-tools/issues/113

**Comment by kelvin-muchiri** [comment]
@moshthepitt @cKellyDesign I don't seem to understand or know how to produce this. I tried but seem to find no problem. What steps should I use?

**Comment by cKellyDesign** [comment]
@kelvin-muchiri do you have `GA_CODE` included in your `env` variables?

### Reproduction Steps
1. run locally with GA enabled
2. go to `Focus Investigation` > [any FI Plan] (at this point the map is mounted and loaded)
3. click a metric in the sidebar to update the url (seeing the map re-initialize indicates re-mounting)
