### ISSUE TITLE
RVL-734 Change Colour Gradient Range for Dashboards

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#646]
New color gradients should be:

- Grey: 0%
- Red: 0 to 70%
- Yellow: 70 to 80%
- Light Green: 80 to 85%
- Green: >85%

Current values: https://github.com/onaio/reveal-frontend/blob/master/src/configs/settings.ts#L848

This change should only affect Namibia.

More info: https://smartregister.atlassian.net/browse/RVL-734

**Comment by moshthepitt** [comment]
Change shade of green for Namibia to #4C9A2A

**Comment by p-netm** [comment]
We got updated values for the color ranges, The new ones are clearer on what the upper and lower bounds of the thresholds should be.

```
Grey 0 <20

Red 20 <75

Yellow 75 <90

Green 90-100.
```
