### ISSUE TITLE
ConnectedAPICallback not working correctly

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#653]
```ts
<ConnectedAPICallback
    LoadingComponent={Loading}
    UnSuccessfulLoginComponent={() => {
    return <Redirect to={LOGIN_URL} />;
    }}
    SuccessfulLoginComponent={withRouter(props => {
    let pathToRedirectTo = HOME_URL;
    const searchString = trimStart(props.location.search, '?');
    const searchParams = querystring.parse(searchString);
    const nextPath = searchParams.next as string | undefined;
    if (nextPath) {
        pathToRedirectTo = nextPath;
    }
    return <Redirect to={pathToRedirectTo} />;
    })}
    apiURL={OAUTH_GET_STATE_URL}
    {...routeProps}
/>
```

If you try to access a URL such as `https://web.reveal-stage.smartregister.org/plans/update/bc78591f-df79-45a7-99e4-c1fbeda629e2`, pathToRedirectTo should be `plans/update/bc78591f-df79-45a7-99e4-c1fbeda629e2` but the code above produces something like `plans/update/:id`

**Comment by moshthepitt** [comment]
@p-netm please let us also move 

```ts
<ConnectedAPICallback
    LoadingComponent={Loading}
    UnSuccessfulLoginComponent={() => {
    return <Redirect to={LOGIN_URL} />;
    }}
    SuccessfulLoginComponent={withRouter(props => {
    let pathToRedirectTo = HOME_URL;
    const searchString = trimStart(props.location.search, '?');
    const searchParams = querystring.parse(searchString);
    const nextPath = searchParams.next as string | undefined;
    if (nextPath) {
        pathToRedirectTo = nextPath;
    }
    return <Redirect to={pathToRedirectTo} />;
    })}
    apiURL={OAUTH_GET_STATE_URL}
    {...routeProps}
/>
```

to a component with tests, etc

**Comment by p-netm** [comment]
> If you try to access a URL such as `https://web.reveal-stage.smartregister.org/plans/update/bc78591f-df79-45a7-99e4-c1fbeda629e2`, pathToRedirectTo should be `plans/update/bc78591f-df79-45a7-99e4-c1fbeda629e2` but the code above produces something like `plans/update/:id`

I think this bug is in the connected private route. will also check from there.

**Comment by p-netm** [comment]
@moshthepitt I believe we can close this. [since](https://github.com/onaio/js-tools/pull/125)

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/js-tools/pull/125
