### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#658]
Our once high test coverage has fallen to 71.86%.  We need to lift this back up to >= 80% by the end of Q1.

These are the most untested parts of our codebase currently:

### Easy Pickings
1. - [x] `src/components/NotFound/index.tsx` ==> 0%
2. - [x] `src/components/formatting/ResponseAdherence.tsx` ==> 0%
3. - [x] `src/components/formatting/OneThreeSevenAdherence.tsx` ==> 0% (might be ok to just remove)
4. - [x] `src/components/DrillDownTableLinkedCell/index.tsx` ==> 33%
5. - [x] `src/containers/forms/OrganizationForm/index.tsx` ==> 40.63%
6. - [x] `src/containers/forms/JurisdictionSelect/index.tsx` ==> 43.75%
7. - [x] `src/containers/forms/PlanForm/tests/fixtures.ts` ==> 52% (need to remove unused fixtures)
8. - [x] `src/helpers/hooks.tsx` ==> 57.14%
9. - [x] `src/store/ducks/plans.ts` ==> 57.33%
10. - [x] `src/containers/forms/AssignTeamTableCell/index.tsx` ==> 59.38%
11. - [x] `src/containers/pages/IRS/JurisdictionsReport/helpers.ts` ==> 64.71%
12. - [x] `src/containers/forms/OrganizationSelect/index.tsx` ==> 67.65%
13. - [x] `src/containers/pages/InterventionPlan/IRS/index.tsx` ==> 69.02%

### Challenging

1. - [x] `src/index.tsx` ==> 0%
2. - [x] `src/serviceWorker.ts` ==> 0%
3. - [x] `src/configs/types.ts` ==> 0%
4. - [x] `src/containers/pages/InterventionPlan/IRS/plan/index.tsx` ==> 6.21%

**Comment by RayceeM** [comment]
I can pick up these:
`src/containers/forms/OrganizationForm/index.tsx ==> 40.63%`
 `src/containers/forms/JurisdictionSelect/index.tsx ==> 43.75%`
 `src/containers/forms/PlanForm/tests/fixtures.ts ==> 52% `

**Comment by cKellyDesign** [comment]
I can see about this one: 
4.  `src/containers/pages/InterventionPlan/IRS/plan/index.tsx` ==> 6.21%

**Comment by ciremusyoka** [comment]
8.  `src/helpers/hooks.tsx ==> 57.14%`
9. `src/store/ducks/plans.ts ==> 57.33%`
10. ` src/containers/forms/AssignTeamTableCell/index.tsx ==> 59.38%`

**Comment by p-netm** [comment]
Picked: 12, CH 2, CH 3

12. `src/containers/forms/OrganizationSelect/index.tsx ==> 67.65%`

CH2. `src/serviceWorker.ts ==> 0%`
CH3.  `src/configs/types.ts ==> 0%`

**Comment by DavisRayM** [comment]
I can pick up:

1. `src/components/NotFound/index.tsx`
2.  `src/components/formatting/ResponseAdherence.tsx`

**Comment by DavisRayM** [comment]
I can also try CH 1 `src/index.tsx`

**Comment by kelvin-muchiri** [comment]
Will do

4. `src/components/DrillDownTableLinkedCell/index.tsx `

11: `src/containers/pages/IRS/JurisdictionsReport/helpers.ts `

13: `src/containers/pages/InterventionPlan/IRS/index.tsx `

**Comment by moshthepitt** [comment]
All issues on this epic are now closed.
