### ISSUE TITLE
Add test coverage report

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#659]
- [x] Add test coverage report from automated tests
- [x] Auto-fail PRs that lower the test coverage

**Comment by kelvin-muchiri** [comment]
@moshthepitt @cKellyDesign @p-netm When we talk of lowering test coverage, what is the limit? The test coverage at the moment is lower than 100%, so what is the limit that each PR should meet at the moment?

**Comment by kelvin-muchiri** [comment]
Can we use the current figures as the threshold?
```
"coverageThreshold": {
      "global": {
        "branches": 55.83,
        "functions": 65.58,
        "lines": 72.36,
        "statements": 71.93
      }
    }
```

**Comment by p-netm** [comment]
> @moshthepitt @cKellyDesign @p-netm What threshold should we use? The test coverage at the moment is lower than 100%, so what is the threshold that each PR should meet at the moment?

I feel like we should aim for a 100% coverage, but i am comfortable with anything above 85%. **This is a personal opinion backed only by gut feeling**.

**Comment by p-netm** [comment]
> It's worth running coverage tools every so often and looking at these bits of untested code. Do they worry you that they aren't being tested? 

1. https://martinfowler.com/bliki/TestCoverage.html

**Comment by moshthepitt** [comment]
> What threshold should we use? The test coverage at the moment is lower than 100%, so what is the threshold that each PR should meet at the moment?

The Reveal Q1 goal and expectation from the client is at least 80% (this is be end of March 2020).

Right now we are lower than that.  I suggest that we use the current figures as the threshold, and adjust upwards after every milestone.

**Comment by moshthepitt** [comment]
@cKellyDesign @p-netm @kelvin-muchiri @ciremusyoka ^^

**Comment by cKellyDesign** [comment]
>  I suggest that we use the current figures as the threshold, and adjust upwards after every milestone.

@moshthepitt - I agree with this approach assuming we hit (at least) 80% by end of March
