### ISSUE TITLE
Assign plans page keeps on loading

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#660]
Initially reported [here](https://onaio.slack.com/archives/CBSU8L2SC/p1580787349010600) .
 
this page just spins when trying to view an assigned team or assign a team.
reveal-stage
plan name: RA MDA Campaign
Note that the plan end date has passed, but I don't think this should matter

![image](https://user-images.githubusercontent.com/28119869/73859822-b5ea4e00-484b-11ea-990f-015829470bbb.png)

**Comment by craigappl** [comment]
Continuing the conversation, I created a new Focus Investigation plan in the Lusaka area and the team assignment works. https://web.reveal-stage.smartregister.org/assign/75c3dac4-82d0-5a9e-8925-a59dbe1fd6ef
![image](https://user-images.githubusercontent.com/6067053/74436751-ffecb880-4e77-11ea-8737-ce61b8300f98.png)

**Comment by craigappl** [comment]
When I try to assign the plan to the operational area ra_ksh_2, it doesn't work. It just keeps spinning.
I think the problem has to do with the operational area hierarchy of the ra_zambia. Have a look at the plan https://web.reveal-stage.smartregister.org/plans/update/f34f590f-b498-506b-8a12-c6f01b538822 A1 ra_ksh_2 2020-02-13
https://web.reveal-stage.smartregister.org/assign/f34f590f-b498-506b-8a12-c6f01b538822

**Comment by p-netm** [comment]
What i know: 
- we are missing an ADM0 configuration `ra zambia`, this has been added in this unmerged branch #611
@moshthepitt @cKellyDesign Advise.

**Comment by cKellyDesign** [comment]
@p-netm if things work on that unmerged branch, please merge it. Otherwise we'll have to figure out how to add the configuration properly.

**Comment by p-netm** [comment]
@cKellyDesign The #611 has WIP tag, while i know that it adds what is missing, i do not know if it addresses the problem exhaustively or maybe enough. I think it would be better if either @cKellyDesign or @moshthepitt were to review and merge it.
