### ISSUE TITLE
Increase test coverage for IRS Plan

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#664]
Increase test coverage to be >= 85% for:

`src/containers/pages/InterventionPlan/IRS/plan/index.tsx ==> 6.21%`

Part of #658

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm @kelvin-muchiri - for the [IRS Jurisdiction Selection/Assignment](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx) we are using quite a few API calls via the [OpenSRP service](https://github.com/onaio/reveal-frontend/blob/master/src/services/opensrp/index.ts) ([1](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L260), [2](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L275), [4](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L348)) and the [SupersetConnector service](https://github.com/onaio/reveal-frontend/blob/master/src/services/superset/index.ts) ([3](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L292)), both use `fetch` but only the OpenSRP service is picking up mock fetch responses in the tests. The current tests don't fail, but they also don't mount anything other than the spinner component b/c none of the calls are being successfully mocked.

Any suggestions on how to mock all these calls together?

**Comment by moshthepitt** [comment]
>@moshthepitt @p-netm @kelvin-muchiri - for the IRS Jurisdiction Selection/Assignment we are using quite a few API calls via the OpenSRP service (1, 2, 4) and the SupersetConnector service (3), both use fetch but only the OpenSRP service is picking up mock fetch responses in the tests. The current tests don't fail, but they also don't mount anything other than the spinner component b/c none of the calls are being successfully mocked. (my progress so far)

> Any suggestions on how to mock all these calls together?

@cKellyDesign I think we have run into similar problems before when testing a component that does more than one fetch.  We ended up mocking the service instead of fetch e.g. [here](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/FocusInvestigation/single/tests/index.test.tsx#L179).  Maybe you can try that? i.e. mock OpenSRP service and SupersetFetch

**Comment by cKellyDesign** [comment]
> We ended up mocking the service instead of fetch e.g. here.

Aaah ok that should help, thanks @moshthepitt

**Comment by moshthepitt** [comment]
Fixed in #789
