### ISSUE TITLE
Increase test coverage for src/index.tsx

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#671]
Increase test coverage to be >= 85% for:

`src/index.tsx`

Part of #658

**Comment by DavisRayM** [comment]
@moshthepitt I'm not quite sure how to go about testing this file exactly. I've tried creating a sample on how it would look like based on its functionality [here](https://github.com/onaio/reveal-frontend/commit/4b32f71968606665a3659f21758321fe036bec89). Please have a look.

**Comment by moshthepitt** [comment]
@DavisRayM added some comments here https://github.com/onaio/reveal-frontend/commit/4b32f71968606665a3659f21758321fe036bec89
