### ISSUE TITLE
Use OpenSRP service from OpenSRP web

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#682]
Use https://github.com/OpenSRP/opensrp-web/tree/master/packages/opensrp-server-service instead of the OpenSRP service class defined in this repo.

**Comment by cKellyDesign** [comment]
@moshthepitt - Should the service be moved to `js-tools`? Or do you think it's appropriate to pull from OpenSRP Web repo because it's an OpenSRP-to-web utility?

**Comment by moshthepitt** [comment]
@cKellyDesign the intention is for the OpenSRP web packages to be published independently to npm under an "opensrp" (as opposed to ona) user.  So it is the same thing, but for OpenSRP specific things.

**Comment by cKellyDesign** [comment]
Perfect!

**Comment by moshthepitt** [comment]
@ciremusyoka The OpenSRP server service package was published last week: https://github.com/OpenSRP/opensrp-web/tree/master/packages/opensrp-server-service
