### ISSUE TITLE
Login page is still accessible to an authenticated user

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#687]
__Currently__:
An authenticated user could route to the login page successfully

__Ideally__:
A user should only be able to route to the login page if they are not logged in.

__scenarios__:
- an already logged in user; types the 'login' url in the address bar
- a user logs in from tab `a`; logs out from tab  `a`, thus the page on tab `a` is the login page. opens a new tab `b`, and successfully logs in, comes back to tab `a`. tab `a` is still on the login page

_Related to this_:
if a user successfully logs in from tab `a`, opens a new tab `b` while still logged in, switches back to tab `a` and logs out, if they circle back to tab `b` they will still be logged in

**Comment by moshthepitt** [comment]
Fixed by #715
