### ISSUE TITLE
Redirect User to a route after logging them in

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#688]
__Current behaviour__:
if a user session does not exist and say they try visiting `/teams`. the app directs them to the authentication page, after which, if they are successfully authenticated they are then redirected to the home page

__expected behavior__:
if a user session does not exist and say they try visiting `/teams`. the app directs them to the authentication page, after which, if they are successfully authenticated they are then redirected to the page that they had initially tried to access i.e. `/teams`

**Comment by moshthepitt** [comment]
Fixed in #734
