### ISSUE TITLE
Re-evaluate usage of Gisida

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#691]
With the coming of Gisdia 2.0 (or Gisida-views), and the uncertainty surrounding Gisida 1.0, we need to re-evaluate Reveal's usage of Gisida 1.0 and whether we need to take any action to ensure that the Reveal project is not affected negatively by the uncertainties surrounding Gisida.

### Things to consider

1. What do we do if Gisida 1.0 is deprecated?
2. Can Reveal's needs be met with Gisida 2.0?

**Comment by cKellyDesign** [comment]
The concept of Gisida Views (G2.0) is more of a product/service than a library like Gisida 1.x (G1.x).

> **1. What do we do if Gisida 1.0 is deprecated?**

Seems like we have three options:
1. Continue with G1.x even though it's deprecated
2. Expose (and use) the Map components/functionalities from G2.0 (maybe like OpenSRP Web)
3. Use [`react-mapbox-gl`](https://uber.github.io/react-map-gl/) to make new maps for Reveal

> **2. Can Reveal's needs be met with Gisida 2.0?**

Currently no. However, it's possible we could publish and install the components from Gisida 2.0 as packages, similar to `js-tools` and `opensrp-web`.

**Comment by moshthepitt** [comment]
> Expose (and use) the Map components/functionalities from G2.0 (maybe like OpenSRP Web)

@cKellyDesign I strongly believe that the Gisida team needs to do this.  In fact, I think our front-end dev approach from last year (at least) has been about making as much of our code re-usable as possible, and Gisida should continue with this tradition.

cc: @kahummer @ciremusyoka @kelvin-muchiri

**Comment by moshthepitt** [comment]
> Continue with G1.x even though it's deprecated 

From a strictly Reveal point of view, this would not be the right thing to do.

@p-netm @cKellyDesign Reveal needs to decide between these two:

> Expose (and use) the Map components/functionalities from G2.0 (maybe like OpenSRP Web)

or

> Use react-mapbox-gl to make new maps for Reveal

**Comment by moshthepitt** [comment]
There is some more context about this discussion here: https://onaio.slack.com/archives/C6HQ1E8H0/p1581680595018000

**Comment by moshthepitt** [comment]
We have since moved away from Gisida and now use [GisidaLite](https://github.com/onaio/reveal-frontend/blob/f1a31218e5b225ca450cd64b65021a3f165a1966/src/components/GisidaLite/index.tsx)
