### ISSUE TITLE
RVL-880 Map does not load on refreshing page

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#694]
map view in SiingleActiveFI loads fine on the first load, however when you either
- refresh the page or
- copy the url and paste in a new tab and load it

the map does not render, it just keeps on loading

more info: https://smartregister.atlassian.net/browse/RVL-880

**Comment by kelvin-muchiri** [comment]
@p-netm @moshthepitt @cKellyDesign The issues mentioned above is as a result of a user being logged out when you refresh the page or copy the URL in a new tab. Seems more like an authentication/session problem than the map itself.

**Comment by moshthepitt** [comment]
@kelvin-muchiri sorry there is additional context that may be missing.  This is to be tested against the #624 branch or http://web.reveal-stage.smartregister.org/ where we have session persistence.

@p-netm can help with set up if needed.

**Comment by moshthepitt** [comment]
Fixed by #708
