### ISSUE TITLE
RVL-878 - Selected plan should persist after refreshing 'Update Plan' page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#697]
When a user refreshes the Update Plan page for an existing plan (e.g. pressing control-R) the page reloads with no information. Note that the urls are the same , and that if the plan is saved, it overwrites the original plan

To reproduce:

1. Navigate to  Manage Plans
2. Click on a Plan
3. Click control-R when on the Update Plan page

As reported here https://smartregister.atlassian.net/browse/RVL-878

**Comment by ciremusyoka** [comment]
@moshthepitt  can we use session storage to persist the selected plans?

**Comment by moshthepitt** [comment]
@ciremusyoka I think we can do that later.

But right now there is probably a bug that makes it not work as expected.

How should it work?  When you visit such a URL - https://web.reveal-stage.smartregister.org/plans/update/24259e0e-a6bd-5972-a256-c8ace20457df it should be able to always populate the Redux store with what it needs, in the process doing any API fetches that it needs.

**Comment by cKellyDesign** [comment]
> can we use session storage to persist the selected plans?

@ciremusyoka @moshthepitt - To me this seems like a bit extra.

In my opinion, if a user refreshes the page with unsaved changes we should:

1. Throw an alert/growl warning (should also happen when navigating away with unsaved changes)

2. If the user choses to allow the refresh, the page should refresh rendering the plan data that is currently saved on the server

@craigappl does this seem like a reasonable expectation to set?

**Comment by moshthepitt** [comment]
@cKellyDesign that sounds like a good plan.  But I think it should go into a different issue - it may be possible to make a Formik helper that does this generically for all our forms.

**Comment by cKellyDesign** [comment]
> that sounds like a good plan. But I think it should go into a different issue

@moshthepitt - then should we close this issue?

**Comment by moshthepitt** [comment]
@cKellyDesign it will be closed by https://github.com/onaio/reveal-frontend/pull/710

**Comment by moshthepitt** [comment]
Closed by #710
