### ISSUE TITLE
Replace getPlanRecordsArray

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#702]
Following #699, we now need to fully replace `getPlanRecordsArray` with `plansArraySelector`.

**Comment by ciremusyoka** [comment]
@moshthepitt  The plans filter for `plansArraySelector` is done on `plansById`  while for `getPlanRecordsArray` is done on `planRecordsById`. There is a significant difference between [plansById](https://github.com/onaio/reveal-frontend/blob/8108f5f4d843c925ec2e934afb8a82d11efbeb4f/src/store/ducks/plans.ts#L70-L77) and [planRecordsById](https://github.com/onaio/reveal-frontend/blob/8108f5f4d843c925ec2e934afb8a82d11efbeb4f/src/store/ducks/plans.ts#L53-L66) making it hard to combine them.

To accommodate filtering of `planRecordsById` or any other objects inside plans, have refactored the [makePlansArraySelector](https://github.com/onaio/reveal-frontend/blob/8108f5f4d843c925ec2e934afb8a82d11efbeb4f/src/store/ducks/plans.ts#L667-L678) function and it's input-selectors. 

Any thoughts on how to make it better or is it OK?

**Comment by moshthepitt** [comment]
@ciremusyoka looks like it can work.  Go ahead and complete it and lets see what the PR looks like.

**Comment by moshthepitt** [comment]
Fixed in #733
