### ISSUE TITLE
Add flow diagram for the tiny backend server

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#705]
This comes from [here](https://github.com/onaio/reveal-frontend/pull/624#issuecomment-583019650).

>  It would be really nice to see a flow-diagram describing the authentication and logout flows implemented by this PR. Also any implementation docs would be good, but maybe these belong in the Gatekeeper package itself?

This diagram and a little README should go into the server directory.

**Comment by cKellyDesign** [comment]
@moshthepitt @p-netm  Please mention this ticket in the PR so it's linked 🙏

**Comment by moshthepitt** [comment]
Closed by #709
