### ISSUE TITLE
Development cycle after oauth change

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#711]
Problem statement:
The need to build every time you change the code.

**Why is this a problem**:
- increased development cycle expecially in cases where a developer might want to view the effect of a code changes on localhost.
- the build optimizes a lot of stuff and makes debugging a dreadful experience

**Silver lining**:
- will probably ensure tests to be top-notch - 

I mean to ask its something I will have to deal with, or is there a better way moving forward?

**Comment by moshthepitt** [comment]
@p-netm this is indeed a huge problem, I agree.

Do you think that there are workarounds (before we get a better solution) though?  For instance, if you are working only on the front end and on a part that does not interact with the server, you can work like we used to work before we had a server/backend, no?

**Comment by p-netm** [comment]
> , you can work like we used to work before we had a server/backend, no?

effort required for this, would be 
- modify the authorizationGrantType prop for the login components.
- modify the callback component.

yeah i think this reasonable, it won't be such a hustle for people already accustomed to the code.

**Comment by p-netm** [comment]
> Do you think that there are workarounds

I had tried to run the server on a different port  ot the react app. This would require tuning a few variables and modifying the redirect uri on the fly in the browser. This _does not work anymore_, the cookies is not sent back to the server. this is probably due to some `sameSite` policy, but am not quite sure.

**Comment by moshthepitt** [comment]
Cool, I am marking this as high priority, due end of Q1.  We need a better workflow.  Ideas on how we can improve this are welcome.

**Comment by cKellyDesign** [comment]
On average how long is it taking to rebuild?

Also, something to keep in the equation is the time we are saving when previously we had to re-login every time our code changed.

**Comment by moshthepitt** [comment]
> On average how long is it taking to rebuild?

About 30 seconds.

**Comment by moshthepitt** [comment]
I think for now #743 addresses this.  You do not have to build the frontend every time you want to see changes.
