### ISSUE TITLE
Plans on Reveal-Stage not visible under Onademo Account

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#712]
- [ ] The following two plans (FI: **A1 ra_ksh_2 2020-02-13** and IRS: **IRS 2020-01-31 Ona IRS** **Demo**) that are assigned to the account onademo, cannot be viewed under the monitor section. This is within reveal-stage.

**Comment by moshthepitt** [comment]
Moved to https://github.com/onaio/canopy/issues/819
