### ISSUE TITLE
Plans removed from Team still show on android client after sync

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#730]
- [ ] On the team assignment feature in reveal-stage, when a team is removed from a plan assignment, the plan still shows for a user who belongs to the team even after syncing. The ideal should be that when a team is removed from a plan, all users on the plan should not be able to see the plan on the android client.

**Comment by moshthepitt** [comment]
Moved to https://github.com/OpenSRP/opensrp-client-reveal/issues/651
