### ISSUE TITLE
Use @onaio/utils

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#739]
Use [@onaio/utils](https://github.com/onaio/js-tools/tree/master/packages/utils)

Remove the following

- [x] Remove FlexObject
- [x] Remove UpdateType
- [x] Remove percentage

Replace them with equivalent utils from @onaio/utils.

**Comment by kahummer** [comment]
@moshthepitt am experiencing a type issue when updating percentage
 ```
Type 'Result<string>' is not assignable to type 'string'.
  Type 'Failure' is not assignable to type 'string'.```.
After going into the types dts file and adding the type param to failure it works. I think this can be updated on js tools published.

**Comment by moshthepitt** [comment]
@kahummer could you share the problematic code - would like to see it?

Additionally, please create a js-tools issue that you'll then work on as part of closing this one

**Comment by kahummer** [comment]
src/helpers/indicators.tsx
![Screenshot from 2020-03-16 19-58-25](https://user-images.githubusercontent.com/16018123/76781989-a520e680-67c0-11ea-930c-74f88d582338.png)

**Comment by moshthepitt** [comment]
@kahummer I think you should look closer at what, exactly, the `percentage` function from @onaio/utils returns (it is not a string) and the [Result type](https://github.com/onaio/js-tools/blob/master/packages/utils/src/types.ts#L48). (read the blog post in the docstring).
