### ISSUE TITLE
RVL-908 Reveal Thailand translation feedback for 0.4.0 release

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#751]
This issue provides translation feedback on the 0.4.0 release to Thailand Production.

The string isn't translated on the login page. I think it's fine to keep the word "OpenSRP" as is in the button.
![image](https://user-images.githubusercontent.com/6067053/76977023-01cfee80-68f2-11ea-9966-a41cdd9ccaed.png)

This page is not translated
![image](https://user-images.githubusercontent.com/6067053/76977061-0ac0c000-68f2-11ea-81c4-51e76a7848fd.png)

This page is not translated
![image](https://user-images.githubusercontent.com/6067053/76977157-2e840600-68f2-11ea-926b-1b34f8ef435b.png)

The default search string isn't translated
![image](https://user-images.githubusercontent.com/6067053/76977542-b10cc580-68f2-11ea-966e-82cc7c8ce113.png)

Page N of N isn't translated. I don't know if it needs to be.
![image](https://user-images.githubusercontent.com/6067053/76977618-c84bb300-68f2-11ea-8f47-19919c452642.png)

The "Add Focus Investigation" button isn't translated in the top right.
![image](https://user-images.githubusercontent.com/6067053/76977699-e31e2780-68f2-11ea-869e-b8fb09419949.png)

The word "Complete" is not translated in this page
![image](https://user-images.githubusercontent.com/6067053/76977776-00eb8c80-68f3-11ea-80c6-b515c48699ba.png)

The word "Progress" isn't translated on the right bar. I think the English text on the right bar isn't translated because it is in English in the plan. Please confirm.
![image](https://user-images.githubusercontent.com/6067053/76977871-2a0c1d00-68f3-11ea-9788-4a49ab591e27.png)

The word "No Options" is not translated in the dropdown in the top right
![image](https://user-images.githubusercontent.com/6067053/76977957-4c059f80-68f3-11ea-89f9-40983c7d89b4.png)

The string "Date Completed" is not translated in this page. https://web.reveal-th.smartregister.org/focus-investigation/view/8de912fe-d9b9-50cd-92ac-7b9fce7df35c
![image](https://user-images.githubusercontent.com/6067053/76978101-7fe0c500-68f3-11ea-961c-b3ca323f08ce.png)

**Comment by moshthepitt** [comment]
@craigappl I think that the pages on the OpenSRP server need to be handled there. i.e. these two:

This:

![image](https://user-images.githubusercontent.com/6067053/76977061-0ac0c000-68f2-11ea-81c4-51e76a7848fd.png)

And this:

![image](https://user-images.githubusercontent.com/6067053/76977157-2e840600-68f2-11ea-926b-1b34f8ef435b.png)


cc: @Rkareko @githengi

**Comment by moshthepitt** [comment]
@p-netm I also think that the word "complete" in the little green label is also not translated.

**Comment by armageddon** [comment]
@craigappl 

RVL-908
