### ISSUE TITLE
Reveal Stage: Unable to assign MDA plans

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#752]
I just keep getting a spinner each time I try to assign MDA Plan 1 and MDA Plan 2.

https://web.reveal-stage.smartregister.org/assign/0b917315-f7e5-41e0-8571-8579a6998be2
![image](https://user-images.githubusercontent.com/6067053/77025014-42108a80-694d-11ea-996c-22aacec1ce4e.png)

https://web.reveal-stage.smartregister.org/assign/6cec8ae0-8aa6-410f-8d0d-532a5e5fffb5
![image](https://user-images.githubusercontent.com/6067053/77025047-5bb1d200-694d-11ea-8b12-ea293486f6d4.png)

I have posted these directly through the API as a workaround.

**Comment by moshthepitt** [comment]
@craigappl we don't have any "official" support for MDA plans in the web UI.  It is true that they may appear in various pages, but the web app has no awareness of MDA plans as a distinct type of plan in the same way that it does for FI and IRS.

Until we do the work to scope that (all the way to what a plan form for MDA needs to look like, to team assignment, to reporting), we will probably have a buggy experience dealing with MDA plans.

**Comment by craigappl** [comment]
Ok, no problem, I'll raise an issue in Jira for Akros to prioritize. Let's close this issue.
