### ISSUE TITLE
Investigate IRS Planning needs

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#76]
It seems that later this year Reveal will replace mSpray for the new IRS seasons.

We need to do a gap analysis of sorts to figure out what the Reveal web app may be lacking that is required for IRS reporting.

One way of doing this may be setting up a Reveal frontend instance that is set up to use mSpray data from the last IRS season (this data may need to be manipulated a little to fit the current data structures i.e, OpenSRP tasks, structures and jurisdictions).

**Comment by cKellyDesign** [comment]
@moshthepitt - do you feel comfortable closing this issue?

**Comment by moshthepitt** [comment]
I moved the reporting stuff here https://github.com/onaio/reveal-frontend/issues/179
