### ISSUE TITLE
RVL-347: Focus Investigation Status field should be renamed to "Focus Classification"

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#760]
**Acceptance Criteria**

- Log into Reaveal-Web and go to Plans > manage Plans > Add Plan 
- Section titled Focus Investigation Status should have been renamed to Focus Classification.

More info: https://smartregister.atlassian.net/browse/RVL-347

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/78762354-6e3b8c00-798c-11ea-8744-160b9a78b0d7.png)
Tested. Passed QA
