### ISSUE TITLE
Pending Thai Translations 

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#764]
Documentation of undone work for Thai translations
- `Add Focus Investigation` Button text.:
   might need clarification: on whether we are changing the text of this button to `Add plan` for all translations(meaning  in staging too), or is this change only suppoed to be in thai. link to translation [sheet](https://docs.google.com/spreadsheets/d/1ONHpPpuPxNW9_-vP8gTTcrVHTbKTT3WaN-cfdySeMCs/edit#gid=0&range=16:16) for the text in question.

- activeFIMap Reporting, the highlighed text is shown as it is received from superset.
![FIthai](https://user-images.githubusercontent.com/28119869/77524733-e720eb00-6e98-11ea-8d5d-f1af7f400e77.png)

- pagination text e.g. This Text is implicitely provided by react-table npm lib.
![translations](https://user-images.githubusercontent.com/28119869/77524801-07e94080-6e99-11ea-8a13-b7f786f68b11.png)

**Comment by moshthepitt** [comment]
![สร้างแผนปฏิบัติงานใหม่   Reveal](https://user-images.githubusercontent.com/372073/77746226-ac9c8700-702d-11ea-82ae-7fadbd704cf6.png)

**Comment by Naima-Bashir** [comment]
@p-netm @moshthepitt the IRS title; should it also be translated like the rest?

![image](https://user-images.githubusercontent.com/61143692/80103963-857a9c00-857e-11ea-8b64-53d83516ff83.png)

**Comment by Naima-Bashir** [comment]
@p-netm @moshthepitt this section is still showing english words 
![image](https://user-images.githubusercontent.com/61143692/80106313-60882800-8582-11ea-8223-404eb93f93f7.png)
http://localhost:3000/focus-investigation/map/ee7fa30d-9fe7-5b9c-9f18-a0d066726e3b

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/80106524-a513c380-8582-11ea-94bf-1cbc2c773a67.png)
@p-netm this is also still there 
http://localhost:3000/plans/new   : shouldn't this be in TH as well?

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/80106765-eefca980-8582-11ea-8edd-15b897b7a493.png)
more english sections

**Comment by moshthepitt** [comment]
Fixed in #1176
