### ISSUE TITLE
RVL-760 Enable WebUI Search for Plans in Plan and Monitor screens

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#772]
Enable search for the Plan entity in the Plan and Monitor screens as follows:

- [x] Plans > Manage Plans
- [x] Monitor > Focused Investigations
- [x] Monitor > IRS Reporting

**Acceptance Criteria:**

1. Allow a user to enter text within the search box
2. The results returned should filter results based on text entered within the search box

**Comment by moshthepitt** [comment]
@samkanga what is the priority for this?  (Medium, Low or High)

**Comment by samkanga** [comment]
@moshthepitt this is high priority. Its part of planned demo by Akros to WHO. They are required to send the presentation deck today and needed this information.

**Comment by samkanga** [comment]
@moshthepitt this is for scheduling in the next milestone.

**Comment by armageddon** [comment]
RVL-760

**Comment by cKellyDesign** [comment]
@kelvin-muchiri is this issue in progress? If so could you be sure to update its column on the `Reveal Canopy Work` Project? 🙏
