### ISSUE TITLE
Edit the percentages on the IRS Reporting Color Codes

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#774]
Edit the percentage ranges on the IRS Reporting color codes. Presently it appears as follows:
![image](https://user-images.githubusercontent.com/5908630/77992162-30a48680-732e-11ea-8b6d-ed6ab197682e.png)

They should read:
- [ ] Grey < 20%
- [ ] Red  20% - <75%
- [ ] Yellow 75% - < 90%
- [ ] Green 90% -  100%

This is to avoid the overlap of the figures

**Comment by moshthepitt** [comment]
@samkanga what is the change that is actually required?  What is the acceptance criteria?

To me it looks like you just want the text to change to include `<`?

**Comment by samkanga** [comment]
@moshthepitt that is correct.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/78763662-1d2c9780-798e-11ea-862c-e89eee047d4e.png)
Passed QA.
