### ISSUE TITLE
RVL-841 - Change in Nifi: The label for Measure for BCC should say "BCC Activities Complete" when we autogen plans

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#775]
https://smartregister.atlassian.net/browse/RVL-841
**Desired Change**

- [ ] The label that is sent through Nifi to BIOPHICS for FI Plans need to be updated from “**Measure for BCC**” to "**BCC Activities Complete**"

This ticket is the change to be made in Nifi so that the label matches in BIOPHICS and the WebUI. The change on the WebUI has been submitted as a separate ticket.

**Comment by armageddon** [comment]
RVL-841 @craigappl

**Comment by moshthepitt** [comment]
@kahummer it seems that we need to change this https://github.com/onaio/reveal-frontend/blob/23e7da6ae63f71c7e4add2d62010a281756a5e87/src/configs/lang.ts#L291 to say "BCC Activities Complete" instead of "Number of BCC Activities Completed"
