### ISSUE TITLE
RVL-806 Logout of OAuth when you hit logout button in WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#776]
https://smartregister.atlassian.net/browse/RVL-806
Signing out of the WebUI does not sign the user out of OpenSRP  OAuth session, and the user can log back in without re-entering their password

**Current behaviour**

1. Click the user name in top right corner of the WebUI and Click Sign out
2. 
![image](https://user-images.githubusercontent.com/5908630/77999010-aa427180-733a-11ea-854a-5882c048a410.png)

3. User is redirected to 
![image](https://user-images.githubusercontent.com/5908630/77999029-b29aac80-733a-11ea-8cb9-53773efdad61.png)

4. Click OpenSRP, user redirected to 
![image](https://user-images.githubusercontent.com/5908630/77999054-bdedd800-733a-11ea-8846-aadd1109e09f.png)

5. Click Authorize

6. User is logged in to the WebUI 

**Expected/Desired behaviour**

Step 1 should send the user to https://reveal-stage.smartregister.org/opensrp/logout.do. When the user reaccesses openSRP, s/he should have to reenter their password.

Try and make the web app also log out of the OpenSRP server. Perhaps when the web app is logging you out it can make an asynchronous request to https://reveal-stage.smartregister.org/opensrp/logout.do and thus we can assume you’re logged out of both systems. Although we must note that this 2nd option is not standard at all and is not part of the OAuth spec. We can only make it work due to the (lucky?) fact that we control both systems.

**Comment by kahummer** [comment]
@moshthepitt @p-netm 
To close this issue we need to logout the user from our reveal and opensrp (this is working well without the backend server using the connectedlogout component.
When using the backend server we have to load the connectedlogout component and move execution to the express server to destroy sessions and clear cookies. Running both of these 
```
<ConnectedLogout
                      {...{
                        logoutURL: 'https://reveal-stage.smartregister.org/opensrp/logout.do',
                        redirectPath: null,
                      }}
                    />;
                    window.location.href = EXPRESS_OAUTH_LOGOUT_URL;
```
Loads the connected logout and fails to go into the express server. I also tried running the redirect on js-tools but it doesn't work either.
I'll try create a custom component that implements what we have on js-tools but also redirects to express as a workaround

**Comment by moshthepitt** [comment]
@kahummer I think right now it roughly works like so:

1. Click logout
2. It sends you to express which clears its session
3. It brings you back to the frontend (I forget which specific component)

Can we not make it such that at step 3 it does a call to OpenSRP's logout URL? 

cc: @p-netm

**Comment by p-netm** [comment]
@moshthepitt @kahummer my thoughts.

So I believe step3 would be either; within the logoutUrl `express/logout` of express server or within the loginUrl `express/login` of express. Note that `express/logout` redirects to `redirect/login`. I think the question would then be if its possible to GET `opensrp/logout.do` in a way that we still retain controll of where to redirect to after. 

essentially this means that if we do the above anywhere within the server, it needs to be something like a fetch(not a redirect) where we can later disregard the response, and redirect to `express/login` or `FE/login`.

If its possible, we can perform the same operations as in js-tools where we open and close a window(This would overcome the session issue mentioned below), AFAIK we don't yet know how to do this.

Now that sounds simple enough, however, for the fetch to work its imperative to pass the OpenSRP session cookie, otherwise it would not make sense to logout something that OpenSRPServer does not know, this is the place I am most iffy about.

**Comment by p-netm** [comment]
> I'll try create a custom component that implements what we have on js-tools but also redirects to express as a workaround

IMO, I think this is sounds like the best option so far.

**Comment by cKellyDesign** [comment]
> I'll try create a custom component that implements what we have on js-tools but also redirects to express as a workaround

IMO, I think this is currently the most feasible and may eventually inspire something that gets added to js-tools.

**Comment by cKellyDesign** [comment]
It seems like if the server is meant for managing auth and sessions, it could make sense to make the request to `opensrp/logout.do` (by whatever method/protocol) on behalf of the frontend, and let the frontend execute business logic to handle what happens after ending the session (in this case, navigating to the login screen) via some simple callback function that gets passed to js-tools.

Maybe this could be a `onLogOutSuccess` method (so we should also have a `onLogOutError`) as props or params of existing js-tools packages (I'm not sure which one tho).

@kahummer @moshthepitt @p-netm - Thoughts? 🤔

**Comment by moshthepitt** [comment]
> It seems like if the server is meant for managing auth and sessions, it could make sense to make the request to opensrp/logout.do (by whatever method/protocol) on behalf of the frontend, and let the frontend execute business logic to handle what happens after ending the session (in this case, navigating to the login screen) via some simple callback function that gets passed to js-tools.

This makes sense, although ultimately I think `opensrp/logout.do` must be called from the frontend for you to be successfully logged out.

**Comment by cKellyDesign** [comment]
> ultimately I think opensrp/logout.do must be called from the frontend for you to be successfully logged out.

@moshthepitt - oh interesting, why is that?

**Comment by moshthepitt** [comment]
> @moshthepitt - oh interesting, why is that?

I think that the express server does not share the same session/context as the frontend when hitting the OpenSRP server.  Thus I suspect hitting `opensrp/logout.do` from express might not log you out.  But we should test this.

**Comment by cKellyDesign** [comment]
> I think that the express server does not share the same session/context as the frontend

That makes a lot of sense, we can test it but yeah it seems like it would be much easier to simply let the FE make that call for itself. 😄
