### ISSUE TITLE
Monitor Dashboards on Reveal Web Loads with Grayed out Structures

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#777]
Access to completed FI plans under Reveal Web > Monitor > Focus Investigation> Select plan

- [x] Loads a map with grayed structures. The map loads on the android client with tasks on it. See sample below:
![image](https://user-images.githubusercontent.com/5908630/78005241-f34af380-7343-11ea-85f3-548de16bd940.png)

- [x] Clicking on any of the indicators e.g. Family Registration, results into a spinner. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/78005699-9d2a8000-7344-11ea-9995-c72dbb6f93e3.png)

**Comment by samkanga** [comment]
@moshthepitt and @kahummer just learnt that the color coding on the structures is gray by default when the map loads. The color coding occurs when the indicators on the right are clicked.

**Comment by kahummer** [comment]
@samkanga  That then means the
The second issue is the one to be fixed ?

**Comment by samkanga** [comment]
Yes @kahummer

**Comment by kahummer** [comment]
@samkanga I think we should close this

**Comment by moshthepitt** [comment]
@kahummer is there not an open PR for this?  If yes then we can't close it until the PR is closed.  No?

**Comment by moshthepitt** [comment]
It seems that this is no longer an issue.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/78764283-00dd2a80-798f-11ea-8ac8-f0ceb4b5b548.png)
Yes this is no longer an issue. Tested; it has passed QA.
