### ISSUE TITLE
IRS Plan Page: Don't Load Jurisdictions From Superset

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#785]
The IRS Plan page should not load jurisdictions from Superset.  It should instead use the OpenSRP API.

**Comment by p-netm** [comment]
@moshthepitt @cKellyDesign There is a function like `getAncestorJurisdictionIds` which loops over the spray areas assigned to a plan and finds their level 0 ancestor location. 

Now I believe replacing this particular piece of functionality with OpenSRP would like so:
- get spray areas from plan : `this.props.plan.plan_jurisdiction_ids`
- for each of these spray areas recursively make calls in the form of 
`opensrp/rest/location/findByJurisdictionIds?jurisdiction_ids=parentID` for each  ancestor location until we get to the level 0 location.

Now the second step is untenable where the plan has alot of spray areas. 

This however would not be a concern if there is a guarantee that all spray areas assigned to a plan share a common level 0 location, such that i can just use the root ancestor for a single spray area and disregard the rest.

**Comment by moshthepitt** [comment]
> This however would not be a concern if there is a guarantee that all spray areas assigned to a plan share a common level 0 location, such that i can just use the root ancestor for a single spray area and disregard the rest.

Yes this is a valid assumption to make, and clearly state in the code via comments.  We do not expect one IRS plan to have more than one level 0 root parent jurisdictions.

**Comment by moshthepitt** [comment]
@p-netm @cKellyDesign ^^

**Comment by p-netm** [comment]
Cool, Thanks.

**Comment by moshthepitt** [comment]
Closed by #1003
