### ISSUE TITLE
[WEB] Assigning a plan to a team gives an internal server error

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#800]
STEPS:
1.Log into the web app
2. Go to assign tab
3. Select a plan eg IRS 2019-11-05 Ona Company Retreat Demo.
4. Click on the location and find the Assign teams section.
5.Assign a team eg OnaTest
6. Click save and observe what error you get.
EXPECTED RESULTS: One should successfully assign a team.
ACTUAL RESULTS: This error keeps on showing. See image below.
![image](https://user-images.githubusercontent.com/61143692/79232968-e1ec0600-7e70-11ea-8b5f-7ec2e16f17bb.png)
And the console shows this error:
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
main.795df8af.chunk.js:1 POST https://reveal-stage.smartregister.org/opensrp/rest/organization/assignLocationsAndPlans 500 (Internal Server Error)

**Comment by Naima-Bashir** [comment]
note: this happens on certain assignments.
I tested on IRS 2019-11-05 Ona Company Retreat Demo to  OnaTest and I get the error.
When I tried on Test_IRS 2020-03-30 to Onatest, it works

**Comment by kelvin-muchiri** [comment]
@p-netm @Naima-Bashir Tested this and seems the error was fixed.

**Comment by p-netm** [comment]
@kelvin-muchiri Thanks. Lets close this then. @Naima-Bashir please free to reopen this if QA is not satisfied.
