### ISSUE TITLE
[WEB] RVL-945 - Change the success pop up notification color from red to green

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#801]
STEPS:
1.Log into the web app
2. Go to assign tab
3. Select a plan eg Test_IRS 2020-03-30.
4. Click on the location and find the Assign teams section.
5.Assign a team eg OnaTest
6. Click save and observe what error you get.
EXPECTED RESULTS: Success 200 should be green not red
ACTUAL RESULTS: error is red. Very confusing.

**Comment by p-netm** [comment]
closed opensrp/opensrp-web#251

**Comment by p-netm** [comment]
@Naima-Bashir this too will require QA

**Comment by Naima-Bashir** [comment]
@p-netm just tested this. the 500 is still red.

**Comment by p-netm** [comment]
for a 500 the toast should be red, the goal here is that now, the toast is green if the assignment was succesful, a status code 500 denotes a failed assignment, That should probably be a new issue
