### ISSUE TITLE
RVL-131 See historical Index Cases on the web UI

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#810]
The target is to deliver this by the end of the next sprint:
https://smartregister.atlassian.net/browse/RVL-131

**Comment by moshthepitt** [comment]
@craigappl just wanted to note here that scoping is still needed.

**Comment by cKellyDesign** [comment]
The scoping in the Jira ticket seems pretty clear to me:

- [ ] `GET` all index case points for an operational area from OpenSRP endpoint
- [ ] Render relative index cases points as cross-hairs on the map
- [ ] Render a tool tip upon click of the index case point, include: Case number, Case Classification, and Date of Diagnosis
- [ ] Historical index case crosshairs should be white
- [ ] Active index case crosshairs should be gold (to match the `active` badge color)

Do we have an endpoint where we can get all the case indexes of an operational area?

**Comment by moshthepitt** [comment]
> Do we have an endpoint where we can get all the case indexes of an operational area?

These will come from Superset

**Comment by moshthepitt** [comment]
@p-netm so to get "Historical Index Cases" you will be pulling case confirmations in the same jurisdiction where the plan is marked as complete.

**Comment by p-netm** [comment]
@moshthepitt 

ok, so I will make a `get` to superset `targets_materialized_view` filter the records by `plan.jurisdiction_id` and action_code=`Case Confirmation` for all plans that are marked as complete?

using Thailand superset:
- I believe this data would come from `public.targets_materialized_view` 
- Assuming 1 is true, how do I filter the data for only complete plans, what column should I use, is it `task_business_status_map`?

**Comment by moshthepitt** [comment]
@p-netm putting this from our slack conversation as documentation:

- Lets use `task_structures_materialized_view`.  Filter by `plan.jurisdiction_id`, `action_code=Case Confirmation` and `task_business_status=Complete`
- One potential problem is that from that view we cannot tell if a plan is completed or not.  We'll keep that in mind as we work.
