### ISSUE TITLE
RVL-781 Fix the Thailand Sticky Sessions on the Load Balancer

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#811]
https://smartregister.atlassian.net/browse/RVL-781 Fix the Thailand Sticky Sessions on the Load Balancer

This is blocking the deployment to Namibia and Thailand

**Comment by moshthepitt** [comment]
@craigappl the fix for this is probably going to happen here: https://github.com/opensrp/opensrp-server-web/
