### ISSUE TITLE
RVL-890 - Web UI Review from Thailand

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#817]
@moshthepitt or @cKellyDesign , please complete this issue. We need to implement the changes recommended in the Web Ui Review from Thailand.

**Comment by moshthepitt** [comment]
More: https://smartregister.atlassian.net/browse/RVL-890

**Comment by moshthepitt** [comment]
@p-netm as noted in my last comment [here](https://smartregister.atlassian.net/browse/RVL-890), please note that we will be doing the search client side, while simultaneously sending an API request to the server with the search/filter parameters

**Comment by p-netm** [comment]
closed by #911
