### ISSUE TITLE
[WEB] The country drop down menu shows cities and countries 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#819]
1. Login to the website
2. Click on the IRS section
3. Scroll down to the bottom
4. Click on the create new plan at the bottom 
5. On the create new plan page, click on the country and scroll down to the drop down.
6. Observe whether the list shown is countries only.

EXPECTED RESULTS: There should be 2 separate sections for countries and cities
ACTUAL RESULTS:At the moment; the countries and cities are all in one drop down. They should be separated into 2 different drop down sections. See image below.
![image](https://user-images.githubusercontent.com/61143692/79875524-72d35c00-83f2-11ea-88a9-8b0f78d49de7.png)

**Comment by moshthepitt** [comment]
This works as expected.  It loads the root jurisdictions.  It just happens that some of the root jurisdictions on the stage server are not countries
