### ISSUE TITLE
Adding a new team gives a 401 error

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#827]
STEPS:

1. Login to the system: https://web.reveal-stage.smartregister.org/teams/new
2. Click on the teams section
3. Click on add new team 
4. Add the name of your team
5. Make the team active 
6. Click on save and observe if it saves or not.

![image](https://user-images.githubusercontent.com/61143692/80137040-4b73bf00-85ab-11ea-9264-a0c1cf5bb57f.png)

**Comment by p-netm** [comment]
@Naima This could be related to #782. when you get the 401 error try logging out and logging in again and retry
