### ISSUE TITLE
Filling the Plan Title only accepts IRS 2020-04-24 (Create New IRS Plan)

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#829]
STEPS:

1. Log into the system
2. Go to the IRS section
3. Click on the Create New IRS Plan button
4. Click on the Plan Title section
5.Try and fill in the Plan tiltle and observe if your text is filled. 

EXPECTED RESULTS: The selected words should be filled in the edit form section
ACTUAL RESULTS: A different text is filled when I select one. Eg I wanted to select Test Naima 24th April but then IRS 2020-04-24 is what was filled instead.
![image](https://user-images.githubusercontent.com/61143692/80205356-21fe7600-8633-11ea-9a9f-61bf6eb361de.png)

**Comment by moshthepitt** [comment]
Whenever you change certain fields: jurisdiction, date this field is recalculated.
