### ISSUE TITLE
RVL-249 - Importing data on coverage targets - System admin

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#837]
**Requirements:**
Some countries do not have coverage targets defined by the enumerated structure count as the denominator. In these cases, e.g. Namibia, coverage targets need to be imported into Reveal before the plan is made active.

The coverage targets would be at an operational unit level and could be stored in the OpenSRP settings field against each operational area.

A coverage file for the entire country, or at other levels above the Operational Area will be imported, and this cannot be done for each operational area individually.

**Notes:**

- A webUI need not be provided for this, but the ability to upload a CSV file should be provided. Worst case scenario would be a specification for a json file to be POSTed to the OpenSRP API.
- Settings are currently assigned to location but targets were downloaded based on team. The API supports both team and location level.
- A WebUI import would happen as part of the Manage Plan Workflow - the workflow to upload these targets would be:
1. **For FI-type plans** (this workflow is not MVP as it involves setting multiple different kinds of targets)
2. **For IRS-type plans** 
After selecting the areas for the intervention from the map or checklist box view, there is an upload/set targets button on this screen:
![image](https://user-images.githubusercontent.com/5908630/81257136-32ebb600-903b-11ea-99ef-b3dbcdec62e0.png)
The suggestion is that the uploaded targets once uploaded appear in a column on this view.

- These targets attributes could be plan specific. I.e. The target in Village A for ITN distribution in 2019 may be 220 houses covered and in 220 may be 245, so we would not want the target set in the 2019 plan to persist into the 2020 plan. 
- Would want to update/manage these settings for active plans

**Comment by craigappl** [comment]
@samkanga "A coverage file for the entire country, or at other levels above the Operational Area will be imported, and this cannot be done for each operational area individually." This seems to contradict the line above it. Does this just mean that we want to import a single coverage target for the entire plan?

**Comment by samkanga** [comment]
@craigappl the ticket above was as initially captured. From the conversations with Derek P and Livashan they agreed to include the structures count at Operational level. In my opinion the ticket RVL-249 is being covered in RVL-157.

**Comment by samkanga** [comment]
@moshthepitt we have agreed to merge this ticket with RVL-157. This is because the solution provides for upload of structure count values. The only ask is that the csv file should allow for nulls where say there are structure counts to be uploaded but no risk profiles for a jurisdiction.
