### ISSUE TITLE
RVL-952 - WebUI should allow filtering of plans by user

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#840]
**Description**
In Thailand it is imperative that users of the WebUI can filter plans by user. This will be implemented using a drop down/auto complete control where the user can select a username from a list. Ideally, the filter should have a way for the user to easily click a 'me' button . This will become important as Thailand adds all staff as 'users' of the WebUI. It is expected that role based access will NOT be implemented, but filtering of plans by user (and ideally logged in user )

**Comment by samkanga** [comment]
@p-netm there is a bug on this feature. See screenshot below:

**Comment by p-netm** [comment]
@samkanga above comment moved to an issue, #883.
