### ISSUE TITLE
RVL-936 Change logo on Reveal and Superset Thailand

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#843]
We need to change the logo to the Thailand instance of the web UI. The logo placement is in the issue. Please work with Pedro if you need a higher fidelity image from the BVBD.

https://smartregister.atlassian.net/browse/RVL-936

**Comment by moshthepitt** [comment]
### Proposed new direction

As a pre-requisite, please read this thread: https://onaio.slack.com/archives/CBSU8L2SC/p1589375814364900

The new proposal is to:

1. Replace the Reveal logo in the header with some text that reads "Reveal"
2. Place the Reveal and BVBD logos side by side on the home page.

![reveal-logos](https://user-images.githubusercontent.com/372073/82880002-75235b80-9f46-11ea-9afb-3a21c75600e8.png)

cc: @rowo

**Comment by samkanga** [comment]
Thank you @moshthepitt for sharing this. I will validate this by @craigappl since the client sent in a mock-up that had two logos on Thursday last week. See sample below:

![image](https://user-images.githubusercontent.com/5908630/82908278-70739d00-9f70-11ea-8f1c-2ea6fe2c7701.png)

**Comment by craigappl** [comment]
I sent this request over email today. Sorry for the delay.
