### ISSUE TITLE
web ui Thailand Feedback

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#847]
Track remaining work of towards having the web app look as in the below mockups.
![All Plans](https://user-images.githubusercontent.com/28119869/81429670-cec61080-9166-11ea-98b0-b7a7a4c2db8f.png)

- hiding columns filter ie. the customize columns button
- a filter where you can filter plans by user #840 
- move DrillDownTable to onaio/js-tools

==> Nice to have:
- DrillDown can have a drill up out of the box

**Comment by moshthepitt** [comment]
Seems this is fixed.  Please re-open if not.
