### ISSUE TITLE
There's a large search icon on the FI page, IRS plans page and Manage plans page

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#848]
Login to the system
Go to the FI page: https://web.reveal-stage.smartregister.org/focus-investigation
There's a There's a large search icon on the FI page
![image](https://user-images.githubusercontent.com/61143692/81554124-e849a100-938e-11ea-8152-27c1b464de0d.png)
![image](https://user-images.githubusercontent.com/61143692/81556559-3496e000-9393-11ea-9c00-e58babb9f010.png)

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/81556499-103b0380-9393-11ea-8fa2-3d0839ecaf8a.png)
On the Manage plans as well

**Comment by p-netm** [comment]
I have made a small change as a temporary fix for this, a permanent fix will be included in the next deployment.

**Comment by moshthepitt** [comment]
> I have made a small change as a temporary fix for this, a permanent fix will be included in the next deployment.

@p-netm could you provide details on what constitutes the small temp fix?

**Comment by p-netm** [comment]
> > I have made a small change as a temporary fix for this, a permanent fix will be included in the next deployment.
> 
> @p-netm could you provide details on what constitutes the small temp fix?

@moshthepitt I have removed the icon, I will be adding it back with updated styles in the coming deployment

**Comment by p-netm** [comment]
closed by #862
