### ISSUE TITLE
The display rows search section has a fixed 1. One cannot delete it and search for pages 19+

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#851]
1. Login to the system
2. Go to manage plans.
3. In the search page section: click on the search and try to search for 20+ 
4. EXPECTED RESULTS: One should be able to search for all 58 pages.
5. ACTUAL RESULTS: One cannot remove the number 1 and therefore can't search for 19+

![image](https://user-images.githubusercontent.com/61143692/81562551-b68c0680-939d-11ea-91a7-83e0355bcafe.png)

**Comment by kelvin-muchiri** [comment]
@moshthepitt This bug resides in the DrillDownTable package right?

**Comment by moshthepitt** [comment]
@kelvin-muchiri not sure what the bug is actually.  @p-netm thoughts?

**Comment by kelvin-muchiri** [comment]
@moshthepitt The page input field is not editable

**Comment by kelvin-muchiri** [comment]
@moshthepitt The page input field is not editable...at least **1** cannot be deleted

**Comment by moshthepitt** [comment]
Ah, cool.  Yes we might need to fix it on the [DrillDownTable](https://github.com/onaio/js-tools) component.  Please reach out to @p-netm for context on how things work.
