### ISSUE TITLE
RVL-954 Data is not populating on stage dashboards when submitted on mobile client

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#859]
Reveal web 0.4.2 Stage
Reveal Mobile 3.4.2
Plan: IRS 2020-04-24 Reuben test
OA: Akros_2

- I logged in to the mobile client and and captured data on the mobile client using the plan and operation area specified above. 
- Data was captured between the 4th and 12th of May, for different statuses. Sprayed, Not sprayed, not eligible etc.

![image](https://user-images.githubusercontent.com/5908630/82194395-6b26aa80-98ff-11ea-84d3-f611e7983dfb.png)

- However when I login to  the dashboard, no data is being populated there despite syncing multiple times on the mobile client and waiting for days.
![image](https://user-images.githubusercontent.com/5908630/82194482-901b1d80-98ff-11ea-8bc1-debede05ada5.png)

**Expected behavior:**

- All data submitted to a plan on the mobile client should be visible on the dashboards.

**Comment by moshthepitt** [comment]
Fixed during live fire testing
