### ISSUE TITLE
Add the Server Settings UI feature to Reveal Web UI

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#863]
The WHO PreGates Grant just released a feature the makes server settings configurable through a web UI. We need to integrate this into the Reveal Web UI so that server settings are configurable.

We need someone to evaluate the current state of the feature, compare it against the Reveal data model and identify how much work it will take.

**Comment by mberg** [comment]
What is this? I’m confused

**Comment by moshthepitt** [comment]
Was done
