### ISSUE TITLE
RVL-643 - Hide from Web UI all functionality that does not work - Thailand

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#865]
For the Thailand implementation, hide from Web UI, functionality that does not work, i.e:

1. Ability to create IRS plans 
3. Reactive plan creation through Web UI 

**Acceptance Criteria:**

1. Ability to create IRS plans  on Thailand implementation removed. Go to Plans > Manage Plans > Add Plan > Intervention Type
3.  “Case Triggered” option under “Focus Investigation Reason” when creating new plans for the Thailand implementation, removed. Go to Plans > Manage Plans > Add Plan > Focus Investigation Reason

**Comment by moshthepitt** [comment]
> Ability to create IRS plans

Looks like this will be done in https://github.com/onaio/reveal-frontend/issues/869

We'll try and get this done:  

- Reactive plan creation through Web UI

**Comment by moshthepitt** [comment]
Closed by #893
