### ISSUE TITLE
The ‘Case Confirmation' indicator should be not clickable 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#866]
- [x] The ‘Case Confirmation' indicator should be not clickable on/off and the index case should be always visible on the map and should be differentiated (text should be bold green) from the other indicators. See screenshot below:
![image](https://user-images.githubusercontent.com/5908630/82787594-6b7af480-9e6f-11ea-81fb-65bbfaa13e83.png)

**Acceptance criteria**

1. Go to Monitor > Focus Investigation > Select Plan 
2. Case Confirmation Indicator text should not be clickable
3. The Case confirmation text should be in bold green (same color as when selected)
4. Index Case should always show on the map when FI plan is selected

**Comment by moshthepitt** [comment]
Closed by #880
