### ISSUE TITLE
Family Registration’ indicators should be selected by default

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#868]
- [ ] The ‘Family Registration’ indicators should be selected by default when the page loads to show all structures in the focus area). See Screenshot below:

![image](https://user-images.githubusercontent.com/5908630/82787326-d841bf00-9e6e-11ea-8c28-af97046696e4.png)

**Acceptance criteria**

1. Go to Monitor > Focus Investigation > Select Plan
2. Family Registration indicator text should be in green (similar to selected indicator) and should show all structures in the focus areas.

**Comment by moshthepitt** [comment]
Closed by #880
