### ISSUE TITLE
RVL-526 - Restrict planning to only plan types available for the region

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#869]
The planning menu at the top of the WebUI has drop down options of 'manage plans' and 'irs'.

Manage plans takes you to a list of all plans for IRS and FI. From here you can create a new plan for IRS or FI

IRS takes you to a list of draft IRS plans (cannot see active or retired plans). You can create a new plan here for IRS or FI.

There needs to be distinct purpose for each option in this drop down menu. I suggest:

- [x] Adding a FI drop down option under the plan Menu that shows only FI draft plans and allows you to add a FI plan. 
- [x] Remove the IRS menu under Plan for Thailand

**Acceptance Criteria**

1. When I go to Plan menu on the WebUI, I should see the three options. Manage Plans, IRS and Focus Investigation.
2. Selection of IRS plan should only allow viewing of draft IRS plans and creation of new IRS plans.
3. Selection of Focus Investigation should only allow viewing of draft FI plans and creation of new FI plans.
4. For Thailand, the IRS option under plan should not be available.

**Comment by moshthepitt** [comment]
> When I go to Plan menu on the WebUI, I should see the three options. Manage Plans, IRS and Focus Investigation.
Selection of IRS plan should only allow viewing of draft IRS plans and creation of new IRS plans.
Selection of Focus Investigation should only allow viewing of draft FI plans and creation of new FI plans.

@samkanga we likely will not do it this way.

I would rather have one "Manage Plans" page, and when you view it you only see the plans that are enabled for you.

---

@ciremusyoka  ^^

**Comment by moshthepitt** [comment]
Closed by #893

**Comment by samkanga** [comment]
@moshthepitt I would like to re-open this ticket based on your last comment. Its OK to have a common manage page but there was additional requirement to have additional menu for Focused Investigation, similar to the IRS one under plan that would provide access to all the FI draft plans.

**Comment by moshthepitt** [comment]
> @moshthepitt I would like to re-open this ticket based on your last comment. Its OK to have a common manage page but there was additional requirement to have additional menu for Focused Investigation, similar to the IRS one under plan that would provide access to all the FI draft plans and be able to create new FI plans.

@samkanga I don't agree with this.  For us to consider it further, could we please have a plan, with mockups, on how this would work with the looming dynamic plans.  

> Separately, could you confirm if the IRS option for the Thailand WebUI was removed?

We have not deployed to Thailand.

**Comment by moshthepitt** [comment]
@samkanga we are still waiting for more information about this from you as noted above.
