### ISSUE TITLE
Refactor Plan Assignment Page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#870]
Things to look into:

- [ ]  The component is a giant piece of code that needs to be broken down
- [ ]  The page needs to use the URL when drilling down through the jurisdictions
- [ ]  We need to audit the calls made to the OpenSRP API to see if all are necessary
- [ ]  We need to remove the need to make an API call to Superset

**Comment by Naima-Bashir** [comment]
The back button and drill down functionality has passed QA
We need to remove the need to make an API call to Superset - known issue: https://github.com/onaio/reveal-frontend/issues/939
