### ISSUE TITLE
The filter and sort buttons change the length of the columns when clicked

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#874]
Login to the web app.
Click on manage plans
Play with the filter and sort buttons to observe if the length of the columns change as you click. 
We can use css to fix this

![image](https://user-images.githubusercontent.com/61143692/83024413-07a32800-a037-11ea-8df8-fca48a4c4963.png)

**Comment by p-netm** [comment]
closed by #911
