### ISSUE TITLE
Fix search in teams and practitioners

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#881]
Search does not seem to be working on:

- http://localhost:3000/practitioners
- http://localhost:3000/teams

We get an error that is something like:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

**Comment by Naima-Bashir** [comment]
Noticed this as well

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/83503805-51bf5a00-a4cc-11ea-9e8f-eb484ed37a1c.png)
the search functionality does not work on the Practitioner's section as well.
@p-netm

**Comment by p-netm** [comment]
yeap will add that in a a future pr. @Naima-Bashir

**Comment by Naima-Bashir** [comment]
good to know. Thanks
