### ISSUE TITLE
Team assignment start date should be now()

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#882]
The team assignment through the web UI uses the plan's startDate as what we need to post. The OpenSRP API doesn't support retroactive plan assignment. All plan assignments need to be done based on the current datetime. Otherwise, it returns a 500 error.

Steps to reproduce on reveal-stage
- Click Assign
- Choose the MDA Demo Plan 1
- Drill down and choose to assign the Nchalenge1 team to ra_ksh_5
- Click Assign Team
- Click Save Assignments
(Get a 500 error)

JSON Posted:
```
[{"jurisdiction":"c138d117-bf30-48b2-804e-964b4891ea51","organization":"97809856-5c31-5a4e-abb2-efe152a0b715","plan":"0b917315-f7e5-41e0-8571-8579a6998be2","fromDate":"2020-03-28T00:00:00.000Z","toDate":"2020-08-30T00:00:00.000Z"}]
```
The fromDate should be the current datetime value
```
[{"jurisdiction":"c138d117-bf30-48b2-804e-964b4891ea51","organization":"97809856-5c31-5a4e-abb2-efe152a0b715","plan":"0b917315-f7e5-41e0-8571-8579a6998be2","fromDate":"2020-06-01T00:00:00.000Z","toDate":"2020-08-30T00:00:00.000Z"}]
```

Changes:
1. Change the fromDate to be the current datetime

**Comment by moshthepitt** [comment]
@craigappl @samkanga what shoould happen if the plan end date is in the past?

**Comment by samkanga** [comment]
@moshthepitt my initial thoughts are that the plan with a date in the past is expired. I am not sure we have a use case where we would need to assign an expired plan to a team but I will defer this to @craigappl .

**Comment by moshthepitt** [comment]
@craigappl @samkanga  It seems, then, that we should not allow team assignment when the plan end date is in the past?

**Comment by craigappl** [comment]
We do not have a use case to accommodate team assignment for plan end dates that have passed. I incorrectly assumed that the Assign plans page filters for Active plans. https://web.reveal-stage.smartregister.org/assign

@samkanga I'll start a thread on the DSME Reveal Internal channel.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/85397407-29230100-b55c-11ea-8e4e-2d31291e8c22.png)
this has passed QA.
Same with editing an assignment.
![image](https://user-images.githubusercontent.com/61143692/85397561-67b8bb80-b55c-11ea-8081-cd0794e81677.png)
