### ISSUE TITLE
The tag at the footer of the page does not update per new release

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#886]
1. Login to the webapp
2. Scroll down to the footer and observe if the tag has been updated.
3. Currently we are in release: https://github.com/onaio/reveal-frontend/releases/tag/v0.5.0-rc2
4. But it shows reveal-frontend: 0.5.0-rc1

![image](https://user-images.githubusercontent.com/61143692/83511365-3443bd80-a4d7-11ea-817c-aab6033c7a22.png)

**Comment by moshthepitt** [comment]
This is manually updated
