### ISSUE TITLE
RVL-157 - CSV import for risk files

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#892]
This document provides details on how to upload the risk and structure count csv and how to use the uploaded information. It includes mock-ups for the risk profile  and the number of structure upload alongside the risk evaluation workflow.

Some points to note are:
- The MVP will focus on one risk profile
- The Upload of the risk profile and number of structures document will be manual for this step

Below is the desired workflow:

1. A user will be provided with a template pre-filled with jurisdiction IDs and names and with provision to capture the risk profile and the structure count. See sample template mock-up below: 
2.  ![image](https://user-images.githubusercontent.com/5908630/83618189-c230ae80-a592-11ea-8bf9-3131034ff3c8.png)
3. The user will fill in the risk profile (the MVP will provide one variable) and provide an option to provide the structure count. Where the structure count already exists in the system, the structure count uploaded will override what exists in the system.
4. Ona will facilitate the manual upload of the completed file into the system from the backend.
5. On the WebUI, the user will select the create plan button and create an IRS plan and have an option to move to the risk threshold page.
6. The page will load with a risk threshold slider that automatically calculates the number of structures that meet the set threshold. See mock-up below:
7. ![image](https://user-images.githubusercontent.com/5908630/83618265-e2f90400-a592-11ea-8bba-74e83ad7d18f.png)
8. On clicking on the “continue to next step” button, the user is provided with a map with the jurisdictions affected by the risk threshold selection in the earlier step. The map allows the user to drill down the maps until they get to the hierarchy level that is the immediate parent of the individual focus areas. Note, you cannot go back once the process has started, but you can start afresh. Selection of the risk check-box allows one to toggle on and off a risk layer allowing one to see the jurisdictions affected by the risk profile. The step further provides a breakdown of the number of structures in each of the jurisdiction. Each of the pages will also provide the total number of structures in the district. See mock-up below:
9. ![image](https://user-images.githubusercontent.com/5908630/83762267-08b00700-a680-11ea-93b6-be6d488390b7.png)
10. On clicking on the “continue to next step” button, the user gets the function allowing editing of the targeted jurisdictions based on the available resources. This is possible through the “change target status” button. It allows one to manually remove areas that may have been automatically selected based on the risk profile but that can not be supported by the available resources. The status change is made from targeted to Not targeted and vice versa. A note is also made on whether the status update was through auto-selection or by a user-change. See sample mock-up below:
11. ![image](https://user-images.githubusercontent.com/5908630/83618326-fc9a4b80-a592-11ea-92d8-a6413a952b3c.png)
12. Once the jurisdiction selection is complete, the process completes with the user being presented with the option to assign team to the plan.

**Comment by Naima-Bashir** [comment]
NOT DONE: 
1.  The Acion column where one can be able to change the target status.

![image](https://user-images.githubusercontent.com/61143692/88377331-a46c1280-cda7-11ea-9c33-47f47bf91cf4.png)
![image](https://user-images.githubusercontent.com/61143692/88377365-b5b51f00-cda7-11ea-8d64-49f9b4e0daab.png)

**Comment by moshthepitt** [comment]
Fially closed out by #1161, #1083, #1095, #1076, #984, #929, among others
