### ISSUE TITLE
RVL-954 - IRS Plan does not show submitted data from android client on Stage

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#895]
- [ ] The IRS plans on reveal stage do not display the data submitted against a plan from the android client. It return the text "No records found". See sample screenshot below:

![image](https://user-images.githubusercontent.com/5908630/83753028-355d2200-a672-11ea-9c4e-2c1fc0f59b6c.png)

**Comment by craigappl** [comment]
@samkanga , the next thing to do from our side is to get an understanding of the underlying issue.

1. Try to load that same plan and confirm.
2. Open up the browser console and see if there's a failure fetching data from Superset
![image](https://user-images.githubusercontent.com/6067053/83834759-fe9fff80-a6a3-11ea-8259-4054c79590b2.png)

So with this we can see in the bottom of the page there is a 400 error. Click on that in the bottom and copy the URL:
![image](https://user-images.githubusercontent.com/6067053/83834841-2727f980-a6a4-11ea-8c7d-6bfb80b5f93a.png)

3. Open it in a new browser and see if there's any information we can use to better triage:
![image](https://user-images.githubusercontent.com/6067053/83834899-47f04f00-a6a4-11ea-885f-b777f737c82d.png)
So with this, we can see that the temp.zambia_irs_jurisdictions doesn't exist.
4. Open up Superset and see if we have that source
![image](https://user-images.githubusercontent.com/6067053/83835035-9c93ca00-a6a4-11ea-87fd-95063eca37df.png)

Here, we see that we don't have a temp database access in SQLite. Let's look for that datasource in slice

5. We see that source on this slice
![image](https://user-images.githubusercontent.com/6067053/83835183-f4323580-a6a4-11ea-8274-774f03ce039a.png)

6. When we click on it we get the same error.
![image](https://user-images.githubusercontent.com/6067053/83835209-06ac6f00-a6a5-11ea-8a8f-4ea5327c76b6.png)


So, we need @moshthepitt  to have a look.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/84745772-b9da6980-afbd-11ea-9382-fb3bfd7aa1f3.png)
@samkanga this is still there on stage

**Comment by moshthepitt** [comment]
Fixed during live fire testing.
