### ISSUE TITLE
Add Web UI to Upload Configurable Forms

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#900]
We need to create the following web UI pages for the following functionalities 

1.View all releases page #903 
2. View release related files #904
3. View JSON widget validators #905
4. Client form upload, edit #901 
5. Release making #902 

This [document](https://docs.google.com/document/d/1vRv3GpivpHQ8wmGDV_2PEmK5tiz4hvTeMkBX3WUSoNQ/edit?pli=1#) will help in case more information is required.

**Comment by moshthepitt** [comment]
Fixed by #949

**Comment by Naima-Bashir** [comment]
1.View all releases page #903    --passed QA
2. View release related files #904     --passed QA
3. View JSON widget validators #905    --passed QA
4. Client form upload, edit #901   --passed QA
