### ISSUE TITLE
Add Form upload & manipulation pages 

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#901]
The endpoint to interact with is the `rest/clientForm`

1. A file upload page
   * We will need to support the entry of the following fields
      * Form name (Required)
      * Modules (optional)
      * The file to be uploaded
   * This is a multi part upload. More on how to interact with the endpoint is defined [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1507000340/OpenSRP+Document+Configurability#2.-Client-Form-endpoint). 

2. A file edit page
    * All fields except the file_upload should be disabled. 
    * We need to have support for a file download for offline edit.
    * Upload the edited file using the same procedure as the new file upload.
    * We also need to display any json widget validation rules defined for the main form that the file being edited is related to.

3. Have an alert/notifications section to display any errors that might occur

Attached are the wire frames for these pages
![Edit Upload File](https://user-images.githubusercontent.com/4817531/84475446-3e16af00-ac95-11ea-807d-b1ebc032ddb4.png)
![Upload file](https://user-images.githubusercontent.com/4817531/84475448-40790900-ac95-11ea-8df3-173ad5765224.png)

**Comment by moshthepitt** [comment]
@dubdabasoduba @craigappl do we have wireframes or a design for this page in the web UI?

**Comment by moshthepitt** [comment]
Fixed by #949
