### ISSUE TITLE
Enabling the "making a release" functionality

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#902]
The endpoint to interact with is the `rest/manifest`

1. We will generate the manifest after the make release button on the view drafts files page is clicked.

2. The web client will be responsible for sending in the following form properties

    *Json - This holds the form_verison & identifiers  which can easily be found on the drafts in the draft file page. This will then be combined with the properties mentioned above to create the complete manifest and save it. 

3. How to interact with the API to achieve the above mentioned requirements is defined [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1507000340/OpenSRP+Document+Configurability#1.-Manifest-Endpoint)

4. Have an alert/notifications section to display any errors that might occur

**Comment by moshthepitt** [comment]
@dubdabasoduba is there any documentation available about this API endpoint?

**Comment by moshthepitt** [comment]
@dubdabasoduba @craigappl do we have wireframes or a design for this page in the web UI?

**Comment by moshthepitt** [comment]
Fixed by #949
