### ISSUE TITLE
Create view all releases page

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#903]
1.  This page should list all releases.
    * Each row on this list will have a view files action button.

2. We should also have a file upload button. This button takes you to the new form upload page. 

Wire frames 
![View all releases](https://user-images.githubusercontent.com/4817531/84475734-b4b3ac80-ac95-11ea-95f4-abd7fd14e9bb.png)

**Comment by moshthepitt** [comment]
Fixed by #949
