### ISSUE TITLE
Create view release related files

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#904]
1.  This page should list all the files related to the release selected.

2. Every row in this page should have the action button Upload & Download button.
    * `Upload button` - This takes the user to the upload edited file page
    * `Download button`  - Allows the user to download the file for offline viewing editing.

Wire frames
![View release files](https://user-images.githubusercontent.com/4817531/84476046-402d3d80-ac96-11ea-8edd-dc3eb93e9393.png)

**Comment by moshthepitt** [comment]
Fixed by #949
