### ISSUE TITLE
Create view JSON widget validators page

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#905]
1.  This page will list all the JSON widget validators

2. Every row in this page should have the action button Upload & Download button.
    * `Upload button` - This takes the user to the `upload edited file page`.This should also in the background update the hidden field on the upload edited file page `is json validator` to true . 
        * This action will help remove the responsibility of suggesting the file type from the user. 
    * `Download button`  - Allows the user to download the file for offline viewing editing. 

Wireframes
![View JSON validators](https://user-images.githubusercontent.com/4817531/84476501-ebd68d80-ac96-11ea-8843-280daed490fe.png)

**Comment by Naima-Bashir** [comment]
This has passed QA.
1. One can download the JSON files. There is a bug I have identified; see here- https://github.com/onaio/reveal-frontend/issues/965
2. One can edit forms
3. One can search for JSON files.
4. One can filter the files by name, version or identifier as well.

**Comment by moshthepitt** [comment]
Fixed by #949
