### ISSUE TITLE
Assign Plans Option on Zambia Production WebUI keeps loading

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#908]
- [ ] When I select a plan for team assignment under the assign menu on the Zambia production instance, it keep loading and does not open the plan assignment page. See screenshot below:

![image](https://user-images.githubusercontent.com/5908630/84651189-2e57ce80-af12-11ea-8c86-263014feb8c7.png)
 The browser does not return any error on the console

**Comment by p-netm** [comment]
seems adding the top jurisdiction description did not fix this.

**Comment by samkanga** [comment]
@p-netm the un-ending load is also on the Plan>IRS page.

**Comment by moshthepitt** [comment]
I think we don't have any geojson for the "Zambia" jurisdiction.  Will try and get that in and then see

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/84744244-a4fcd680-afbb-11ea-88b9-aa3c573c24cb.png)
I'm getting the same on my end as well. @samkanga @moshthepitt

**Comment by Naima-Bashir** [comment]
This has passed QA on stage. Will retest on zambia later on.
