### ISSUE TITLE
CSV import of arbitrary jurisdiction metadata

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#909]
We want to create a simple [Formik](https://jaredpalmer.com/formik/) form that takes a CSV file upload.

The CSV file will contain these standard fields:

- jurisdiction_id
- jurisdiction_name

Any other field that the CSV contains will be considered to be metadata for the jurisdiction that it is attached to.

On submitting the form, we will use [papaparse](https://www.papaparse.com/) to convert the CSV to JSON and then submit it using the [OpenSRP server service](https://github.com/OpenSRP/opensrp-web/tree/master/packages/opensrp-server-service) so the OpenSRP server settings API endpoint.

This is part of https://github.com/onaio/reveal-frontend/issues/892

**Comment by moshthepitt** [comment]
If a row/record in the CSV file does not have `jurisdiction_id` then it should be ignored

**Comment by moshthepitt** [comment]
Some extra info from a slack conversation with Roger and Sam K:

> A sample CSV file may have these columns jurisdiction_id, jurisdiction_name, risk_2019 and another may have jurisdiction_id, jurisdiction_name, risk_2019, target_2019  etc.  All of the values in the columns not named jurisdiction_id or jurisdiction_name will be uploaded and attached to jurisdictions (and will overwrite anything previously uploaded).

> When uploaded, the name of the metadata field on the description will be prefixed by something so that the web app can identify such metadata and make its retrieval possible.  So this means we will be able to present a list to the user of metadata that was previously uploaded, and should they want, we can allow them to view or download the metadata

**Comment by Naima-Bashir** [comment]
This has failed QA.
![image](https://user-images.githubusercontent.com/61143692/85377841-5498f200-b542-11ea-96b1-fb2ab9c72f2f.png)
@gmwasi @moshthepitt

**Comment by moshthepitt** [comment]
@Naima-Bashir do you have more details?

**Comment by Naima-Bashir** [comment]
@moshthepitt https://github.com/onaio/reveal-frontend/issues/940   
here is a more detailed issue
