### ISSUE TITLE
Improve performance of IRS Plan Page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#913]
Right now we can potentially make hundreds or thousands of calls to the OpenSRP API when trying to [fetch assignments](https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/InterventionPlan/IRS/plan/index.tsx#L283).  It seems that we can make this better performing by replacing the many call with just one i.e. fetching all assignments for the plan using something like `assignedLocationsAndPlans?plan=identifier`.

**Comment by moshthepitt** [comment]
Right now we are calling this endpoint https://reveal-zm.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans/23ee9e55-8824-44b1-a826-352dfe2d5c96?plan=f1c3aedf-2c7b-563c-b1e2-5f0af070002b which in Zambia results is hundreds of calls to OpenSRP.

**Comment by Naima-Bashir** [comment]
This has passed QA on stage

**Comment by moshthepitt** [comment]
Fixed by #929 and #983
