### ISSUE TITLE
Placeholder: View data from risk file import

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#923]
This is a placeholder to note that we need to add the web UI to view data from the risk file import.

**Comment by moshthepitt** [comment]
After https://github.com/onaio/reveal-frontend/pull/922 we have a way to upload Jurisdiction Metadata, next we need a way to:

1. retrieve specific to the identifier e.g. risk2019 for all jurisdictions
2. put this in the redux store
3. allow a user to download as CSV
