### ISSUE TITLE
Add space between logo and app version

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#928]
Lets add some space between the bottom logo and the app version.

![IRS_2020_06_18_Test_Script_Plan_Reveal_Stage](https://user-images.githubusercontent.com/372073/85191420-7d618300-b2c7-11ea-8c9b-a203ec40a31c.png)

**Comment by p-netm** [comment]
@moshthepitt how's this:
![image](https://user-images.githubusercontent.com/28119869/85263723-44b4db80-b478-11ea-88c9-a794ae13a496.png)

**Comment by moshthepitt** [comment]
LGTM @p-netm
