### ISSUE TITLE
RVL-1002 - Active FI Map Issues

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#930]
- Tracking issues around using the map in the active FI map page
  - Fix map jankiness(probably because it gets mounted with each of the component's rerenders.)
      - takes a while to show up, 
      - rerenders the whole map when props change
  - Render a tool tip upon click of the index case point, include: Case number, Case Classification, and Date of Diagnosis

**Comment by moshthepitt** [comment]
This is blocked because it needs Case number, Case Classification, and Date of Diagnosis added to the database view that the web UI uses.

**Comment by moshthepitt** [comment]
Closed by #1096
