### ISSUE TITLE
How to edit plan team assignment dates

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#931]
![after](https://user-images.githubusercontent.com/372073/85257747-02d36780-b46f-11ea-89ac-f0d4a2809ca6.png)

Right now when we assign teams, we set the start date to now() or the plan date - whichever is later.  And we set the end date to the plan end date.

Should we make it possible to set these dates manually?  If so, how?

**Comment by samkanga** [comment]
@moshthepitt my vote would be to keep maintain the plan assignment as is. I have not come across a scenario where a team is assigned to a team for a duration that is less than the duration of the plan. I will @craigappl and @rowo share their thoughts.

**Comment by craigappl** [comment]
@moshthepitt Keep it as is, we do not have a customer requirement for that.

**Comment by moshthepitt** [comment]
Closing as it does not seem like something we should do.

For documentation:

- For new assignments, the start date is now() and the end date if the date of the plan
- For invalidating assignments, the end date is set to yesterday
