### ISSUE TITLE
Unable to do team assignment at jurisdictions below country level

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#935]
- [ ] I created a plan named **IRS 2020-06-22Test24** under raZambia on reveal stage and was able to select the lower level jurisdictions. However, at the team assignment level the page only provides the assignment for the country level and not for the areas below it. See screenshots below:
![image](https://user-images.githubusercontent.com/5908630/85276308-4091b980-b48a-11ea-89a2-90521126a8c2.png)

**Comment by moshthepitt** [comment]
@samkanga this happens for new plans as documented here https://github.com/onaio/reveal-frontend/pull/929.  The solution is to develop and use an OpenSRP API to get the plan hierarchy, i.e. https://github.com/OpenSRP/opensrp-server-web/issues/396

**Comment by samkanga** [comment]
@moshthepitt this means we can only work with existing plans. Right?

**Comment by moshthepitt** [comment]
@samkanga  No it means that for new plans we have to wait for the plan hierarchy to be created on the data warehouse.

**Comment by Naima-Bashir** [comment]
This has passed QA. We now have a drill down of the selected jurisdictions. 
For plans that are new: one has to wait for a few minutes to be able to assign.
See here: https://github.com/onaio/reveal-frontend/issues/939
![image](https://user-images.githubusercontent.com/61143692/85398328-bb77d480-b55d-11ea-921c-de118d89c601.png)
