### ISSUE TITLE
The checkbox for selecting jurisdictions on the IRS page doesn't work  RVL-980

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#938]
Login to the app
Click on IRS
Select a draft plan
When the map loads, scroll down to the jurisdictions 
Try and select the checkboxes.
Observe if they can be selected.
RESULTS: The checkboxes don't work

![image](https://user-images.githubusercontent.com/61143692/85306451-29b58c00-b4b7-11ea-9c5e-293a0135c68c.png)

**Comment by moshthepitt** [comment]
Fixed by #977
