### ISSUE TITLE
The assign page does not work on newly created plans-RVL-981

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#939]
Environment: stage 
https://web.reveal-stage.smartregister.org/plans/list
Login to the webapp
Create a new plan- IRS and the focus area.
After saving it
Click on assign on the newly created plan and observe the error
RESULTS: The error that is seen on the assign page is: Unable to the plan jurisdiction hierarchy
![image](https://user-images.githubusercontent.com/61143692/85385377-ead11600-b54a-11ea-9816-868ad612c511.png)

**Comment by Naima-Bashir** [comment]
update: that is expected. It is because we have to wait a few minutes for the plan hierarchy to be built on the Canopy data warehouse. It will be fixed after  
update: after afew minutes, the newly created plan can now be assigned
![image](https://user-images.githubusercontent.com/61143692/85386996-f4f41400-b54c-11ea-9ecf-e58807c94cf8.png)

**Comment by moshthepitt** [comment]
Fixed by #1003
