### ISSUE TITLE
The is a 401 error when one clicks on other plans in the FI map page  RVL-983

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#941]
Login to the webapp
Go to a specific FI
Drill down till you see a map
When the map loads with the points, click o the drop down menu: Other plans in the this area.
Select another plan, observe if you get an error.
NOTE: If there are no points in the selected plan; The 401 error should be changed to: There are no points in this area
https://web.reveal-stage.smartregister.org/focus-investigation/map/5f2fbbeb-6bec-5a5c-8c52-be1ce47393c8

![image](https://user-images.githubusercontent.com/61143692/85401332-83bf5b80-b562-11ea-9850-cad6118a4b60.png)

**Comment by moshthepitt** [comment]
Not a bug that we can fix in this repo.
