### ISSUE TITLE
flickering when changing to other plans in this area RVL-984

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#942]
Login to the webapp
Go to a specific FI
Drill down till you see a map
When the map loads with the points, click o the drop down menu: Other plans in the this area.
Select another plan, and observe how the map is loaded.
https://web.reveal-stage.smartregister.org/focus-investigation/map/5f2fbbeb-6bec-5a5c-8c52-be1ce47393c8
RESULTS: There is a flickering when trying to load the map.
![image](https://user-images.githubusercontent.com/61143692/85401637-03e5c100-b563-11ea-8a22-5eb693f3b7fb.png)

**Comment by moshthepitt** [comment]
Map filckering was fixed by https://github.com/onaio/reveal-frontend/pull/1096
