### ISSUE TITLE
The conditional formatting rules table is not shown in some instances

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#945]
Login to the app
Click on MDA Point Reporting
Drill down to this for example: https://web.reveal-stage.smartregister.org/intervention/mda-point/location-report/40357eff-81b6-4e32-bd3d-484019689f7c/3951
Observe if the conditional formatting table is shown
EXPECTED RESULTS: It should be shown
![image](https://user-images.githubusercontent.com/61143692/85420948-88910900-b57c-11ea-8580-8462a3f22fd2.png)

**Comment by moshthepitt** [comment]
The page in the screenshot does not have conditional formatting, hence we don't show the table of rules.
