### ISSUE TITLE
Jurisdiction Tree Traversal: 414 Request-URI Too Large -RVL-987

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#951]
This is happening here: https://web.reveal-zm.smartregister.org/assign/9f1e0cfa-5313-49ff-af2c-f7dbf4fbdb9d/ee21d269-1179-4d04-aea9-900155f890cd

We are trying to access OpenSRP like this: https://reveal-zm.smartregister.org/opensrp/rest/location/findByJurisdictionIds?is_jurisdiction=true&return_geometry=false&properties_filter=status%3AActive%2CparentId%3Aee21d269-1179-4d04-aea9-900155f890cd&jurisdiction_ids=06c1e660-b902-4b35-aecb-cd04f5cbb438%2C0878c743-a4f9-4f4d-a990-7771b7eb703d%2C0dcf7aee-a8bc-49d3-9700-4ee8cc3321c0%2C15e6aeb0-cef1-41df-baab-533e28ab36fa%2C1961a0cf-dbe5-41a4-8b4e-eae8de945858%2C38191aa4-5324-490c-b2f0-37305402c1b4%2C3c2b6d9c-2f09-47e1-af91-0c1fa83ccfd5%2C43ef81fd-3ae9-48d9-8208-0b0b62c01d32%2C47fef033-f5bd-4e37-9e31-46c7de77fc90%2C54152630-4122-430f-89fb-3f1944465c07%2C6352b5af-14bc-4c87-a104-0e1aa4bb42fb%2C635ec0bc-ee09-4067-93e9-b3171c43f564%2C65717770-59da-4aa6-9904-53a2e9226244%2C6a4a7db8-d946-485f-adb3-948b4c5aa94f%2C72417f43-7bee-4b4c-b4ca-bd47a97e0a90%2C75adaf2c-022a-4576-9207-af9e4f83045e%2C7be9e0b0-cda5-43f2-a59c-66a6fb06b96c%2C89044207-0b58-49dd-8b28-f7b24d4be8b4%2C92e3128b-9cd3-4d74-999f-d744a8f58c03%2C931a6c64-0a73-427e-b6f2-ecf33d98b4d1%2C93cf884a-8554-4a16-b681-c9d257e47647%2C94e3cd2f-4811-4d03-aad7-2425c6198ed5%2C992f1c0e-cc3e-4f0d-a8bb-9dbcd62f3721%2Ca3d0d483-1373-4529-926e-35bfb357739c%2Ca65e2529-f7ed-44e2-b3a8-6e2605293e0b%2Cab136122-1616-46cd-9efb-85bdd0225853%2Cb52940e4-fbb2-475a-bf11-811f822a7019%2Cb7fcc52e-c5c2-4c43-bad0-3d97a42bb724%2Cbb8ad0ed-65ea-428d-838c-4a6077ef0c17%2Cc99d7d5e-b26c-49d8-8f0b-01c1cf7bd9d2%2Cefc2ccf5-6d0a-4147-8192-2cb492b0b977%2Cfb849e43-4d9e-424a-ab3d-e9e0171c119e

Maybe we should send multiple requests instead of on when we have more than a certain number of ids to fetch

**Comment by Naima-Bashir** [comment]
Just tested this on Zambia production. This has passed QA
cc @samkanga @moshthepitt
