### ISSUE TITLE
Fix Leaf Node Calculation

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#952]
```ts
const isLeafNode: boolean = !knownParentIds.includes(node.id) || focusAreas.includes(node.id);
```

The above is incorrect.  It seems that there are indeed non-leaf nodes withing the `focusAreas` array.  This is happening here: https://web.reveal-zm.smartregister.org/assign/9f1e0cfa-5313-49ff-af2c-f7dbf4fbdb9d/62bdf9f8-57f7-48c4-87b0-0fbce698199b

**Comment by Naima-Bashir** [comment]
This has passed QA
