### ISSUE TITLE
Drafts page caches the previous drafts lists

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/reveal-frontend#954]
How to replicate

- [ ] Update and upload a file.  

- [ ] After being redirected to drafts page you will notice a list of earlier added files.  

- [ ] If you refresh the page you notice the earlier ones get lost. 

My thinking is that the cache is not cleared after the make release is done. @ciremusyoka or @moshthepitt ?

**Comment by ciremusyoka** [comment]
@dubdabasoduba you are right the drafts store is not cleared after making release.
