### ISSUE TITLE
Feedback on the new Form Configuration Web UI features

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#958]
Craig spoke with Matt and recommended the following changes to the form config page:
1. Add a timestamp to the table on the manifest releases page so users have a sense of when these were updated
![image](https://user-images.githubusercontent.com/6067053/85649412-fcecaa80-b657-11ea-9ac7-fd134d71c615.png)
2. Add a timestamp for each file on the manifest releases page so people know when that file was last updated (Assuming they can be different. If they can't be different, maybe add it to the title next to the version number.)
![image](https://user-images.githubusercontent.com/6067053/85649493-24dc0e00-b658-11ea-9d3b-1250175adc9f.png)
3. Add an upload button to the draft files page The upload new file from the manifest page may need to be removed, we need to discuss why that button is there.
![image](https://user-images.githubusercontent.com/6067053/85649523-358c8400-b658-11ea-893d-d2788c091163.png)
4. Add a timestamp to the draft files page that shows when that file was uploaded.
![image](https://user-images.githubusercontent.com/6067053/85649573-5523ac80-b658-11ea-8134-ab1336c48990.png)
5. Change the name `manifest releases` to `releases`

**Comment by dubdabasoduba** [comment]
> Add an upload button to the draft files page The upload new file from the manifest page may need to be removed, we need to discuss why that button is there.
@craigappl This button is here to enable users to easily upload any new files they are sure were not sent to the server in the initial files upload or any other upload.

**Comment by dubdabasoduba** [comment]
> Add an upload button to the draft files page The upload new file from the manifest page may need to be removed, we need to discuss why that button is there.

@ciremusyoka You can go ahead and add the upload button as we discuss whether we still need it on the releases page

**Comment by ciremusyoka** [comment]
@dubdabasoduba  @craigappl what is the decision on the `Upload New File` button in `Manifest Releases` page?

**Comment by moshthepitt** [comment]
Closed by https://github.com/onaio/reveal-frontend/pull/971

**Comment by Naima-Bashir** [comment]
1- Add a timestamp to the table on the manifest releases page so users have a sense of when these were updated --passed QA
2- Add a timestamp for each file on the manifest releases page so people know when that file was last updated (Assuming they can be different. If they can't be different, maybe add it to the title next to the version number.) --Passed QA
3- Add an upload button to the draft files page The upload new file from the manifest page may need to be removed, we need to discuss why that button is there.  --Passed QA
4- Add a timestamp to the draft files page that shows when that file was uploaded.  --Passed QA
5- Change the name manifest releases to releases  --Passed QA
