### ISSUE TITLE
RVL-158 - Development of the Resource Calculation Widget

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#960]
1. On the WebUI, the user will select the create plan button and create an IRS plan and be allowed to move to team assignment.
2. The next page page will load with a risk threshold slider that automatically calculates the number of structures that meet the set threshold. On the same screen the user will have the the option to capture the number of structures that can be covered by 1 team, and an option to capture the number of teams available. Entry of these two variables will facilitate calculation of the number of days needed to completed the provided structure count. **# of days needed to cover the structures = Total # of target structures / (# of structures that can be covered by 1 team per day X # of teams available)** (see screenshot below)
3. ![image](https://user-images.githubusercontent.com/5908630/85692411-09b3e180-b6de-11ea-8371-6518ea4a61f5.png)
4. The resource calculator will be available to all the levels that follow as one drills down the hierarchy. See the screenshots below.
5. ![image](https://user-images.githubusercontent.com/5908630/85692475-19332a80-b6de-11ea-867f-6455f66ae30b.png)
6. ![image](https://user-images.githubusercontent.com/5908630/85692503-20f2cf00-b6de-11ea-9ab4-52071c9e8f30.png)

**Comment by p-netm** [comment]
closed #1088
