### ISSUE TITLE
Downloading certain json files gives a 404 error -RVL-991

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#965]
Login to the web in stage: https://web.reveal-stage.smartregister.org/json-validators
Try and download afew of the files 
EG: eric-test-form (1).json
eric form test and blood_screening.json
Observe the error you see.
EXPECTED RESULT: One should be able to download all the forms
ACTUAL RESULT: Certain forms eg Eric-test cannot be downloaded; they give an error.
See image below
![image](https://user-images.githubusercontent.com/61143692/85840365-0a637b00-b7a5-11ea-958e-b2fe68b6dc06.png)

**Comment by ciremusyoka** [comment]
@dubdabasoduba do you think issue #955 addresses the cause of this bug.

**Comment by dubdabasoduba** [comment]
Yes, it might fix it.

**Comment by moshthepitt** [comment]
@ciremusyoka @dubdabasoduba did it fix it?

**Comment by ciremusyoka** [comment]
> @ciremusyoka @dubdabasoduba did it fix it?

@moshthepitt Yah I can download all files without any error.
@Naima-Bashir can you confirm please.

**Comment by moshthepitt** [comment]
k, going to close.  Please reopen is something is amiss

**Comment by Naima-Bashir** [comment]
this works. the download feature is okay
