### ISSUE TITLE
Some sections are overflowing when one minimizes the screen  RVL-992

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#966]
Login to the webapp
Eg: https://web.reveal-stage.smartregister.org/json-validators
Minimize the page from a full screen view and observe the form
RESULTS: Some sections in the form are overflowing when one exists full screen

![image](https://user-images.githubusercontent.com/61143692/85844313-308c1980-b7ab-11ea-923c-d90da99d543c.png)

**Comment by moshthepitt** [comment]
We aren't really building it to be mobile friendly
