### ISSUE TITLE
Add child level view to the MDA Point Reporting 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#979]
We need to add one last reporting view to the current MDA Point reporting. This layer will be the lowest level aka you will view it by clicking through the school view. 

Each row will represent an individual child and the columns will reflect the information below: 

**Column Headers:** 
Child's name
National ID
Enrolled in school --> (yes or no)
MMA drug administered --> (yes or no)
SAC refused --> (yes or no)
SAC sick/pregnant/contraindicated --> (yes or no)
ADR reported --> (yes or no)
PZQ tablets distributed --> (total number)
Alb tablets distributed -- (total number) 

[Data Dictionary found here](https://docs.google.com/spreadsheets/d/14NyA7b67arS_oy0uG3NOY0KcaTjK36kkobGRi02A0xk/edit#gid=1336356138)

**UI:** 
Because the view before this view has rows for children split into age categories instead of just a row for the school, we need a solution for how to click through to the full list of children (see image below). What we will do is add a row to the bottom of the table on the school view (view below) that has clickable text in the first column that says "See all children" - when they click it, the user will be taken to the view described above.  

<img width="1239" alt="Screen Shot 2020-07-01 at 9 28 14 PM" src="https://user-images.githubusercontent.com/12836913/86316529-d5f72100-bbe1-11ea-83ca-17cef3652e7f.png">

**Comment by rowo** [comment]
@isabelcshaw 
1. I don't understand the statement "this view is formatted so that the school name is replaced by age categories (which was a requirement)". Does that mean this is one level down from a school i.e. "Primary school A --> Age group categories --> student list" or that there are no school names because areas only have one school so they want to just jump straight to age breakdowns?
2. Does "this view is formatted so that the school name is replaced by age categories (which was a requirement)" mean that we can't have all children listed and then put "age range" into a column?
3. If number 2 isn't possible, would it be possible just to add an "all age ranges" row and be able to click into that?

**Comment by gstuder-ona** [comment]
On the data side, we already have a child view that can be filtered by plan_id and school(location)_id:
mda_client_dispense_task_report

These fields exist / can be easily derived:
MMA drug administered --> (yes or no) mmadrugadmin
SAC refused --> (yes or no)  mmanodrugadminreason
SAC sick/pregnant/contraindicated --> (yes or no) mmanodrugadminreason
ADR reported --> (yes or no) (mmaadr)
PZQ tablets distributed --> (total number) (mmapzqdosagegiven)
Alb tablets distributed --> (total number) (mmaalbgiven)
Child's name (from clients table join) (firstname, lastname)

These fields aren't currently linked and need to be linked to the child via a registration event, which is a bit more complex:
National ID (sactaNationalId)?
Enrolled in school --> (yes or no) (sactaCurrEnroll)?

I think the overall idea would be to update mda_client_dispense_task_report to:
1) add the easily-computed fields in a way consistent with the school/jurisdiction reports
2) add another WITH clause for child_registration_event_observations (similar to mda_dispense_event_observations) to link in the latest 'Child Registration'/'Update Child Registration' event data for the sactaNationalId and sactaCurrEnroll fields

Maybe 2-3 days of work for someone unfamiliar with the current tables, 1-2 days if familiar.

**Comment by isabelcshaw** [comment]
Spoke with @rowo (thank you!) and will update the UI expectations above

**Comment by gstuder-ona** [comment]
https://github.com/onaio/data-solutions/pull/48/

**Comment by gstuder-ona** [comment]
Migration PR is up - we'll need to deploy that as well as update the reveal-esw nifi processors to refresh "_impl" views
