### ISSUE TITLE
User can create a "MDA Community" plan

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#981]
When generating a new plan, the user can select a "NTD MDA in community" plan type.
This plan type should follow the IRS model for plan, where we see a map of all eligible operational areas and point and click which we prioritize.

Tasks for this plan:

Register Family (linked to location) - Run on Plan-Activation for all locations that do not have a family registered
Register (floating) - Floating families will be counted against the Register Family Action.
Register Child - We will not create any tasks separately for children that are registered. When a child is registered, we will create a drug distribution task.
Drug Distribution - Run on Plan-Activation for all eligible children that are in the system. (We need to define eligibility criteria and generate tasks based on these criteria and NOT for all person-entities.)

Functional expectations: 
- User can use the IRS planning workflow to create a plan 
- This includes the ability to click through and select both jurisdictions at higher levels and operational levels 
- User can assign teams to MDA Community plans on the assignment page 

**Plan Details**
{
	"identifier": "5d64b033-913d-49e5-8e30-348db07ae89f",
	"version": "1",
	"name": "MDA-Community-Test-Plan-2020-06-25",
	"title": "MDA Community Test Plan 2020-06-25",
	"status": "active",
	"date": "2020-06-25",
	"effectivePeriod": {
		"start": "2020-06-25",
		"end": "2020-10-01"
	},
	"useContext": [
		{
			"code": "interventionType",
			"valueCodableConcept": "MDA"
		},
		{
			"code": "taskGenerationStatus",
			"valueCodableConcept": "False"
		}
	],
	"jurisdiction": [
		{
			"code": "cd5ec29e-6be9-41a2-9b88-bc81fbc691c6"
		},
		{
			"code": "122adc11-e7ab-4fe8-84dd-9853c5587456"
		},
		{
			"code": "c3ab6b62-48da-42d1-9952-83c8d30e87da"
		},
		{
			"code": "f094e646-cb70-4f76-a451-ab9d24e61405"
		},
		{
			"code": "fa351dc7-478c-4be9-be60-de05827dba8e"
		}
	],
	"goal": [
		{
			"id": "RACD_register_all_families",
			"description": "Register all families and family members in all residential structures enumerated or added (100%) within operational area",
			"priority": "medium-priority",
			"target": [
				{
					"measure": "Percent of residential structures with full family registration",
					"detail": {
						"detailQuantity": {
							"value": 75.0,
							"comparator": ">=",
							"unit": "Percent"
						}
					},
					"due": "2020-10-01"
				}
			]
		},
		{
			"id": "MDA_Dispense",
			"description": "Visit all residential structures (100%) distribute drugs to each eligible person",
			"priority": "medium-priority",
			"target": [
				{
					"measure": "Percent of individuals treated",
					"detail": {
						"detailQuantity": {
							"value": 75.0,
							"comparator": ">=",
							"unit": "Percent"
						}
					},
					"due": "2020-10-01"
				}
			]
		}
	],
	"action": [
		{
			"identifier": "478c7dc9-bec1-4e39-8330-8f0c70782584",
			"prefix": 1,
			"title": "Family Registration",
			"description": "Register all families and family members in all residential structures enumerated (75%) within the operational area",
			"code": "RACD Register Family",
			"timingPeriod": {
				"start": "2020-06-25",
				"end": "2020-10-01"
			},
			"reason": "Investigation",
			"goalId": "RACD_register_all_families",
			"subjectCodableConcept": {
				"text": "Residential_Structure"
			},
			"taskTemplate": "RACD_register_families"
		},
		{
			"identifier": "37f81c90-19f3-44bc-9e86-d17e23b1d963",
			"prefix": 2,
			"title": "Distribute Drugs",
			"description": "Visit all residential structures (100%) distribute drugs to each eligible individual",
			"code": "MDA Dispense",
			"timingPeriod": {
				"start": "2020-06-25",
				"end": "2020-10-01"
			},
			"reason": "Routine",
			"goalId": "MDA_Dispense",
			"subjectCodableConcept": {
				"text": "Person"
			},
			"taskTemplate": "MDA_Dispense"
		}
	]
}

**Comment by moshthepitt** [comment]
Right now one is able to create dynamic MDA plans.  Is that sufficient for this issue?  I am hesitant to do work on the old-style plans if we are just going to discard it in a short while.

**Comment by moshthepitt** [comment]
Going to close this based on this slack conversation: https://onaio.slack.com/archives/CBSU8L2SC/p1594063334148800?thread_ts=1594023468.144500&cid=CBSU8L2SC
