### ISSUE TITLE
Dynamic Plan Web UI Feedback

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#992]
This issue includes feedback on the planning web UI that includes dynamic plan generation.

1. We need to display the action.definitionUri for each action in the dynamic plans. We need to do this because different countries will have different forms.
2. We need to display the action.trigger.expression.expression. Currently, it's hidden and that's used so we can identify which eventType to read.
3. We need to populate default descriptions for the triggers, which I will need to provide tomorrow
4. I hope it's possible to set default values per country implementation. So, Thailand would have default values for definitionUri and conditions compared to Namibia.

**Comment by craigappl** [comment]
I have an update to the ticket based on discussions with Isabel and Sam G:

First, we need to update the default values for the dynamic MDA plan so that users of Zambia NTD don't have to change anything when they create a Dynamic Dispense plan.
Changes:
- [x] Change the dispense criteria to evaluate the patient's age between 5 and 14 years old
Old Expression: https://github.com/onaio/reveal-frontend/blob/master/src/configs/settings.ts#L888
New Expression: "($this.is(FHIR.Patient) and $this.birthDate <= today() - 60 'months' and $this.birthDate >= today() - 179 'months') or ($this.contained.where(Patient.birthDate <= today() - 60 'months' and $this.birthDate >= today() - 179 'months').exists())",
- [x] Change action title to "Distribute Drugs"
- [x] Change default goal to 75%

Second, we need to add descriptions to all expressions
- [x] Confirm all expressions have descriptions and create those which are missing.

Third, we need to update the questionnaire name to remove spaces in the expression
- [x] Remove spaces and replace them with underscores

Fourth, if possible, default the triggers and conditions to be collapsed in the web UI

**Comment by Naima-Bashir** [comment]
Change the dispense criteria to evaluate the patient's age between 5 and 14 years old---I've tested this functionality on android. The dispense criteria is the same for those between 5-14 and those above. cc @ciremusyoka  @craigappl 

Change action title to "Distribute Drugs" @craigappl  could you kindly explain where this should be? I've tested on Create new MDA plan on web and could not find it. And android Record Dose functionality. It is not there. cc @ciremusyoka 
![image](https://user-images.githubusercontent.com/61143692/87657948-3058bb80-c764-11ea-902e-b409ced7668a.png)

Change default goal to 75%   -**passed QA**

Remove spaces and replace them with underscores
