### ISSUE TITLE
Planning tool checkbox does not work as expected

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#993]
Login to the web app
In the planning drop down, click on planning tool
Select a jurisdiction https://web.reveal-stage.smartregister.org/assignJurisdictions/56fb52a7-138d-53b9-9369-4294ad718049/9c3c2db4-bddd-44c5-870a-a0eef539e4da/872cc59e-0bce-427a-bd1f-6ef674dba8e2
Eg: Lop Buri- Distric Tha Luang-
In the list of 6 jurisdictions shown, click on two and save those as your preferred assignment.
Observe whether the pop up notification says 6 of the assigned plans are successful 
EXPECTED RESULTS: Only the selected number should be shown in the notification

![image](https://user-images.githubusercontent.com/61143692/86762263-33aac380-c04f-11ea-8a88-865af51ecfb3.png)

**Comment by p-netm** [comment]
@Naima-Bashir could you please revisit this, now that we have a tally of the selected jurisdictions in the tree before saving them.

**Comment by p-netm** [comment]
some context; we are only sending the leaf nodes to opensrp as part of the plan's jurisdictions. In other words we collate only the jurisdictions that do not have children and post those. so for instance in this case , the 2 shown selected jurisdictions have other jurisdictions underneath, at the end of the drilldown we expect to have 6 jurisdictions that have no children. these 6 are the ones we will send to Opensrp and not the 2  that are shown as selected in the image.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/87786793-438e8880-c843-11ea-8319-aeb1adbb584f.png)
There is a bug here. When I click on a certain jurisdiction and drill down, I can uncheck the location. However, when I try to click on the check box again, it is not possible. 
https://web.reveal-stage.smartregister.org/assignJurisdictions/56fb52a7-138d-53b9-9369-4294ad718049/9c3c2db4-bddd-44c5-870a-a0eef539e4da/07b09ec1-0589-4a98-9480-4c403ac24d59
cc @p-netm

**Comment by p-netm** [comment]
closed in #1065.

@Naima-Bashir this will require QA in the next release, I will include it in the notes, but just incase I forget.
