### ISSUE TITLE
Improve the error messaging when certain jurisdictions cant be loaded RVL-1008

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#998]
Login to the web app on stage
Create a new plan on the FI type. For example: 
FI- Nigeria- Drill down to a certain jurisdiction
Once the side panel shows up, click on the jurisdiction and observe the error that is shown.
RESULTS: We get an error that says: "An error prevented this jurisdiction from loading."
EXPECTED RESULT: We should have a better error message to explain to the user why the selected jurisdiction can't be loaded.

![image](https://user-images.githubusercontent.com/61143692/86896485-b34b9780-c10e-11ea-9663-334b81fba4f6.png)
![image](https://user-images.githubusercontent.com/61143692/86899073-2dc9e680-c112-11ea-8b8d-92fdc4d8b484.png)
cc @moshthepitt @craigappl @samkanga

**Comment by moshthepitt** [comment]
This is expected.
