### ISSUE TITLE
Error message at the "other plans in this area" should be improved  RVL-1010

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#999]
Login to the webapp on stage
Select FI- Lusaka-Mtendere-Akros_01 then select one of the jurisdictions.
Once the map page loads, click on the other plans in this area Eg A1 Akros_1 2020-04-01 Investigation
Observe the error that is shown.
RESULTS: There is a code shown instead of a text in the error section
cc @moshthepitt 
![image](https://user-images.githubusercontent.com/61143692/86906608-78e8f700-c11c-11ea-9096-a619ac0961f2.png)

**Comment by kelvin-muchiri** [comment]
@moshthepitt The error is displayed when the[ API call ](of https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/FocusInvestigation/map/active/index.tsx#L209 )results in an error. I presume the fix required here is to not display the raw error message but show the generic **An error occured** ?
